// ─── PARTIE 2 : UE 2.1 · UE 2.2 · UE 2.4 · UE 2.10 ─────────────────────────
module.exports = [

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 2.1 – Biologie fondamentale (~42 cartes)
  // ═══════════════════════════════════════════════════════════════════════════

  // Chapitre : La cellule
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'La cellule', difficulty:'easy', isPublished:true,
    front:'La cellule — unité de base du vivant',
    back:'Plus petite unité structurale et fonctionnelle du vivant. Elle assure : métabolisme, reproduction, réponse aux stimuli, homéostasie.' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'La cellule', difficulty:'easy', isPublished:true,
    front:'La membrane plasmique — rôle et composition',
    back:'Bicouche phospholipidique avec protéines intégrées.\nRôle : sélectivité des échanges (perméabilité sélective), communication cellulaire, réception des signaux.' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'La cellule', difficulty:'medium', isPublished:true,
    front:'Le noyau cellulaire — fonctions',
    back:'Centre de commande de la cellule :\n• Contient l\'ADN (information génétique)\n• Contrôle la synthèse des protéines\n• Dirige la division cellulaire\nEntouré de l\'enveloppe nucléaire à pores.' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'La cellule', difficulty:'medium', isPublished:true,
    front:'Les mitochondries — rôle',
    back:'"Centrale énergétique" de la cellule.\nProduisent l\'ATP (adénosine triphosphate) par la respiration cellulaire (cycle de Krebs + chaîne respiratoire).\nPossèdent leur propre ADN.' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'La cellule', difficulty:'easy', isPublished:true,
    front:'L\'ATP — définition et rôle',
    back:'Adénosine TriPhosphate : molécule énergétique universelle de la cellule.\nL\'hydrolyse d\'une liaison phosphate libère de l\'énergie utilisable par la cellule.' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'La cellule', difficulty:'medium', isPublished:true,
    front:'Le réticulum endoplasmique — 2 types',
    back:'• RE rugueux (avec ribosomes) : synthèse des protéines destinées à l\'exportation\n• RE lisse (sans ribosomes) : synthèse lipidique, détoxification (foie)' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'La cellule', difficulty:'medium', isPublished:true,
    front:'L\'appareil de Golgi — rôle',
    back:'Centre de tri, modification et emballage des protéines.\nRéceptionne les protéines du RE rugueux, les modifie (glycosylation) et les envoie vers leur destination (lysosomes, membrane, exocytose).' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'La cellule', difficulty:'easy', isPublished:true,
    front:'Les lysosomes — rôle',
    back:'Organites contenant des enzymes digestives acides.\nDétruisent les déchets cellulaires, les bactéries phagocytées, les organites endommagés (autophagie).' },

  // Chapitre : ADN et génétique
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'ADN et génétique', difficulty:'easy', isPublished:true,
    front:'La structure de l\'ADN',
    back:'Double hélice composée de 2 brins antiparallèles reliés par des liaisons hydrogène entre bases azotées :\n• A-T (adénine-thymine)\n• G-C (guanine-cytosine)',
    hint:'A-T : 2 liaisons H / G-C : 3 liaisons H' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'ADN et génétique', difficulty:'medium', isPublished:true,
    front:'La transcription (ADN → ARN)',
    back:'Processus de copie d\'un gène de l\'ADN en ARN messager (ARNm) dans le noyau.\nL\'ARNm sort du noyau et va vers les ribosomes pour la traduction.' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'ADN et génétique', difficulty:'medium', isPublished:true,
    front:'La traduction (ARN → protéine)',
    back:'Lecture de l\'ARNm par les ribosomes pour synthétiser une chaîne d\'acides aminés (protéine).\nChaque codon (3 bases) code pour un acide aminé.' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'ADN et génétique', difficulty:'medium', isPublished:true,
    front:'La mitose vs la méiose',
    back:'• Mitose : division cellulaire donnant 2 cellules filles identiques (diploïdes 2n) → croissance, réparation\n• Méiose : division donnant 4 cellules filles (haploïdes n) → gamètes (spermatozoïdes, ovocytes)' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'ADN et génétique', difficulty:'medium', isPublished:true,
    front:'Hérédité autosomale dominante — caractéristiques',
    back:'• Le gène est sur un autosome (non sexuel)\n• Une seule copie mutée suffit à exprimer la maladie\n• Exemple : maladie de Huntington, neurofibromatose\n• Transmission : 50% de risque pour les enfants' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'ADN et génétique', difficulty:'medium', isPublished:true,
    front:'Hérédité autosomale récessive — caractéristiques',
    back:'• Deux copies mutées nécessaires\n• Les porteurs hétérozygotes sont sains\n• Exemple : mucoviscidose, phénylcétonurie, drépanocytose\n• 25% de risque si 2 parents porteurs' },

  // Chapitre : Métabolisme et homéostasie
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'Métabolisme et homéostasie', difficulty:'easy', isPublished:true,
    front:'L\'homéostasie — définition',
    back:'Capacité d\'un organisme à maintenir ses paramètres internes (température, pH, glycémie, pression artérielle) dans des valeurs compatibles avec la vie, malgré les variations du milieu extérieur.' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'Métabolisme et homéostasie', difficulty:'medium', isPublished:true,
    front:'La rétroaction négative (feedback négatif)',
    back:'Mécanisme de régulation principal de l\'homéostasie.\nLa réponse s\'oppose au stimulus initial pour rétablir l\'équilibre.\nEx : augmentation glycémie → sécrétion d\'insuline → baisse glycémie.' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'Métabolisme et homéostasie', difficulty:'medium', isPublished:true,
    front:'Le pH sanguin normal et régulation',
    back:'pH normal : 7,35 – 7,45\n• < 7,35 : acidose\n• > 7,45 : alcalose\nRégulé par : poumons (CO₂), reins (HCO₃⁻), systèmes tampons (bicarbonate)' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'Métabolisme et homéostasie', difficulty:'easy', isPublished:true,
    front:'La glycémie normale à jeun',
    back:'0,7 – 1,10 g/L (3,9 – 6,1 mmol/L)\n• Hypoglycémie < 0,7 g/L\n• Hyperglycémie > 1,26 g/L à 2 reprises → diabète' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'Métabolisme et homéostasie', difficulty:'medium', isPublished:true,
    front:'L\'osmolarité plasmatique normale',
    back:'285 – 295 mOsm/L\nDéterminée principalement par le sodium.\nRégulée par : ADH (hormone antidiurétique), soif, rein.\nHyperosmolarité → déshydratation intracellulaire.' },

  // Chapitre : Les tissus
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'Les tissus', difficulty:'easy', isPublished:true,
    front:'Les 4 grands types de tissus de l\'organisme',
    back:'1. Tissu épithélial : revêtement et glandes\n2. Tissu conjonctif : soutien et transport (os, sang, graisse)\n3. Tissu musculaire : contraction\n4. Tissu nerveux : conduction de l\'influx',
    hint:'Épi → Conj → Musc → Nerv' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'Les tissus', difficulty:'medium', isPublished:true,
    front:'Tissu épithélial — rôles',
    back:'• Protection (peau)\n• Absorption (intestin)\n• Sécrétion (glandes exo/endocrines)\n• Filtration (glomérule rénal)\nCaractérisé par l\'absence de vaisseaux (avasculaire), nutrition par diffusion.' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'Les tissus', difficulty:'medium', isPublished:true,
    front:'Tissu osseux — types et fonctions',
    back:'• Os compact (cortical) : résistance mécanique\n• Os spongieux (trabéculaire) : siège de l\'hématopoïèse dans la moelle rouge\nFonctions : soutien, protection, réserve minérale (Ca²⁺, PO₄)' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'Les tissus', difficulty:'medium', isPublished:true,
    front:'L\'hématopoïèse — définition et lieu',
    back:'Production des cellules sanguines à partir des cellules souches hématopoïétiques.\nLieu : moelle osseuse rouge (os plats et courts chez l\'adulte : sternum, iliaques, vertèbres).' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'Les tissus', difficulty:'easy', isPublished:true,
    front:'Les 3 types de tissu musculaire',
    back:'1. Strié squelettique : volontaire, attaché aux os\n2. Strié cardiaque : involontaire, myocarde\n3. Lisse : involontaire, viscères (intestin, vaisseaux, utérus)' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'Les tissus', difficulty:'medium', isPublished:true,
    front:'Le neurone — structure et fonctions',
    back:'Cellule nerveuse composée de :\n• Corps cellulaire (soma)\n• Dendrites : réception des signaux\n• Axone : conduction du potentiel d\'action\n• Terminaisons synaptiques : transmission\nCommunication par synapse (neurotransmetteurs).' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'Les tissus', difficulty:'medium', isPublished:true,
    front:'La synapse chimique — fonctionnement',
    back:'1. Arrivée du potentiel d\'action → libération de neurotransmetteurs dans la fente synaptique\n2. Fixation sur récepteurs de la cellule post-synaptique\n3. Réponse (excitation ou inhibition)\nEx : acétylcholine, dopamine, sérotonine, GABA' },

  // Chapitre : Les liquides corporels
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'Les liquides corporels', difficulty:'medium', isPublished:true,
    front:'Répartition de l\'eau dans l\'organisme (adulte)',
    back:'L\'eau représente 60% du poids corporel :\n• Liquide intracellulaire (LIC) : 40% du poids (2/3)\n• Liquide extracellulaire (LEC) : 20% du poids (1/3)\n  - Plasma : 5%\n  - Liquide interstitiel : 15%' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'Les liquides corporels', difficulty:'medium', isPublished:true,
    front:'Sodium (Na⁺) — valeurs normales et rôle',
    back:'Valeur normale : 135–145 mmol/L (plasmatique)\nPrincipal cation du LEC → régule l\'osmolarité et la volémie.\n• Hyponatrémie < 135 : œdème cellulaire\n• Hypernatrémie > 145 : déshydratation intracellulaire' },
  { semester:'Semestre 1', category:'UE 2.1 - Biologie fondamentale', chapter:'Les liquides corporels', difficulty:'medium', isPublished:true,
    front:'Potassium (K⁺) — valeurs normales et rôle',
    back:'Valeur normale : 3,5–5,0 mmol/L (plasmatique)\nPrincipal cation du LIC → potentiel membranaire, contraction musculaire.\n• Hypokaliémie < 3,5 : risque trouble du rythme, faiblesse\n• Hyperkaliémie > 5,0 : risque arrêt cardiaque' },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 2.2 – Cycles de la vie et grandes fonctions (~42 cartes)
  // ═══════════════════════════════════════════════════════════════════════════

  // Chapitre : Appareil cardiovasculaire
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Appareil cardiovasculaire', difficulty:'easy', isPublished:true,
    front:'Le cycle cardiaque — systole et diastole',
    back:'• Systole : contraction ventriculaire → éjection du sang\n• Diastole : relaxation ventriculaire → remplissage\nFréquence cardiaque normale adulte : 60–100 bpm.' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Appareil cardiovasculaire', difficulty:'easy', isPublished:true,
    front:'La pression artérielle normale',
    back:'Adulte : < 140/90 mmHg\n• Systolique (PAS) : pression lors de la systole\n• Diastolique (PAD) : pression lors de la diastole\nOptimale : 120/80 mmHg.',
    hint:'PAS / PAD' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Appareil cardiovasculaire', difficulty:'medium', isPublished:true,
    front:'La grande et la petite circulation',
    back:'• Grande circulation (systémique) : Ventricule gauche → aorte → organes → veines caves → Oreillette droite\n• Petite circulation (pulmonaire) : Ventricule droit → artères pulmonaires → poumons (hématose) → veines pulmonaires → Oreillette gauche' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Appareil cardiovasculaire', difficulty:'medium', isPublished:true,
    front:'Les valves cardiaques — noms et localisation',
    back:'• Mitrale (bicuspide) : entre OG et VG\n• Tricuspide : entre OD et VD\n• Aortique : entre VG et aorte (sigmoïde)\n• Pulmonaire : entre VD et artère pulmonaire (sigmoïde)',
    hint:'Gauche = Mitrale | Droite = Tricuspide' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Appareil cardiovasculaire', difficulty:'medium', isPublished:true,
    front:'Le débit cardiaque (DC)',
    back:'DC = Volume d\'éjection systolique (VES) × Fréquence cardiaque (FC)\nNormale au repos : ~5 L/min\nPeut atteindre 20–25 L/min à l\'effort.' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Appareil cardiovasculaire', difficulty:'medium', isPublished:true,
    front:'L\'hémostase — 3 phases',
    back:'1. Hémostase primaire : vasoconstriction + clou plaquettaire (plaquettes + vWF)\n2. Coagulation (hémostase secondaire) : cascade de coagulation → fibrine\n3. Fibrinolyse : dissolution du caillot par la plasmine' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Appareil cardiovasculaire', difficulty:'easy', isPublished:true,
    front:'Les groupes sanguins ABO et Rhésus',
    back:'• Groupe O : pas d\'antigène, donne à tous (donneur universel)\n• Groupe AB : tous les antigènes, reçoit de tous (receveur universel)\n• Rhésus + : antigène D présent\n• Rhésus - : antigène D absent (à surveiller en grossesse : allo-immunisation)' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Appareil cardiovasculaire', difficulty:'medium', isPublished:true,
    front:'Les globules rouges (érythrocytes) — caractéristiques',
    back:'• Durée de vie : 120 jours\n• Contiennent l\'hémoglobine (transport O₂/CO₂)\n• Anucléés (pas de noyau)\n• Valeurs normales : H 4,5–6 M/µL ; F 4–5,5 M/µL\n• Créés dans la moelle osseuse (érythropoïèse sous EPO)' },

  // Chapitre : Appareil respiratoire
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Appareil respiratoire', difficulty:'easy', isPublished:true,
    front:'L\'hématose — définition',
    back:'Échange gazeux entre l\'air alvéolaire et le sang capillaire pulmonaire.\n• O₂ passe de l\'alvéole vers le sang\n• CO₂ passe du sang vers l\'alvéole\nSe produit au niveau des alvéoles pulmonaires par diffusion.' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Appareil respiratoire', difficulty:'easy', isPublished:true,
    front:'Les valeurs normales de la SpO₂',
    back:'SpO₂ (saturation pulsée en O₂) normale : 95–100%\n• 90–94% : hypoxémie modérée → surveillance\n• < 90% : hypoxémie sévère → intervention urgente\nMesurée par oxymètre de pouls.' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Appareil respiratoire', difficulty:'medium', isPublished:true,
    front:'La fréquence respiratoire normale par âge',
    back:'• Adulte : 12–20 cycles/min\n• Enfant (2-12 ans) : 20–30/min\n• Nourrisson : 30–40/min\n• Nouveau-né : 40–60/min\nTachypnée > 20/min chez l\'adulte.' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Appareil respiratoire', difficulty:'medium', isPublished:true,
    front:'La mécanique ventilatoire — inspiration/expiration',
    back:'• Inspiration : active — contraction diaphragme et intercostaux → ↑ volume thoracique → ↓ pression → entrée d\'air\n• Expiration : passive au repos — relâchement muscles → ↓ volume → ↑ pression → sortie d\'air' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Appareil respiratoire', difficulty:'medium', isPublished:true,
    front:'Les volumes respiratoires — principaux',
    back:'• Volume courant (VC) : ~500 mL (air inspiré/expiré au repos)\n• Capacité vitale (CV) : ~4,5 L\n• Volume résiduel (VR) : ~1,2 L (air incompressible)\n• DEP (débit expiratoire de pointe) : évalué dans l\'asthme' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Appareil respiratoire', difficulty:'medium', isPublished:true,
    front:'Le transport de l\'O₂ dans le sang',
    back:'• 98% : lié à l\'hémoglobine (oxyhémoglobine)\n• 2% : dissous dans le plasma\nCapacité liée à : taux d\'Hb, SpO₂, 2,3-DPG.\nAnémie → transport insuffisant d\'O₂.' },

  // Chapitre : Appareil digestif
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Appareil digestif', difficulty:'easy', isPublished:true,
    front:'Les étapes de la digestion',
    back:'1. Ingestion (bouche)\n2. Digestion mécanique (mastication, péristaltisme)\n3. Digestion chimique (enzymes, bile)\n4. Absorption (intestin grêle)\n5. Élimination (côlon → rectum → anus)',
    hint:'Inge → Mécanique → Chimique → Absorption → Élim' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Appareil digestif', difficulty:'medium', isPublished:true,
    front:'Le rôle du foie dans la digestion',
    back:'• Synthèse de la bile (digestion des lipides)\n• Métabolisme glucidique (glycogénèse, glycogénolyse, néoglucogenèse)\n• Synthèse protéique (albumine, facteurs coagulation)\n• Détoxification\n• Stockage (glycogène, vitamines liposolubles)' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Appareil digestif', difficulty:'medium', isPublished:true,
    front:'Le rôle du pancréas — fonctions exo et endocrine',
    back:'• Exocrine : sécrétion du suc pancréatique (lipase, amylase, protéases) dans le duodénum → digestion\n• Endocrine : îlots de Langerhans → insuline (cellules β), glucagon (cellules α)' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Appareil digestif', difficulty:'easy', isPublished:true,
    front:'L\'intestin grêle — rôle et particularités',
    back:'Lieu principal de l\'absorption des nutriments (7m de long).\nAugmentation de la surface par : villosités et microvillosités (bordure en brosse).\nAbsorption de : glucides, protéines, lipides, vitamines, eau.' },

  // Chapitre : Système nerveux
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Système nerveux', difficulty:'easy', isPublished:true,
    front:'SNC vs SNP — organisation',
    back:'• SNC (Système nerveux central) : encéphale + moelle épinière → intégration et traitement\n• SNP (Système nerveux périphérique) : nerfs → transmission\n  - Somatique (volontaire)\n  - Autonome/végétatif (involontaire : sympathique + parasympathique)' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Système nerveux', difficulty:'medium', isPublished:true,
    front:'Système nerveux sympathique vs parasympathique',
    back:'• Sympathique (ortho) : "fight or flight"\n  ↑ FC, ↑ PA, mydriase, bronchodilatation, ↓ digestion\n• Parasympathique (vague) : "rest and digest"\n  ↓ FC, myosis, bronchoconstriction, ↑ digestion' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Système nerveux', difficulty:'medium', isPublished:true,
    front:'Les lobes du cerveau et leurs fonctions',
    back:'• Frontal : motricité volontaire, raisonnement, langage (Broca)\n• Pariétal : sensibilité somatique, espace\n• Temporal : audition, mémoire, langage (Wernicke)\n• Occipital : vision' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Système nerveux', difficulty:'medium', isPublished:true,
    front:'Le score de Glasgow (GCS) — principe',
    back:'Évalue l\'état de conscience sur 3 critères :\n• Ouverture des yeux (E) : 1–4\n• Réponse verbale (V) : 1–5\n• Réponse motrice (M) : 1–6\nScore max : 15 (normal) — Score 8 ou < : coma' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Système nerveux', difficulty:'easy', isPublished:true,
    front:'Les méninges — 3 couches',
    back:'De l\'extérieur vers l\'intérieur :\n1. Dure-mère (pachyméninge)\n2. Arachnoïde\n3. Pie-mère\nL\'espace sous-arachnoïdien contient le liquide céphalorachidien (LCR).',
    hint:'Dure → Arach → Pie' },

  // Chapitre : Développement de la vie et vieillissement
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Cycles de la vie', difficulty:'easy', isPublished:true,
    front:'Les grandes étapes du développement humain',
    back:'1. Fœtus (0–9 mois in utero)\n2. Nouveau-né (0–28 jours)\n3. Nourrisson (1 mois – 2 ans)\n4. Enfant (2–12 ans)\n5. Adolescent (12–18 ans)\n6. Adulte (18–65 ans)\n7. Personne âgée (> 65 ans)' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Cycles de la vie', difficulty:'medium', isPublished:true,
    front:'Les modifications physiologiques du vieillissement',
    back:'• Cardiovasculaire : ↓ compliance, ↑ PA\n• Respiratoire : ↓ CVF, ↓ tonus musculaire\n• Rénal : ↓ DFG (filtration)\n• Musculaire : sarcopénie\n• Osseux : ostéoporose (↓ densité)\n• Sensoriel : presbytie, presbyacousie' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Cycles de la vie', difficulty:'medium', isPublished:true,
    front:'La ménopause — définition et conséquences',
    back:'Arrêt définitif des règles (> 12 mois consécutifs).\nMoyenne : 51 ans.\nConséquences : chute des œstrogènes → bouffées de chaleur, sécheresse vaginale, ostéoporose, risque cardio-vasculaire ↑.' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Cycles de la vie', difficulty:'medium', isPublished:true,
    front:'La puberté — repères',
    back:'• Filles : 10–14 ans (développement seins → ménarche)\n• Garçons : 11–16 ans (développement testicules → spermarche)\nDéclenchée par l\'axe hypothalamo-hypophyso-gonadique (↑ GnRH → LH/FSH).' },
  { semester:'Semestre 1', category:'UE 2.2 - Cycles de la vie et grandes fonctions', chapter:'Cycles de la vie', difficulty:'easy', isPublished:true,
    front:'L\'indice de masse corporelle (IMC)',
    back:'IMC = Poids (kg) / Taille² (m)\n• < 18,5 : maigreur\n• 18,5–24,9 : normal\n• 25–29,9 : surpoids\n• ≥ 30 : obésité\n• ≥ 40 : obésité morbide' },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 2.4 – Processus traumatiques (~42 cartes)
  // ═══════════════════════════════════════════════════════════════════════════

  // Chapitre : Plaies et cicatrisation
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'Plaies et cicatrisation', difficulty:'easy', isPublished:true,
    front:'Les 3 phases de la cicatrisation',
    back:'1. Phase inflammatoire (J0–J5) : vasodilatation, détersion, macrophages\n2. Phase proliférative (J5–J21) : tissu de granulation, angiogenèse, fibroblastes\n3. Phase de remodelage (J21 – 2 ans) : maturation du collagène, cicatrice finale',
    hint:'Inflammation → Prolifération → Remodelage' },
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'Plaies et cicatrisation', difficulty:'medium', isPublished:true,
    front:'Cicatrisation par première intention vs seconde intention',
    back:'• Première intention : berges rapprochées (sutures), cicatrisation rapide et discrète\n• Seconde intention : plaie laissée ouverte, comblement progressif par tissu de granulation (plus longue, cicatrice plus visible)\n• Troisième intention : fermeture différée après détersion' },
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'Plaies et cicatrisation', difficulty:'medium', isPublished:true,
    front:'Les facteurs défavorables à la cicatrisation',
    back:'• Généraux : âge, diabète, dénutrition, immunodépression, insuffisance veineuse, tabac, corticoïdes\n• Locaux : infection, corps étranger, hématome, ischémie, mauvais pansement' },
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'Plaies et cicatrisation', difficulty:'easy', isPublished:true,
    front:'La classification des plaies chroniques — 4 couleurs',
    back:'• Noir : nécrose sèche → détersion\n• Jaune : fibrine (tissu mort humide) → détersion\n• Rouge : tissu de granulation → protéger et favoriser\n• Rose/Rosé : épidermisation → protéger',
    hint:'N → J → R → Rose (du plus mauvais au meilleur)' },
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'Plaies et cicatrisation', difficulty:'medium', isPublished:true,
    front:'La détersion des plaies — méthodes',
    back:'• Autolytique : corps lui-même (pansements humides)\n• Mécanique : irrigation au sérum, curette\n• Chirurgicale : excision par le médecin\n• Enzymatique : application de pommades enzymatiques\nObjectif : éliminer les tissus nécrotiques et fibrineux.' },
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'Plaies et cicatrisation', difficulty:'medium', isPublished:true,
    front:'L\'escarre — définition et stades',
    back:'Lésion cutanée d\'origine ischémique due à une pression prolongée sur les tissus.\nStades (European Pressure Ulcer Advisory Panel) :\n• Stade 1 : érythème non blanchissable\n• Stade 2 : phlyctène ou abrasion superficielle\n• Stade 3 : perte de substance (fascia non atteint)\n• Stade 4 : nécrose profonde (os, tendon, muscle)' },

  // Chapitre : Brûlures
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'Brûlures', difficulty:'easy', isPublished:true,
    front:'La classification des brûlures par profondeur',
    back:'• 1er degré : épiderme seul (érythème, pas de phlyctène) → guérison spontanée\n• 2e degré superficiel : derme superficiel (phlyctènes, douloureux)\n• 2e degré profond : derme profond (insensible, livide)\n• 3e degré : destruction totale (peau cartonnée, insensible) → greffe nécessaire' },
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'Brûlures', difficulty:'medium', isPublished:true,
    front:'La règle des 9 de Wallace (surface brûlée)',
    back:'Estimation de la Surface Corporelle Brûlée (SCB) :\n• Tête et cou : 9%\n• Chaque membre supérieur : 9%\n• Tronc antérieur : 18%\n• Tronc postérieur : 18%\n• Chaque membre inférieur : 18%\n• Périnée : 1%' },
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'Brûlures', difficulty:'medium', isPublished:true,
    front:'Les brûlures graves — critères de gravité',
    back:'• SCB > 25% adulte (> 10% enfant)\n• Brûlures 3e degré > 10%\n• Localisation : face, mains, périnée, articulations\n• Inhalation de fumées\n• Terrain : âges extrêmes, pathologies associées\n→ Orientation en centre de brûlés.' },
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'Brûlures', difficulty:'easy', isPublished:true,
    front:'Premiers soins face à une brûlure thermique',
    back:'1. Refroidissement : eau tempérée (15-25°C) pendant 15–20 min → analgésie et limiter l\'extension\n2. Retirer bijoux et vêtements non adhérents\n3. Couvrir d\'un pansement propre\n4. Ne pas percer les phlyctènes\n5. Appel du 15 si brûlure étendue ou grave' },

  // Chapitre : Fractures et traumatismes ostéo-articulaires
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'Fractures', difficulty:'easy', isPublished:true,
    front:'Fracture — définition et types',
    back:'Rupture de la continuité d\'un os.\n• Fermée : peau intacte\n• Ouverte : communication avec l\'extérieur (risque infectieux +++)\n• Complète vs incomplète\n• Déplacée vs non déplacée\n• Comminutive : en plusieurs fragments' },
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'Fractures', difficulty:'medium', isPublished:true,
    front:'Les signes cliniques d\'une fracture',
    back:'• Douleur vive et localisée\n• Impotence fonctionnelle\n• Déformation du membre\n• Gonflement (œdème, hématome)\n• Mobilité anormale / crépitement osseux\nNe jamais mobiliser sans immobilisation préalable.' },
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'Fractures', difficulty:'medium', isPublished:true,
    front:'La consolidation osseuse — durées',
    back:'3 phases :\n1. Hématome péri-fracturaire (J0–J7)\n2. Cal cartilagineux (2–4 sem)\n3. Cal osseux + remodelage (4–12 sem)\nDurées selon localisation :\n• Poignet : 4–6 sem\n• Cheville : 6–8 sem\n• Fémur : 3–4 mois\n• Plateau tibial : 2–3 mois' },
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'Fractures', difficulty:'medium', isPublished:true,
    front:'Le syndrome des loges — signes cliniques',
    back:'Compression des nerfs et vaisseaux dans une loge musculaire rigide.\nSigne clinique : les 6 P :\n• Pain (douleur intense, irréductible)\n• Pressure (tension loge)\n• Paresthésie\n• Paralysie\n• Pallor (pâleur)\n• Pulselessness (abolition pouls)\n→ Urgence chirurgicale (fasciotomie)' },
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'Fractures', difficulty:'easy', isPublished:true,
    front:'L\'entorse — définition et grades',
    back:'Étirement ou déchirure des ligaments d\'une articulation sans luxation.\n• Grade 1 : élongation sans rupture (légère)\n• Grade 2 : rupture partielle (modérée)\n• Grade 3 : rupture totale (grave, instabilité)\nTraitement RICE : Rest, Ice, Compression, Elevation.' },
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'Fractures', difficulty:'medium', isPublished:true,
    front:'La luxation — définition et prise en charge',
    back:'Perte permanente du contact entre les surfaces articulaires.\nSignes : douleur, déformation, impotence fonctionnelle.\nPEC : analgésie, radio (éliminer fracture associée), réduction (souvent sous AG ou AL), immobilisation.' },

  // Chapitre : État de choc
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'État de choc', difficulty:'medium', isPublished:true,
    front:'L\'état de choc — définition',
    back:'Défaillance circulatoire aiguë entraînant une inadéquation entre apport et besoins en O₂ des tissus → hypoxie tissulaire → défaillance organique.' },
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'État de choc', difficulty:'medium', isPublished:true,
    front:'Les 4 types de choc',
    back:'1. Choc hypovolémique : hémorragie, déshydratation\n2. Choc cardiogénique : insuffisance du cœur (IDM, trouble rythme)\n3. Choc distributif : vasodilatation massive (septique, anaphylactique, neurogénique)\n4. Choc obstructif : obstacle mécanique (tamponnade, EP massive)' },
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'État de choc', difficulty:'medium', isPublished:true,
    front:'Les signes cliniques du choc hypovolémique',
    back:'• Hypotension artérielle (PAS < 90 mmHg)\n• Tachycardie compensatrice (> 100 bpm)\n• Marbrures, extrémités froides, pâleur\n• Oligurie (< 0,5 mL/kg/h)\n• Agitation puis troubles de conscience\n• Temps de recoloration cutanée > 3 sec' },
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'État de choc', difficulty:'medium', isPublished:true,
    front:'Le choc anaphylactique — signes et traitement',
    back:'Signes : urticaire, œdème de Quincke, bronchospasme, hypotension, tachycardie.\nTraitement immédiat :\n1. Adrénaline IM 0,5 mg (cuisse)\n2. Allonger le patient (jambes surélevées)\n3. Appel SAMU (15)\n4. Remplissage vasculaire\n5. Antihistaminiques et corticoïdes en 2e intention' },
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'État de choc', difficulty:'medium', isPublished:true,
    front:'La classification de l\'hémorragie (4 stades)',
    back:'• Stade 1 : < 15% volémie — pas de signe clinique notable\n• Stade 2 : 15–30% — tachycardie, anxiété\n• Stade 3 : 30–40% — hypotension, confusion, oligurie\n• Stade 4 : > 40% — choc irréversible, décès imminent' },

  // Chapitre : Traumatismes crâniens
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'Traumatismes crâniens', difficulty:'medium', isPublished:true,
    front:'La commotion cérébrale — définition et signes',
    back:'Traumatisme crânien avec dysfonction neurologique transitoire sans lésion anatomique visible.\nSignes : perte de connaissance brève (< 30 min), amnésie, céphalées, nausées, vertiges.\nSurveillance neurologique rapprochée 24h.' },
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'Traumatismes crâniens', difficulty:'medium', isPublished:true,
    front:'L\'hématome extradural (HED) — présentation clinique',
    back:'Saignement artériel (artère méningée moyenne) entre crâne et dure-mère.\nTriade classique :\n1. Traumatisme + perte de connaissance initiale\n2. Intervalle libre (patient reprend connaissance)\n3. Dégradation rapide → coma\n→ Urgence neurochirurgicale.' },
  { semester:'Semestre 1', category:'UE 2.4 - Processus traumatiques', chapter:'Traumatismes crâniens', difficulty:'medium', isPublished:true,
    front:'L\'HTIC (hypertension intracrânienne) — signes',
    back:'Triade de Cushing :\n• Hypertension artérielle\n• Bradycardie\n• Troubles respiratoires\nAutres signes : céphalées (pire le matin), vomissements en jet, œdème papillaire, baisse de conscience.' },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 2.10 – Infectiologie, hygiène (~42 cartes)
  // ═══════════════════════════════════════════════════════════════════════════

  // Chapitre : Agents infectieux
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Agents infectieux', difficulty:'easy', isPublished:true,
    front:'Les principaux agents infectieux — classification',
    back:'1. Bactéries : unicellulaires procaryotes (ex : Staphylocoque, E. coli)\n2. Virus : parasites intracellulaires obligatoires (ex : VIH, SARS-CoV-2)\n3. Champignons (mycoses) : ex : Candida, Aspergillus\n4. Parasites : ex : Plasmodium (paludisme), oxyures\n5. Prions : protéines mal conformées (MCJ)' },
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Agents infectieux', difficulty:'medium', isPublished:true,
    front:'Bactéries Gram+ vs Gram- — différence fondamentale',
    back:'Coloration de Gram :\n• Gram+ (violet) : paroi épaisse en peptidoglycane (ex : Staphylocoque, Streptocoque)\n• Gram- (rose) : double membrane + LPS endotoxine (ex : E. coli, Pseudomonas)\nImpact : sensibilité différente aux antibiotiques.' },
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Agents infectieux', difficulty:'medium', isPublished:true,
    front:'La résistance bactérienne aux antibiotiques — mécanismes',
    back:'• Production d\'enzymes dégradant l\'antibiotique (ex : bêta-lactamases)\n• Modification de la cible\n• Imperméabilité membranaire\n• Efflux actif\nBMR : Bactérie Multi-Résistante (ex : SARM, EBLSE, ERV)' },
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Agents infectieux', difficulty:'easy', isPublished:true,
    front:'La différence entre infection et colonisation',
    back:'• Colonisation : présence d\'un micro-organisme sans signe clinique ni réaction inflammatoire (portage sain)\n• Infection : micro-organisme envahit les tissus → réaction de l\'hôte → signes cliniques (fièvre, inflammation…)' },
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Agents infectieux', difficulty:'medium', isPublished:true,
    front:'Le sepsis — définition (Sepsis-3, 2016)',
    back:'Dysfonction d\'organe menaçant le pronostic vital, causée par une réponse dérégulée de l\'hôte à une infection.\nCritères SOFA : score ≥ 2.\nChoc septique : sepsis + vasopresseurs + lactate > 2 mmol/L.' },

  // Chapitre : Chaîne de l'infection
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Chaîne de l\'infection', difficulty:'easy', isPublished:true,
    front:'La chaîne épidémiologique de l\'infection — 6 maillons',
    back:'1. Agent infectieux\n2. Réservoir (humain, animal, environnement)\n3. Porte de sortie\n4. Mode de transmission\n5. Porte d\'entrée\n6. Hôte réceptif\nRompre UN maillon suffit à stopper la transmission.',
    hint:'Agent → Réservoir → Sortie → Transmission → Entrée → Hôte' },
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Chaîne de l\'infection', difficulty:'medium', isPublished:true,
    front:'Les modes de transmission des infections',
    back:'• Contact direct (mains, peau à peau)\n• Contact indirect (matériel souillé)\n• Gouttelettes (< 1m, toux : grippe, COVID)\n• Aérosols/air (> 1m : tuberculose, rougeole, varicelle)\n• Voie fécale-orale (gastroentérites)\n• Voie sanguine (VIH, hépatites B/C)' },
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Chaîne de l\'infection', difficulty:'medium', isPublished:true,
    front:'Les infections nosocomiales (IAS) — définition',
    back:'Infection Associée aux Soins (IAS) : infection contractée lors d\'une prise en charge médicale (ambulatoire ou hospitalière), absente à l\'admission.\nDélai conventionnel : ≥ 48h après l\'admission (ou ≥ 30 jours pour ISO).' },
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Chaîne de l\'infection', difficulty:'medium', isPublished:true,
    front:'Les principales IAS et leurs agents',
    back:'• Infections urinaires (40%) : E. coli, sonde urinaire\n• Pneumopathies (15%) : Pseudomonas, ventilation mécanique\n• ISO (site opératoire) : Staphylocoque\n• Bactériémies (10%) : cathéter central, Staphylocoque\n• DACD : Clostridium difficile après antibiothérapie' },

  // Chapitre : Précautions standard
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Précautions standard', difficulty:'easy', isPublished:true,
    front:'Les précautions standard (PS) — principe',
    back:'S\'appliquent pour TOUS les patients, quel que soit leur statut infectieux.\nConsidèrent que tout sang, liquide biologique, peau lésée et muqueuse sont potentiellement infectieux.\nBase de la prévention des IAS.' },
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Précautions standard', difficulty:'medium', isPublished:true,
    front:'Les 11 mesures des précautions standard',
    back:'1. Hygiène des mains\n2. Port de gants\n3. Port de masque/lunettes/surblouse si projection\n4. Matériel piquant-coupant (OPCT) → conteneur rigide\n5. Matériel souillé → circuit des déchets\n6. Surfaces → décontamination\n7. Linge souillé → circuit adapté\n8. Transport des prélèvements → flacon étanche\n9. Environnement → bionettoyage\n10. AES → protocole immédiat\n11. Hygiène respiratoire' },
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Précautions standard', difficulty:'medium', isPublished:true,
    front:'Les précautions complémentaires — 3 types',
    back:'En plus des PS, selon la voie de transmission :\n• PC Contact (PCC) : SARM, ERV, C. difficile → gants + surblouse\n• PC Gouttelettes (PCG) : grippe, méningocoque → masque chirurgical\n• PC Air (PCA) : tuberculose, rougeole, varicelle → masque FFP2, chambre à pression négative' },
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Précautions standard', difficulty:'medium', isPublished:true,
    front:'L\'AES (Accident d\'Exposition au Sang) — conduite à tenir',
    back:'1. Premiers soins : nettoyage eau + savon, rinçage, antisepsie (Dakin ou alcool 70°)\n2. Déclaration d\'AT dans les 24h\n3. Évaluation du risque VIH → TPE (Trithérapie) si nécessaire (< 4h)\n4. Sérologies : VIH, VHB, VHC (patient source + soignant)\n5. Suivi sérologique 3–6 mois' },

  // Chapitre : Hygiène des mains
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Hygiène des mains', difficulty:'easy', isPublished:true,
    front:'La friction hydro-alcoolique (FHA) — indications',
    back:'Technique de référence pour l\'hygiène des mains (si mains non visiblement souillées).\nDurée : 20–30 secondes.\nEfficacité supérieure au lavage simple.\nHABM : Hygiène des mains — première action préventive des IAS.' },
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Hygiène des mains', difficulty:'medium', isPublished:true,
    front:'Les 5 indications à l\'hygiène des mains (OMS — "Mes 5 moments")',
    back:'1. Avant de toucher le patient\n2. Avant un geste aseptique\n3. Après risque d\'exposition à un liquide biologique\n4. Après avoir touché le patient\n5. Après contact avec l\'environnement du patient' },
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Hygiène des mains', difficulty:'medium', isPublished:true,
    front:'Lavage simple vs lavage antiseptique vs FHA',
    back:'• Lavage simple (savon doux) : mains visiblement souillées, retrait spores C. difficile\n• Lavage antiseptique (savon antiseptique) : avant acte chirurgical\n• FHA : méthode de référence pour tous les soins courants (+ rapide, + efficace, moins irritant)' },

  // Chapitre : Stérilisation et désinfection
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Stérilisation et désinfection', difficulty:'medium', isPublished:true,
    front:'Niveaux de traitement du matériel médical — classification de Spaulding',
    back:'• Critique (pénètre tissu stérile) → stérilisation\n• Semi-critique (muqueuse intacte) → désinfection haut niveau (DHN)\n• Non critique (peau saine) → désinfection bas/moyen niveau\nEx : endoscope = semi-critique → DHA.' },
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Stérilisation et désinfection', difficulty:'easy', isPublished:true,
    front:'La stérilisation — méthodes principales',
    back:'• Chaleur humide (autoclave) : 134°C, 18 min — méthode de référence\n• Chaleur sèche (poupinel) : 180°C, 60 min — matériel ne supportant pas la vapeur\n• OPA (oxyde d\'éthylène/plasma) : matériel thermosensible\n• Irradiation (industrielle)' },
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Stérilisation et désinfection', difficulty:'easy', isPublished:true,
    front:'L\'antisepsie — définition et différence avec désinfection',
    back:'• Antisepsie : traitement des tissus vivants (peau, muqueuses) pour détruire ou inhiber les micro-organismes\n• Désinfection : traitement des surfaces inertes (matériel, environnement)\nEx antiseptiques : Bétadine, Dakin, alcool 70°, chlorhexidine.' },
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Stérilisation et désinfection', difficulty:'medium', isPublished:true,
    front:'Le bionettoyage — définition et étapes',
    back:'Association d\'un nettoyage et d\'une désinfection des surfaces.\nÉtapes :\n1. Pré-désinfection / détrempage\n2. Rinçage\n3. Désinfection (produit adapté)\n4. Rinçage (si nécessaire)\n5. Séchage' },

  // Chapitre : Vaccinations et immunité
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Vaccinations et immunité', difficulty:'easy', isPublished:true,
    front:'Immunité innée vs immunité adaptative',
    back:'• Innée : non spécifique, immédiate (barrières cutanéo-muqueuses, phagocytes, NK, complément)\n• Adaptative : spécifique, développée après contact avec l\'antigène\n  - Cellulaire : lymphocytes T cytotoxiques\n  - Humorale : lymphocytes B → anticorps' },
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Vaccinations et immunité', difficulty:'medium', isPublished:true,
    front:'L\'immunité active vs passive',
    back:'• Active : production d\'anticorps par le propre système immunitaire\n  - Naturelle : suite à infection\n  - Artificielle : vaccination\n• Passive : apport d\'anticorps extérieurs\n  - Naturelle : passage transplacentaire IgG, allaitement IgA\n  - Artificielle : immunoglobulines thérapeutiques' },
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Vaccinations et immunité', difficulty:'medium', isPublished:true,
    front:'Les vaccinations obligatoires des professionnels de santé (France)',
    back:'• Hépatite B (anti-HBs ≥ 100 UI/L requis)\n• Diphtérie-Tétanos-Polio (DTPa)\n• Covid-19 (décret 2021)\n• Grippe saisonnière (recommandée, non obligatoire en 2024)\nBase légale : art. L. 3111-4 du CSP.' },
  { semester:'Semestre 1', category:'UE 2.10 - Infectiologie, hygiène', chapter:'Vaccinations et immunité', difficulty:'easy', isPublished:true,
    front:'Les effets indésirables courants des vaccins',
    back:'• Locaux : douleur, rougeur, œdème au site d\'injection (fréquents, bénins)\n• Généraux : fièvre, fatigue, myalgies (réaction inflammatoire normale)\n• Rares et graves : réaction anaphylactique (surveillance 15-30 min post-vaccination)' },

];
