// ─── PARTIE 1 : UE 1.1 · UE 1.3 ────────────────────────────────────────────
module.exports = [

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 1.1 – Psychologie, sociologie, anthropologie (~42 cartes)
  // ═══════════════════════════════════════════════════════════════════════════

  // Chapitre : Introduction à la psychologie
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Introduction à la psychologie', difficulty:'easy', isPublished:true,
    front:'Définition de la psychologie',
    back:'Science qui étudie les comportements humains et les processus mentaux (pensées, émotions, motivations, perceptions).' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Introduction à la psychologie', difficulty:'easy', isPublished:true,
    front:'Qui a fondé la psychanalyse ?',
    back:'Sigmund Freud (1856-1939). Il théorise que les comportements sont en grande partie déterminés par l\'inconscient.' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Introduction à la psychologie', difficulty:'medium', isPublished:true,
    front:'Les 3 instances psychiques selon Freud',
    back:'• Le Ça : pulsions inconscientes\n• Le Moi : instance réaliste médiateur\n• Le Surmoi : interdits et idéaux intériorisés' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Introduction à la psychologie', difficulty:'medium', isPublished:true,
    front:'Définition de la résilience',
    back:'Capacité d\'une personne à se reconstruire positivement après un traumatisme, en mobilisant ses ressources internes et externes.' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Introduction à la psychologie', difficulty:'medium', isPublished:true,
    front:'Le transfert dans la relation soignant-soigné',
    back:'Phénomène par lequel le patient projette sur le soignant des sentiments liés à des figures importantes de son passé (parents, etc.).' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Introduction à la psychologie', difficulty:'medium', isPublished:true,
    front:'Le contre-transfert',
    back:'Réactions émotionnelles inconscientes du soignant envers le patient, en lien avec sa propre histoire personnelle. Doit être identifié pour préserver la qualité du soin.' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Introduction à la psychologie', difficulty:'easy', isPublished:true,
    front:'Modèle bio-psycho-social (George Engel, 1977)',
    back:'Modèle intégrant 3 dimensions pour comprendre la santé :\n• Biologique (corps)\n• Psychologique (émotions, cognition)\n• Sociale (environnement, relations)' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Introduction à la psychologie', difficulty:'medium', isPublished:true,
    front:'La relation d\'aide selon Carl Rogers — 3 conditions',
    back:'1. Empathie : comprendre le vécu de l\'autre\n2. Congruence : authenticité du soignant\n3. Acceptation inconditionnelle : sans jugement' },

  // Chapitre : Psychologie du développement
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Psychologie du développement', difficulty:'medium', isPublished:true,
    front:'Les 4 stades de Piaget',
    back:'1. Sensori-moteur (0-2 ans) : action et sens\n2. Préopératoire (2-7 ans) : langage, égocentrisme\n3. Opérations concrètes (7-12 ans) : logique\n4. Formel (12+) : abstraction',
    hint:'Sensori → Préop → Concret → Formel' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Psychologie du développement', difficulty:'easy', isPublished:true,
    front:'La permanence de l\'objet (Piaget)',
    back:'Acquisition vers 18-24 mois (fin du stade sensori-moteur) : comprendre qu\'un objet continue d\'exister même s\'il n\'est plus visible.' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Psychologie du développement', difficulty:'medium', isPublished:true,
    front:'L\'égocentrisme intellectuel (Piaget)',
    back:'Caractéristique du stade préopératoire (2-7 ans) : l\'enfant ne peut pas adopter le point de vue d\'autrui, il centre tout sur sa propre perception.' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Psychologie du développement', difficulty:'medium', isPublished:true,
    front:'La théorie de l\'attachement (Bowlby)',
    back:'Le lien affectif précoce entre l\'enfant et son caregiver est fondamental pour le développement psychologique.\n• Attachement sécure : base de sécurité pour l\'exploration\n• Attachement insécure : anxieux, évitant ou désorganisé' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Psychologie du développement', difficulty:'medium', isPublished:true,
    front:'Les 8 stades d\'Erikson — principe',
    back:'Erikson décrit 8 crises psychosociales à résoudre tout au long de la vie. Ex :\n• 0-1 an : Confiance vs Méfiance\n• Ado : Identité vs Confusion\n• Adulte jeune : Intimité vs Isolement' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Psychologie du développement', difficulty:'easy', isPublished:true,
    front:'Zone proximale de développement (Vygotsky)',
    back:'Espace entre ce que l\'enfant peut faire seul et ce qu\'il peut faire avec l\'aide d\'un adulte ou d\'un pair plus compétent. C\'est la zone d\'apprentissage optimale.' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Psychologie du développement', difficulty:'medium', isPublished:true,
    front:'La pyramide des besoins de Maslow (5 niveaux)',
    back:'De la base au sommet :\n1. Besoins physiologiques (manger, dormir)\n2. Sécurité\n3. Appartenance / Amour\n4. Estime de soi\n5. Accomplissement de soi',
    hint:'Physio → Sécu → Appart → Estime → Accom' },

  // Chapitre : Mécanismes de défense
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Mécanismes de défense', difficulty:'medium', isPublished:true,
    front:'Le mécanisme de défense : la projection',
    back:'Attribuer à autrui ses propres pensées, désirs ou sentiments inacceptables que l\'on refuse de reconnaître en soi.' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Mécanismes de défense', difficulty:'medium', isPublished:true,
    front:'Le mécanisme de défense : le déni',
    back:'Refuser de reconnaître la réalité d\'une situation douloureuse ou menaçante (ex : refuser d\'admettre une maladie grave).' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Mécanismes de défense', difficulty:'medium', isPublished:true,
    front:'Le mécanisme de défense : la régression',
    back:'Retour à des comportements appartenant à un stade de développement antérieur face à l\'angoisse (ex : adulte qui se met en position fœtale).' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Mécanismes de défense', difficulty:'medium', isPublished:true,
    front:'Le mécanisme de défense : la sublimation',
    back:'Transformation d\'une pulsion inacceptable en activité socialement valorisée (ex : agressivité canalisée dans le sport ou l\'art).' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Mécanismes de défense', difficulty:'hard', isPublished:true,
    front:'Le mécanisme de défense : la formation réactionnelle',
    back:'Transformer une pulsion inacceptable en son contraire (ex : une haine inconsciente se manifeste par une gentillesse excessive).' },

  // Chapitre : Sociologie des soins
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Sociologie des soins', difficulty:'easy', isPublished:true,
    front:'Socialisation primaire vs secondaire',
    back:'• Primaire : intégration des normes dans l\'enfance au sein de la famille\n• Secondaire : apprentissage de nouveaux rôles à l\'âge adulte (école, travail, pairs)' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Sociologie des soins', difficulty:'medium', isPublished:true,
    front:'Le rôle de malade selon Talcott Parsons',
    back:'Statut social légitime accordant 2 droits (dispense de rôles habituels, absence de responsabilité) en échange de 2 obligations (chercher à guérir, consulter un médecin).' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Sociologie des soins', difficulty:'medium', isPublished:true,
    front:'La stigmatisation (Goffman)',
    back:'Processus par lequel un attribut (maladie, handicap, différence) discrédite l\'individu et réduit son identité à cette seule caractéristique.' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Sociologie des soins', difficulty:'medium', isPublished:true,
    front:'Les inégalités sociales de santé',
    back:'Variations systématiques et évitables de l\'état de santé selon la position sociale. Liées aux conditions de vie, de travail et d\'accès aux soins.' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Sociologie des soins', difficulty:'hard', isPublished:true,
    front:'La médicalisation de la société',
    back:'Processus par lequel des phénomènes de la vie courante (naissance, vieillesse, deuil, obésité) sont de plus en plus définis et traités comme des problèmes médicaux.' },

  // Chapitre : Anthropologie et santé
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Anthropologie et santé', difficulty:'easy', isPublished:true,
    front:'L\'ethnocentrisme',
    back:'Tendance à juger les autres cultures à partir des valeurs de sa propre culture, en la considérant comme référence supérieure.' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Anthropologie et santé', difficulty:'medium', isPublished:true,
    front:'Le relativisme culturel',
    back:'Principe méthodologique selon lequel chaque culture doit être comprise et évaluée dans son propre contexte, sans jugement extérieur.' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Anthropologie et santé', difficulty:'medium', isPublished:true,
    front:'Les 3 dimensions de la maladie (anthropologie)',
    back:'• Disease : dysfonction biologique objectivable\n• Illness : vécu subjectif de la maladie\n• Sickness : construction socioculturelle de la maladie' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Anthropologie et santé', difficulty:'medium', isPublished:true,
    front:'La compétence culturelle en soins infirmiers',
    back:'Capacité du soignant à reconnaître, comprendre et respecter les valeurs, croyances et pratiques culturelles du patient pour adapter les soins.' },
  { semester:'Semestre 1', category:'UE 1.1 - Psychologie, sociologie, anthropologie', chapter:'Anthropologie et santé', difficulty:'easy', isPublished:true,
    front:'Rite de passage (anthropologie)',
    back:'Cérémonie qui marque et légitime le changement de statut social d\'un individu au sein d\'une communauté (naissance, mariage, mort, initiation).' },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 1.3 – Législation, éthique, déontologie (~42 cartes)
  // ═══════════════════════════════════════════════════════════════════════════

  // Chapitre : Droits des patients
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Droits des patients', difficulty:'easy', isPublished:true,
    front:'Loi du 4 mars 2002 (loi Kouchner)',
    back:'Loi relative aux droits des malades et à la qualité du système de santé. Consacre :\n• Droit à l\'information\n• Consentement éclairé\n• Accès au dossier médical\n• Personne de confiance' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Droits des patients', difficulty:'medium', isPublished:true,
    front:'Le consentement éclairé — conditions',
    back:'Il doit être :\n• Libre (sans contrainte)\n• Éclairé (information loyale et adaptée)\n• Révocable à tout moment\n• Donné par personne capable ou représentant légal' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Droits des patients', difficulty:'medium', isPublished:true,
    front:'La personne de confiance (loi 2002)',
    back:'Personne librement choisie par le patient pour :\n• L\'accompagner dans ses démarches\n• Être consultée si le patient ne peut s\'exprimer\n• Être son porte-parole (non représentant légal)' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Droits des patients', difficulty:'medium', isPublished:true,
    front:'Les directives anticipées',
    back:'Instructions écrites rédigées à l\'avance par toute personne majeure indiquant ses souhaits sur les conditions de fin de vie, en cas d\'impossibilité à les exprimer. Révisables et révocables.' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Droits des patients', difficulty:'medium', isPublished:true,
    front:'Droit d\'accès au dossier médical',
    back:'Depuis la loi 2002 : le patient accède directement à son dossier (sans intermédiaire médical).\n• Délai : 8 jours (48h si hospitalisation récente)\n• Conservation : 20 ans après dernière hospitalisation' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Droits des patients', difficulty:'hard', isPublished:true,
    front:'Loi Claeys-Leonetti 2016 — apports',
    back:'• Droit à la sédation profonde et continue jusqu\'au décès\n• Renforce la valeur des directives anticipées\n• Interdit l\'obstination déraisonnable\n• S\'applique aux patients dont le pronostic vital est engagé à court terme' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Droits des patients', difficulty:'easy', isPublished:true,
    front:'L\'obstination déraisonnable',
    back:'Fait de poursuivre des traitements inutiles, disproportionnés ou n\'ayant d\'autre effet que le maintien artificiel de la vie. Interdite en France (art. L. 1110-5-1 CSP).' },

  // Chapitre : Secret professionnel
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Secret professionnel', difficulty:'easy', isPublished:true,
    front:'Le secret professionnel infirmier — fondements',
    back:'Fondé sur :\n• Art. L. 1110-4 du Code de la santé publique\n• Art. 226-13 du Code pénal\nProtège toutes les informations recueillies dans le cadre de la prise en charge.' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Secret professionnel', difficulty:'medium', isPublished:true,
    front:'Secret partagé vs secret professionnel',
    back:'• Secret professionnel : s\'impose envers toute personne non impliquée dans le soin\n• Secret partagé : peut être levé au sein de l\'équipe soignante directement impliquée dans la prise en charge du patient' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Secret professionnel', difficulty:'medium', isPublished:true,
    front:'Exceptions légales au secret professionnel',
    back:'• Signalement de maltraitance (enfants, personnes vulnérables)\n• Déclarations obligatoires (maladies contagieuses, naissance, décès)\n• Réquisition judiciaire\n• Levée par le patient lui-même' },

  // Chapitre : Déontologie infirmière
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Déontologie infirmière', difficulty:'easy', isPublished:true,
    front:'Code de déontologie infirmier — intégration légale',
    back:'Intégré dans le Code de la santé publique par décret du 25 novembre 2016 (art. R. 4312-1 à R. 4312-92).' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Déontologie infirmière', difficulty:'medium', isPublished:true,
    front:'Obligation de moyens vs obligation de résultat',
    back:'• Obligation de moyens : mettre en œuvre tous les moyens disponibles conformes aux bonnes pratiques (infirmier)\n• Obligation de résultat : s\'engager sur un résultat précis (ex : contrat de transport)' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Déontologie infirmière', difficulty:'medium', isPublished:true,
    front:'Le rôle propre infirmier',
    back:'Soins relevant de l\'initiative de l\'infirmier sans prescription médicale (art. R. 4311-3 CSP) :\n• Surveillance\n• Nursing\n• Éducation thérapeutique\n• Soutien psychologique' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Déontologie infirmière', difficulty:'medium', isPublished:true,
    front:'Les 3 types de responsabilité infirmière',
    back:'1. Civile : réparation d\'un préjudice causé\n2. Pénale : sanction d\'une infraction (crime, délit)\n3. Disciplinaire/Ordinale : sanctions professionnelles (Ordre, employeur)',
    hint:'Civil → répare, Pénal → sanctionne, Disciplinaire → interdit de pratiquer' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Déontologie infirmière', difficulty:'medium', isPublished:true,
    front:'La règle des 5B (sécurité médicamenteuse)',
    back:'Avant toute administration :\n1. Bon médicament\n2. Bonne dose\n3. Bon patient\n4. Bonne voie\n5. Bon moment' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Déontologie infirmière', difficulty:'easy', isPublished:true,
    front:'Le DPC (Développement Professionnel Continu)',
    back:'Obligation légale pour tous les infirmiers de maintenir et développer leurs compétences tout au long de leur carrière. Comprend formation, évaluation des pratiques et gestion des risques.' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Déontologie infirmière', difficulty:'medium', isPublished:true,
    front:'EIAS — Événement Indésirable Associé aux Soins',
    back:'Événement inattendu lié aux soins ayant entraîné ou risqué d\'entraîner un dommage au patient.\nDéclaration obligatoire, non punitive, dans une logique d\'amélioration continue de la qualité.' },

  // Chapitre : Éthique médicale
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Éthique médicale', difficulty:'medium', isPublished:true,
    front:'Les 4 principes de Beauchamp et Childress',
    back:'1. Autonomie : respecter les choix du patient\n2. Bienfaisance : agir pour le bien du patient\n3. Non-malfaisance : ne pas nuire (primum non nocere)\n4. Justice : équité dans les soins',
    hint:'Autonomie — Bienfaisance — Non-malfaisance — Justice' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Éthique médicale', difficulty:'easy', isPublished:true,
    front:'Primum non nocere',
    back:'"D\'abord ne pas nuire" — Principe fondamental de la non-malfaisance. Le soignant doit peser les bénéfices et les risques de chaque acte avant de l\'entreprendre.' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Éthique médicale', difficulty:'medium', isPublished:true,
    front:'La bientraitance',
    back:'Culture soignante plaçant la personne au centre :\n• Respect de la dignité et des droits\n• Attention à la singularité de chacun\n• Va au-delà de l\'absence de maltraitance' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Éthique médicale', difficulty:'medium', isPublished:true,
    front:'La dignité humaine dans les soins',
    back:'Respect de la valeur intrinsèque de chaque personne, indépendamment de son état de santé, de sa dépendance, de son statut social ou de sa capacité à communiquer.' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Éthique médicale', difficulty:'hard', isPublished:true,
    front:'Le principe du double-effet (éthique médicale)',
    back:'Autorise un acte dont l\'effet bénéfique coexiste avec un effet néfaste prévisible mais non voulu, si :\n• L\'intention est bonne\n• Le mal n\'est pas le moyen d\'obtenir le bien\n• Le bien est proportionné au mal' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Éthique médicale', difficulty:'medium', isPublished:true,
    front:'La clause de conscience',
    back:'Permet à un professionnel de santé de refuser d\'effectuer certains actes légaux contraires à ses convictions, sous condition d\'orienter le patient vers un autre professionnel.' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Éthique médicale', difficulty:'medium', isPublished:true,
    front:'La démarche collégiale (fin de vie)',
    back:'Réunion pluridisciplinaire obligatoire pour toute décision de limitation/arrêt de traitement. Réunit médecins, soignants, intègre la personne de confiance et les directives anticipées.' },

  // Chapitre : Responsabilité juridique
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Responsabilité juridique', difficulty:'medium', isPublished:true,
    front:'Faute de service vs faute personnelle (secteur public)',
    back:'• Faute de service : engage la responsabilité de l\'établissement (remplacée par l\'État)\n• Faute personnelle détachable du service : engage la responsabilité propre de l\'agent (poursuites civiles/pénales personnelles)' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Responsabilité juridique', difficulty:'medium', isPublished:true,
    front:'L\'erreur médicamenteuse — définition',
    back:'Tout écart non intentionnel entre la prescription et ce qui est réellement préparé, dispensé ou administré :\n• Mauvais patient\n• Mauvais médicament\n• Mauvaise dose\n• Mauvaise voie\n• Mauvais moment' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Responsabilité juridique', difficulty:'easy', isPublished:true,
    front:'Traçabilité des soins — importance médicolégale',
    back:'"Ce qui n\'est pas tracé est réputé ne pas avoir été fait." La traçabilité dans le dossier patient a valeur de preuve en cas de litige judiciaire.' },
  { semester:'Semestre 1', category:'UE 1.3 - Législation, éthique, déontologie', chapter:'Responsabilité juridique', difficulty:'medium', isPublished:true,
    front:'Que faire face à une prescription dangereuse ?',
    back:'1. Contacter le prescripteur et exposer ses doutes\n2. Ne pas exécuter si le danger est confirmé\n3. Tracer le refus dans le dossier patient\n4. Alerter la hiérarchie si nécessaire' },
];
