// ─── PARTIE 3 : UE 2.11 · UE 3.1 · UE 4.1 · UE 5.1 · UE 6.1 · UE 6.2 ───────
module.exports = [

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 2.11 – Pharmacologie et thérapeutiques (~42 cartes)
  // ═══════════════════════════════════════════════════════════════════════════

  // Chapitre : Principes de pharmacologie
  { semester:'Semestre 1', category:'UE 2.11 - Pharmacologie et thérapeutiques', chapter:'Principes de pharmacologie', difficulty:'easy', isPublished:true,
    front:'Pharmacocinétique vs pharmacodynamique',
    back:'• Pharmacocinétique : ce que l\'organisme fait au médicament (ADME)\n• Pharmacodynamique : ce que le médicament fait à l\'organisme (mécanisme d\'action, effets)' },
  { semester:'Semestre 1', category:'UE 2.11 - Pharmacologie et thérapeutiques', chapter:'Principes de pharmacologie', difficulty:'medium', isPublished:true,
    front:'Les 4 étapes de la pharmacocinétique (ADME)',
    back:'1. Absorption : passage dans la circulation (selon voie d\'administration)\n2. Distribution : répartition dans les tissus (liaison protéines plasmatiques)\n3. Métabolisme : biotransformation (foie +++)\n4. Élimination : reins (urine), bile, poumons',
    hint:'Absorb → Distrib → Métab → Élim' },
  { semester:'Semestre 1', category:'UE 2.11 - Pharmacologie et thérapeutiques', chapter:'Principes de pharmacologie', difficulty:'medium', isPublished:true,
    front:'La biodisponibilité d\'un médicament',
    back:'Fraction d\'un médicament administré qui atteint la circulation systémique sous forme active.\n• IV : biodisponibilité = 100%\n• Orale : réduite par effet de premier passage hépatique\n• Facteurs : solubilité, métabolisme intestinal, liaison protéines.' },
  { semester:'Semestre 1', category:'UE 2.11 - Pharmacologie et thérapeutiques', chapter:'Principes de pharmacologie', difficulty:'medium', isPublished:true,
    front:'L\'effet de premier passage hépatique',
    back:'Métabolisation du médicament absorbé par voie orale avant d\'atteindre la circulation systémique.\nLe sang intestinal → veine porte → foie → métabolisation partielle → moins de principe actif disponible.\nEx : propranolol, morphine ont un fort premier passage hépatique.' },
  { semester:'Semestre 1', category:'UE 2.11 - Pharmacologie et thérapeutiques', chapter:'Principes de pharmacologie', difficulty:'medium', isPublished:true,
    front:'La demi-vie d\'un médicament (t½)',
    back:'Temps nécessaire pour que la concentration plasmatique diminue de moitié.\nImplications :\n• t½ court → prise fréquente ou forme LP (libération prolongée)\n• t½ long → accumulation possible\n• Équilibre atteint en ~5 demi-vies' },
  { semester:'Semestre 1', category:'UE 2.11 - Pharmacologie et thérapeutiques', chapter:'Principes de pharmacologie', difficulty:'easy', isPublished:true,
    front:'Les voies d\'administration — avantages comparés',
    back:'• IV : rapide, biodispo 100%, douloureux\n• IM : rapide, utile si inconscient\n• SC : lente, insuline, anticoagulants\n• Orale : confort, mais premier passage hépatique\n• Sublinguale : rapide, évite effet 1er passage (ex : TRINITRINE)\n• Transdermique : lente, patch, évite voie orale' },
  { semester:'Semestre 1', category:'UE 2.11 - Pharmacologie et thérapeutiques', chapter:'Principes de pharmacologie', difficulty:'medium', isPublished:true,
    front:'Les interactions médicamenteuses — types',
    back:'• Synergie (addition ou potentialisation) : effets s\'additionnent ou se multiplient\n• Antagonisme : effets s\'annulent\n• Pharmacocinétique : modification de l\'ADME d\'un médicament par un autre\n  Ex : inducteurs enzymatiques (rifampicine) → ↓ efficacité\n  Inhibiteurs enzymatiques (érythromycine) → ↑ toxicité' },

  // Chapitre : Grandes classes médicamenteuses
  { semester:'Semestre 1', category:'UE 2.11 - Pharmacologie et thérapeutiques', chapter:'Grandes classes médicamenteuses', difficulty:'medium', isPublished:true,
    front:'Les antalgiques — classification de l\'OMS (3 paliers)',
    back:'• Palier 1 : antalgiques non opioïdes (paracétamol, AINS, aspirine)\n• Palier 2 : opioïdes faibles (codéine, tramadol)\n• Palier 3 : opioïdes forts (morphine, oxycodone, fentanyl)\nChoisir selon l\'intensité de la douleur (EVA).' },
  { semester:'Semestre 1', category:'UE 2.11 - Pharmacologie et thérapeutiques', chapter:'Grandes classes médicamenteuses', difficulty:'medium', isPublished:true,
    front:'Le paracétamol — dose maximale et toxicité',
    back:'Dose maximale adulte : 4 g/24h (1 g toutes les 6h).\nSurdosage → nécrose hépatique (toxicité retardée 24–72h).\nAntidote : N-acétylcystéine (Fluimucil® IV).\nPas de contre-indication rénale (avantage vs AINS).' },
  { semester:'Semestre 1', category:'UE 2.11 - Pharmacologie et thérapeutiques', chapter:'Grandes classes médicamenteuses', difficulty:'medium', isPublished:true,
    front:'Les AINS — mécanisme et contre-indications',
    back:'Mécanisme : inhibition des COX → ↓ prostaglandines → anti-inflammatoire, antalgique, antipyrétique.\nContre-indications : ulcère gastrique, insuffisance rénale, grossesse (≥ 6 mois), hémostase perturbée.\nEffets secondaires : gastrotoxicité, néphrotoxicité, risque CV.' },
  { semester:'Semestre 1', category:'UE 2.11 - Pharmacologie et thérapeutiques', chapter:'Grandes classes médicamenteuses', difficulty:'medium', isPublished:true,
    front:'La morphine — effets et surveillance infirmière',
    back:'Opioïde fort de référence.\nEffets :\n• Antalgique puissant\n• Euphorie, sédation, constipation, rétention urinaire\n• Nausées, vomissements\n• Dépression respiratoire (surdosage)\nSurveillance : FR, SpO₂, conscience, douleur, transit.\nAntidote : Naloxone (Narcan®).' },
  { semester:'Semestre 1', category:'UE 2.11 - Pharmacologie et thérapeutiques', chapter:'Grandes classes médicamenteuses', difficulty:'medium', isPublished:true,
    front:'Les anticoagulants — héparine vs AVK vs AOD',
    back:'• Héparine (HNF, HBPM) : action rapide, parentérale, urgences, antidote (protamine)\n• AVK (warfarine, fluindione) : oral, surveillance INR (cible 2–3), antidote vitamine K\n• AOD (apixaban, rivaroxaban, dabigatran) : oral, dose fixe, pas de surveillance biologique courante, antidotes spécifiques' },
  { semester:'Semestre 1', category:'UE 2.11 - Pharmacologie et thérapeutiques', chapter:'Grandes classes médicamenteuses', difficulty:'medium', isPublished:true,
    front:'Les antibiotiques — principales classes et cibles',
    back:'• Bêta-lactamines (pénicillines, céphalos, carbapénèmes) : paroi bactérienne\n• Aminosides (gentamicine) : synthèse protéique\n• Quinolones (ciprofloxacine) : ADN gyrase\n• Macrolides (érythromycine) : synthèse protéique\n• Glycopeptides (vancomycine) : paroi → SARM' },
  { semester:'Semestre 1', category:'UE 2.11 - Pharmacologie et thérapeutiques', chapter:'Grandes classes médicamenteuses', difficulty:'medium', isPublished:true,
    front:'L\'insuline — types et durée d\'action',
    back:'• Rapide/ultrarapide (Humalog®, NovoRapid®) : 15 min – 4h\n• Semi-retard (Actrapid®) : 30 min – 8h\n• Lente/basale (Lantus®, Levemir®) : 12–24h\n→ Surveillance glycémie avant injection.\nHypoglycémie < 0,7 g/L : resucrage immédiat.' },

  // Chapitre : Règles d'administration et sécurité
  { semester:'Semestre 1', category:'UE 2.11 - Pharmacologie et thérapeutiques', chapter:'Règles d\'administration', difficulty:'easy', isPublished:true,
    front:'La règle des 5B (sécurité médicamenteuse)',
    back:'Avant toute administration :\n1. Bon médicament\n2. Bonne dose\n3. Bon patient (vérification identité)\n4. Bonne voie\n5. Bon moment\nCertains ajoutent : Bonne traçabilité (6B).' },
  { semester:'Semestre 1', category:'UE 2.11 - Pharmacologie et thérapeutiques', chapter:'Règles d\'administration', difficulty:'medium', isPublished:true,
    front:'Le circuit du médicament en milieu hospitalier',
    back:'1. Prescription médicale (informatisée)\n2. Validation pharmaceutique\n3. Préparation par l\'infirmier\n4. Administration au patient (vérification 5B)\n5. Traçabilité dans le dossier\nChaque étape est une barrière à l\'erreur médicamenteuse.' },
  { semester:'Semestre 1', category:'UE 2.11 - Pharmacologie et thérapeutiques', chapter:'Règles d\'administration', difficulty:'medium', isPublished:true,
    front:'Les effets indésirables médicamenteux — classification',
    back:'• Type A (augmenté, dose-dépendant) : prévisible, lié au mécanisme → toxicité rénale des AINS\n• Type B (bizarre, idiosyncrasique) : imprévisible, indépendant de la dose → allergie\n• Type C (chronique) : accumulation au long cours → ostéoporose sous corticoïdes\n• Type D (différé) : tératogénicité, carcinogénicité' },
  { semester:'Semestre 1', category:'UE 2.11 - Pharmacologie et thérapeutiques', chapter:'Règles d\'administration', difficulty:'medium', isPublished:true,
    front:'La surveillance d\'une perfusion IV',
    back:'Surveiller toutes les heures :\n• Débit (réglage correct)\n• Site d\'insertion : signes de phlébite (rougeur, chaleur, douleur, cordon veineux)\n• Extravasation (gonflement périveineux)\n• Signes d\'allergie ou d\'intolérance\n• Bonne identité du médicament' },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 3.1 – Raisonnement et démarche clinique infirmière (~42 cartes)
  // ═══════════════════════════════════════════════════════════════════════════

  // Chapitre : Démarche clinique
  { semester:'Semestre 1', category:'UE 3.1 - Raisonnement et démarche clinique infirmière', chapter:'Démarche clinique', difficulty:'easy', isPublished:true,
    front:'La démarche clinique infirmière — définition',
    back:'Processus intellectuel structuré et délibéré permettant à l\'infirmier d\'analyser la situation clinique d\'un patient, de poser des diagnostics infirmiers, de planifier et d\'évaluer les soins.' },
  { semester:'Semestre 1', category:'UE 3.1 - Raisonnement et démarche clinique infirmière', chapter:'Démarche clinique', difficulty:'easy', isPublished:true,
    front:'Les 5 étapes de la démarche de soins',
    back:'1. Collecte des données (recueil d\'informations)\n2. Analyse et interprétation (diagnostics infirmiers)\n3. Planification des soins (objectifs, interventions)\n4. Réalisation des soins\n5. Évaluation des résultats',
    hint:'Collecte → Analyse → Plan → Réalisation → Éval' },
  { semester:'Semestre 1', category:'UE 3.1 - Raisonnement et démarche clinique infirmière', chapter:'Démarche clinique', difficulty:'medium', isPublished:true,
    front:'Le diagnostic infirmier — structure NANDA',
    back:'Formulation en 3 parties (PES) :\n• Problème : libellé du diagnostic\n• Étiologie : facteurs favorisants (lié à…)\n• Signes : manifestations cliniques (se manifestant par…)\nEx : "Douleur aiguë liée à une fracture se manifestant par une EVA à 7/10"' },
  { semester:'Semestre 1', category:'UE 3.1 - Raisonnement et démarche clinique infirmière', chapter:'Démarche clinique', difficulty:'medium', isPublished:true,
    front:'Diagnostic infirmier vs diagnostic médical',
    back:'• Médical : identifie une pathologie, pose par le médecin (ex : pneumonie)\n• Infirmier : identifie la réponse du patient à la pathologie, orienté soin (ex : "Altération des échanges gazeux" ou "Anxiété liée à la dyspnée")\nL\'infirmier n\'a pas le droit de poser un diagnostic médical.' },
  { semester:'Semestre 1', category:'UE 3.1 - Raisonnement et démarche clinique infirmière', chapter:'Démarche clinique', difficulty:'medium', isPublished:true,
    front:'Les objectifs de soins — critères SMART',
    back:'Un objectif doit être :\n• Spécifique\n• Mesurable\n• Atteignable\n• Réaliste\n• Temporellement défini\nEx : "Le patient marchera 50m avec aide dans les 48h"' },

  // Chapitre : Recueil de données
  { semester:'Semestre 1', category:'UE 3.1 - Raisonnement et démarche clinique infirmière', chapter:'Recueil de données', difficulty:'easy', isPublished:true,
    front:'Les sources de données en démarche clinique',
    back:'• Primaires : informations données par le patient lui-même (anamnèse, ressenti)\n• Secondaires : famille, dossier médical, autres soignants, résultats biologiques, imagerie\n• Objectives : mesurables (TA, SpO₂, température)\n• Subjectives : ressenties par le patient (douleur, anxiété)' },
  { semester:'Semestre 1', category:'UE 3.1 - Raisonnement et démarche clinique infirmière', chapter:'Recueil de données', difficulty:'medium', isPublished:true,
    front:'L\'entretien infirmier — principes',
    back:'• Se présenter et expliquer l\'objectif\n• Lieu calme, préserver la confidentialité\n• Questions ouvertes puis fermées\n• Écoute active, pas de jugement\n• Reformuler pour valider la compréhension\n• Tracer les informations recueillies' },
  { semester:'Semestre 1', category:'UE 3.1 - Raisonnement et démarche clinique infirmière', chapter:'Recueil de données', difficulty:'medium', isPublished:true,
    front:'Les 14 besoins fondamentaux de Virginia Henderson',
    back:'1. Respirer\n2. Boire et manger\n3. Éliminer\n4. Se mouvoir\n5. Dormir et se reposer\n6. S\'habiller et se déshabiller\n7. Maintenir la température\n8. Être propre et protéger ses téguments\n9. Éviter les dangers\n10. Communiquer\n11. Pratiquer sa religion\n12. S\'accomplir\n13. Se recréer\n14. Apprendre',
    hint:'14 besoins de VH — base de la démarche de soins' },
  { semester:'Semestre 1', category:'UE 3.1 - Raisonnement et démarche clinique infirmière', chapter:'Recueil de données', difficulty:'medium', isPublished:true,
    front:'L\'observation clinique — signes à surveiller',
    back:'• Constantes : TA, FC, FR, T°, SpO₂, douleur (EVA)\n• Aspect général : teint, conscience (GCS), mobilité\n• Peau : couleur, hydratation, lésions\n• Éliminations : diurèse, transit\n• Comportement : anxiété, agitation, repli\n• Alimentation : appétit, poids' },

  // Chapitre : Raisonnement clinique
  { semester:'Semestre 1', category:'UE 3.1 - Raisonnement et démarche clinique infirmière', chapter:'Raisonnement clinique', difficulty:'medium', isPublished:true,
    front:'Le raisonnement hypothético-déductif en soins infirmiers',
    back:'1. Recueil de données → identification d\'indices\n2. Formulation d\'hypothèses diagnostiques\n3. Collecte d\'indices supplémentaires pour confirmer/infirmer\n4. Rétention de l\'hypothèse la plus probable\n5. Actions et évaluation' },
  { semester:'Semestre 1', category:'UE 3.1 - Raisonnement et démarche clinique infirmière', chapter:'Raisonnement clinique', difficulty:'medium', isPublished:true,
    front:'Le raisonnement par analogie (pattern recognition)',
    back:'Reconnaissance rapide d\'une situation clinique par comparaison avec des cas mémorisés.\nUsage chez les soignants expérimentés.\nRisque : biais de confirmation → toujours valider avec des données objectives.' },
  { semester:'Semestre 1', category:'UE 3.1 - Raisonnement et démarche clinique infirmière', chapter:'Raisonnement clinique', difficulty:'medium', isPublished:true,
    front:'La pensée critique en soins infirmiers',
    back:'Capacité à analyser, questionner, évaluer les informations de manière méthodique et réflexive avant d\'agir.\nComportements : remise en question, vérification des sources, tolérance à l\'incertitude, prise en compte du contexte.' },
  { semester:'Semestre 1', category:'UE 3.1 - Raisonnement et démarche clinique infirmière', chapter:'Raisonnement clinique', difficulty:'medium', isPublished:true,
    front:'La transmission ciblée — format',
    back:'Mode de traçabilité des soins orienté vers les problèmes prioritaires.\nStructure :\n• D : Données (constat clinique)\n• A : Actions (soins réalisés)\n• R : Résultats (évaluation de l\'efficacité)\nEx : "D : EVA 8/10. A : antalgique palier 2 donné. R : EVA 4/10 à 1h."' },
  { semester:'Semestre 1', category:'UE 3.1 - Raisonnement et démarche clinique infirmière', chapter:'Raisonnement clinique', difficulty:'medium', isPublished:true,
    front:'La méthode SBAR (communication entre soignants)',
    back:'Outil de communication structurée pour transmettre une situation clinique :\n• S : Situation (qui, quoi, où)\n• B : Background (contexte médical)\n• A : Assessment (évaluation clinique actuelle)\n• R : Recommendation (ce que je demande/propose)' },

  // Chapitre : Évaluation de la douleur
  { semester:'Semestre 1', category:'UE 3.1 - Raisonnement et démarche clinique infirmière', chapter:'Évaluation de la douleur', difficulty:'easy', isPublished:true,
    front:'Définition de la douleur (IASP)',
    back:'"Expérience sensorielle et émotionnelle désagréable associée à une lésion tissulaire réelle ou potentielle, ou décrite en de tels termes."\nLa douleur est toujours subjective → auto-évaluation = gold standard.' },
  { semester:'Semestre 1', category:'UE 3.1 - Raisonnement et démarche clinique infirmière', chapter:'Évaluation de la douleur', difficulty:'easy', isPublished:true,
    front:'Les échelles d\'auto-évaluation de la douleur',
    back:'• EVA (Échelle Visuelle Analogique) : 0–10 cm, patient trace un trait\n• EN (Échelle Numérique) : 0–10 en mots\n• EVS (Échelle Verbale Simple) : absente/légère/modérée/intense/extrême\n→ Choisir selon âge et capacités cognitives.' },
  { semester:'Semestre 1', category:'UE 3.1 - Raisonnement et démarche clinique infirmière', chapter:'Évaluation de la douleur', difficulty:'medium', isPublished:true,
    front:'Les échelles d\'hétéro-évaluation de la douleur',
    back:'Pour les patients ne pouvant pas s\'auto-évaluer :\n• ALGOPLUS : personne âgée en urgence (5 items, seuil ≥ 2)\n• DOLOPLUS-2 : personne âgée, 10 items comportementaux\n• NFCS / EDIN / DAN : nouveau-né et nourrisson\n• FLACC : enfant 2 mois–7 ans' },
  { semester:'Semestre 1', category:'UE 3.1 - Raisonnement et démarche clinique infirmière', chapter:'Évaluation de la douleur', difficulty:'medium', isPublished:true,
    front:'Douleur aiguë vs douleur chronique',
    back:'• Aiguë : signal d\'alarme, durée < 3 mois, cause identifiable, réversible → traiter la cause\n• Chronique : > 3 mois, souvent multifactorielle, peut devenir maladie en soi → prise en charge globale (biopsychosociale), centres douleur' },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 4.1 – Soins de confort et de bien-être (~30 cartes)
  // ═══════════════════════════════════════════════════════════════════════════

  { semester:'Semestre 1', category:'UE 4.1 - Soins de confort et de bien-être', chapter:'Soins de base', difficulty:'easy', isPublished:true,
    front:'La toilette au lit — principes généraux',
    back:'• Respecter la pudeur et la dignité\n• Eau à 37°C, pièce à 20°C\n• Commencer par les yeux (intérieur → extérieur), puis visage, corps, périnée\n• Rincer et sécher soigneusement (plis cutanés)\n• Observer la peau à chaque toilette (lésions, rougeurs, escarres)' },
  { semester:'Semestre 1', category:'UE 4.1 - Soins de confort et de bien-être', chapter:'Soins de base', difficulty:'medium', isPublished:true,
    front:'Le soin de bouche — techniques et indications',
    back:'• Patients conscients : brosse à dents, dentifrice fluoré, 2x/j minimum\n• Patients inconscients : bâtonnet glycériné, aspiration, Eosine® ou bicarbonate\n• Patients sous O₂ ou ventilés : 4–6x/j (prévention PAVM)\n• Observer : mucosités, mycose (candidose), stomatite' },
  { semester:'Semestre 1', category:'UE 4.1 - Soins de confort et de bien-être', chapter:'Soins de base', difficulty:'medium', isPublished:true,
    front:'La prévention des escarres — mesures',
    back:'• Évaluation du risque : échelle de Braden ou Norton\n• Changements de position toutes les 2–3h\n• Matelas anti-escarres (mousse haute résilience, à air)\n• Hydratation cutanée, nutrition adaptée\n• Mobilisation précoce\n• Éviter frictions et cisaillements' },
  { semester:'Semestre 1', category:'UE 4.1 - Soins de confort et de bien-être', chapter:'Soins de base', difficulty:'medium', isPublished:true,
    front:'L\'échelle de Braden — évaluation du risque d\'escarre',
    back:'6 items cotés 1–4 (ou 1–3) :\n1. Perception sensorielle\n2. Humidité\n3. Activité\n4. Mobilité\n5. Nutrition\n6. Friction/cisaillement\nScore max : 23. Risque élevé si score ≤ 12.' },
  { semester:'Semestre 1', category:'UE 4.1 - Soins de confort et de bien-être', chapter:'Soins de base', difficulty:'easy', isPublished:true,
    front:'Le positionnement d\'un patient en décubitus latéral',
    back:'Installation :\n• 30° (demi-latéral) pour prévenir les escarres trochantiennes\n• Oreiller entre les jambes (protège les genoux et malléoles)\n• Tête et cou alignés\n• Bras non comprimé\n• Appel-malade à portée de main' },
  { semester:'Semestre 1', category:'UE 4.1 - Soins de confort et de bien-être', chapter:'Soins de base', difficulty:'medium', isPublished:true,
    front:'Les soins de nursing — importance clinique',
    back:'Soins d\'hygiène, confort et prévention relevant du rôle propre infirmier.\nFonctions :\n• Prévention des complications de l\'immobilisation (escarres, phlébites, rétractions)\n• Maintien de la dignité et de l\'image corporelle\n• Moment privilégié d\'observation et de communication' },
  { semester:'Semestre 1', category:'UE 4.1 - Soins de confort et de bien-être', chapter:'Soins de base', difficulty:'medium', isPublished:true,
    front:'La prévention des chutes en milieu hospitalier',
    back:'• Évaluation du risque : échelle de Morse ou Hendrich\n• Environnement : lit en position basse, barres d\'appui, éclairage\n• Appel-malade accessible\n• Chaussures antidérapantes\n• Accompagnement aux WC\n• Révision des médicaments à risque (psychotropes, antihypertenseurs)' },
  { semester:'Semestre 1', category:'UE 4.1 - Soins de confort et de bien-être', chapter:'Soins de base', difficulty:'medium', isPublished:true,
    front:'La contention physique — encadrement réglementaire',
    back:'Mesure de dernier recours, nécessite :\n• Prescription médicale (renouvelée régulièrement)\n• Consentement du patient ou tuteur\n• Information du patient et de la famille\n• Surveillance rapprochée (2h max sans réévaluation)\n• Traçabilité dans le dossier\n• Déclaration en EIAS si incident' },
  { semester:'Semestre 1', category:'UE 4.1 - Soins de confort et de bien-être', chapter:'Soins de base', difficulty:'easy', isPublished:true,
    front:'Le repos et le sommeil — rôles physiologiques',
    back:'Le sommeil est nécessaire pour :\n• Restauration physiologique (sécrétions GH, réparation tissulaire)\n• Consolidation mémorielle\n• Régulation émotionnelle\n• Récupération énergétique\nL\'infirmier favorise le sommeil : réduire bruit, lumière, regrouper les soins la nuit.' },
  { semester:'Semestre 1', category:'UE 4.1 - Soins de confort et de bien-être', chapter:'Soins de base', difficulty:'medium', isPublished:true,
    front:'L\'alimentation entérale par sonde nasogastrique',
    back:'Indications : patient ne pouvant avaler.\nSurveillance IDE :\n• Position de la sonde (radio de contrôle à la pose, puis test aspiration gastrique pH < 5)\n• Résidu gastrique avant chaque administration\n• Signes d\'inhalation (FR, SpO₂)\n• Débit de perfusion\n• Hygiène buccale maintenue' },
  { semester:'Semestre 1', category:'UE 4.1 - Soins de confort et de bien-être', chapter:'Soins de base', difficulty:'easy', isPublished:true,
    front:'Les soins liés à l\'élimination urinaire',
    back:'• Surveiller : diurèse, couleur, odeur, troubles mictionnels\n• Sondage vésical : technique stérile, prescription médicale\n• Prévention des infections urinaires sur sonde : sac déclive, circuit fermé, bon entretien du méat\n• Globe vésical → sondage en urgence' },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 5.1 – Accompagnement dans la réalisation des soins quotidiens (~30 cartes)
  // ═══════════════════════════════════════════════════════════════════════════

  { semester:'Semestre 1', category:'UE 5.1 - Accompagnement dans la réalisation des soins quotidiens', chapter:'Accompagnement du patient', difficulty:'easy', isPublished:true,
    front:'Le concept d\'accompagnement en soins infirmiers',
    back:'Être présent auprès du patient en respectant son rythme, ses choix et son autonomie.\nNe pas faire "à la place" mais "avec".\nInclut : soutien, aide technique, éducation, communication, gestion de l\'environnement.' },
  { semester:'Semestre 1', category:'UE 5.1 - Accompagnement dans la réalisation des soins quotidiens', chapter:'Accompagnement du patient', difficulty:'medium', isPublished:true,
    front:'Le principe de suppléance (Virginia Henderson)',
    back:'"L\'infirmière doit aider le patient à accomplir les activités qu\'il accomplirait seul s\'il en avait la force, la volonté ou le savoir-faire, et ce de façon à l\'aider à recouvrer son indépendance le plus rapidement possible."' },
  { semester:'Semestre 1', category:'UE 5.1 - Accompagnement dans la réalisation des soins quotidiens', chapter:'Accompagnement du patient', difficulty:'medium', isPublished:true,
    front:'L\'autonomie du patient — respect et promotion',
    back:'• Toujours proposer, jamais imposer\n• Evaluer les capacités réelles et potentielles\n• Favoriser les actes que le patient peut réaliser seul (même partiellement)\n• Adapter l\'aide sans créer de dépendance\n• Inclure le patient dans les décisions le concernant' },
  { semester:'Semestre 1', category:'UE 5.1 - Accompagnement dans la réalisation des soins quotidiens', chapter:'Accompagnement du patient', difficulty:'medium', isPublished:true,
    front:'L\'éducation thérapeutique du patient (ETP) — définition',
    back:'Processus continu visant à aider le patient à acquérir ou maintenir des compétences pour gérer sa maladie chronique.\nObjectif : patient acteur de sa santé.\nÉtapes : diagnostic éducatif → plan éducatif → séances → évaluation.' },
  { semester:'Semestre 1', category:'UE 5.1 - Accompagnement dans la réalisation des soins quotidiens', chapter:'Accompagnement du patient', difficulty:'medium', isPublished:true,
    front:'Le diagnostic éducatif — contenu',
    back:'Évaluation initiale en ETP : ce que le patient\n• Sait (connaissances)\n• Peut faire (compétences, habilitées)\n• Fait réellement (comportements)\n• Ressent (émotions, croyances)\n→ Identifier les besoins, les obstacles et les ressources du patient.' },
  { semester:'Semestre 1', category:'UE 5.1 - Accompagnement dans la réalisation des soins quotidiens', chapter:'Accompagnement du patient', difficulty:'easy', isPublished:true,
    front:'La communication avec un patient anxieux',
    back:'• Approche calme, voix posée, contact visuel\n• Nommer l\'émotion : "je vois que vous êtes inquiet"\n• Questions ouvertes pour laisser s\'exprimer\n• Éviter le flot d\'informations\n• Reformuler, rassurer sur ce qui peut l\'être\n• Laisser du silence si nécessaire' },
  { semester:'Semestre 1', category:'UE 5.1 - Accompagnement dans la réalisation des soins quotidiens', chapter:'Accompagnement du patient', difficulty:'medium', isPublished:true,
    front:'La relation soignant-soigné — caractéristiques',
    back:'• Asymétrique (vulnérabilité du patient)\n• Professionnelle (pas d\'amitié ni relation personnelle)\n• Limitée dans le temps et l\'espace\n• Basée sur la confiance\n• Orientée vers le bien-être du patient\nIl ne faut ni se suridentifier ni rester dans une distance excessive.' },
  { semester:'Semestre 1', category:'UE 5.1 - Accompagnement dans la réalisation des soins quotidiens', chapter:'Accompagnement du patient', difficulty:'medium', isPublished:true,
    front:'L\'annonce d\'une mauvaise nouvelle — principes',
    back:'• Cadre adapté (calme, assis, temps suffisant)\n• Pas de mensonge, ni information brutale\n• Évaluer ce que le patient sait et souhaite savoir\n• Adapter le langage (éviter jargon)\n• Laisser exprimer les émotions\n• Proposer un accompagnement et un soutien\n• Tracer dans le dossier' },
  { semester:'Semestre 1', category:'UE 5.1 - Accompagnement dans la réalisation des soins quotidiens', chapter:'Accompagnement du patient', difficulty:'medium', isPublished:true,
    front:'L\'accompagnement en fin de vie — soins palliatifs',
    back:'Soins actifs délivrés par une équipe multidisciplinaire pour :\n• Soulager la douleur et les symptômes\n• Maintenir la qualité de vie\n• Soutenir le patient et sa famille\n• Préparer la mort dans la dignité\nNe pas confondre avec euthanasie (illégale en France).' },
  { semester:'Semestre 1', category:'UE 5.1 - Accompagnement dans la réalisation des soins quotidiens', chapter:'Accompagnement du patient', difficulty:'medium', isPublished:true,
    front:'Le deuil — stades de Kübler-Ross',
    back:'5 stades (non linéaires) :\n1. Déni (choc)\n2. Colère\n3. Marchandage ("si seulement…")\n4. Dépression\n5. Acceptation\nLe soignant accompagne sans brusquer ni forcer les étapes.' },
  { semester:'Semestre 1', category:'UE 5.1 - Accompagnement dans la réalisation des soins quotidiens', chapter:'Accompagnement du patient', difficulty:'easy', isPublished:true,
    front:'Les besoins de la famille du patient hospitalisé',
    back:'• Information : sur l\'état de santé, les soins, l\'évolution\n• Rassurance : savoir que le patient est en sécurité\n• Proximité : pouvoir rendre visite\n• Soutien émotionnel\n• Participation aux soins si possible\n• Respect de leur présence dans l\'équation de soins' },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 6.1 – Méthodes de travail et TIC (~20 cartes)
  // ═══════════════════════════════════════════════════════════════════════════

  { semester:'Semestre 1', category:'UE 6.1 - Méthodes de travail et TIC', chapter:'Organisation du travail', difficulty:'easy', isPublished:true,
    front:'Le dossier patient informatisé (DPI) — objectifs',
    back:'• Centraliser toutes les informations du patient\n• Favoriser la coordination entre soignants\n• Améliorer la traçabilité des soins\n• Réduire les erreurs (médicamenteuses, identité)\n• Faciliter la continuité des soins (transmissions)' },
  { semester:'Semestre 1', category:'UE 6.1 - Méthodes de travail et TIC', chapter:'Organisation du travail', difficulty:'medium', isPublished:true,
    front:'Le secret professionnel et les données de santé numériques',
    back:'• Données de santé = données sensibles (RGPD - règlement européen)\n• Accès limité aux professionnels habilités\n• Hébergement sur serveurs certifiés HDS (Hébergeurs de Données de Santé)\n• Traçabilité des accès (audit log)\n• Ne pas partager ses identifiants' },
  { semester:'Semestre 1', category:'UE 6.1 - Méthodes de travail et TIC', chapter:'Organisation du travail', difficulty:'medium', isPublished:true,
    front:'La gestion du temps infirmier — outils',
    back:'• Planification des soins en début de poste\n• Priorisation : urgences > soins programmés\n• Organisation des tournées pour minimiser les déplacements\n• Outils : tableau de soins, check-lists, transmissions ciblées\n• Anticipation des imprévus (marge de temps)' },
  { semester:'Semestre 1', category:'UE 6.1 - Méthodes de travail et TIC', chapter:'Organisation du travail', difficulty:'easy', isPublished:true,
    front:'La démarche de recherche documentaire en soins infirmiers',
    back:'1. Identifier la question clinique (PICO)\n2. Choisir les bases de données (PubMed, Cochrane, HAS, Soins)\n3. Définir les mots-clés\n4. Sélectionner et évaluer les articles (niveau de preuve)\n5. Synthétiser et appliquer à la pratique (EBP)' },
  { semester:'Semestre 1', category:'UE 6.1 - Méthodes de travail et TIC', chapter:'Organisation du travail', difficulty:'medium', isPublished:true,
    front:'L\'Evidence-Based Practice (EBP)',
    back:'Pratique basée sur les meilleures preuves disponibles :\n• Preuves scientifiques (études, méta-analyses)\n• Expertise clinique du soignant\n• Préférences et valeurs du patient\nObjectif : améliorer la qualité des soins par l\'intégration des connaissances actualisées.' },
  { semester:'Semestre 1', category:'UE 6.1 - Méthodes de travail et TIC', chapter:'Organisation du travail', difficulty:'medium', isPublished:true,
    front:'Les transmissions infirmières — objectifs et formes',
    back:'Objectifs : continuité des soins, sécurité, traçabilité.\nFormes :\n• Orales : relève (transmissions de poste)\n• Écrites : dossier patient, transmissions ciblées\n• Téléphoniques : appel médecin (SBAR)\nToujours tracer DANS le dossier, jamais sur papier libre perdu.' },
  { semester:'Semestre 1', category:'UE 6.1 - Méthodes de travail et TIC', chapter:'Organisation du travail', difficulty:'easy', isPublished:true,
    front:'La gestion des risques en établissement de santé',
    back:'• Identifier les risques (cartographie)\n• Analyser les causes (méthode ALARM, Ishikawa)\n• Mettre en œuvre des actions correctives\n• Évaluer et mesurer l\'efficacité\n→ Principe de culture non punitive : apprendre de ses erreurs sans crainte de sanction.' },
  { semester:'Semestre 1', category:'UE 6.1 - Méthodes de travail et TIC', chapter:'Organisation du travail', difficulty:'medium', isPublished:true,
    front:'Le travail en équipe pluriprofessionnelle',
    back:'• Communication efficace (outils SBAR, check-lists)\n• Respect des compétences de chacun\n• Objectifs communs centrés sur le patient\n• Réunions de synthèse (staff, RCP)\n• Gestion constructive des conflits\n• Rôle IDE : pivot entre médecin, AS et patient' },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 6.2 – Anglais médical (~20 cartes)
  // ═══════════════════════════════════════════════════════════════════════════

  { semester:'Semestre 1', category:'UE 6.2 - Anglais', chapter:'Vocabulaire médical', difficulty:'easy', isPublished:true,
    front:'Vocabulaire : les symptômes courants (EN)',
    back:'• Pain : douleur\n• Fever / Temperature : fièvre\n• Nausea : nausée\n• Vomiting : vomissement\n• Dizziness : vertige\n• Shortness of breath : dyspnée\n• Chest pain : douleur thoracique\n• Headache : céphalée\n• Fatigue : fatigue / asthénie' },
  { semester:'Semestre 1', category:'UE 6.2 - Anglais', chapter:'Vocabulaire médical', difficulty:'easy', isPublished:true,
    front:'Vocabulaire : les constantes vitales (EN)',
    back:'• Blood pressure (BP) : pression artérielle\n• Heart rate (HR) : fréquence cardiaque\n• Respiratory rate (RR) : fréquence respiratoire\n• Temperature (T°) : température\n• Oxygen saturation (SpO₂) : saturation en O₂\n• Blood glucose : glycémie' },
  { semester:'Semestre 1', category:'UE 6.2 - Anglais', chapter:'Vocabulaire médical', difficulty:'medium', isPublished:true,
    front:'Vocabulaire : les appareils et systèmes (EN)',
    back:'• Cardiovascular system : appareil cardiovasculaire\n• Respiratory system : appareil respiratoire\n• Digestive system : appareil digestif\n• Nervous system : système nerveux\n• Musculoskeletal system : appareil locomoteur\n• Urinary tract : voies urinaires' },
  { semester:'Semestre 1', category:'UE 6.2 - Anglais', chapter:'Vocabulaire médical', difficulty:'medium', isPublished:true,
    front:'Vocabulaire : les soins infirmiers (EN)',
    back:'• Nursing care : soins infirmiers\n• Ward / Unit : service / unité\n• Bedside : au chevet\n• Drip / Infusion : perfusion\n• Catheter : cathéter / sonde\n• Dressing : pansement\n• Vital signs : constantes\n• Medical record : dossier médical' },
  { semester:'Semestre 1', category:'UE 6.2 - Anglais', chapter:'Vocabulaire médical', difficulty:'medium', isPublished:true,
    front:'Vocabulaire : les médicaments et la pharmacologie (EN)',
    back:'• Drug / Medication : médicament\n• Prescription : ordonnance\n• Dosage : posologie\n• Side effect : effet indésirable\n• Contraindication : contre-indication\n• Overdose : surdosage\n• Painkiller / Analgesic : antalgique\n• Antibiotic : antibiotique' },
  { semester:'Semestre 1', category:'UE 6.2 - Anglais', chapter:'Vocabulaire médical', difficulty:'easy', isPublished:true,
    front:'Expressions utiles pour la communication avec un patient anglophone',
    back:'• "How are you feeling?" : Comment vous sentez-vous ?\n• "Where does it hurt?" : Où avez-vous mal ?\n• "On a scale of 0 to 10, how is your pain?" : EVA en anglais\n• "I\'m going to take your blood pressure." : Prise de TA\n• "Do you have any allergies?" : Allergies ?\n• "Please ring the bell if you need anything." : Sonnette' },
  { semester:'Semestre 1', category:'UE 6.2 - Anglais', chapter:'Vocabulaire médical', difficulty:'medium', isPublished:true,
    front:'Les abréviations médicales anglaises courantes',
    back:'• COPD : Chronic Obstructive Pulmonary Disease (BPCO)\n• MI : Myocardial Infarction (IDM)\n• CVA : Cerebrovascular Accident (AVC)\n• UTI : Urinary Tract Infection (infection urinaire)\n• DVT : Deep Vein Thrombosis (TVP)\n• ICU : Intensive Care Unit (réanimation)\n• ER / ED : Emergency Room / Department (urgences)' },
  { semester:'Semestre 1', category:'UE 6.2 - Anglais', chapter:'Vocabulaire médical', difficulty:'medium', isPublished:true,
    front:'Lecture d\'un article scientifique en anglais — structure IMRAD',
    back:'• I : Introduction (contexte, problématique)\n• M : Methods (méthode, population)\n• R : Results (résultats, données brutes)\n• A : And\n• D : Discussion (interprétation, limites, perspectives)\n→ Lire d\'abord l\'abstract et la discussion pour évaluer la pertinence.' },
  { semester:'Semestre 1', category:'UE 6.2 - Anglais', chapter:'Vocabulaire médical', difficulty:'easy', isPublished:true,
    front:'Vocabulaire : les professions de santé (EN)',
    back:'• Nurse : infirmier(ière)\n• Physician / Doctor : médecin\n• Surgeon : chirurgien\n• Pharmacist : pharmacien\n• Physiotherapist : kinésithérapeute\n• Midwife : sage-femme\n• Healthcare assistant / Nursing aide : aide-soignant\n• Head nurse : infirmier cadre' },
  { semester:'Semestre 1', category:'UE 6.2 - Anglais', chapter:'Vocabulaire médical', difficulty:'medium', isPublished:true,
    front:'Comprendre les niveaux de preuve en recherche (EN)',
    back:'• Systematic review / Meta-analysis : niveau le plus élevé\n• Randomized Controlled Trial (RCT) : essai randomisé\n• Cohort study : étude de cohorte\n• Case-control study : cas-témoin\n• Case report : cas clinique\n• Expert opinion : opinion d\'expert (niveau le plus bas)' },

];
