// ─── PARTIE 1 : UE 1.1 · UE 1.3 · UE 2.1 ──────────────────────────────────
module.exports = [

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 1.1 – Psychologie, sociologie, anthropologie (4 quiz)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Fondements de la psychologie",
    description: "Les bases de la psychologie appliquées aux soins infirmiers",
    semester: "Semestre 1",
    category: "UE 1.1 - Psychologie, sociologie, anthropologie",
    chapter: "Introduction à la psychologie",
    difficulty: "easy", duration: 15, isPublished: true,
    questions: [
      { text: "Quelle est la définition de la psychologie ?",
        options: [{ text: "L'étude des comportements et des processus mentaux", isCorrect: true },{ text: "L'étude exclusive des maladies mentales", isCorrect: false },{ text: "L'étude des groupes sociaux uniquement", isCorrect: false },{ text: "L'étude du cerveau en imagerie", isCorrect: false }],
        explanation: "La psychologie est la science étudiant les comportements humains et les processus mentaux (pensées, émotions, motivations, perceptions)." },
      { text: "Qui est le fondateur de la psychanalyse ?",
        options: [{ text: "Carl Rogers", isCorrect: false },{ text: "Jean Piaget", isCorrect: false },{ text: "Sigmund Freud", isCorrect: true },{ text: "Abraham Maslow", isCorrect: false }],
        explanation: "Sigmund Freud (1856-1939) est le fondateur de la psychanalyse, théorie selon laquelle les comportements sont en grande partie déterminés par l'inconscient." },
      { text: "Selon Maslow, quel est le premier niveau de la pyramide des besoins ?",
        options: [{ text: "La sécurité", isCorrect: false },{ text: "Les besoins physiologiques", isCorrect: true },{ text: "L'appartenance sociale", isCorrect: false },{ text: "L'estime de soi", isCorrect: false }],
        explanation: "Les besoins physiologiques (respirer, manger, dormir) sont à la base de la pyramide car essentiels à la survie." },
      { text: "Qu'est-ce que le mécanisme de défense de la 'projection' ?",
        options: [{ text: "Nier une réalité douloureuse", isCorrect: false },{ text: "Attribuer à autrui ses propres sentiments inacceptables", isCorrect: true },{ text: "Revenir à un comportement infantile", isCorrect: false },{ text: "Transformer une pulsion en son contraire", isCorrect: false }],
        explanation: "La projection consiste à attribuer à autrui des pensées ou sentiments que l'on refuse de reconnaître en soi-même." },
      { text: "Qu'appelle-t-on 'transfert' dans la relation soignant-soigné ?",
        options: [{ text: "Le passage d'un patient d'un service à l'autre", isCorrect: false },{ text: "Le report sur le soignant de sentiments liés à une figure passée", isCorrect: true },{ text: "La transmission d'une maladie infectieuse", isCorrect: false },{ text: "L'échange d'informations entre professionnels", isCorrect: false }],
        explanation: "Le transfert désigne la projection par le patient sur le soignant de sentiments initialement vécus envers des figures parentales ou importantes de son passé." },
      { text: "Qu'est-ce que la 'résilience' en psychologie ?",
        options: [{ text: "La capacité à mémoriser des informations traumatiques", isCorrect: false },{ text: "La tendance à refouler les souvenirs douloureux", isCorrect: false },{ text: "La capacité à se reconstruire positivement après un traumatisme", isCorrect: true },{ text: "L'absence totale de réaction face au stress", isCorrect: false }],
        explanation: "La résilience est la capacité à surmonter des épreuves difficiles et à se reconstruire positivement en mobilisant ses ressources internes et externes." },
      { text: "Quel psychologue a développé la théorie de l'attachement ?",
        options: [{ text: "Erik Erikson", isCorrect: false },{ text: "John Bowlby", isCorrect: true },{ text: "Albert Bandura", isCorrect: false },{ text: "Carl Jung", isCorrect: false }],
        explanation: "John Bowlby (1907-1990) a développé la théorie de l'attachement, soulignant l'importance du lien affectif précoce entre l'enfant et son caregiver." },
      { text: "Selon Carl Rogers, la relation d'aide repose sur :",
        options: [{ text: "L'autorité, la distance et l'objectivité", isCorrect: false },{ text: "L'empathie, la congruence et l'acceptation inconditionnelle", isCorrect: true },{ text: "La manipulation, la persuasion et le renforcement", isCorrect: false },{ text: "Le diagnostic, le traitement et l'évaluation", isCorrect: false }],
        explanation: "Carl Rogers définit la relation d'aide par trois conditions : l'empathie (comprendre le vécu), la congruence (authenticité du soignant) et l'acceptation inconditionnelle de l'autre." },
      { text: "Le modèle bio-psycho-social a été proposé par :",
        options: [{ text: "Sigmund Freud", isCorrect: false },{ text: "Abraham Maslow", isCorrect: false },{ text: "George Engel", isCorrect: true },{ text: "Ivan Pavlov", isCorrect: false }],
        explanation: "George Engel a proposé en 1977 le modèle bio-psycho-social, intégrant les dimensions biologique, psychologique et sociale dans la compréhension de la santé." },
      { text: "En psychologie, qu'est-ce que le 'contre-transfert' ?",
        options: [{ text: "Les réactions émotionnelles du soignant envers le patient", isCorrect: true },{ text: "Le rejet conscient d'un patient par le soignant", isCorrect: false },{ text: "La transmission d'une maladie du soignant au patient", isCorrect: false },{ text: "Le refus de soins de la part du patient", isCorrect: false }],
        explanation: "Le contre-transfert désigne les réactions émotionnelles inconscientes du soignant envers le patient, en lien avec sa propre histoire. Il doit être identifié pour préserver la qualité du soin." }
    ]
  },
  {
    title: "Développement psychologique de l'enfant",
    description: "Les stades du développement psychologique selon Piaget et Erikson",
    semester: "Semestre 1",
    category: "UE 1.1 - Psychologie, sociologie, anthropologie",
    chapter: "Psychologie du développement",
    difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Selon Piaget, quel stade correspond à la période 0-2 ans ?",
        options: [{ text: "Stade préopératoire", isCorrect: false },{ text: "Stade sensori-moteur", isCorrect: true },{ text: "Stade des opérations concrètes", isCorrect: false },{ text: "Stade des opérations formelles", isCorrect: false }],
        explanation: "Le stade sensori-moteur (0-2 ans) selon Piaget est caractérisé par la découverte du monde via les sens et les actions motrices, avec l'acquisition de la permanence de l'objet." },
      { text: "Quel est le principal conflit du stade oral selon Freud ?",
        options: [{ text: "Autonomie vs honte", isCorrect: false },{ text: "Confiance vs méfiance", isCorrect: true },{ text: "Initiative vs culpabilité", isCorrect: false },{ text: "Travail vs infériorité", isCorrect: false }],
        explanation: "Selon Erikson (associé au stade oral de Freud), le premier conflit est la confiance vs la méfiance : l'enfant développe ou non un sentiment de sécurité selon la fiabilité de son entourage." },
      { text: "La 'permanence de l'objet' est acquise à quel stade chez Piaget ?",
        options: [{ text: "Stade préopératoire", isCorrect: false },{ text: "Stade sensori-moteur", isCorrect: true },{ text: "Stade des opérations concrètes", isCorrect: false },{ text: "Stade formel", isCorrect: false }],
        explanation: "La permanence de l'objet (comprendre qu'un objet continue d'exister même s'il n'est plus visible) est acquise à la fin du stade sensori-moteur, vers 18-24 mois." },
      { text: "L'égocentrisme intellectuel caractérise quel stade de Piaget ?",
        options: [{ text: "Sensori-moteur", isCorrect: false },{ text: "Préopératoire (2-7 ans)", isCorrect: true },{ text: "Opérations concrètes (7-12 ans)", isCorrect: false },{ text: "Opérations formelles (12+ ans)", isCorrect: false }],
        explanation: "Durant le stade préopératoire (2-7 ans), l'enfant est centré sur son propre point de vue et ne peut pas encore adopter le point de vue d'autrui : c'est l'égocentrisme intellectuel." },
      { text: "Quel concept Freudien désigne l'ensemble des règles et interdits intériorisés ?",
        options: [{ text: "Le Ça", isCorrect: false },{ text: "Le Moi", isCorrect: false },{ text: "Le Surmoi", isCorrect: true },{ text: "Le Moi idéal", isCorrect: false }],
        explanation: "Le Surmoi est l'instance psychique représentant les interdits et les idéaux intériorisés lors du développement, principalement à travers les figures parentales." },
      { text: "Selon Erikson, la crise d'identité vs confusion des rôles est propre à :",
        options: [{ text: "La petite enfance (0-3 ans)", isCorrect: false },{ text: "L'enfance (6-12 ans)", isCorrect: false },{ text: "L'adolescence (12-18 ans)", isCorrect: true },{ text: "L'âge adulte (20-40 ans)", isCorrect: false }],
        explanation: "Selon Erikson, l'adolescence est marquée par la crise identité vs confusion des rôles : le jeune construit son identité propre en questionnant les valeurs et rôles sociaux." },
      { text: "La notion de 'zone proximale de développement' est due à :",
        options: [{ text: "Jean Piaget", isCorrect: false },{ text: "Lev Vygotsky", isCorrect: true },{ text: "Sigmund Freud", isCorrect: false },{ text: "John Bowlby", isCorrect: false }],
        explanation: "Lev Vygotsky définit la zone proximale de développement comme l'espace entre ce que l'enfant sait faire seul et ce qu'il peut faire avec l'aide d'un adulte ou d'un pair plus compétent." },
      { text: "Le complexe d'Œdipe se manifeste selon Freud chez l'enfant de :",
        options: [{ text: "0 à 1 an", isCorrect: false },{ text: "1 à 3 ans", isCorrect: false },{ text: "3 à 6 ans", isCorrect: true },{ text: "7 à 12 ans", isCorrect: false }],
        explanation: "Le complexe d'Œdipe (stade phallique chez Freud) se manifeste entre 3 et 6 ans, avec une attirance pour le parent du sexe opposé et une rivalité avec le parent du même sexe." },
      { text: "Quel type d'attachement est caractérisé par une détresse modérée à la séparation et un retour rapide au jeu lors des retrouvailles ?",
        options: [{ text: "Attachement insécure évitant", isCorrect: false },{ text: "Attachement insécure ambivalent", isCorrect: false },{ text: "Attachement sécure", isCorrect: true },{ text: "Attachement désorganisé", isCorrect: false }],
        explanation: "L'attachement sécure est caractérisé par une détresse modérée à la séparation, une recherche active de réconfort lors des retrouvailles et un retour rapide à l'exploration." },
      { text: "Le stade anal selon Freud (1-3 ans) est caractérisé par :",
        options: [{ text: "La découverte de la différence anatomique des sexes", isCorrect: false },{ text: "Les enjeux de rétention/expulsion et l'émergence de l'autonomie", isCorrect: true },{ text: "La primauté du plaisir oral (succion)", isCorrect: false },{ text: "La latence des pulsions sexuelles", isCorrect: false }],
        explanation: "Le stade anal voit l'enfant investir la zone anale (contrôle des sphincters) et les enjeux de rétention/expulsion, parallèlement à l'émergence de l'autonomie et de la volonté propre." }
    ]
  },
  {
    title: "Sociologie et soins infirmiers",
    description: "Concepts sociologiques appliqués au contexte des soins",
    semester: "Semestre 1",
    category: "UE 1.1 - Psychologie, sociologie, anthropologie",
    chapter: "Sociologie des soins",
    difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Qu'est-ce que la socialisation primaire ?",
        options: [{ text: "L'apprentissage des normes sociales à l'âge adulte", isCorrect: false },{ text: "L'intégration des normes et valeurs lors de l'enfance dans la famille", isCorrect: true },{ text: "L'intégration professionnelle dans le monde du travail", isCorrect: false },{ text: "L'apprentissage scolaire", isCorrect: false }],
        explanation: "La socialisation primaire désigne le processus d'intégration des normes, valeurs et rôles sociaux fondamentaux qui se produit durant l'enfance, principalement au sein de la famille." },
      { text: "Qu'appelle-t-on 'inégalités sociales de santé' ?",
        options: [{ text: "Les inégalités d'accès aux médicaments", isCorrect: false },{ text: "Les variations systématiques de l'état de santé selon la position sociale", isCorrect: true },{ text: "Les différences de traitement entre femmes et hommes", isCorrect: false },{ text: "L'inégalité des ressources hospitalières entre régions", isCorrect: false }],
        explanation: "Les inégalités sociales de santé désignent les écarts systématiques et évitables d'état de santé entre groupes sociaux, liés aux conditions de vie, de travail et d'accès aux soins." },
      { text: "Qui a introduit le concept de 'capital social' en sociologie ?",
        options: [{ text: "Émile Durkheim", isCorrect: false },{ text: "Max Weber", isCorrect: false },{ text: "Pierre Bourdieu", isCorrect: true },{ text: "Karl Marx", isCorrect: false }],
        explanation: "Pierre Bourdieu a développé le concept de capital social (ensemble des ressources liées à un réseau de relations), ainsi que les capitaux économique, culturel et symbolique." },
      { text: "Qu'est-ce que le 'rôle de malade' selon Talcott Parsons ?",
        options: [{ text: "L'obligation pour le malade de travailler malgré la maladie", isCorrect: false },{ text: "La dispensation temporaire de certains rôles sociaux en échange de l'obligation de chercher à guérir", isCorrect: true },{ text: "Le rôle infirmier dans la prise en charge des patients", isCorrect: false },{ text: "La stigmatisation du patient par la société", isCorrect: false }],
        explanation: "Parsons définit le rôle de malade comme un statut social légitime dispensant temporairement le malade de ses obligations normales, en contrepartie de l'obligation de chercher à guérir et de se soumettre aux soins." },
      { text: "La stigmatisation en sociologie de la santé désigne :",
        options: [{ text: "L'attribution d'une récompense à un soignant méritant", isCorrect: false },{ text: "La marque distinctive d'une maladie visible", isCorrect: false },{ text: "Un attribut profondément disqualifiant qui réduit l'individu à sa différence", isCorrect: true },{ text: "L'inscription d'un patient dans un registre", isCorrect: false }],
        explanation: "Selon Goffman, la stigmatisation est le processus par lequel un attribut (maladie, handicap, appartenance sociale) discrédite l'individu et réduit son identité à cette différence." },
      { text: "Qu'est-ce que la 'médicalisation de la société' ?",
        options: [{ text: "L'augmentation du nombre de médecins", isCorrect: false },{ text: "L'extension du champ médical à des phénomènes qui ne relevaient pas de la médecine", isCorrect: true },{ text: "L'amélioration des techniques médicales", isCorrect: false },{ text: "La nationalisation des hôpitaux", isCorrect: false }],
        explanation: "La médicalisation désigne le processus par lequel des aspects de la vie (naissance, vieillesse, deuil, obésité…) sont de plus en plus définis et traités comme des problèmes médicaux nécessitant une intervention." },
      { text: "Selon Durkheim, le suicide 'anomique' est lié à :",
        options: [{ text: "Un excès d'intégration sociale", isCorrect: false },{ text: "Une carence de régulation sociale (dissolution des normes)", isCorrect: true },{ text: "Un isolement volontaire de l'individu", isCorrect: false },{ text: "Une altruisme excessif", isCorrect: false }],
        explanation: "Le suicide anomique selon Durkheim résulte d'un affaiblissement de la régulation sociale : quand les normes collectives se dissolvent (anomie), l'individu perd ses repères et est plus vulnérable." },
      { text: "Qu'est-ce que la 'relation soignant-soigné asymétrique' implique ?",
        options: [{ text: "Une égalité parfaite entre soignant et patient", isCorrect: false },{ text: "Un déséquilibre de pouvoir lié au savoir médical et à la vulnérabilité du patient", isCorrect: true },{ text: "Une relation uniquement affective", isCorrect: false },{ text: "Un échange financier entre patient et soignant", isCorrect: false }],
        explanation: "La relation soignant-soigné est structurellement asymétrique car le soignant possède un savoir expert et se trouve en position de force face au patient vulnérable, d'où l'importance de l'éthique du soin." },
      { text: "Le concept de 'représentations sociales' en psychologie sociale est associé à :",
        options: [{ text: "Kurt Lewin", isCorrect: false },{ text: "Serge Moscovici", isCorrect: true },{ text: "Stanley Milgram", isCorrect: false },{ text: "Henri Tajfel", isCorrect: false }],
        explanation: "Serge Moscovici a développé la théorie des représentations sociales : des formes de connaissance pratique, socialement élaborées et partagées, qui permettent aux individus d'interpréter leur réalité." },
      { text: "La notion de 'groupe social' en sociologie désigne :",
        options: [{ text: "N'importe quel ensemble d'individus au même endroit", isCorrect: false },{ text: "Un ensemble d'individus partageant des interactions régulières, des valeurs communes et une identité collective", isCorrect: true },{ text: "Une famille uniquement", isCorrect: false },{ text: "Un parti politique", isCorrect: false }],
        explanation: "Un groupe social est caractérisé par des interactions régulières entre ses membres, des normes et valeurs partagées, et un sentiment d'appartenance collective qui le distingue d'une simple agrégation d'individus." }
    ]
  },
  {
    title: "Anthropologie médicale et culturelle",
    description: "Anthropologie appliquée à la santé et aux pratiques de soins",
    semester: "Semestre 1",
    category: "UE 1.1 - Psychologie, sociologie, anthropologie",
    chapter: "Anthropologie et santé",
    difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Qu'est-ce que l'anthropologie médicale étudie ?",
        options: [{ text: "L'anatomie humaine uniquement", isCorrect: false },{ text: "Les relations entre culture, société et santé/maladie", isCorrect: true },{ text: "Les techniques chirurgicales ancestrales", isCorrect: false },{ text: "L'évolution de l'espèce humaine", isCorrect: false }],
        explanation: "L'anthropologie médicale explore comment les facteurs culturels, sociaux et économiques influencent la santé, la maladie, les soins et les représentations du corps dans différentes cultures." },
      { text: "Qu'appelle-t-on 'ethnocentrisme' ?",
        options: [{ text: "La valorisation de toutes les cultures de manière égale", isCorrect: false },{ text: "Le fait de juger les autres cultures à partir des valeurs de sa propre culture", isCorrect: true },{ text: "L'étude comparative des différentes ethnies", isCorrect: false },{ text: "Le respect des pratiques culturelles d'autrui", isCorrect: false }],
        explanation: "L'ethnocentrisme consiste à considérer sa propre culture comme référence et à juger les autres cultures à partir de ses propres valeurs, souvent de façon péjorative." },
      { text: "La 'compétence culturelle' dans les soins infirmiers implique :",
        options: [{ text: "De parler plusieurs langues étrangères", isCorrect: false },{ text: "De connaître et respecter les croyances et pratiques culturelles du patient", isCorrect: true },{ text: "D'imposer les normes médicales occidentales", isCorrect: false },{ text: "D'ignorer les différences culturelles pour soigner de façon identique", isCorrect: false }],
        explanation: "La compétence culturelle est la capacité du soignant à reconnaître, comprendre et respecter les valeurs, croyances et pratiques culturelles du patient, pour adapter les soins de manière appropriée." },
      { text: "Qu'est-ce que le 'relativisme culturel' ?",
        options: [{ text: "La supériorité d'une culture sur les autres", isCorrect: false },{ text: "Le principe selon lequel chaque culture doit être comprise dans son propre contexte", isCorrect: true },{ text: "L'idée que toutes les cultures sont identiques", isCorrect: false },{ text: "Le refus de tout jugement moral", isCorrect: false }],
        explanation: "Le relativisme culturel est le principe méthodologique selon lequel les pratiques et valeurs d'une culture doivent être comprises et évaluées dans leur propre contexte, sans les juger selon des critères extérieurs." },
      { text: "Comment appelle-t-on les pratiques de soins traditionnelles non reconnues par la médecine scientifique ?",
        options: [{ text: "Médecines conventionnelles", isCorrect: false },{ text: "Médecines parallèles ou alternatives", isCorrect: true },{ text: "Médecines officielles", isCorrect: false },{ text: "Médecines académiques", isCorrect: false }],
        explanation: "Les médecines alternatives ou parallèles (homéopathie, naturopathie, médecines traditionnelles…) sont des pratiques de soin non intégrées à la médecine conventionnelle. Elles peuvent coexister avec les soins officiels." },
      { text: "Le rite de passage en anthropologie désigne :",
        options: [{ text: "Un traitement médical réservé aux anciens", isCorrect: false },{ text: "Un cérémonial marquant le changement de statut social d'un individu", isCorrect: true },{ text: "Une procédure administrative à l'hôpital", isCorrect: false },{ text: "Un rituel réservé aux croyants", isCorrect: false }],
        explanation: "Les rites de passage (naissance, mariage, mort, initiation…) sont des cérémonies qui marquent et légitiment le changement de statut social ou de rôle d'un individu au sein d'une communauté." },
      { text: "Qu'est-ce que la 'maladie' selon une approche anthropologique ?",
        options: [{ text: "Uniquement une dysfonction biologique objectivable", isCorrect: false },{ text: "Un phénomène à la fois biologique, subjectif et socioculturel", isCorrect: true },{ text: "Un phénomène purement psychologique", isCorrect: false },{ text: "Un événement uniquement médicalement défini", isCorrect: false }],
        explanation: "En anthropologie, la maladie est appréhendée comme un phénomène multidimensionnel : biologique (disease), vécu subjectif (illness) et construit socioculturel (sickness)." },
      { text: "L'alimentation relève de l'anthropologie car :",
        options: [{ text: "Elle n'est qu'un besoin biologique universel", isCorrect: false },{ text: "Elle est profondément marquée par les cultures et les identités sociales", isCorrect: true },{ text: "Elle est identique dans toutes les sociétés", isCorrect: false },{ text: "Elle relève uniquement de la diététique", isCorrect: false }],
        explanation: "L'alimentation est un fait social total : elle exprime l'identité culturelle, les croyances religieuses, les structures familiales et sociales. Le soignant doit en tenir compte pour respecter les habitudes du patient." },
      { text: "Comment nomme-t-on le refus de soins motivé par des convictions religieuses ?",
        options: [{ text: "Non-observance thérapeutique", isCorrect: false },{ text: "Objection de conscience", isCorrect: false },{ text: "Refus de soins pour motif religieux", isCorrect: true },{ text: "Insubordination médicale", isCorrect: false }],
        explanation: "Le refus de soins pour motif religieux (ex : refus de transfusion chez les Témoins de Jéhovah) met en tension le droit au refus de soins du patient et le devoir de bienfaisance du soignant. Il doit être respecté sauf urgence vitale." },
      { text: "La mort est-elle appréhendée de la même façon dans toutes les cultures ?",
        options: [{ text: "Oui, la mort est vécue universellement de la même manière", isCorrect: false },{ text: "Non, les représentations, rites et pratiques funéraires varient selon les cultures", isCorrect: true },{ text: "Oui, car c'est un fait biologique universel", isCorrect: false },{ text: "Non, uniquement dans les pays en développement", isCorrect: false }],
        explanation: "Les représentations de la mort, les rites funéraires, le deuil et l'au-delà varient considérablement d'une culture à l'autre. Le soignant doit respecter ces pratiques culturelles dans l'accompagnement de fin de vie." }
    ]
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 1.3 – Législation, éthique, déontologie (4 quiz)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Droits des patients",
    description: "Les droits fondamentaux des usagers du système de santé",
    semester: "Semestre 1",
    category: "UE 1.3 - Législation, éthique, déontologie",
    chapter: "Droits des usagers",
    difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Quelle loi fondamentale définit les droits des patients en France ?",
        options: [{ text: "Loi Huriet du 20 décembre 1988", isCorrect: false },{ text: "Loi du 4 mars 2002 (loi Kouchner)", isCorrect: true },{ text: "Loi du 9 juin 1999 sur les soins palliatifs", isCorrect: false },{ text: "Loi HPST du 21 juillet 2009", isCorrect: false }],
        explanation: "La loi du 4 mars 2002 relative aux droits des malades et à la qualité du système de santé (loi Kouchner) consacre les droits des patients : information, consentement, accès au dossier médical, etc." },
      { text: "Le consentement éclairé du patient exige :",
        options: [{ text: "Une signature sur un formulaire administratif", isCorrect: false },{ text: "Une information complète et compréhensible, librement donnée, et révocable", isCorrect: true },{ text: "L'accord de la famille uniquement", isCorrect: false },{ text: "Un consentement donné au médecin traitant exclusivement", isCorrect: false }],
        explanation: "Le consentement éclairé requiert que le patient ait reçu une information loyale, claire et adaptée sur les soins, qu'il consente librement et qu'il puisse révoquer son consentement à tout moment." },
      { text: "Qui peut prendre des décisions médicales pour un patient inconscient sans personne de confiance désignée ?",
        options: [{ text: "L'infirmière référente", isCorrect: false },{ text: "Le médecin, en concertation avec l'équipe et la famille", isCorrect: true },{ text: "Le directeur de l'établissement", isCorrect: false },{ text: "L'assistante sociale", isCorrect: false }],
        explanation: "En l'absence de personne de confiance et de directives anticipées, le médecin prend les décisions médicales après concertation collégiale avec l'équipe soignante et, si possible, après consultation de la famille." },
      { text: "Qu'est-ce que les 'directives anticipées' ?",
        options: [{ text: "Un testament rédigé par un notaire", isCorrect: false },{ text: "Des instructions écrites sur les souhaits de soins en cas d'incapacité à les exprimer", isCorrect: true },{ text: "Une procuration médicale donnée à un médecin", isCorrect: false },{ text: "Un refus de soins définitif", isCorrect: false }],
        explanation: "Les directives anticipées sont des instructions écrites, rédigées à l'avance par toute personne majeure, indiquant ses souhaits concernant les conditions de fin de vie, en cas d'impossibilité à les exprimer." },
      { text: "Le secret professionnel en soins infirmiers est régi par :",
        options: [{ text: "L'article 226-13 du Code pénal uniquement", isCorrect: false },{ text: "Le Code de la santé publique et le Code pénal", isCorrect: true },{ text: "Les règlements intérieurs de chaque établissement", isCorrect: false },{ text: "La convention collective des soignants", isCorrect: false }],
        explanation: "Le secret professionnel infirmier est fondé sur l'article L. 1110-4 du Code de la santé publique et l'article 226-13 du Code pénal. Il protège toutes les informations recueillies dans le cadre de la prise en charge." },
      { text: "La loi Claeys-Leonetti de 2016 introduit :",
        options: [{ text: "Le droit à l'euthanasie active en France", isCorrect: false },{ text: "Le droit à une sédation profonde et continue jusqu'au décès en fin de vie", isCorrect: true },{ text: "L'obligation de soins en fin de vie", isCorrect: false },{ text: "La légalisation du suicide assisté", isCorrect: false }],
        explanation: "La loi Claeys-Leonetti (2016) renforce les droits des patients en fin de vie : elle instaure le droit à une sédation profonde et continue jusqu'au décès pour les patients dont le pronostic vital est engagé à court terme." },
      { text: "Qu'est-ce que la 'personne de confiance' au sens de la loi française ?",
        options: [{ text: "Un proche désigné pour être informé en priorité en cas d'urgence", isCorrect: false },{ text: "Une personne désignée par le patient pour l'accompagner et être consultée si le patient ne peut s'exprimer", isCorrect: true },{ text: "Un représentant légal désigné par la justice", isCorrect: false },{ text: "Le médecin traitant habituel du patient", isCorrect: false }],
        explanation: "La personne de confiance est librement choisie par le patient (membre de la famille, ami, médecin traitant). Elle est consultée lorsque le patient ne peut exprimer sa volonté et joue un rôle de porte-parole." },
      { text: "L'accès au dossier médical par le patient est un droit depuis :",
        options: [{ text: "La loi HPST de 2009", isCorrect: false },{ text: "La loi du 4 mars 2002", isCorrect: true },{ text: "La loi de 1978 sur l'informatique et les libertés", isCorrect: false },{ text: "Le Code de déontologie médicale de 1995", isCorrect: false }],
        explanation: "Depuis la loi du 4 mars 2002, tout patient peut accéder directement à son dossier médical, sans avoir à passer par un médecin intermédiaire. Le délai de communication est de 8 jours (48h en cas d'hospitalisation récente)." },
      { text: "Le refus de soins d'un patient majeur et conscient doit être :",
        options: [{ text: "Ignoré si sa vie est en danger", isCorrect: false },{ text: "Respecté après information sur les conséquences, avec signature d'une décharge", isCorrect: true },{ text: "Signalé à la justice", isCorrect: false },{ text: "Systématiquement contourné par l'équipe médicale", isCorrect: false }],
        explanation: "Le droit au refus de soins est fondamental. L'équipe informe le patient des risques liés au refus, s'assure qu'il est éclairé et conscient, puis respecte son choix en lui faisant signer une décharge." },
      { text: "La maltraitance d'une personne vulnérable par un soignant est :",
        options: [{ text: "Une faute déontologique uniquement", isCorrect: false },{ text: "Une infraction pénale aggravée", isCorrect: true },{ text: "Une faute uniquement si elle laisse des traces physiques", isCorrect: false },{ text: "Sanctionnée uniquement par l'ordre infirmier", isCorrect: false }],
        explanation: "La maltraitance d'une personne vulnérable (âgée, handicapée, malade) par un soignant constitue une infraction pénale aggravée (article 222-3 du Code pénal), en plus des sanctions disciplinaires." }
    ]
  },
  {
    title: "Déontologie et responsabilité infirmière",
    description: "Code de déontologie et responsabilité professionnelle de l'infirmier",
    semester: "Semestre 1",
    category: "UE 1.3 - Législation, éthique, déontologie",
    chapter: "Déontologie infirmière",
    difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Le code de déontologie infirmier est intégré dans :",
        options: [{ text: "Le Code du travail", isCorrect: false },{ text: "Le Code de la santé publique (décret de 2016)", isCorrect: true },{ text: "Le Code civil", isCorrect: false },{ text: "La convention collective hospitalière", isCorrect: false }],
        explanation: "Le code de déontologie des infirmiers a été intégré dans le Code de la santé publique par décret du 25 novembre 2016 (articles R. 4312-1 à R. 4312-92)." },
      { text: "Qu'est-ce que l'obligation de moyens en matière de responsabilité infirmière ?",
        options: [{ text: "L'obligation d'obtenir un résultat thérapeutique précis", isCorrect: false },{ text: "L'obligation de mettre en œuvre tous les moyens disponibles conformes aux bonnes pratiques", isCorrect: true },{ text: "L'obligation d'acheter le matériel nécessaire aux soins", isCorrect: false },{ text: "L'obligation de résultat pour les actes techniques", isCorrect: false }],
        explanation: "L'infirmier est soumis à une obligation de moyens : il doit dispenser des soins consciencieux, attentifs et conformes aux données acquises de la science, sans être tenu d'un résultat précis." },
      { text: "L'infirmier peut-il exercer le rôle propre sans prescription médicale ?",
        options: [{ text: "Non, tous les actes infirmiers nécessitent une prescription", isCorrect: false },{ text: "Oui, pour les soins relevant de son initiative et de sa compétence propre", isCorrect: true },{ text: "Oui, uniquement en urgence", isCorrect: false },{ text: "Non, sauf en cas d'absence du médecin", isCorrect: false }],
        explanation: "Le rôle propre infirmier (Art. R. 4311-3 CSP) comprend les soins relevant de l'initiative de l'infirmier : surveillance, nursing, éducation, soutien psychologique... Il ne nécessite pas de prescription médicale." },
      { text: "La faute inexcusable en droit de la responsabilité médicale se définit comme :",
        options: [{ text: "Une simple erreur technique", isCorrect: false },{ text: "Une faute d'une exceptionnelle gravité, inexcusable eu égard à la formation professionnelle", isCorrect: true },{ text: "Un oubli passager dans la surveillance", isCorrect: false },{ text: "Tout incident survenu lors d'un soin", isCorrect: false }],
        explanation: "La faute inexcusable est une faute d'une particulière gravité, révélatrice d'une violation manifeste d'une obligation de sécurité, incompatible avec le niveau de formation et d'expérience du professionnel." },
      { text: "Que signifie l'acronyme CREX dans les établissements de santé ?",
        options: [{ text: "Comité de Recherche et d'EXpertise", isCorrect: false },{ text: "Comité de Retour d'EXpérience", isCorrect: true },{ text: "Centre de Recueil des EXpositions professionnelles", isCorrect: false },{ text: "Commission de Révision des EXercices", isCorrect: false }],
        explanation: "Le CREX (Comité de Retour d'EXpérience) est une démarche d'analyse des événements indésirables graves (EIG) en équipe, visant à améliorer la sécurité des soins par le partage d'expérience." },
      { text: "L'infirmier est tenu au secret professionnel envers :",
        options: [{ text: "Uniquement les tiers extérieurs à l'établissement", isCorrect: false },{ text: "Toute personne non impliquée dans la prise en charge du patient", isCorrect: true },{ text: "Toute personne y compris les proches du patient", isCorrect: false },{ text: "Uniquement les journalistes et les assureurs", isCorrect: false }],
        explanation: "Le secret professionnel s'impose à l'infirmier envers toute personne non impliquée dans la prise en charge du patient. Il existe un secret partagé au sein de l'équipe soignante." },
      { text: "Le signalement de maltraitance est :",
        options: [{ text: "Facultatif pour le soignant", isCorrect: false },{ text: "Une obligation légale pour tout professionnel de santé", isCorrect: true },{ text: "Réservé aux médecins et assistants sociaux", isCorrect: false },{ text: "Uniquement requis pour les mineurs", isCorrect: false }],
        explanation: "Tout professionnel de santé est légalement obligé de signaler les cas de maltraitance ou de privation envers des personnes vulnérables (mineurs, personnes âgées, handicapées) aux autorités compétentes." },
      { text: "Qu'est-ce que la 'délégation de tâches' en soins infirmiers ?",
        options: [{ text: "La transmission d'un patient à un autre service", isCorrect: false },{ text: "La confiance de certains actes à un aide-soignant sous sa responsabilité", isCorrect: true },{ text: "Le transfert de responsabilité vers le médecin", isCorrect: false },{ text: "Le report d'un soin à plus tard", isCorrect: false }],
        explanation: "L'infirmier peut confier certains actes à l'aide-soignant (dans le cadre du rôle délégué), mais conserve la responsabilité de la surveillance et de la coordination. Cette délégation doit être explicite et encadrée." },
      { text: "L'infirmier libéral est responsable de ses actes envers :",
        options: [{ text: "Son employeur uniquement", isCorrect: false },{ text: "L'Ordre National des Infirmiers et ses patients", isCorrect: true },{ text: "La Caisse d'Assurance Maladie uniquement", isCorrect: false },{ text: "Le Conseil de l'Ordre des médecins", isCorrect: false }],
        explanation: "L'infirmier libéral est responsable de ses actes envers ses patients (responsabilité civile/pénale), l'Ordre National des Infirmiers (responsabilité ordinale/déontologique) et l'Assurance Maladie (responsabilité conventionnelle)." },
      { text: "Qu'est-ce que l''obligation de formation continue' pour un infirmier ?",
        options: [{ text: "Une obligation uniquement pour les infirmiers spécialisés", isCorrect: false },{ text: "L'obligation de maintenir et développer ses compétences tout au long de sa carrière (DPC)", isCorrect: true },{ text: "Une obligation uniquement lors de la prise de nouvelles fonctions", isCorrect: false },{ text: "Une obligation facultative encouragée par l'employeur", isCorrect: false }],
        explanation: "Le Développement Professionnel Continu (DPC) est une obligation légale pour tous les infirmiers. Il comprend des actions de formation, d'évaluation des pratiques et de gestion des risques." }
    ]
  },
  {
    title: "Éthique dans les soins",
    description: "Les principes éthiques fondamentaux appliqués à la pratique infirmière",
    semester: "Semestre 1",
    category: "UE 1.3 - Législation, éthique, déontologie",
    chapter: "Éthique médicale",
    difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Quels sont les quatre principes fondateurs de l'éthique médicale selon Beauchamp et Childress ?",
        options: [{ text: "Vérité, Justice, Liberté, Équité", isCorrect: false },{ text: "Autonomie, Bienfaisance, Non-malfaisance, Justice", isCorrect: true },{ text: "Respect, Dignité, Solidarité, Efficacité", isCorrect: false },{ text: "Consentement, Information, Confidentialité, Sécurité", isCorrect: false }],
        explanation: "Les quatre principes de Beauchamp et Childress (1979) sont : l'autonomie (respect des choix), la bienfaisance (agir pour le bien), la non-malfaisance (ne pas nuire) et la justice (équité dans les soins)." },
      { text: "Le principe de 'non-malfaisance' en éthique médicale signifie :",
        options: [{ text: "Traiter tous les patients de façon identique", isCorrect: false },{ text: "Ne pas causer de tort inutile par ses actes ou omissions", isCorrect: true },{ text: "Respecter l'autonomie du patient", isCorrect: false },{ text: "Favoriser le bien-être du patient", isCorrect: false }],
        explanation: "La non-malfaisance (primum non nocere) oblige le soignant à ne pas infliger de tort inutile, à peser les bénéfices et les risques de tout acte de soin." },
      { text: "L'obstination déraisonnable (anciennement acharnement thérapeutique) désigne :",
        options: [{ text: "Des soins palliatifs intensifs", isCorrect: false },{ text: "Des investigations ou traitements inutiles, disproportionnés et sans bénéfice pour le patient", isCorrect: true },{ text: "Le refus de traiter un patient", isCorrect: false },{ text: "Des soins de confort en fin de vie", isCorrect: false }],
        explanation: "L'obstination déraisonnable (art. L. 1110-5-1 CSP) désigne le fait de poursuivre des traitements inutiles, disproportionnés ou n'ayant d'autre effet que le maintien artificiel de la vie. Elle est interdite en France." },
      { text: "La 'dignité humaine' dans les soins infirmiers implique :",
        options: [{ text: "De traiter le patient selon son statut social", isCorrect: false },{ text: "De respecter la personne dans son intégralité, quelles que soient ses conditions", isCorrect: true },{ text: "De toujours accéder aux demandes du patient", isCorrect: false },{ text: "De préserver uniquement l'intégrité physique", isCorrect: false }],
        explanation: "La dignité humaine est un principe fondamental imposant de respecter la valeur intrinsèque de chaque personne, indépendamment de son état de santé, de sa dépendance, de son statut social ou de sa capacité à communiquer." },
      { text: "Qu'est-ce que la 'bientraitance' dans les soins ?",
        options: [{ text: "L'absence de maltraitance physique uniquement", isCorrect: false },{ text: "Une culture du soin qui place la personne au centre, respectant ses droits et son bien-être global", isCorrect: true },{ text: "Un protocole de gestion des plaintes", isCorrect: false },{ text: "Une formation obligatoire annuelle", isCorrect: false }],
        explanation: "La bientraitance est une culture soignante qui va au-delà de l'absence de maltraitance : elle implique une attention positive à la personne, le respect de ses droits, de sa singularité et de son bien-être global." },
      { text: "Dans une situation de conflit éthique, la démarche collégiale implique :",
        options: [{ text: "De confier la décision au médecin chef uniquement", isCorrect: false },{ text: "Une réflexion pluridisciplinaire intégrant soignants, patient et famille", isCorrect: true },{ text: "De consulter uniquement la famille", isCorrect: false },{ text: "D'appliquer le protocole le plus récent", isCorrect: false }],
        explanation: "La démarche collégiale réunit l'équipe pluridisciplinaire (médecins, infirmiers, psychologue…) pour analyser la situation et prendre une décision partagée. Elle est obligatoire dans les décisions de limitation ou arrêt de traitement." },
      { text: "La 'bienfaisance' en éthique soignante signifie :",
        options: [{ text: "Faire du bien uniquement si le patient le demande", isCorrect: false },{ text: "Agir positivement dans l'intérêt du patient, en promouvant son bien-être", isCorrect: true },{ text: "Donner de l'argent aux patients démunis", isCorrect: false },{ text: "Traiter la maladie quoi qu'il en coûte", isCorrect: false }],
        explanation: "La bienfaisance oblige le soignant à agir activement dans l'intérêt du patient, à promouvoir son bien-être physique, psychologique et social et à prévenir ou traiter la maladie." },
      { text: "Qu'est-ce que la 'double-effet' en éthique médicale ?",
        options: [{ text: "L'utilisation de deux médicaments simultanément", isCorrect: false },{ text: "Le principe autorisant un acte dont l'effet bénéfique voulu coexiste avec un effet néfaste prévisible mais non voulu", isCorrect: true },{ text: "L'information donnée deux fois au patient pour s'assurer de sa compréhension", isCorrect: false },{ text: "La double signature d'une ordonnance", isCorrect: false }],
        explanation: "Le principe du double-effet (ex. : morphine en fin de vie pouvant hâter le décès mais soulagreant la douleur) autorise un acte si l'intention est bonne, l'effet bénéfique est visé, et le mal est proportionné au bien attendu." },
      { text: "L'éthique de la sollicitude (care ethics) met l'accent sur :",
        options: [{ text: "Les règles universelles et les droits individuels", isCorrect: false },{ text: "La relation, l'attention à l'autre et la réponse aux besoins de vulnérabilité", isCorrect: true },{ text: "L'efficacité des soins et la réduction des coûts", isCorrect: false },{ text: "L'autonomie absolue du patient", isCorrect: false }],
        explanation: "L'éthique du care (Carol Gilligan, Nel Noddings) valorise la relation, l'attention portée à la vulnérabilité de l'autre et la réponse à ses besoins concrets, en complément des principes éthiques universels." },
      { text: "La clause de conscience permet à un professionnel de santé de :",
        options: [{ text: "Refuser de soigner tout patient qu'il n'apprécie pas", isCorrect: false },{ text: "Refuser d'effectuer certains actes légaux contraires à ses convictions, sous conditions", isCorrect: true },{ text: "Refuser de travailler les week-ends", isCorrect: false },{ text: "Refuser de suivre les protocoles de l'établissement", isCorrect: false }],
        explanation: "La clause de conscience permet à un professionnel de santé de refuser d'effectuer certains actes légaux (ex. IVG) contraires à ses convictions personnelles, à condition d'orienter le patient vers un autre professionnel." }
    ]
  },
  {
    title: "Responsabilité juridique du soignant",
    description: "Les différentes formes de responsabilité dans l'exercice infirmier",
    semester: "Semestre 1",
    category: "UE 1.3 - Législation, éthique, déontologie",
    chapter: "Responsabilité juridique",
    difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "Quels sont les trois types de responsabilité pouvant être engagés pour un infirmier ?",
        options: [{ text: "Administrative, financière et morale", isCorrect: false },{ text: "Civile, pénale et disciplinaire/ordinale", isCorrect: true },{ text: "Professionnelle, personnelle et collective", isCorrect: false },{ text: "Directe, indirecte et partagée", isCorrect: false }],
        explanation: "Un infirmier peut voir sa responsabilité engagée sur trois plans : civil (réparation d'un préjudice), pénal (sanction d'une infraction) et disciplinaire/ordinale (sanctions professionnelles par l'Ordre ou l'employeur)." },
      { text: "Dans le secteur public hospitalier, la responsabilité en cas de faute de service incombe à :",
        options: [{ text: "L'infirmier personnellement", isCorrect: false },{ text: "L'établissement de santé (responsabilité administrative)", isCorrect: true },{ text: "Le médecin chef de service", isCorrect: false },{ text: "L'État directement", isCorrect: false }],
        explanation: "Dans le service public hospitalier, c'est l'établissement (personne morale) qui est responsable des fautes de service commises par ses agents. L'infirmier n'est personnellement poursuivi qu'en cas de faute personnelle détachable du service." },
      { text: "Qu'est-ce qu'un événement indésirable grave (EIG) ?",
        options: [{ text: "Tout incident technique dans un service hospitalier", isCorrect: false },{ text: "Un événement inattendu lié aux soins causant décès, mise en jeu du pronostic vital ou séquelle grave", isCorrect: true },{ text: "Une insatisfaction exprimée par un patient", isCorrect: false },{ text: "Un retard dans la transmission des informations", isCorrect: false }],
        explanation: "Un EIG est un événement inattendu lié aux soins (et non à l'évolution naturelle de la maladie) ayant entraîné ou risqué d'entraîner un décès, une mise en jeu du pronostic vital ou des séquelles graves." },
      { text: "La prescription médicale doit obligatoirement comporter :",
        options: [{ text: "Le nom du patient, le médicament, la posologie, la voie d'administration et la signature du médecin", isCorrect: true },{ text: "Le numéro de sécurité sociale du patient uniquement", isCorrect: false },{ text: "La durée du traitement uniquement", isCorrect: false },{ text: "Le diagnostic médical obligatoirement", isCorrect: false }],
        explanation: "Une prescription médicale valide comporte : identité du patient, date, médicament (DCI), dose, voie d'administration, durée, identité et signature du prescripteur. L'infirmier ne doit pas exécuter une prescription incomplète." },
      { text: "L'erreur médicamenteuse est définie comme :",
        options: [{ text: "Uniquement l'administration d'un mauvais médicament", isCorrect: false },{ text: "Tout écart entre la prescription et ce qui est réellement administré au patient", isCorrect: true },{ text: "Un oubli de prise médicamenteuse par le patient", isCorrect: false },{ text: "Un effet indésirable d'un médicament correctement administré", isCorrect: false }],
        explanation: "L'erreur médicamenteuse est tout écart non intentionnel entre la prescription et ce qui a été préparé, dispensé ou administré : mauvais patient, mauvais médicament, mauvaise dose, mauvaise voie, mauvais moment." },
      { text: "La règle des '5B' en sécurité médicamenteuse comprend :",
        options: [{ text: "Bon médicament, Bonne dose, Bon patient, Bonne voie, Bon moment", isCorrect: true },{ text: "Bon médecin, Bon budget, Bon bilan, Bon bolus, Bonne balance", isCorrect: false },{ text: "Bon diagnostic, Bonne indication, Bon effet, Bonne tolérance, Bon suivi", isCorrect: false },{ text: "Bonne infirmière, Bonne famille, Bonne pharmacie, Bon rangement, Bon traçage", isCorrect: false }],
        explanation: "La règle des 5B (ou 5 rights en anglais) est un protocole de sécurité médicamenteuse : vérifier le Bon médicament, la Bonne dose, le Bon patient, la Bonne voie d'administration et le Bon moment." },
      { text: "Quand un infirmier reçoit une prescription qu'il juge dangereuse, il doit :",
        options: [{ text: "L'appliquer quand même pour respecter la hiérarchie médicale", isCorrect: false },{ text: "En référer au prescripteur et ne pas l'exécuter si le danger est confirmé", isCorrect: true },{ text: "Modifier la prescription à sa convenance", isCorrect: false },{ text: "Signaler directement à la direction sans en parler au médecin", isCorrect: false }],
        explanation: "L'infirmier a le droit et le devoir de refuser d'exécuter une prescription qu'il estime dangereuse. Il doit en informer le prescripteur, tracer son refus dans le dossier et alerter la hiérarchie si nécessaire." },
      { text: "La notion de 'contrat de soins' entre le patient et l'établissement est de nature :",
        options: [{ text: "Commerciale", isCorrect: false },{ text: "Quasi-contractuelle (service public) ou contractuelle (secteur privé)", isCorrect: true },{ text: "Pénale", isCorrect: false },{ text: "Morale uniquement", isCorrect: false }],
        explanation: "Dans le secteur privé, la relation patient-établissement est contractuelle. Dans le service public, elle est quasi-contractuelle. Dans les deux cas, elle génère des obligations pour l'établissement et des droits pour le patient." },
      { text: "Qu'est-ce que la 'traçabilité des soins' et pourquoi est-elle importante ?",
        options: [{ text: "L'étiquetage des médicaments, sans valeur juridique", isCorrect: false },{ text: "La documentation systématique des soins dans le dossier patient, à valeur médicolégale", isCorrect: true },{ text: "Le traçage des mouvements du patient dans l'établissement", isCorrect: false },{ text: "La vérification du matériel stérile uniquement", isCorrect: false }],
        explanation: "La traçabilité des soins (inscription dans le dossier patient) est une obligation légale et déontologique. En cas de litige, le dossier patient est la pièce maîtresse : ce qui n'est pas tracé est réputé ne pas avoir été fait." },
      { text: "Un infirmier qui commet une faute lourde personnelle dans un service public peut :",
        options: [{ text: "Être poursuivi personnellement devant les juridictions civiles ou pénales", isCorrect: true },{ text: "Être uniquement sanctionné par son employeur en interne", isCorrect: false },{ text: "Bénéficier systématiquement de la protection de l'établissement", isCorrect: false },{ text: "Être uniquement traduit devant l'Ordre infirmier", isCorrect: false }],
        explanation: "En cas de faute personnelle grave (intentionnelle, détachable du service), l'infirmier peut être poursuivi personnellement devant les juridictions civiles (responsabilité) ou pénales (sanction), même dans le secteur public." }
    ]
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 2.1 – Biologie fondamentale (5 quiz)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "La cellule : organisation et fonctions",
    description: "Structure et fonctionnement de la cellule humaine",
    semester: "Semestre 1",
    category: "UE 2.1 - Biologie fondamentale",
    chapter: "Biologie cellulaire",
    difficulty: "easy", duration: 15, isPublished: true,
    questions: [
      { text: "Quelle est la principale différence entre une cellule procaryote et une cellule eucaryote ?",
        options: [{ text: "La cellule eucaryote n'a pas de membrane cellulaire", isCorrect: false },{ text: "La cellule eucaryote possède un noyau délimité par une membrane nucléaire", isCorrect: true },{ text: "La cellule procaryote est plus grande que la cellule eucaryote", isCorrect: false },{ text: "La cellule procaryote possède des mitochondries", isCorrect: false }],
        explanation: "La cellule eucaryote (cellules humaines, végétales, champignons) se distingue par la présence d'un noyau entouré d'une membrane nucléaire. Les cellules procaryotes (bactéries) n'ont pas de noyau délimité." },
      { text: "Quel organite cellulaire est responsable de la production d'énergie (ATP) ?",
        options: [{ text: "Le réticulum endoplasmique", isCorrect: false },{ text: "L'appareil de Golgi", isCorrect: false },{ text: "La mitochondrie", isCorrect: true },{ text: "Le lysosome", isCorrect: false }],
        explanation: "Les mitochondries produisent l'ATP (adénosine triphosphate) par respiration cellulaire (phosphorylation oxydative). Elles ont leur propre ADN, preuve de leur origine bactérienne ancestrale (endosymbiose)." },
      { text: "Quelle est la fonction principale du noyau cellulaire ?",
        options: [{ text: "Produire de l'énergie pour la cellule", isCorrect: false },{ text: "Conserver et transmettre l'information génétique (ADN)", isCorrect: true },{ text: "Digérer les déchets cellulaires", isCorrect: false },{ text: "Synthétiser les lipides membranaires", isCorrect: false }],
        explanation: "Le noyau contient l'ADN (support de l'information génétique). Il est le siège de la réplication de l'ADN et de la transcription (synthèse d'ARN messager), première étape de l'expression génique." },
      { text: "Le réticulum endoplasmique rugueux (RER) est associé à :",
        options: [{ text: "La production d'énergie par ATP", isCorrect: false },{ text: "La synthèse et le transport des protéines destinées à être sécrétées", isCorrect: true },{ text: "La digestion cellulaire", isCorrect: false },{ text: "La division cellulaire", isCorrect: false }],
        explanation: "Le RER, hérissé de ribosomes, est le lieu de synthèse des protéines destinées à être exportées ou intégrées aux membranes. Les protéines y sont ensuite acheminées vers l'appareil de Golgi." },
      { text: "Qu'est-ce que la phagocytose ?",
        options: [{ text: "La division d'une cellule en deux cellules filles", isCorrect: false },{ text: "L'ingestion de particules solides (bactéries, débris) par la cellule", isCorrect: true },{ text: "L'absorption de liquides par la cellule", isCorrect: false },{ text: "La synthèse de molécules complexes à partir de précurseurs simples", isCorrect: false }],
        explanation: "La phagocytose est le processus par lequel certaines cellules (macrophages, neutrophiles) engloutissent des particules solides (bactéries, cellules mortes) dans des vésicules appelées phagosomes." },
      { text: "La membrane plasmique est principalement composée de :",
        options: [{ text: "Protéines uniquement", isCorrect: false },{ text: "Une double couche de phospholipides avec des protéines enchâssées", isCorrect: true },{ text: "Glucides et lipides exclusivement", isCorrect: false },{ text: "ADN et protéines histones", isCorrect: false }],
        explanation: "La membrane plasmique est une bicouche phospholipidique (modèle mosaïque fluide de Singer et Nicolson) dans laquelle sont enchâssées des protéines membranaires (canaux, récepteurs, enzymes)." },
      { text: "L'osmose est définie comme :",
        options: [{ text: "Le transport actif d'ions à travers la membrane", isCorrect: false },{ text: "Le mouvement passif de l'eau d'une zone hypotonique vers une zone hypertonique à travers une membrane semi-perméable", isCorrect: true },{ text: "La diffusion des molécules lipidiques", isCorrect: false },{ text: "Le passage de grosses molécules par endocytose", isCorrect: false }],
        explanation: "L'osmose est le déplacement passif de l'eau à travers une membrane semi-perméable, du milieu le moins concentré (hypotonique) vers le milieu le plus concentré (hypertonique), jusqu'à l'équilibre osmotique." },
      { text: "Lors de la mitose, quel est l'ordre des phases ?",
        options: [{ text: "Interphase → Télophase → Anaphase → Métaphase → Prophase", isCorrect: false },{ text: "Prophase → Métaphase → Anaphase → Télophase", isCorrect: true },{ text: "Métaphase → Prophase → Anaphase → Télophase", isCorrect: false },{ text: "Anaphase → Prophase → Métaphase → Télophase", isCorrect: false }],
        explanation: "La mitose se déroule en quatre phases : Prophase (condensation des chromosomes), Métaphase (alignement au plan équatorial), Anaphase (séparation des chromatides) et Télophase (reformation de 2 noyaux)." },
      { text: "Qu'appelle-t-on 'apoptose' ?",
        options: [{ text: "La mort cellulaire accidentelle par traumatisme", isCorrect: false },{ text: "La mort cellulaire programmée, physiologique et ordonnée", isCorrect: true },{ text: "La fusion de deux cellules", isCorrect: false },{ text: "La multiplication incontrôlée des cellules (cancer)", isCorrect: false }],
        explanation: "L'apoptose est la mort cellulaire programmée, un processus physiologique essentiel (développement embryonnaire, renouvellement tissulaire, élimination des cellules endommagées). Elle diffère de la nécrose qui est accidentelle." },
      { text: "Quel est le rôle des lysosomes dans la cellule ?",
        options: [{ text: "Synthétiser des protéines", isCorrect: false },{ text: "Dégrader les macromolécules et les organites usagés par digestion enzymatique", isCorrect: true },{ text: "Produire de l'ATP", isCorrect: false },{ text: "Transporter des vésicules vers la membrane", isCorrect: false }],
        explanation: "Les lysosomes sont des organites contenant des enzymes digestives (hydrolases acides). Ils dégradent les macromolécules ingérées par phagocytose ou endocytose, et recyclent les organites usagés (autophagie)." }
    ]
  },
  {
    title: "Génétique fondamentale",
    description: "Les bases de la génétique : ADN, expression génique et hérédité",
    semester: "Semestre 1",
    category: "UE 2.1 - Biologie fondamentale",
    chapter: "Génétique fondamentale",
    difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "De combien de paires de chromosomes est composé le caryotype humain normal ?",
        options: [{ text: "22 paires", isCorrect: false },{ text: "23 paires (46 chromosomes)", isCorrect: true },{ text: "24 paires (48 chromosomes)", isCorrect: false },{ text: "21 paires (42 chromosomes)", isCorrect: false }],
        explanation: "L'être humain possède 46 chromosomes regroupés en 23 paires : 22 paires d'autosomes et 1 paire de chromosomes sexuels (XX chez la femme, XY chez l'homme)." },
      { text: "La trisomie 21 (syndrome de Down) est due à :",
        options: [{ text: "La délétion d'un chromosome 21", isCorrect: false },{ text: "La présence d'un chromosome 21 surnuméraire (3 au lieu de 2)", isCorrect: true },{ text: "Une mutation sur le chromosome 21", isCorrect: false },{ text: "Une translocation du chromosome X", isCorrect: false }],
        explanation: "La trisomie 21 résulte d'une non-disjonction méiotique donnant 3 copies du chromosome 21. Elle se manifeste par une déficience intellectuelle, des particularités morphologiques et un risque accru de cardiopathies." },
      { text: "L'ADN est une molécule composée de :",
        options: [{ text: "Acides aminés liés par des liaisons peptidiques", isCorrect: false },{ text: "Nucléotides (bases azotées + désoxyribose + phosphate) en double hélice", isCorrect: true },{ text: "Acides gras et glycérol", isCorrect: false },{ text: "Glucose et fructose", isCorrect: false }],
        explanation: "L'ADN est un polynucléotide en double hélice (Watson & Crick, 1953). Chaque nucléotide est composé d'une base azotée (A, T, G, C), d'un désoxyribose et d'un groupement phosphate." },
      { text: "Dans la réplication de l'ADN, les bases azotées s'apparient selon la règle :",
        options: [{ text: "A-G et T-C", isCorrect: false },{ text: "A-T et G-C", isCorrect: true },{ text: "A-C et G-T", isCorrect: false },{ text: "A-U et G-C", isCorrect: false }],
        explanation: "L'appariement des bases est complémentaire et spécifique : Adénine (A) avec Thymine (T) par 2 liaisons hydrogène, et Guanine (G) avec Cytosine (C) par 3 liaisons hydrogène. (En ARN, T est remplacé par Uracile U)." },
      { text: "La transcription est le processus par lequel :",
        options: [{ text: "L'ADN se réplique avant la division cellulaire", isCorrect: false },{ text: "L'ADN est copié en ARN messager (ARNm)", isCorrect: true },{ text: "L'ARN messager est traduit en protéine", isCorrect: false },{ text: "Les protéines sont dégradées", isCorrect: false }],
        explanation: "La transcription se déroule dans le noyau : l'ARN polymérase synthétise un ARN messager complémentaire à partir d'un brin matrice d'ADN. L'ARNm est ensuite exporté vers le cytoplasme pour la traduction." },
      { text: "La traduction est assurée par :",
        options: [{ text: "L'ADN polymérase dans le noyau", isCorrect: false },{ text: "Les ribosomes qui lisent l'ARNm et assemblent les acides aminés", isCorrect: true },{ text: "L'appareil de Golgi", isCorrect: false },{ text: "Les histones dans le noyau", isCorrect: false }],
        explanation: "La traduction a lieu dans le cytoplasme, sur les ribosomes. Ces derniers lisent le code de l'ARNm (codons de 3 bases) et assemblent les acides aminés correspondants pour former la protéine." },
      { text: "Un gène 'dominant' signifie que :",
        options: [{ text: "Le gène est présent sur le chromosome X", isCorrect: false },{ text: "Le caractère s'exprime même si le gène n'est présent qu'en un seul exemplaire (hétérozygote)", isCorrect: true },{ text: "Le gène n'est exprimé qu'à l'état homozygote", isCorrect: false },{ text: "Le gène est toujours transmis aux descendants", isCorrect: false }],
        explanation: "Un allèle dominant s'exprime phénotypiquement même à l'état hétérozygote (une seule copie suffit). Un allèle récessif ne s'exprime que si l'individu est homozygote (deux copies identiques)." },
      { text: "Quelle maladie génétique est liée au chromosome X (hémophilie) ?",
        options: [{ text: "Elle atteint autant les hommes que les femmes", isCorrect: false },{ text: "Elle touche principalement les hommes, les femmes étant conductrices", isCorrect: true },{ text: "Elle se transmet exclusivement de père en fils", isCorrect: false },{ text: "Elle atteint uniquement les personnes de groupe sanguin O", isCorrect: false }],
        explanation: "L'hémophilie est une maladie récessive liée à l'X. Les femmes ont deux chromosomes X (XX) : une copie saine peut compenser. Les hommes n'ont qu'un X (XY) : un allèle défectueux suffit à exprimer la maladie." },
      { text: "Une mutation génétique est :",
        options: [{ text: "Toujours héréditaire et pathologique", isCorrect: false },{ text: "Une modification permanente de la séquence nucléotidique de l'ADN", isCorrect: true },{ text: "Uniquement causée par des agents chimiques", isCorrect: false },{ text: "Un phénomène toujours visible dans le phénotype", isCorrect: false }],
        explanation: "Une mutation est une altération permanente de la séquence d'ADN. Elle peut être spontanée ou induite, germinale (transmissible) ou somatique (non transmissible). Elle n'est pas toujours pathologique ni phénotypiquement visible." },
      { text: "Le génotype d'un individu désigne :",
        options: [{ text: "L'ensemble des caractères physiques observables", isCorrect: false },{ text: "L'ensemble des allèles présents dans le génome de l'individu", isCorrect: true },{ text: "Les gènes exprimés uniquement", isCorrect: false },{ text: "Les chromosomes sexuels uniquement", isCorrect: false }],
        explanation: "Le génotype est la composition allélique de l'individu (l'information génétique dans ses cellules). Le phénotype est l'expression observable du génotype, influencée par l'environnement." }
    ]
  },
  {
    title: "Biochimie de base",
    description: "Les grandes molécules biologiques et leur rôle dans l'organisme",
    semester: "Semestre 1",
    category: "UE 2.1 - Biologie fondamentale",
    chapter: "Biochimie",
    difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Les glucides servent principalement à :",
        options: [{ text: "Constituer les membranes cellulaires", isCorrect: false },{ text: "Fournir de l'énergie rapide à l'organisme", isCorrect: true },{ text: "Transporter l'oxygène dans le sang", isCorrect: false },{ text: "Construire les muscles", isCorrect: false }],
        explanation: "Les glucides (sucres) sont la principale source d'énergie rapide : le glucose est le carburant préférentiel des cellules, notamment du cerveau et des globules rouges. 1g de glucides fournit environ 4 kcal." },
      { text: "Quel est le pH normal du sang humain ?",
        options: [{ text: "6,8 à 7,0", isCorrect: false },{ text: "7,35 à 7,45", isCorrect: true },{ text: "7,6 à 7,8", isCorrect: false },{ text: "8,0 à 8,5", isCorrect: false }],
        explanation: "Le pH sanguin normal est de 7,35 à 7,45 (légèrement alcalin). En dessous de 7,35 on parle d'acidose, au-dessus de 7,45 d'alcalose. Ces déséquilibres peuvent être mortels s'ils ne sont pas corrigés." },
      { text: "Les protéines sont des polymères constitués de :",
        options: [{ text: "Acides gras", isCorrect: false },{ text: "Nucléotides", isCorrect: false },{ text: "Acides aminés liés par des liaisons peptidiques", isCorrect: true },{ text: "Monosaccharides", isCorrect: false }],
        explanation: "Les protéines sont des macromolécules composées de chaînes d'acides aminés reliés par des liaisons peptidiques. Il existe 20 acides aminés dont 8 essentiels (ne pouvant être synthétisés par l'organisme)." },
      { text: "L'hémoglobine est une protéine spécialisée dans :",
        options: [{ text: "La coagulation du sang", isCorrect: false },{ text: "Le transport de l'oxygène dans les globules rouges", isCorrect: true },{ text: "La digestion des protéines", isCorrect: false },{ text: "La synthèse des hormones", isCorrect: false }],
        explanation: "L'hémoglobine est une protéine des érythrocytes (globules rouges) qui fixe l'O2 dans les poumons et le libère dans les tissus. Elle contient 4 sous-unités avec un groupement hème portant un atome de fer." },
      { text: "L'ATP (adénosine triphosphate) est :",
        options: [{ text: "Un acide aminé essentiel", isCorrect: false },{ text: "La molécule universelle de transfert d'énergie dans la cellule", isCorrect: true },{ text: "Un acide gras insaturé", isCorrect: false },{ text: "Un glucide complexe de stockage", isCorrect: false }],
        explanation: "L'ATP est la monnaie énergétique universelle de la cellule. L'hydrolyse de ses liaisons phosphate à haute énergie libère l'énergie nécessaire à toutes les réactions cellulaires (contraction musculaire, transport actif, biosynthèse)." },
      { text: "Quelle est la fonction des enzymes dans les réactions biochimiques ?",
        options: [{ text: "Fournir de l'énergie pour la réaction", isCorrect: false },{ text: "Accélérer les réactions sans être consommées (biocatalyseurs)", isCorrect: true },{ text: "Former de nouvelles molécules", isCorrect: false },{ text: "Neutraliser les radicaux libres", isCorrect: false }],
        explanation: "Les enzymes sont des protéines biocatalyseurs : elles accélèrent les réactions biochimiques en abaissant l'énergie d'activation, sans être consommées. Leur activité dépend du pH, de la température et de la concentration en substrat." },
      { text: "Le glycogène est :",
        options: [{ text: "Un lipide de réserve hépatique", isCorrect: false },{ text: "La forme de stockage du glucose dans le foie et les muscles", isCorrect: true },{ text: "Un glucide sanguin simple", isCorrect: false },{ text: "Un acide aminé glucogénique", isCorrect: false }],
        explanation: "Le glycogène est un polysaccharide de réserve stocké dans le foie (glycogène hépatique, régulation glycémique) et les muscles (glycogène musculaire, réserve locale d'énergie pour l'effort)." },
      { text: "Les lipides remplissent dans l'organisme :",
        options: [{ text: "Uniquement un rôle de réserve énergétique", isCorrect: false },{ text: "Un rôle énergétique, structural (membranes) et de précurseur hormonal", isCorrect: true },{ text: "Uniquement un rôle structural membranaire", isCorrect: false },{ text: "Uniquement un rôle de signalisation", isCorrect: false }],
        explanation: "Les lipides ont des rôles multiples : énergie (1g = 9 kcal), structure des membranes (phospholipides), isolant thermique, précurseurs des hormones stéroïdes et des vitamines liposolubles (A, D, E, K)." },
      { text: "Le taux normal de glucose sanguin (glycémie) à jeun est de :",
        options: [{ text: "0,3 à 0,5 g/L", isCorrect: false },{ text: "0,7 à 1,1 g/L", isCorrect: true },{ text: "1,5 à 2,0 g/L", isCorrect: false },{ text: "2,5 à 3,5 g/L", isCorrect: false }],
        explanation: "La glycémie normale à jeun est de 0,70 à 1,10 g/L (3,9 à 6,1 mmol/L). En dessous de 0,70 g/L : hypoglycémie. Au-dessus de 1,26 g/L à jeun à deux reprises : diabète." },
      { text: "Qu'est-ce que l'insuline et quel est son rôle principal ?",
        options: [{ text: "Une protéine de transport sanguin", isCorrect: false },{ text: "Une hormone pancréatique qui diminue la glycémie en favorisant l'entrée du glucose dans les cellules", isCorrect: true },{ text: "Une enzyme digestive", isCorrect: false },{ text: "Un neurotransmetteur cérébral", isCorrect: false }],
        explanation: "L'insuline est une hormone sécrétée par les cellules bêta du pancréas. Elle permet l'entrée du glucose dans les cellules (muscle, foie, tissu adipeux), diminuant ainsi la glycémie. Sa carence provoque le diabète de type 1." }
    ]
  },
  {
    title: "Microbiologie fondamentale",
    description: "Les micro-organismes, leur classification et leur pathogénicité",
    semester: "Semestre 1",
    category: "UE 2.1 - Biologie fondamentale",
    chapter: "Microbiologie",
    difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Quelle est la différence fondamentale entre bactéries et virus ?",
        options: [{ text: "Les bactéries sont plus petites que les virus", isCorrect: false },{ text: "Les bactéries sont des cellules vivantes autonomes ; les virus sont des agents acellulaires parasites", isCorrect: true },{ text: "Les virus peuvent être traités par antibiotiques, pas les bactéries", isCorrect: false },{ text: "Les bactéries n'ont pas d'ADN contrairement aux virus", isCorrect: false }],
        explanation: "Les bactéries sont des cellules procaryotes autonomes pouvant se reproduire seules. Les virus sont des entités acellulaires (ARN ou ADN + protéines) ne pouvant se répliquer qu'en parasitant une cellule hôte." },
      { text: "La coloration de Gram permet de distinguer :",
        options: [{ text: "Les bactéries vivantes des bactéries mortes", isCorrect: false },{ text: "Les bactéries à paroi épaisse de peptidoglycane (Gram+) des bactéries à double membrane (Gram-)", isCorrect: true },{ text: "Les bacilles des cocci", isCorrect: false },{ text: "Les bactéries aérobies des anaérobies", isCorrect: false }],
        explanation: "La coloration de Gram est fondamentale en bactériologie. Les bactéries Gram+ (ex : Staphylococcus, Streptococcus) ont une paroi épaisse de peptidoglycane et se colorent en violet. Les Gram- (ex : E. coli) ont une double membrane et se colorent en rose." },
      { text: "Qu'est-ce qu'un bacille ?",
        options: [{ text: "Une bactérie en forme de sphère", isCorrect: false },{ text: "Une bactérie en forme de bâtonnet", isCorrect: true },{ text: "Une bactérie en forme de spirale", isCorrect: false },{ text: "Un virus à enveloppe", isCorrect: false }],
        explanation: "Les bactéries se classent selon leur forme : coque (cocci, ex : Staphylococcus), bâtonnet (bacilles, ex : E. coli), spirale (spirochètes, ex : Treponema) et virgule (vibrions, ex : Vibrio cholerae)." },
      { text: "La flore commensale (microbiote) désigne :",
        options: [{ text: "Les micro-organismes pathogènes responsables d'infections", isCorrect: false },{ text: "L'ensemble des micro-organismes vivant normalement dans/sur l'organisme sans nuire à l'hôte", isCorrect: true },{ text: "Les bactéries présentes uniquement dans l'intestin", isCorrect: false },{ text: "Les parasites permanents de l'organisme humain", isCorrect: false }],
        explanation: "Le microbiote (flore commensale) est l'ensemble des micro-organismes résidant normalement sur/dans l'organisme (peau, intestin, voies respiratoires…). Il joue des rôles essentiels : protection contre les pathogènes, immunité, digestion." },
      { text: "Les champignons responsables d'infections sont appelés :",
        options: [{ text: "Mycobactéries", isCorrect: false },{ text: "Mycoses ou infections fongiques", isCorrect: true },{ text: "Parasitoses", isCorrect: false },{ text: "Prions", isCorrect: false }],
        explanation: "Les infections causées par des champignons microscopiques sont les mycoses (ex : candidose, aspergillose, dermatophytoses). Elles sont causées par des champignons tels que Candida albicans ou Aspergillus fumigatus." },
      { text: "Qu'est-ce que la virulence d'un micro-organisme ?",
        options: [{ text: "Sa capacité à survivre hors de l'organisme", isCorrect: false },{ text: "Sa capacité à provoquer une maladie grave chez l'hôte", isCorrect: true },{ text: "Sa résistance aux antibiotiques", isCorrect: false },{ text: "Sa vitesse de multiplication", isCorrect: false }],
        explanation: "La virulence est la capacité d'un micro-organisme pathogène à provoquer une maladie de gravité importante chez l'hôte. Elle dépend de ses facteurs de virulence (toxines, adhésines, capsule, enzymes de défense)." },
      { text: "Les prions sont des agents infectieux particuliers car ils sont :",
        options: [{ text: "Des virus très petits sans enveloppe", isCorrect: false },{ text: "Des protéines anormalement repliées, sans acide nucléique", isCorrect: true },{ text: "Des parasites intracellulaires", isCorrect: false },{ text: "Des bactéries sans paroi cellulaire", isCorrect: false }],
        explanation: "Les prions sont des protéines infectieuses anormalement repliées, sans ADN ni ARN. Ils causent des encéphalopathies spongiformes (maladie de Creutzfeldt-Jakob, ESB/vache folle). Ils résistent aux procédés habituels de décontamination." },
      { text: "Qu'est-ce qu'une culture bactérienne en milieu sélectif ?",
        options: [{ text: "Un milieu permettant la croissance de toutes les bactéries", isCorrect: false },{ text: "Un milieu contenant des substances inhibant certaines bactéries pour ne laisser pousser que celles recherchées", isCorrect: true },{ text: "Un milieu pauvre en nutriments pour ralentir la croissance", isCorrect: false },{ text: "Un milieu liquide pour suspension bactérienne", isCorrect: false }],
        explanation: "Un milieu sélectif contient des agents (antibiotiques, colorants, sels) inhibant certaines bactéries et permettant la croissance sélective de l'espèce recherchée, facilitant son identification en microbiologie diagnostique." },
      { text: "La résistance aux antibiotiques peut se transmettre entre bactéries par :",
        options: [{ text: "Simple contact physique entre patients", isCorrect: false },{ text: "Transfert horizontal de gènes (plasmides, transposons) entre bactéries", isCorrect: true },{ text: "L'air ambiant uniquement", isCorrect: false },{ text: "Uniquement par mutation spontanée", isCorrect: false }],
        explanation: "La résistance aux antibiotiques se propage principalement par transfert horizontal de gènes (conjugaison via plasmides, transformation, transduction). C'est un problème de santé publique majeur lié à l'usage excessif d'antibiotiques." },
      { text: "Un antibiogramme permet de :",
        options: [{ text: "Identifier l'espèce bactérienne responsable d'une infection", isCorrect: false },{ text: "Déterminer la sensibilité d'une bactérie aux différents antibiotiques testés", isCorrect: true },{ text: "Mesurer la quantité de bactéries dans un prélèvement", isCorrect: false },{ text: "Détecter la présence d'une infection virale", isCorrect: false }],
        explanation: "L'antibiogramme mesure la sensibilité (S), l'intermédiaire (I) ou la résistance (R) d'une bactérie isolée vis-à-vis des antibiotiques testés. Il guide le choix thérapeutique ciblé (antibiothérapie documentée)." }
    ]
  },
  {
    title: "Organisation du corps humain",
    description: "Niveaux d'organisation anatomique et systèmes de l'organisme",
    semester: "Semestre 1",
    category: "UE 2.1 - Biologie fondamentale",
    chapter: "Anatomie générale",
    difficulty: "easy", duration: 15, isPublished: true,
    questions: [
      { text: "Du plus simple au plus complexe, quel est l'ordre des niveaux d'organisation du corps humain ?",
        options: [{ text: "Cellule → Organe → Tissu → Système → Organisme", isCorrect: false },{ text: "Cellule → Tissu → Organe → Système → Organisme", isCorrect: true },{ text: "Tissu → Cellule → Organe → Système → Organisme", isCorrect: false },{ text: "Organe → Tissu → Cellule → Système → Organisme", isCorrect: false }],
        explanation: "L'organisation du corps humain s'échelonne du plus simple au plus complexe : atomes → molécules → cellules → tissus → organes → systèmes → organisme." },
      { text: "Combien de systèmes organiques majeurs composent le corps humain ?",
        options: [{ text: "5 systèmes", isCorrect: false },{ text: "11 systèmes", isCorrect: true },{ text: "7 systèmes", isCorrect: false },{ text: "15 systèmes", isCorrect: false }],
        explanation: "Le corps humain est organisé en 11 systèmes majeurs : tégumentaire, osseux, musculaire, nerveux, endocrinien, cardiovasculaire, lymphatique/immunitaire, respiratoire, digestif, urinaire et reproducteur." },
      { text: "Qu'est-ce que l'homéostasie ?",
        options: [{ text: "La capacité du corps à augmenter sa température en cas d'infection", isCorrect: false },{ text: "La tendance de l'organisme à maintenir un équilibre interne stable malgré les variations externes", isCorrect: true },{ text: "L'adaptation du corps à des conditions extrêmes", isCorrect: false },{ text: "Le rétablissement après une maladie grave", isCorrect: false }],
        explanation: "L'homéostasie est le maintien d'un environnement interne stable (température, pH, glycémie, pression artérielle…) grâce à des mécanismes de régulation (rétroaction négative essentiellement)." },
      { text: "Le plan sagittal médian divise le corps humain en :",
        options: [{ text: "Une partie supérieure et une partie inférieure", isCorrect: false },{ text: "Deux moitiés droite et gauche symétriques", isCorrect: true },{ text: "Une partie antérieure et une partie postérieure", isCorrect: false },{ text: "Trois parties : gauche, droite et centrale", isCorrect: false }],
        explanation: "Le plan sagittal médian (ou plan médian) est vertical et divise le corps en deux moitiés gauche et droite. Le plan frontal (coronal) divise le corps en avant/arrière ; le plan transversal en haut/bas." },
      { text: "Quel tissu est responsable de la contraction et du mouvement ?",
        options: [{ text: "Le tissu épithélial", isCorrect: false },{ text: "Le tissu conjonctif", isCorrect: false },{ text: "Le tissu musculaire", isCorrect: true },{ text: "Le tissu nerveux", isCorrect: false }],
        explanation: "Le tissu musculaire est spécialisé dans la contraction. Il existe trois types : le muscle strié squelettique (mouvement volontaire), le muscle cardiaque (myocarde) et le muscle lisse (organes creux, vaisseaux)." },
      { text: "Le tissu épithélial se caractérise par :",
        options: [{ text: "Une grande vascularisation et une matrice extracellulaire abondante", isCorrect: false },{ text: "Des cellules jointives sans espace intercellulaire, reposant sur une lame basale", isCorrect: true },{ text: "La présence de fibres collagènes et de cellules adipeuses", isCorrect: false },{ text: "La capacité de se contracter", isCorrect: false }],
        explanation: "L'épithélium est formé de cellules très jointives (peu d'espace intercellulaire), avasculaires, reposant sur une membrane basale. Il recouvre les surfaces corporelles (épiderme) et tapisse les cavités (muqueuses)." },
      { text: "Le périoste est :",
        options: [{ text: "La membrane interne tapissant les os creux", isCorrect: false },{ text: "La membrane conjonctive externe recouvrant les os", isCorrect: true },{ text: "Le tissu cartilagineux des articulations", isCorrect: false },{ text: "La cavité médullaire des os longs", isCorrect: false }],
        explanation: "Le périoste est la membrane fibreuse vascularisée enveloppant la surface externe des os (sauf au niveau du cartilage articulaire). Il joue un rôle dans la croissance osseuse, la réparation des fractures et la fixation des tendons." },
      { text: "Le système endocrinien régule l'organisme par :",
        options: [{ text: "Des influx électriques le long des neurones", isCorrect: false },{ text: "La sécrétion d'hormones dans le sang agissant sur des organes cibles", isCorrect: true },{ text: "Des contractions musculaires réflexes", isCorrect: false },{ text: "La production de lymphocytes", isCorrect: false }],
        explanation: "Le système endocrinien (glandes : hypophyse, thyroïde, surrénales, pancréas, gonades…) régule l'organisme par voie hormonale : les hormones sont sécrétées dans le sang et agissent sur des organes cibles à distance." },
      { text: "Le foie est un organe appartenant à quel système ?",
        options: [{ text: "Au système cardiovasculaire uniquement", isCorrect: false },{ text: "Au système digestif, avec également des fonctions métaboliques et de détoxification", isCorrect: true },{ text: "Au système immunitaire uniquement", isCorrect: false },{ text: "Au système endocrinien uniquement", isCorrect: false }],
        explanation: "Le foie est la plus grande glande du corps. Rattaché au système digestif (production de bile), il a aussi des fonctions métaboliques (glycogénèse, synthèse protéique), de détoxification, de stockage et de synthèse de facteurs de coagulation." },
      { text: "Qu'est-ce que la cavité péritonéale ?",
        options: [{ text: "L'espace entre les deux poumons", isCorrect: false },{ text: "La cavité abdominale tapissée par le péritoine contenant les organes digestifs", isCorrect: true },{ text: "L'espace entre le cœur et les poumons", isCorrect: false },{ text: "La cavité à l'intérieur des vertèbres", isCorrect: false }],
        explanation: "La cavité péritonéale est l'espace virtuel dans l'abdomen délimité par le péritoine pariétal (paroi) et viscéral (organes). Elle contient estomac, intestins, foie, rate. Elle peut se remplir de liquide (ascite) en cas de pathologie." }
    ]
  }
];
