// ─── PARTIE 8 : 2e quiz par chapitre — UE 4.1 · UE 5.1 · UE 6.1 · UE 6.2 ────
module.exports = [

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 4.1 – Soins de confort et de bien-être
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Soins d'hygiène corporelle — situations complexes",
    description: "Toilette au lit, soins bucco-dentaires, soins des téguments et prévention",
    semester: "Semestre 1", category: "UE 4.1 - Soins de confort et de bien-être",
    chapter: "Hygiène corporelle", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Lors d'une toilette au lit d'un patient hémiplégique, l'IDE doit :",
        options: [{ text: "Réaliser entièrement la toilette sans impliquer le patient pour gagner du temps", isCorrect: false },{ text: "Solliciter le côté valide du patient, réaliser ce qu'il ne peut pas faire et respecter son rythme", isCorrect: true },{ text: "Déléguer entièrement la toilette à l'aide-soignante", isCorrect: false },{ text: "Utiliser uniquement des lingettes humides pour éviter de fatiguer le patient", isCorrect: false }],
        explanation: "Principe de suppléance (Henderson) : faire AVEC le patient, pas À SA PLACE. Solliciter le membre valide favorise la récupération neurologique et maintient l'autonomie et l'estime de soi." },
      { text: "La fréquence recommandée des soins de bouche chez un patient ventilé mécaniquement est :",
        options: [{ text: "Une fois par jour, le matin", isCorrect: false },{ text: "4 à 6 fois par 24h pour prévenir les PAVM (pneumopathies acquises sous ventilation mécanique)", isCorrect: true },{ text: "Uniquement en cas de mauvaise odeur", isCorrect: false },{ text: "2 fois par semaine selon le protocole standard", isCorrect: false }],
        explanation: "Les PAVM (Pneumopathies Acquises sous Ventilation Mécanique) sont liées à la colonisation buccale. Les soins de bouche 4–6×/24h (avec chlorhexidine à 0,12–0,2%) sont la principale mesure préventive recommandée." },
      { text: "L'observation de la peau lors de la toilette inclut la recherche de :",
        options: [{ text: "Uniquement les rougeurs aux zones d'appui", isCorrect: false },{ text: "Rougeurs, macération, lésions, œdèmes, hématomes, signes d'infection, mycoses interdigitales", isCorrect: true },{ text: "Uniquement les signes d'escarre aux stades 3 et 4", isCorrect: false },{ text: "Uniquement les plaies traumatiques visibles", isCorrect: false }],
        explanation: "La toilette est un moment d'observation clinique privilégié : peau (hydratation, lésions, rougeurs, macération, hématomes), ongles, plis cutanés (mycose, macération), œdèmes, état général du patient." },
      { text: "Pour un soin des pieds d'un patient diabétique, l'IDE doit :",
        options: [{ text: "Couper les ongles en arrondi court pour éviter l'incarnation", isCorrect: false },{ text: "Inspecter minutieusement chaque pied, sécher soigneusement les espaces interdigitaux et couper les ongles droit", isCorrect: true },{ text: "Utiliser une bouillotte pour réchauffer les pieds engourdis", isCorrect: false },{ text: "Appliquer une crème hydratante entre les orteils pour prévenir la sécheresse", isCorrect: false }],
        explanation: "Pied diabétique : inspection minutieuse (neuropathie → insensibilité → blessure inaperçue), séchage soigneux des espaces interdigitaux (prévention mycose/macération), ongles coupés droit (prévention incarnation). Eau tiède < 37°C." },
      { text: "Le rasage d'un patient sous anticoagulants doit être réalisé avec :",
        options: [{ text: "Un rasoir traditionnel à lame pour plus de précision", isCorrect: false },{ text: "Un rasoir électrique pour éviter les coupures et risques hémorragiques", isCorrect: true },{ text: "Une crème dépilatoire uniquement", isCorrect: false },{ text: "Aucun rasage n'est possible sous anticoagulants", isCorrect: false }],
        explanation: "Sous anticoagulants (AVK, HBPM, AOD) : risque hémorragique augmenté. Le rasoir électrique est préféré pour éviter toute coupure. Si lame indispensable, précautions maximales et pression immédiate en cas de saignement." },
      { text: "La prévention des macérations dans les plis cutanés (obésité, alitement) inclut :",
        options: [{ text: "Application d'une crème grasse épaisse pour protéger", isCorrect: false },{ text: "Séchage soigneux des plis, application d'un film protecteur ou compresse non tissée pour limiter l'humidité", isCorrect: true },{ text: "Nettoyer une seule fois par semaine pour ne pas irriter", isCorrect: false },{ text: "Utilisation systématique de poudre de talc dans les plis", isCorrect: false }],
        explanation: "Prévention macération : séchage soigneux des plis (sous-mammaires, inguinaux, abdominaux), films protecteurs ou compresses non tissées entre les plis, surveillance quotidienne, signalement de toute irritation." },
      { text: "Un patient en fin de vie doit bénéficier de soins d'hygiène :",
        options: [{ text: "Uniquement si son état clinique le permet et s'il en fait la demande", isCorrect: false },{ text: "Adaptés, doux et respectueux de la dignité, même en phase terminale", isCorrect: true },{ text: "Réduits au minimum pour ne pas le fatiguer", isCorrect: false },{ text: "Délégués entièrement à la famille présente", isCorrect: false }],
        explanation: "Les soins d'hygiène en fin de vie sont des soins palliatifs essentiels : ils maintiennent la dignité, le confort, permettent le contact humain et l'observation clinique. Ils sont adaptés à l'état du patient mais jamais supprimés." },
      { text: "La pose de bas de contention doit se faire :",
        options: [{ text: "Le soir, avant le coucher du patient", isCorrect: false },{ text: "Le matin, avant le lever du patient, membres encore déclives", isCorrect: true },{ text: "Après que le patient s'est levé et mobilisé", isCorrect: false },{ text: "Uniquement en post-opératoire immédiat", isCorrect: false }],
        explanation: "Les bas de contention se posent LE MATIN, AVANT le lever, quand les veines sont encore vidées (membre horizontal). Si posés debout ou après mobilisation, le sang a déjà rempli les veines → inefficacité." },
      { text: "Face à un patient refusant la toilette pour raisons culturelles ou religieuses, l'IDE doit :",
        options: [{ text: "Imposer la toilette car elle est médicalement nécessaire", isCorrect: false },{ text: "Respecter les croyances, proposer des alternatives et adapter les soins avec le patient", isCorrect: true },{ text: "Signaler le refus comme maltraitance envers soi-même", isCorrect: false },{ text: "Déléguer au médecin cette décision", isCorrect: false }],
        explanation: "Autonomie et respect culturel : négocier, proposer des alternatives (même sexe du soignant, toilette partielle, intimité renforcée). Tracer le refus et l'accord trouvé. Jamais forcer : c'est une maltraitance." },
      { text: "L'évaluation de l'autonomie d'un patient pour les soins d'hygiène utilise :",
        options: [{ text: "L'échelle de Braden uniquement", isCorrect: false },{ text: "La grille d'évaluation des AVQ (Activités de la Vie Quotidienne) ou l'indice de Barthel", isCorrect: true },{ text: "Le score de Glasgow", isCorrect: false },{ text: "L'échelle de Morse pour les chutes", isCorrect: false }],
        explanation: "L'indice de Barthel évalue l'autonomie pour 10 AVQ (toilette, habillage, alimentation, continence, transfert, marche...). Il guide la démarche de suppléance et l'orientation vers les soins de suite." }
    ]
  },
  {
    title: "Prévention des complications du décubitus et mobilisation",
    description: "Escarres, phlébite, raideurs articulaires — prévention et prise en charge",
    semester: "Semestre 1", category: "UE 4.1 - Soins de confort et de bien-être",
    chapter: "Prévention des plaies", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "L'escarre trochantérienne se prévient en évitant la position :",
        options: [{ text: "De décubitus dorsal strict à plat", isCorrect: false },{ text: "Latérale à 90° (appui direct sur le trochanter)", isCorrect: true },{ text: "Semi-assise à 30°", isCorrect: false },{ text: "De décubitus ventral", isCorrect: false }],
        explanation: "L'escarre trochantérienne se forme en décubitus latéral à 90°. On prévient en utilisant une inclinaison à 30° maximum (demi-latérale), oreiller entre les jambes. Le trochanter ne doit jamais être en appui direct." },
      { text: "La durée maximale recommandée entre deux changements de position en prévention des escarres est :",
        options: [{ text: "30 minutes", isCorrect: false },{ text: "2 à 3 heures (selon le risque évalué)", isCorrect: true },{ text: "6 heures minimum pour ne pas perturber le sommeil", isCorrect: false },{ text: "12 heures en cas de patient stable", isPublished: false, isCorrect: false }],
        explanation: "Recommandations EPUAP : alternance de position toutes les 2–3h chez les patients à risque alités. Un matelas à air dynamique permet d'allonger les intervalles mais ne remplace pas les changements de position." },
      { text: "La nutrition joue un rôle dans la prévention des escarres car :",
        options: [{ text: "Elle n'a aucun impact, seule la pression compte", isCorrect: false },{ text: "La dénutrition (protéines, zinc, vitamine C) altère les capacités de cicatrisation et la tolérance tissulaire", isCorrect: true },{ text: "Un excès de graisses protège les zones d'appui", isCorrect: false },{ text: "Seule l'hydratation compte, pas les apports protéiques", isCorrect: false }],
        explanation: "La dénutrition est un facteur de risque majeur d'escarre : ↓ albumine → ↓ pression oncotique → œdèmes, ↓ apports en zinc et vitamine C → cicatrisation altérée. Objectif protéines : 1,2–1,5 g/kg/j chez les patients à risque." },
      { text: "Le massage des zones d'appui en prévention des escarres est :",
        options: [{ text: "Recommandé pour stimuler la circulation locale", isCorrect: false },{ text: "Contre-indiqué car il peut aggraver les lésions des capillaires déjà fragilisés", isCorrect: true },{ text: "Recommandé uniquement avec une huile de massage spécialisée", isCorrect: false },{ text: "Indiqué uniquement pour les stades 1 et 2", isCorrect: false }],
        explanation: "Le massage des zones à risque (érythème, proéminences osseuses) est CONTRE-INDIQUÉ : il peut aggraver les lésions capillaires sous-cutanées et accélérer la formation d'escarre. On réhydrate la peau sans masser." },
      { text: "Les anneaux et cercles de mousse pour protéger les zones d'appui sont :",
        options: [{ text: "Très efficaces car ils suppriment la pression sur la zone centrale", isCorrect: false },{ text: "Contre-indiqués car ils créent une pression périphérique aggravant l'ischémie locale", isCorrect: true },{ text: "Recommandés uniquement pour les talons", isCorrect: false },{ text: "La meilleure solution pour les escarres de stade 1", isCorrect: false }],
        explanation: "Les anneaux de mousse sont CONTRE-INDIQUÉS : ils créent une pression circulaire péri-lésionnelle qui aggrave l'ischémie. On utilise des coussins de décharge (talonnières en mousse) qui répartissent la pression." },
      { text: "La raideur articulaire par manque de mobilisation (enraidissement) est prévenue par :",
        options: [{ text: "L'immobilisation stricte pour protéger les articulations", isCorrect: false },{ text: "La mobilisation passive et active des articulations plusieurs fois par jour", isCorrect: true },{ text: "L'application de chaleur uniquement", isCorrect: false },{ text: "L'administration d'anti-inflammatoires en prévention", isCorrect: false }],
        explanation: "La mobilisation articulaire (passive si le patient ne peut pas, active assistée dès que possible) prévient les rétractions musculo-tendineuses et les ankyloses. Kinésithérapie et ergothérapie sont partenaires." },
      { text: "La kinésithérapie respiratoire en prévention des complications du décubitus vise à prévenir :",
        options: [{ text: "La thrombose veineuse profonde uniquement", isCorrect: false },{ text: "L'encombrement bronchique, l'atélectasie et la pneumopathie d'inhalation", isCorrect: true },{ text: "L'essoufflement à l'effort uniquement", isCorrect: false },{ text: "Uniquement les pneumopathies infectieuses", isCorrect: false }],
        explanation: "En décubitus prolongé : hypoventilation, accumulation de sécrétions, atélectasie. La kinésithérapie respiratoire (drainage postural, percussion, spirométrie incitative) prévient ces complications pulmonaires." },
      { text: "La surveillance d'un patient sous contention physique (bandes de maintien) comprend :",
        options: [{ text: "Uniquement la vérification que la contention reste en place", isCorrect: false },{ text: "Réévaluation toutes les 2h, circulation distale, état cutané, état mental, proposer des alternatives", isCorrect: true },{ text: "Une vérification quotidienne par le médecin uniquement", isCorrect: false },{ text: "Aucune surveillance particulière si le patient est calme", isCorrect: false }],
        explanation: "Contention physique : réévaluation ≥ toutes les 2h (voire plus fréquente), vérification de la circulation distale, état cutané sous la contention, état psychologique, recherche d'alternatives permanente." },
      { text: "La verticalisation progressive d'un patient alité depuis longtemps vise à prévenir :",
        options: [{ text: "Les escarres des talons uniquement", isCorrect: false },{ text: "L'hypotension orthostatique, le déconditionnement cardiovasculaire et la perte d'autonomie", isCorrect: true },{ text: "La dépression liée à l'hospitalisation uniquement", isCorrect: false },{ text: "Les infections urinaires sur sonde uniquement", isCorrect: false }],
        explanation: "La verticalisation progressive (bord de lit → fauteuil → debout) prévient l'hypotension orthostatique, le déconditionnement cardiaque et musculaire, et facilite la reprise de l'autonomie." },
      { text: "L'hypotension orthostatique se manifeste par :",
        options: [{ text: "Une augmentation de la PA dès le lever", isCorrect: false },{ text: "Une chute de la PAS ≥ 20 mmHg ou PAD ≥ 10 mmHg dans les 3 minutes suivant le lever", isCorrect: true },{ text: "Une tachycardie isolée sans modification de la PA", isCorrect: false },{ text: "Des douleurs des membres inférieurs au lever uniquement", isCorrect: false }],
        explanation: "Hypotension orthostatique : ↓ PAS ≥ 20 mmHg ou ↓ PAD ≥ 10 mmHg dans les 3 min du lever. Signes : vertiges, lipothymie, chute. Prévention : lever progressif, bas de contention, hydratation, révision des médicaments." }
    ]
  },
  {
    title: "Accompagnement psychologique et confort global du patient hospitalisé",
    description: "Bien-être psychologique, gestion de l'anxiété et qualité de vie en soins",
    semester: "Semestre 1", category: "UE 4.1 - Soins de confort et de bien-être",
    chapter: "Modèle de Henderson", difficulty: "easy", duration: 15, isPublished: true,
    questions: [
      { text: "Virginia Henderson définit le rôle infirmier comme :",
        options: [{ text: "Exécuter les prescriptions médicales avec précision", isCorrect: false },{ text: "Aider le patient à satisfaire ses 14 besoins fondamentaux qu'il accomplirait seul s'il en avait la capacité", isCorrect: true },{ text: "Diagnostiquer les maladies et prescrire des traitements", isCorrect: false },{ text: "Surveiller le patient et transmettre les informations au médecin", isCorrect: false }],
        explanation: "Henderson : l'IDE aide le patient à satisfaire ses 14 besoins fondamentaux 'qu'il accomplirait seul s'il en avait la force, la volonté ou le savoir-faire', dans le but de recouvrer son indépendance." },
      { text: "Selon Henderson, le besoin 'Communiquer avec ses semblables' comprend :",
        options: [{ text: "Uniquement la communication verbale orale", isCorrect: false },{ text: "La communication verbale et non verbale, les relations sociales et l'expression des émotions", isCorrect: true },{ text: "L'utilisation des médias et réseaux sociaux", isCorrect: false },{ text: "Uniquement la relation avec les professionnels de santé", isCorrect: false }],
        explanation: "Le besoin de communiquer inclut : expression verbale et non verbale, relations sociales, expression des émotions et des besoins, compréhension des informations reçues. La maladie peut altérer chaque dimension." },
      { text: "Pour favoriser le sommeil d'un patient hospitalisé, l'IDE peut :",
        options: [{ text: "Administrer systématiquement un somnifère en début de soirée", isCorrect: false },{ text: "Regrouper les soins nocturnes, réduire le bruit et la lumière, respecter les rituels du patient", isCorrect: true },{ text: "Imposer un coucher à 21h pour tous les patients", isCorrect: false },{ text: "Maintenir l'activité physique le soir pour favoriser l'endormissement", isCorrect: false }],
        explanation: "Mesures non pharmacologiques pour le sommeil : regrouper les soins (éviter les interruptions nocturnes), réduire bruit et lumière, respecter les rituels (lecture, boisson chaude), position confortable, gestion de la douleur." },
      { text: "L'anxiété préopératoire peut être réduite par :",
        options: [{ text: "L'évitement du sujet pour ne pas augmenter les craintes", isCorrect: false },{ text: "L'information adaptée sur le déroulement de l'intervention, l'écoute des craintes et la présence rassurante", isCorrect: true },{ text: "La prescription systématique de benzodiazépines la veille de l'opération", isCorrect: false },{ text: "L'interdiction de poser des questions au patient pour ne pas l'angoisser davantage", isCorrect: false }],
        explanation: "L'anxiété préopératoire est normale. Elle est réduite par : information claire et adaptée (chemin clinique), écoute des craintes, consultation pré-anesthésique, visite de la salle de réveil, prémédication si nécessaire." },
      { text: "Le soutien spirituel d'un patient en fin de vie fait partie :",
        options: [{ text: "Exclusivement de la mission des aumôniers et personnels religieux", isCorrect: false },{ text: "Du rôle infirmier : écouter, respecter les croyances, faciliter l'accès aux représentants religieux", isCorrect: true },{ text: "D'une approche non médicale qui n'a pas sa place à l'hôpital", isCorrect: false },{ text: "Du travail des psychologues uniquement", isCorrect: false }],
        explanation: "Les besoins spirituels sont des besoins fondamentaux (Henderson, OMS). L'IDE écoute, respecte les croyances, accompagne sans imposer et facilite l'accès aux représentants religieux si le patient le souhaite." },
      { text: "La douleur chronique impacte le bien-être du patient principalement sur :",
        options: [{ text: "Uniquement la dimension physique (intensité douloureuse)", isCorrect: false },{ text: "Les dimensions physique, psychologique, sociale et existentielle (concept de douleur totale)", isCorrect: true },{ text: "La dimension professionnelle uniquement (arrêt de travail)", isCorrect: false },{ text: "La dimension biologique (résultats d'analyses)", isCorrect: false }],
        explanation: "La 'douleur totale' (Cicely Saunders) englobe 4 dimensions : physique (symptômes), psychologique (anxiété, dépression), sociale (isolement, perte de rôle) et existentielle (sens de la vie, spiritualité)." },
      { text: "Le projet de vie personnalisé en EHPAD s'appuie sur :",
        options: [{ text: "Les recommandations médicales uniquement", isCorrect: false },{ text: "Les habitudes de vie, les préférences, l'histoire de vie et les valeurs du résident", isCorrect: true },{ text: "Le règlement intérieur de l'établissement", isCorrect: false },{ text: "La décision de la famille sans consulter le résident", isCorrect: false }],
        explanation: "Le projet de vie personnalisé (loi 2002-2) individualise la prise en charge en EHPAD en tenant compte des habitudes, préférences, histoire de vie et valeurs de chaque résident. Il est co-construit avec la personne." },
      { text: "L'environnement chambre d'un patient hospitalisé doit permettre :",
        options: [{ text: "Une surveillance maximale du soignant en permanence", isCorrect: false },{ text: "L'intimité, la sécurité, l'accès aux effets personnels et le maintien d'un lien avec l'extérieur", isCorrect: true },{ text: "Un environnement standardisé identique pour tous les patients", isCorrect: false },{ text: "La restriction des visites pour éviter les infections", isCorrect: false }],
        explanation: "L'environnement thérapeutique : intimité (rideaux, chambre individuelle si possible), sécurité (barres, sonnette), effets personnels (photos, objets signifiants), ouverture vers l'extérieur (fenêtre, TV, téléphone)." },
      { text: "La musicothérapie en soins palliatifs est utilisée car :",
        options: [{ text: "Elle remplace les antalgiques médicamenteux", isCorrect: false },{ text: "Elle peut réduire l'anxiété, la douleur et améliorer la qualité de vie sans effets indésirables", isCorrect: true },{ text: "Elle est obligatoire dans les unités de soins palliatifs françaises", isCorrect: false },{ text: "Elle améliore le pronostic médical des patients", isCorrect: false }],
        explanation: "La musicothérapie est une thérapie non médicamenteuse validée en soins palliatifs : réduit anxiété, douleur (distraction), agitation, améliore humeur et qualité de vie. Elle complète sans remplacer le traitement médicamenteux." },
      { text: "La qualité de vie d'un patient hospitalisé est évaluée notamment par :",
        options: [{ text: "Uniquement les résultats biologiques et les constantes vitales", isCorrect: false },{ text: "Des échelles validées (SF-36, WHOQOL) mesurant les dimensions physique, psychologique, sociale et environnementale", isCorrect: true },{ text: "Le taux de satisfaction des proches uniquement", isCorrect: false },{ text: "L'opinion subjective du soignant référent", isCorrect: false }],
        explanation: "La qualité de vie est évaluée par des outils multidimensionnels validés (SF-36, WHOQOL-26, EuroQol) mesurant le fonctionnement physique, psychologique, social et le bien-être général." }
    ]
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 5.1 – Accompagnement dans la réalisation des soins quotidiens
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Éducation thérapeutique du patient (ETP) — mise en œuvre",
    description: "Diagnostic éducatif, séances d'ETP et évaluation des compétences du patient",
    semester: "Semestre 1", category: "UE 5.1 - Accompagnement dans la réalisation des soins quotidiens",
    chapter: "Nutrition clinique", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "L'ETP (Éducation Thérapeutique du Patient) est définie par l'OMS comme :",
        options: [{ text: "La remise de documents d'information au patient à la sortie", isCorrect: false },{ text: "Un processus continu d'apprentissage pour aider le patient à acquérir des compétences d'autogestion de sa maladie", isCorrect: true },{ text: "Les conseils donnés par l'IDE pendant les soins techniques", isCorrect: false },{ text: "La formation des soignants aux maladies chroniques", isCorrect: false }],
        explanation: "OMS 1998 : l'ETP aide les patients à acquérir les compétences pour gérer leur vie avec une maladie chronique. C'est un processus structuré, planifié, coordonné, évalué — pas une simple information ponctuelle." },
      { text: "Le diagnostic éducatif doit explorer :",
        options: [{ text: "Uniquement les connaissances médicales du patient sur sa maladie", isCorrect: false },{ text: "Ce que le patient sait, fait, ressent et ce qui l'entoure (ressources et obstacles)", isCorrect: true },{ text: "Le niveau scolaire du patient pour adapter le vocabulaire", isCorrect: false },{ text: "Les préférences alimentaires du patient uniquement", isCorrect: false }],
        explanation: "Le diagnostic éducatif explore les 4 dimensions : ce que le patient SAIT (connaissances), PEUT FAIRE (compétences), FAIT (comportements réels), RESSENT (émotions, représentations, motivations) et son environnement." },
      { text: "Un patient diabétique de type 2 sous insuline doit apprendre à reconnaître les signes d'hypoglycémie. Cette compétence est de type :",
        options: [{ text: "Compétence sécuritaire d'autosoins", isCorrect: true },{ text: "Compétence d'adaptation à la maladie", isCorrect: false },{ text: "Compétence relationnelle", isCorrect: false },{ text: "Compétence organisationnelle", isCorrect: false }],
        explanation: "Les compétences d'autosoins de sécurité permettent d'agir en situation à risque (hypoglycémie, crise d'asthme...). Elles sont prioritaires car elles préviennent des urgences vitales." },
      { text: "La méthode pédagogique 'teach-back' consiste à :",
        options: [{ text: "Répéter plusieurs fois la même information au patient", isCorrect: false },{ text: "Demander au patient de reformuler avec ses propres mots ce qu'il a compris", isCorrect: true },{ text: "Enseigner aux soignants les techniques d'ETP", isCorrect: false },{ text: "Utiliser uniquement des supports visuels pour l'enseignement", isCorrect: false }],
        explanation: "Le teach-back (retour d'enseignement) : le soignant demande au patient de réexpliquer avec ses propres mots. C'est la méthode la plus validée pour vérifier la compréhension et identifier les lacunes." },
      { text: "L'ETP pour un patient insuffisant cardiaque inclut l'apprentissage de :",
        options: [{ text: "Uniquement la prise de médicaments selon l'ordonnance", isCorrect: false },{ text: "La pesée quotidienne, restriction sodée, seuil d'alerte, activité physique adaptée et médicaments", isCorrect: true },{ text: "Le régime alimentaire hypocalorique uniquement", isCorrect: false },{ text: "La reconnaissance des signes d'AVC uniquement", isCorrect: false }],
        explanation: "ETP insuffisance cardiaque : pesée quotidienne (alerte si + 2kg en 3j), restriction en sel, médicaments (diurétiques, bêtabloquants), activité physique adaptée, signes d'alerte (dyspnée, œdèmes), consultation si décompensation." },
      { text: "L'entretien motivationnel en ETP vise à :",
        options: [{ text: "Convaincre le patient de l'importance de changer ses habitudes", isCorrect: false },{ text: "Explorer et renforcer la motivation intrinsèque du patient au changement de comportement", isCorrect: true },{ text: "Évaluer la résistance du patient au traitement", isCorrect: false },{ text: "Motiver financièrement le patient à suivre son traitement", isCorrect: false }],
        explanation: "L'entretien motivationnel (Miller & Rollnick) explore l'ambivalence du patient, renforce ses motivations intrinsèques et son sentiment d'efficacité personnelle. Non directif, centré patient." },
      { text: "L'évaluation des compétences acquises en ETP se fait par :",
        options: [{ text: "Un questionnaire écrit noté à l'issue de chaque séance", isCorrect: false },{ text: "Des mises en situation, jeux de rôle, démonstration de gestes et entretiens d'évaluation", isCorrect: true },{ text: "Uniquement les résultats biologiques (HbA1c, INR...)", isCorrect: false },{ text: "L'opinion subjective du soignant éducateur", isCorrect: false }],
        explanation: "L'évaluation ETP utilise des méthodes actives : simulation, mise en situation clinique (démonstration/contre-démonstration), jeux de rôle, entretiens. Les résultats biologiques sont complémentaires mais insuffisants." },
      { text: "L'autosurveillance glycémique doit être enseignée avec :",
        options: [{ text: "Une démonstration unique par le soignant sans pratique du patient", isCorrect: false },{ text: "Démonstration, pratique supervisée, feed-back immédiat et évaluation de la compréhension", isCorrect: true },{ text: "Uniquement une brochure illustrée donnée à la sortie", isCorrect: false },{ text: "Un cours théorique sur le diabète avant toute démonstration pratique", isCorrect: false }],
        explanation: "Pour les gestes techniques (glycémie capillaire, injection insuline, utilisation inhalateur) : démonstration par le soignant + pratique par le patient + feed-back correctif + réévaluation à distance. La pratique est indispensable." },
      { text: "L'ETP est un droit du patient reconnu par :",
        options: [{ text: "Le code du travail infirmier de 2016", isCorrect: false },{ text: "La loi HPST (Hôpital, Patients, Santé, Territoires) de 2009", isCorrect: true },{ text: "La loi Kouchner de 2002 uniquement", isCorrect: false },{ text: "Le règlement européen de 2018", isCorrect: false }],
        explanation: "La loi HPST (2009) a intégré l'ETP dans le Code de la santé publique (art. L1161-1). Elle définit l'ETP comme un droit des patients atteints de maladies chroniques et une mission des professionnels de santé." },
      { text: "Un patient qui dit 'Je sais que je devrais, mais je n'y arrive pas' est en phase :",
        options: [{ text: "De contemplation : il perçoit le problème mais n'est pas encore prêt à agir", isCorrect: true },{ text: "De pré-contemplation : il ne reconnaît pas le problème", isCorrect: false },{ text: "De maintenance : il maintient déjà le changement", isCorrect: false },{ text: "D'action : il a commencé à changer", isCorrect: false }],
        explanation: "Modèle transthéorique de Prochaska : contemplation (ambivalence — conscient du problème mais bloqué), pré-contemplation (déni), préparation, action, maintenance. L'IDE adapte son approche à la phase du patient." }
    ]
  },
  {
    title: "Relation thérapeutique, communication et soutien au patient",
    description: "Communication thérapeutique, accompagnement des patients et des familles",
    semester: "Semestre 1", category: "UE 5.1 - Accompagnement dans la réalisation des soins quotidiens",
    chapter: "Mobilisation et relation de soin", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "La communication non verbale représente environ ___% du message total :",
        options: [{ text: "20%", isCorrect: false },{ text: "65–80%", isCorrect: true },{ text: "50% exactement", isCorrect: false },{ text: "Moins de 10%", isCorrect: false }],
        explanation: "Les études (Mehrabian) suggèrent que 65–80% de la communication est non verbale (posture, regard, expression faciale, ton de la voix, gestes). En soins, la cohérence entre verbal et non verbal est essentielle." },
      { text: "Face à un patient en pleurs, la première réaction thérapeutique de l'IDE est :",
        options: [{ text: "Changer rapidement de sujet pour éviter la détresse", isCorrect: false },{ text: "Rester présent en silence, lui laisser le temps, nommer l'émotion et proposer une écoute", isCorrect: true },{ text: "Appeler immédiatement le psychologue", isCorrect: false },{ text: "Sortir de la chambre pour lui laisser de l'intimité", isCorrect: false }],
        explanation: "Présence thérapeutique : rester, ne pas fuir la détresse, silence bienveillant, toucher (si approprié), nommer l'émotion ('je vois que vous êtes triste'), écoute active. Proposer le psychologue viendra après." },
      { text: "La question ouverte en relation d'aide est :",
        options: [{ text: "'Avez-vous bien dormi ?' (réponse oui/non)", isCorrect: false },{ text: "'Comment vous sentez-vous ce matin ?'", isCorrect: true },{ text: "'Prenez-vous votre traitement ?' (réponse oui/non)", isCorrect: false },{ text: "'Votre douleur est à 5/10 ?' (réponse oui/non)", isCorrect: false }],
        explanation: "La question ouverte invite à l'expression libre et approfondie. 'Comment vous sentez-vous ?' ouvre la conversation. Les questions fermées (oui/non) recueillent une information précise mais limitent l'expression." },
      { text: "La reformulation en relation d'aide permet :",
        options: [{ text: "De corriger les erreurs du patient sur sa maladie", isCorrect: false },{ text: "De montrer qu'on a écouté, de vérifier la compréhension et d'approfondir l'exploration", isCorrect: true },{ text: "De résoudre rapidement le problème du patient", isCorrect: false },{ text: "De donner un avis sur la situation du patient", isCorrect: false }],
        explanation: "Reformuler = redire avec ses propres mots ce que le patient vient d'exprimer. Bénéfices : preuve d'écoute, validation, clarification, invitation à approfondir. Ex : 'Si je comprends bien, vous vous sentez dépassé par...'" },
      { text: "La relation d'aide se distingue de l'amitié car :",
        options: [{ text: "Il n'y a pas de différence importante entre les deux", isCorrect: false },{ text: "Elle est professionnelle, temporaire, orientée vers le bien-être du patient et asymétrique", isCorrect: true },{ text: "Elle est fondée sur des intérêts mutuels et la réciprocité", isCorrect: false },{ text: "Elle peut inclure des rencontres en dehors du contexte de soins", isCorrect: false }],
        explanation: "La relation d'aide est professionnelle : asymétrique (centralité du patient), limitée dans le temps et l'espace, fondée sur les besoins du patient (pas les nôtres). Les limites protègent le patient et le soignant." },
      { text: "L'accompagnement des proches d'un patient en fin de vie comprend :",
        options: [{ text: "Leur demander de quitter la chambre pour ne pas perturber le patient", isCorrect: false },{ text: "Information adaptée, soutien émotionnel, présence facilitée, préparation au deuil et accompagnement après le décès", isCorrect: true },{ text: "Les orienter systématiquement vers un groupe de soutien sans les impliquer dans les soins", isCorrect: false },{ text: "Les tenir à l'écart des décisions médicales pour éviter les conflits", isCorrect: false }],
        explanation: "Les proches sont des partenaires de soins en fin de vie. Leur accompagnement : information adaptée, soutien émotionnel, aide à la présence, implication dans les soins si ils le souhaitent, accompagnement du deuil après le décès." },
      { text: "Le silence thérapeutique en relation d'aide est :",
        options: [{ text: "Un signe d'incompétence du soignant qui ne sait pas quoi dire", isCorrect: false },{ text: "Un outil thérapeutique puissant qui laisse le temps à la réflexion et à l'expression émotionnelle", isCorrect: true },{ text: "Toujours inconfortable et à éviter", isCorrect: false },{ text: "Interprété par le patient comme un désintérêt du soignant", isCorrect: false }],
        explanation: "Le silence bienveillant est un outil puissant : il respecte le rythme du patient, laisse le temps à la réflexion, favorise l'émergence des émotions et signale que le soignant est pleinement présent et attentif." },
      { text: "La limite professionnelle dans la relation soignant-soigné est dépassée quand :",
        options: [{ text: "L'IDE ressent de l'empathie pour le patient", isCorrect: false },{ text: "L'IDE partage ses coordonnées personnelles, accepte des cadeaux onéreux ou entretient une relation hors soins", isCorrect: true },{ text: "L'IDE consacre plus de temps à un patient anxieux", isCorrect: false },{ text: "L'IDE se souvient du prénom et de l'histoire de vie du patient", isCorrect: false }],
        explanation: "Les limites professionnelles protègent patient et soignant. Elles sont franchies par : échanges de coordonnées personnelles, cadeaux significatifs, contact hors cadre institutionnel, confidences personnelles intimes." },
      { text: "L'accompagnement de l'aidant naturel (famille) d'un proche dépendant à domicile comprend :",
        options: [{ text: "Uniquement des formations techniques aux soins (toilette, transfert)", isCorrect: false },{ text: "Formation aux soins, soutien psychologique, information sur les ressources (répit, aides) et détection de l'épuisement", isCorrect: true },{ text: "Le remplacement total de l'aidant par des professionnels", isCorrect: false },{ text: "Uniquement la surveillance médicale du proche dépendant", isCorrect: false }],
        explanation: "L'aidant naturel peut s'épuiser (burn-out de l'aidant). Son accompagnement : formation aux soins, écoute de ses difficultés, information sur les services de répit (HAD, accueil de jour, SSIAD), détection de l'épuisement." },
      { text: "La notion de 'juste distance' en soins infirmiers désigne :",
        options: [{ text: "La distance physique à maintenir entre le soignant et le patient lors des soins", isCorrect: false },{ text: "L'équilibre entre la distance protectrice et la proximité empathique dans la relation de soin", isCorrect: true },{ text: "La distance hiérarchique entre IDE et médecin", isCorrect: false },{ text: "Le temps de présence maximum autorisé dans la chambre du patient", isCorrect: false }],
        explanation: "La juste distance est l'équilibre délicat entre trop de distance (froideur, déshumanisation) et trop de proximité (fusion, perte de la posture professionnelle). Elle se construit avec l'expérience et la supervision." }
    ]
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 6.1 – Méthodes de travail et TIC
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Gestion des risques, qualité et sécurité des soins",
    description: "Culture de sécurité, indicateurs qualité, gestion des erreurs en établissement",
    semester: "Semestre 1", category: "UE 6.1 - Méthodes de travail et TIC",
    chapter: "Organisation professionnelle", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "La culture 'juste' (Just Culture) en établissement de santé signifie :",
        options: [{ text: "Sanctionner systématiquement tout professionnel ayant commis une erreur", isCorrect: false },{ text: "Distinguer les erreurs honnêtes (systémiques) des comportements délibérément dangereux, et apprendre de chaque incident", isCorrect: true },{ text: "Ignorer toutes les erreurs pour maintenir la motivation des équipes", isCorrect: false },{ text: "Rendre publique l'identité de tout soignant ayant commis une erreur", isCorrect: false }],
        explanation: "La culture juste distingue : erreurs honnêtes (à analyser systémiquement, sans punir), négligences (à corriger par coaching), violations délibérées (à sanctionner). Elle favorise la déclaration et l'apprentissage." },
      { text: "La méthode d'analyse des causes profondes (RCA — Root Cause Analysis) est utilisée pour :",
        options: [{ text: "Identifier rapidement le soignant responsable d'un incident", isCorrect: false },{ text: "Comprendre les facteurs systémiques ayant contribué à un EIG et éviter sa récurrence", isCorrect: true },{ text: "Calculer le coût financier d'un événement indésirable", isCorrect: false },{ text: "Évaluer la satisfaction des patients après un incident", isCorrect: false }],
        explanation: "La RCA (méthode ALARM, ORION, arbre des causes) analyse tous les facteurs contributifs (humains, organisationnels, techniques, environnementaux) pour identifier les causes racines et proposer des actions préventives." },
      { text: "La HAS (Haute Autorité de Santé) certifie les établissements de santé selon une périodicité de :",
        options: [{ text: "Chaque année", isCorrect: false },{ text: "Tous les 5–6 ans (certification V2020/2024)", isCorrect: true },{ text: "Tous les 10 ans", isCorrect: false },{ text: "Une seule fois à l'ouverture de l'établissement", isCorrect: false }],
        explanation: "La certification HAS évalue la qualité et la sécurité des soins dans les établissements de santé (hôpitaux, cliniques). Depuis V2020, elle est basée sur des indicateurs continus et des visites ciblées tous les 5–6 ans." },
      { text: "Un indicateur de qualité des soins mesure :",
        options: [{ text: "Uniquement la satisfaction des patients via des questionnaires", isCorrect: false },{ text: "Des aspects mesurables de la qualité (structure, processus, résultats) permettant de comparer et d'améliorer", isCorrect: true },{ text: "Uniquement le nombre d'infections nosocomiales", isCorrect: false },{ text: "La rentabilité financière du service de soins", isCorrect: false }],
        explanation: "Les indicateurs qualité couvrent 3 dimensions (Donabedian) : structure (moyens humains et matériels), processus (pratiques de soins) et résultats (outcomes : mortalité, complications, satisfaction)." },
      { text: "Le CREX (Comité de Retour d'EXpérience) est une réunion d'équipe qui analyse :",
        options: [{ text: "Les résultats financiers du service", isCorrect: false },{ text: "Les événements indésirables survenus pour en tirer des enseignements collectifs", isCorrect: true },{ text: "Les performances individuelles de chaque soignant", isCorrect: false },{ text: "Les formations suivies par les membres de l'équipe", isCorrect: false }],
        explanation: "Le CREX est une méthode d'amélioration continue : l'équipe analyse collégialement les EI survenus (y compris les presqu'accidents) dans un cadre bienveillant, et décide d'actions correctives." },
      { text: "Le principe de check-list (liste de vérification) au bloc opératoire (OMS 'Safe Surgery') a permis de réduire :",
        options: [{ text: "Le temps opératoire de 50%", isCorrect: false },{ text: "La mortalité péri-opératoire de 40% et les complications de 36%", isCorrect: true },{ text: "Les coûts hospitaliers de 30%", isCorrect: false },{ text: "Les infections du site opératoire de 5% uniquement", isCorrect: false }],
        explanation: "La check-list 'Surgical Safety Checklist' (OMS 2008) : pause avant anesthésie, avant incision, avant sortie du bloc. Les études montrent une réduction de 40% de la mortalité et 36% des complications. Obligatoire en France depuis 2010." },
      { text: "La traçabilité médicamenteuse informatisée (prescription-dispensation-administration) vise à :",
        options: [{ text: "Réduire les coûts pharmaceutiques uniquement", isCorrect: false },{ text: "Sécuriser le circuit du médicament en réduisant les erreurs à chaque étape", isCorrect: true },{ text: "Faciliter la facturation des actes pharmaceutiques", isCorrect: false },{ text: "Remplacer l'infirmière dans la vérification des médicaments", isCorrect: false }],
        explanation: "La dispensation nominative informatisée sécurise le circuit du médicament : prescription électronique (lisible, complète), validation pharmaceutique, préparation traçable, administration avec scan du code-barres patient + médicament." },
      { text: "Le ratio soignant/patient en soins infirmiers influence directement :",
        options: [{ text: "Uniquement la satisfaction professionnelle des IDE", isCorrect: false },{ text: "La mortalité, les complications (escarres, infections), la satisfaction patient et les arrêts de travail IDE", isCorrect: true },{ text: "Uniquement le coût des séjours hospitaliers", isCorrect: false },{ text: "Seulement la rapidité d'exécution des soins techniques", isCorrect: false }],
        explanation: "Des études (Aiken et al.) prouvent que chaque patient supplémentaire par IDE augmente la mortalité de 7%. Un ratio inadéquat est associé à plus de complications, d'erreurs, d'épuisement professionnel et de turn-over." },
      { text: "La gestion documentaire en établissement de santé impose que les protocoles soient :",
        options: [{ text: "Rédigés une fois et conservés sans modification", isCorrect: false },{ text: "Datés, validés par les instances compétentes, diffusés, appliqués et mis à jour régulièrement", isCorrect: true },{ text: "Uniquement accessibles au cadre de santé du service", isCorrect: false },{ text: "Rédigés uniquement par le médecin responsable du service", isCorrect: false }],
        explanation: "Les protocoles doivent être : datés, versionnés, validés (commission médicale, CLIN...), diffusés à tous les soignants concernés, appliqués et révisés régulièrement selon les nouvelles recommandations." },
      { text: "L'amélioration continue de la qualité (PDCA) signifie :",
        options: [{ text: "Performance, Décision, Contrôle, Application", isCorrect: false },{ text: "Plan (planifier), Do (faire), Check (vérifier), Act (améliorer)", isCorrect: true },{ text: "Prévention, Diagnostic, Correction, Analyse", isCorrect: false },{ text: "Projet, Développement, Certification, Audit", isCorrect: false }],
        explanation: "Le cycle PDCA (Deming) : Plan (définir objectifs, méthodes), Do (mettre en œuvre), Check (mesurer et analyser les résultats), Act (corriger et standardiser). C'est la base de la démarche qualité continue." }
    ]
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 6.2 – Anglais médical
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Clinical English : patient assessment and care communication",
    description: "Évaluation clinique, communication infirmière et situations d'urgence en anglais",
    semester: "Semestre 1", category: "UE 6.2 - Anglais",
    chapter: "Clinical communication in English", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "How do you say 'tension artérielle' in English?",
        options: [{ text: "Cardiac output", isCorrect: false },{ text: "Blood pressure (BP)", isCorrect: true },{ text: "Heart rate", isCorrect: false },{ text: "Pulse pressure", isCorrect: false }],
        explanation: "Blood pressure (BP) = pression artérielle. Systolic BP = pression systolique. Diastolic BP = pression diastolique. Normal BP: below 140/90 mmHg." },
      { text: "A patient says 'I feel nauseous and my head is spinning'. This describes:",
        options: [{ text: "Chest pain and shortness of breath", isCorrect: false },{ text: "Nausea and dizziness", isCorrect: true },{ text: "Fatigue and muscle weakness", isCorrect: false },{ text: "Abdominal pain and bloating", isCorrect: false }],
        explanation: "Nauseous = nauséeux (nausea). Head is spinning = vertiges (dizziness). Ces symptômes sont fréquents après une chirurgie (NVPO = Post-Operative Nausea and Vomiting)." },
      { text: "What does 'NPO' (Nil Per Os) mean in clinical settings?",
        options: [{ text: "The patient needs oral medications only", isCorrect: false },{ text: "The patient must have nothing by mouth (fasting)", isCorrect: true },{ text: "The patient is on a normal diet", isCorrect: false },{ text: "The patient needs nutritional supplements", isCorrect: false }],
        explanation: "NPO (Nil Per Os = rien par la bouche) : le patient doit rester à jeun. Indiqué avant une chirurgie, une anesthésie ou en cas de troubles de la déglutition. Équivalent français : 'à jeun'." },
      { text: "Which phrase correctly describes the nursing role in English?",
        options: [{ text: "The nurse prescribes medications and performs surgery", isCorrect: false },{ text: "The nurse assesses patients, provides care, educates and advocates for patients", isCorrect: true },{ text: "The nurse only follows doctor's orders without any autonomous practice", isCorrect: false },{ text: "The nurse diagnoses diseases and orders laboratory tests", isCorrect: false }],
        explanation: "Le rôle infirmier en anglais : assess (évaluer), provide care (prodiger des soins), educate (éduquer), advocate (défendre les intérêts du patient), collaborate (collaborer). L'IDE a un rôle propre ET délégué." },
      { text: "A patient is described as 'SOB'. What does this abbreviation mean?",
        options: [{ text: "Signs Of Bleeding", isCorrect: false },{ text: "Shortness Of Breath (dyspnée)", isCorrect: true },{ text: "Swelling Of the Back", isCorrect: false },{ text: "Status Of Blood (bilan sanguin)", isCorrect: false }],
        explanation: "SOB = Shortness Of Breath = dyspnée. Autres abréviations respiratoires : RR (respiratory rate), FiO₂ (fraction of inspired oxygen), CPAP (Continuous Positive Airway Pressure = VNI en CPAP)." },
      { text: "How do you document a patient's pain level in English?",
        options: [{ text: "The patient scores pain at 7 out of 10 on the numerical rating scale", isCorrect: true },{ text: "The patient pain is very high", isCorrect: false },{ text: "The patient complains about pain level", isCorrect: false },{ text: "The patient feels pain during nursing care", isCorrect: false }],
        explanation: "Documentation infirmière en anglais : 'Patient rates pain at X/10 on the NRS (Numerical Rating Scale).' Puis les actions et résultats (SOAPIE ou DAR format en anglais : Data, Action, Response)." },
      { text: "In English medical abbreviation, 'PRN' means:",
        options: [{ text: "Please Refer Now (référer immédiatement)", isCorrect: false },{ text: "Pro Re Nata — as needed (à la demande)", isCorrect: true },{ text: "Primary Renal Nephropathy", isCorrect: false },{ text: "Patient Risk Notification", isCorrect: false }],
        explanation: "PRN (Pro Re Nata) = à la demande, selon les besoins du patient. Ex : 'Paracetamol 1g PRN for pain, max 4g/24h'. Equivalent français : 'si besoin'." },
      { text: "What should a nurse say when calling a doctor about a deteriorating patient (SBAR)?",
        options: [{ text: "'The patient is bad, please come quickly'", isCorrect: false },{ text: "'This is nurse X calling about patient Y in room Z. The situation is... Background... I assess... I recommend...'", isCorrect: true },{ text: "'Doctor, something is wrong with your patient'", isCorrect: false },{ text: "'Please check the patient when you have time'", isCorrect: false }],
        explanation: "SBAR en anglais : Situation ('I'm calling about Mr. X in room Y...'), Background ('He was admitted for...'), Assessment ('I'm concerned because...'), Recommendation ('I'd like you to...'). Structuré et professionnel." },
      { text: "What is the English term for 'escarre' (pressure ulcer)?",
        options: [{ text: "Wound infection", isCorrect: false },{ text: "Pressure ulcer / pressure injury / bedsore", isCorrect: true },{ text: "Surgical wound", isCorrect: false },{ text: "Skin rash", isCorrect: false }],
        explanation: "Escarre = pressure ulcer (US) ou pressure injury (NPUAP 2016) ou decubitus ulcer ou bedsore. Les stades sont I à IV en anglais. Stage I: non-blanchable erythema. Stage IV: full thickness tissue loss." },
      { text: "How do you ask a patient about their allergy history in English?",
        options: [{ text: "'Are you sick?'", isCorrect: false },{ text: "'Do you have any known allergies to medications, food or latex?'", isCorrect: true },{ text: "'What medicines do you take?'", isCorrect: false },{ text: "'Have you ever been in hospital?'", isCorrect: false }],
        explanation: "Anamnèse allergique : 'Do you have any known allergies?' Si oui : 'What happens when you take/eat...?' (quelle réaction ?) Pour distinguer allergie vraie (réaction IgE-médiée) d'intolérance ou effet secondaire." }
    ]
  },
  {
    title: "Medical English in clinical practice — drugs, emergencies and research",
    description: "Médicaments, urgences et littérature médicale en anglais",
    semester: "Semestre 1", category: "UE 6.2 - Anglais",
    chapter: "Clinical situations and abbreviations", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "What does 'stat' mean in clinical English?",
        options: [{ text: "Slowly and carefully", isCorrect: false },{ text: "Immediately / at once (from Latin 'statim')", isCorrect: true },{ text: "As a routine task", isCorrect: false },{ text: "Once a day", isCorrect: false }],
        explanation: "'STAT' (statim en latin) = immédiatement, en urgence. Ex : 'Give 1mg Atropine IV STAT'. On le retrouve aussi dans 'stat lab' = analyse biologique en urgence." },
      { text: "A patient with 'DOE' has:",
        options: [{ text: "Difficulty Of Eating", isCorrect: false },{ text: "Dyspnea On Exertion (dyspnée d'effort)", isCorrect: true },{ text: "Disorder Of Excretion", isCorrect: false },{ text: "Duration Of Effect", isCorrect: false }],
        explanation: "DOE = Dyspnea On Exertion = dyspnée d'effort. Classiquement observée dans l'insuffisance cardiaque (stade II NYHA), la BPCO, l'anémie. À distinguer du SOB (dyspnée de repos)." },
      { text: "In a research article, what does 'RCT' stand for?",
        options: [{ text: "Routine Clinical Test", isCorrect: false },{ text: "Randomized Controlled Trial (essai randomisé contrôlé)", isCorrect: true },{ text: "Rapid Care Technique", isCorrect: false },{ text: "Renal Clearance Time", isCorrect: false }],
        explanation: "RCT (Randomized Controlled Trial) = essai clinique randomisé contrôlé : le niveau de preuve le plus élevé après les méta-analyses. Les participants sont assignés aléatoirement au groupe traitement ou placebo/contrôle." },
      { text: "What is a 'placebo' in clinical trials?",
        options: [{ text: "A very powerful experimental drug", isCorrect: false },{ text: "An inactive substance given to the control group to compare with the real treatment", isCorrect: true },{ text: "A preliminary dose before the real treatment", isCorrect: false },{ text: "A combination of two drugs given simultaneously", isCorrect: false }],
        explanation: "Placebo = substance inerte (comprimé de sucre, sérum physiologique) donnée au groupe contrôle dans un essai clinique. L'effet placebo est la réponse positive liée aux attentes du patient, indépendamment du traitement." },
      { text: "What does 'QID' mean in a prescription?",
        options: [{ text: "Once daily", isCorrect: false },{ text: "Four times daily (quater in die)", isCorrect: true },{ text: "Every other day", isCorrect: false },{ text: "Twice daily", isCorrect: false }],
        explanation: "Abréviations de fréquence : OD/QD = once daily (1×/j), BID = twice daily (2×/j), TID = three times daily (3×/j), QID = four times daily (4×/j), QHS = every bedtime, PRN = as needed." },
      { text: "In English, 'informed consent' refers to:",
        options: [{ text: "The doctor's consent to perform a procedure", isCorrect: false },{ text: "A patient's agreement to treatment after receiving clear and complete information", isCorrect: true },{ text: "The nursing staff's agreement with the treatment plan", isCorrect: false },{ text: "A legal document signed only in emergency situations", isCorrect: false }],
        explanation: "Informed consent (consentement éclairé) : le patient reçoit une information loyale, claire et adaptée sur les bénéfices, risques et alternatives, PUIS consent librement. Il peut le révoquer à tout moment." },
      { text: "What is 'septic shock' in English?",
        options: [{ text: "A psychological state of fear following infection", isCorrect: false },{ text: "Life-threatening organ dysfunction caused by an uncontrolled host response to infection requiring vasopressors", isCorrect: true },{ text: "A mild allergic reaction to antibiotics", isCorrect: false },{ text: "Surgical shock following infection of an operative wound", isCorrect: false }],
        explanation: "Septic shock (Sepsis-3 définition 2016) : sepsis + hypotension nécessitant des vasopresseurs pour maintenir MAP ≥ 65 mmHg + lactate > 2 mmol/L malgré le remplissage. Mortalité 40–50%." },
      { text: "In a clinical note, 'CC:' stands for:",
        options: [{ text: "Critical Condition", isCorrect: false },{ text: "Chief Complaint (motif de consultation)", isCorrect: true },{ text: "Complete Care", isCorrect: false },{ text: "Cardiac Catheterization", isCorrect: false }],
        explanation: "CC = Chief Complaint = motif principal de consultation exprimé par le patient lui-même. Ex : 'CC: chest pain for 2 hours'. La structure SOAP (Subjective, Objective, Assessment, Plan) organise la note clinique." },
      { text: "What does 'NPE' or 'TPN' mean in nutritional support?",
        options: [{ text: "Normal Protein Evaluation", isCorrect: false },{ text: "Total Parenteral Nutrition (nutrition parentérale totale)", isCorrect: true },{ text: "Nasal Probe Enteral feeding", isCorrect: false },{ text: "Tube Placed Nasally", isCorrect: false }],
        explanation: "TPN = Total Parenteral Nutrition = nutrition parentérale totale (administrée par voie veineuse centrale). EN = Enteral Nutrition (sonde naso-gastrique ou jéjunostomie). TPN est réservée si le tube digestif est non fonctionnel." },
      { text: "A patient is described as 'A&O x3'. This means they are:",
        options: [{ text: "Allergic to 3 medications", isCorrect: false },{ text: "Alert and oriented to person, place and time", isCorrect: true },{ text: "Answering 3 questions correctly", isCorrect: false },{ text: "Able to perform 3 activities of daily living", isCorrect: false }],
        explanation: "A&O x3 = Alert and Oriented to person (who they are), place (where they are) and time (the date/year). A&O x4 includes 'situation' (understanding of their condition). Très utilisé en évaluation neurologique." }
    ]
  },
];
