// ─── PARTIE 3 : UE 2.10 · UE 2.11 ──────────────────────────────────────────
module.exports = [

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 2.10 – Infectiologie, hygiène (4 quiz)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Agents infectieux et pathogénicité",
    description: "Classification des agents infectieux et mécanismes d'infection",
    semester: "Semestre 1", category: "UE 2.10 - Infectiologie, hygiène",
    chapter: "Microbiologie clinique", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Quelle est la principale différence entre infection et colonisation ?",
        options: [{ text: "La colonisation entraîne des signes cliniques, l'infection non", isCorrect: false },{ text: "L'infection entraîne une réponse inflammatoire et des signes cliniques ; la colonisation non", isCorrect: true },{ text: "La colonisation est toujours pathologique", isCorrect: false },{ text: "L'infection concerne les virus, la colonisation les bactéries", isCorrect: false }],
        explanation: "La colonisation est la présence de micro-organismes sur/dans l'organisme sans réaction de l'hôte ni signes cliniques. L'infection implique une multiplication microbienne avec réponse inflammatoire de l'hôte et symptômes." },
      { text: "Le SARS-CoV-2 est un virus à :",
        options: [{ text: "ADN double brin enveloppé", isCorrect: false },{ text: "ARN simple brin positif enveloppé (coronavirus)", isCorrect: true },{ text: "ARN double brin non enveloppé", isCorrect: false },{ text: "ADN simple brin non enveloppé", isCorrect: false }],
        explanation: "Le SARS-CoV-2 est un coronavirus à ARN simple brin de polarité positive, enveloppé, dont la protéine Spike (S) lui permet de se fixer aux récepteurs ACE2 des cellules pulmonaires humaines." },
      { text: "Le VIH (virus de l'immunodéficience humaine) cible principalement :",
        options: [{ text: "Les lymphocytes B", isCorrect: false },{ text: "Les lymphocytes T CD4+ (auxiliaires)", isCorrect: true },{ text: "Les polynucléaires neutrophiles", isCorrect: false },{ text: "Les macrophages uniquement", isCorrect: false }],
        explanation: "Le VIH infecte préférentiellement les lymphocytes T CD4+ (et les macrophages) grâce à son enveloppe glycoprotéique (gp120) qui se lie aux récepteurs CD4. La destruction progressive des CD4 entraîne l'immunodépression caractéristique du SIDA." },
      { text: "L'incubation d'une maladie infectieuse est :",
        options: [{ text: "La période de contagiosité maximale", isCorrect: false },{ text: "La période entre la contamination et l'apparition des premiers symptômes", isCorrect: true },{ text: "La durée totale de la maladie", isCorrect: false },{ text: "La phase de guérison après traitement", isCorrect: false }],
        explanation: "La période d'incubation est le délai entre la pénétration du micro-organisme et l'apparition des premiers signes cliniques. Elle varie selon l'agent pathogène (ex : COVID-19 : 2-14j ; rougeole : 10-12j ; VIH : 2-4 semaines pour la primo-infection)." },
      { text: "La septicémie (sepsis) est définie comme :",
        options: [{ text: "Une infection localisée à un organe", isCorrect: false },{ text: "Une réponse systémique dérégulée de l'hôte à une infection, menaçant les organes vitaux", isCorrect: true },{ text: "La présence de bactéries dans le sang sans symptômes", isCorrect: false },{ text: "Une intoxination par des toxines bactériennes uniquement", isCorrect: false }],
        explanation: "Le sepsis est défini (Sepsis-3, 2016) comme une dysfonction organique potentiellement mortelle causée par une réponse dérégulée de l'hôte à l'infection. Le score SOFA permet d'identifier les dysfonctions d'organe." },
      { text: "Qu'est-ce qu'une hémoculture ?",
        options: [{ text: "Un bilan sanguin complet", isCorrect: false },{ text: "Une mise en culture du sang pour détecter et identifier des micro-organismes", isCorrect: true },{ text: "Un dosage des anticorps sanguins", isCorrect: false },{ text: "Un examen microscopique d'un frottis sanguin", isCorrect: false }],
        explanation: "L'hémoculture consiste à prélever du sang en conditions stériles et à l'ensemencer dans des flacons de culture (aérobie et anaérobie). Elle permet d'identifier la bactériémie ou la fongémie et de guider l'antibiothérapie." },
      { text: "Les bactéries sporulées (comme Clostridium difficile) sont difficiles à éliminer car :",
        options: [{ text: "Elles résistent à tous les antibiotiques", isCorrect: false },{ text: "Leurs spores résistent à la chaleur, aux désinfectants alcooliques et à de nombreux agents chimiques", isCorrect: true },{ text: "Elles se multiplient uniquement dans les tissus profonds", isCorrect: false },{ text: "Elles sont invisibles au microscope", isCorrect: false }],
        explanation: "Les spores bactériennes (Clostridium difficile, Bacillus anthracis) sont des formes de résistance extrêmement solides, résistant à l'alcool, à la chaleur (< 121°C) et à de nombreux désinfectants. Seule la solution d'hypochlorite (eau de Javel) est efficace contre C. difficile." },
      { text: "La méningite à méningocoque est une urgence car elle peut entraîner :",
        options: [{ text: "Une simple otite compliquée", isCorrect: false },{ text: "Un purpura fulminans et un choc septique potentiellement mortel en quelques heures", isCorrect: true },{ text: "Une pneumonie grave", isCorrect: false },{ text: "Une encéphalite chronique", isCorrect: false }],
        explanation: "La méningite bactérienne à méningocoque peut se compliquer d'un purpura fulminans (lésions hémorragiques cutanées, choc septique, CIVD, défaillance multiviscérale) pouvant tuer en quelques heures. Elle impose l'antibiothérapie intraveineuse IMMÉDIATE." },
      { text: "La transmission féco-orale concerne principalement :",
        options: [{ text: "La tuberculose et la rougeole", isCorrect: false },{ text: "Les infections entériques (hépatite A, gastro-entérites à rotavirus, typhoïde)", isCorrect: true },{ text: "Le VIH et l'hépatite C", isCorrect: false },{ text: "La grippe et le COVID-19", isCorrect: false }],
        explanation: "La voie féco-orale transmet les agents pathogènes digestifs : hépatite A, poliovirus, rotavirus, Salmonella, E. coli entéropathogène, Vibrio cholerae. La prévention passe par l'hygiène des mains, l'eau potable et la cuisson des aliments." },
      { text: "Qu'est-ce que la zoonose ?",
        options: [{ text: "Une infection exclusive aux animaux sauvages", isCorrect: false },{ text: "Une maladie infectieuse transmissible naturellement entre les animaux vertébrés et l'homme", isCorrect: true },{ text: "Une infection causée par des parasites uniquement", isCorrect: false },{ text: "Une maladie infectieuse sans agent pathogène identifié", isCorrect: false }],
        explanation: "Une zoonose est une maladie infectieuse transmissible entre animaux et êtres humains. Exemples : rage (morsure), brucellose (animaux d'élevage), leptospirose (rats), grippe aviaire (volailles), lyme (tiques), COVID-19 (chauve-souris probablement)." }
    ]
  },
  {
    title: "Infections associées aux soins (IAS)",
    description: "Prévention et gestion des infections nosocomiales",
    semester: "Semestre 1", category: "UE 2.10 - Infectiologie, hygiène",
    chapter: "Infections nosocomiales", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "Une infection nosocomiale (IAS) est définie comme :",
        options: [{ text: "Toute infection contractée dans un établissement de santé", isCorrect: false },{ text: "Une infection acquise lors d'une prise en charge dans un établissement de santé, absente à l'admission (délai > 48h)", isCorrect: true },{ text: "Une infection causée par une bactérie multirésistante uniquement", isCorrect: false },{ text: "Une infection survenant uniquement en réanimation", isCorrect: false }],
        explanation: "Une IAS (infection associée aux soins) est une infection survenant au cours ou après une prise en charge diagnostique, thérapeutique ou préventive. Pour être nosocomiale, elle doit être absente à l'admission et apparaître après 48h (ou après la durée d'incubation si connue)." },
      { text: "Le taux d'IAS en France représente environ :",
        options: [{ text: "0,1% des hospitalisations", isCorrect: false },{ text: "5% des hospitalisations (environ 800 000/an)", isCorrect: true },{ text: "20% des hospitalisations", isCorrect: false },{ text: "0,5% des hospitalisations", isCorrect: false }],
        explanation: "En France, environ 5% des patients hospitalisés contractent une IAS (≈ 800 000 infections/an), dont 4 500 décès directement attribuables. Les services les plus touchés : réanimation (15-20%), chirurgie, médecine interne." },
      { text: "Les bactéries multirésistantes (BMR) fréquemment rencontrées à l'hôpital sont :",
        options: [{ text: "Streptococcus pyogenes et Candida albicans", isCorrect: false },{ text: "SARM, entérocoques résistants à la vancomycine (ERV), entérobactéries BLSE", isCorrect: true },{ text: "E. coli sensible et Streptococcus pneumoniae", isCorrect: false },{ text: "Clostridium botulinum et Listeria monocytogenes", isCorrect: false }],
        explanation: "Les principales BMR en milieu hospitalier : SARM (Staphylococcus aureus résistant à la méticilline), ERV (entérocoques résistants à la vancomycine), entérobactéries BLSE (bêta-lactamases à spectre élargi), Pseudomonas aeruginosa multirésistant, Acinetobacter baumannii." },
      { text: "Les précautions complémentaires de type 'contact' impliquent :",
        options: [{ text: "Le port d'un masque chirurgical obligatoire en permanence", isCorrect: false },{ text: "Le port de gants et surblouse pour tout contact avec le patient ou son environnement", isCorrect: true },{ text: "L'isolement en chambre à pression négative", isCorrect: false },{ text: "Le port de lunettes de protection systématique", isCorrect: false }],
        explanation: "Les précautions contact (pour BMR, C. difficile, gale…) : chambre seule si possible, port de gants et surblouse dès l'entrée dans la chambre, hygiène des mains à la sortie, matériel dédié au patient, limitation des transports." },
      { text: "Les précautions 'air' (isolement respiratoire haute protection) sont indiquées pour :",
        options: [{ text: "La grippe saisonnière uniquement", isCorrect: false },{ text: "La tuberculose pulmonaire, la varicelle, la rougeole", isCorrect: true },{ text: "Les gastro-entérites virales", isCorrect: false },{ text: "Les infections cutanées à SARM", isCorrect: false }],
        explanation: "Les précautions 'air' sont requises pour les agents transmissibles par des noyaux de gouttelettes (particules < 5 µm restant en suspension) : tuberculose, rougeole, varicelle, zona disséminé. Elles nécessitent une chambre à pression négative et un masque FFP2." },
      { text: "La pneumonie acquise sous ventilation mécanique (PAVM) est prévenue par :",
        options: [{ text: "L'administration prophylactique systématique d'antibiotiques", isCorrect: false },{ text: "L'élévation de la tête du lit (30-45°), l'hygiène buccale et la surveillance du ballonnet", isCorrect: true },{ text: "Le remplacement quotidien du circuit du ventilateur", isCorrect: false },{ text: "La mise sous oxygène à débit élevé systématiquement", isCorrect: false }],
        explanation: "La prévention des PAVM repose sur : élévation de la tête du lit (30-45° si possible), hygiène buccale pluriquotidienne à la chlorhexidine, vérification de la pression du ballonnet, aspiration sous-glottique, sevrage précoce du ventilateur." },
      { text: "L'infection urinaire sur sonde vésicale est réduite par :",
        options: [{ text: "Le changement de sonde toutes les 24h", isCorrect: false },{ text: "La pose en conditions d'asepsie stricte et le maintien d'un système clos", isCorrect: true },{ text: "L'irrigation vésicale prophylactique aux antiseptiques", isCorrect: false },{ text: "Le clampage régulier de la sonde", isCorrect: false }],
        explanation: "La prévention des IUCS : indication justifiée au sondage, pose en asepsie stricte, maintien d'un système de drainage clos, positionnement de la poche en déclive (jamais au sol), hygiène méatale, ablation dès que possible." },
      { text: "L'EOB (Examen de Dépistage des Bactéries Résistantes) est prescrit pour :",
        options: [{ text: "Tout patient hospitalisé systématiquement", isCorrect: false },{ text: "Les patients à risque de portage de BMR/BHRe (antécédent d'hospitalisation à l'étranger, secteur à risque)", isCorrect: true },{ text: "Uniquement les patients en réanimation", isCorrect: false },{ text: "Les personnels soignants lors de leur embauche", isCorrect: false }],
        explanation: "L'EOB (prélèvement rectal ± nasal) dépiste le portage de BMR et BHRe (bactéries hautement résistantes émergentes) chez les patients à risque : hospitalisés à l'étranger dans les 12 mois, patients de réanimation, transferts entre établissements." },
      { text: "La surveillance épidémiologique des IAS en France est assurée par :",
        options: [{ text: "La Haute Autorité de Santé (HAS)", isCorrect: false },{ text: "Santé Publique France et les réseaux de surveillance (RAISIN)", isCorrect: true },{ text: "L'Ordre National des Infirmiers", isCorrect: false },{ text: "Les caisses d'Assurance Maladie", isCorrect: false }],
        explanation: "La surveillance des IAS est coordonnée par Santé Publique France, via le RAISIN (Réseau d'Alerte, d'Investigation et de Surveillance des Infections Nosocomiales) et les CPIAS (Centres d'Appui pour la Prévention des IAS) dans chaque région." },
      { text: "L'indicateur IQSS 'ICSHA' mesure :",
        options: [{ text: "Le taux d'infections nosocomiales de l'établissement", isCorrect: false },{ text: "La consommation de produits hydro-alcooliques rapportée au nombre de journées d'hospitalisation", isCorrect: true },{ text: "La satisfaction des patients concernant l'hygiène", isCorrect: false },{ text: "Le taux de recours aux précautions complémentaires", isCorrect: false }],
        explanation: "L'ICSHA (Indicateur de Consommation de Solutions Hydro-Alcooliques) est un indicateur qualité qui mesure la consommation de SHA par 1000 journées d'hospitalisation. Il est utilisé comme proxy de la conformité à l'hygiène des mains." }
    ]
  },
  {
    title: "Hygiène des mains et précautions standard",
    description: "Techniques d'hygiène des mains et précautions universelles en soins",
    semester: "Semestre 1", category: "UE 2.10 - Infectiologie, hygiène",
    chapter: "Hygiène hospitalière", difficulty: "easy", duration: 15, isPublished: true,
    questions: [
      { text: "La friction hydro-alcoolique (SHA) est recommandée en priorité sur le lavage au savon car :",
        options: [{ text: "Elle est moins efficace mais plus pratique", isCorrect: false },{ text: "Elle est plus rapide, plus efficace sur la flore transitoire et moins agressante pour la peau", isCorrect: true },{ text: "Elle élimine également les spores bactériennes", isCorrect: false },{ text: "Elle ne nécessite pas de séchage", isCorrect: false }],
        explanation: "La SHA est la méthode de référence pour l'hygiène des mains en soins (OMS, SFHH) : plus rapide (20-30 secondes), très efficace sur bactéries et virus enveloppés, moins agressive que le lavage répété. Exception : souillure visible, spores (C. difficile) → lavage savon obligatoire." },
      { text: "Les 5 indications de l'hygiène des mains selon l'OMS (My 5 moments) incluent :",
        options: [{ text: "Avant et après chaque soin uniquement", isCorrect: false },{ text: "Avant contact patient, avant geste aseptique, après exposition au liquide biologique, après contact patient, après contact environnement", isCorrect: true },{ text: "Uniquement avant la pose d'un cathéter", isCorrect: false },{ text: "Seulement lors de précautions complémentaires", isCorrect: false }],
        explanation: "Les 5 moments OMS : 1) Avant de toucher un patient ; 2) Avant un geste aseptique ; 3) Après risque d'exposition aux liquides biologiques ; 4) Après avoir touché un patient ; 5) Après contact avec l'environnement du patient." },
      { text: "La durée de la friction hydro-alcoolique doit être de :",
        options: [{ text: "5 secondes", isCorrect: false },{ text: "20 à 30 secondes (jusqu'à séchage complet)", isCorrect: true },{ text: "2 minutes", isCorrect: false },{ text: "45 secondes minimum", isCorrect: false }],
        explanation: "La friction hydro-alcoolique dure 20 à 30 secondes, jusqu'à séchage complet des mains. Elle couvre : paumes, dos des mains, espaces interdigitaux, pouces, extrémités des doigts et poignets. Elle doit être effectuée sur des mains propres, sèches et sans bijoux." },
      { text: "Les précautions standard s'appliquent :",
        options: [{ text: "Uniquement aux patients porteurs de maladies infectieuses connues", isCorrect: false },{ text: "À tous les patients, quel que soit leur statut infectieux, pour tout contact avec sang et liquides biologiques", isCorrect: true },{ text: "Uniquement en réanimation et chirurgie", isCorrect: false },{ text: "Seulement lors de soins invasifs", isCorrect: false }],
        explanation: "Les précautions standard (anciennement précautions universelles) s'appliquent à TOUS les patients, quel que soit leur statut sérologique connu ou non. Elles protègent contre tout risque de transmission par le sang et les liquides biologiques." },
      { text: "En cas d'AES (accident d'exposition au sang), la première action est :",
        options: [{ text: "Appeler immédiatement le SAMU", isCorrect: false },{ text: "Nettoyer immédiatement la plaie à l'eau et au savon, puis antisepsie à la Bétadine ou alcool 70°", isCorrect: true },{ text: "Prendre une prophylaxie antirétrovirale immédiatement", isCorrect: false },{ text: "Déclarer l'accident à la direction avant tout soin", isCorrect: false }],
        explanation: "En cas d'AES : 1) Nettoyer immédiatement (eau + savon, 5 min) puis antisepsie (Bétadine 5% ou alcool 70°, 5 min) ; 2) Déclarer en accident du travail dans les 24h ; 3) Consulter le médecin référent pour évaluation VIH/VHC/VHB et éventuelle prophylaxie < 4h." },
      { text: "Le port de gants non stériles est indiqué pour :",
        options: [{ text: "Tout contact avec un patient, même sans risque de liquide biologique", isCorrect: false },{ text: "Les soins exposant au sang, liquides biologiques, muqueuses ou peau non intacte", isCorrect: true },{ text: "Uniquement les soins de nursing basique", isCorrect: false },{ text: "Remplacer l'hygiène des mains", isCorrect: false }],
        explanation: "Les gants non stériles sont indiqués lors des soins exposant aux liquides biologiques, muqueuses, peau lésée, et lors des précautions complémentaires contact. Ils ne remplacent PAS l'hygiène des mains (friction avant et après le port de gants)." },
      { text: "Le masque chirurgical protège principalement :",
        options: [{ text: "Le porteur contre les agents infectieux aéroportés", isCorrect: false },{ text: "L'environnement et le patient contre les projections du porteur (gouttelettes)", isCorrect: true },{ text: "Contre les virus à transmission aérienne (particules < 5 µm)", isCorrect: false },{ text: "Uniquement contre les gaz anesthésiques", isCorrect: false }],
        explanation: "Le masque chirurgical (type IIR) protège principalement l'environnement du porteur en filtrant ses projections de gouttelettes. Pour se protéger contre les agents à transmission aérienne (tuberculose, rougeole, varicelle), un masque FFP2 est nécessaire." },
      { text: "La tenue professionnelle en milieu hospitalier doit :",
        options: [{ text: "Comprendre des bijoux pour l'identification du soignant", isCorrect: false },{ text: "Être propre, à manches courtes, sans bijoux aux mains, ongles courts et non vernis", isCorrect: true },{ text: "Être changée uniquement en cas de souillure visible", isCorrect: false },{ text: "Inclure une blouse blanche longue à manches longues", isCorrect: false }],
        explanation: "La tenue professionnelle hospitalière : manches courtes (pour permettre l'hygiène des mains jusqu'aux coudes), pas de bijoux aux mains (microorganismes), ongles courts et sans vernis, cheveux attachés. Elle est lavée à l'hôpital à 60°C minimum." },
      { text: "Le tri et l'élimination des déchets d'activité de soins à risque infectieux (DASRI) impose :",
        options: [{ text: "De les mélanger aux ordures ménagères classiques", isCorrect: false },{ text: "Un conditionnement immédiat dans les conteneurs adaptés (boîtes DASRI jaunes) dès le lieu de production", isCorrect: true },{ text: "Un stockage de 72h maximum avant élimination", isCorrect: false },{ text: "Une désinfection chimique préalable dans le service", isCorrect: false }],
        explanation: "Les DASRI (aiguilles, compresses souillées, poches de sang…) doivent être triés et conditionnés dans des conteneurs réglementaires (rigides pour piquants/coupants, souples pour mous) dès le lieu de production, puis incinérés." },
      { text: "La décontamination des surfaces dans une chambre de patient porteur de C. difficile nécessite :",
        options: [{ text: "Un désinfectant alcoolique standard", isCorrect: false },{ text: "Une solution d'hypochlorite de sodium (eau de Javel) diluée à 0,5% minimum", isCorrect: true },{ text: "Un savon bactéricide uniquement", isCorrect: false },{ text: "Une aération de 30 minutes suffit", isCorrect: false }],
        explanation: "Clostridium difficile produit des spores résistant aux désinfectants alcooliques et à de nombreux biocides. Seule l'eau de Javel (hypochlorite de sodium, ≥ 0,5% de chlore actif) détruit efficacement les spores. L'hygiène des mains au savon est indispensable (non à la SHA)." }
    ]
  },
  {
    title: "Stérilisation et désinfection",
    description: "Niveaux et méthodes de décontamination du matériel médical",
    semester: "Semestre 1", category: "UE 2.10 - Infectiologie, hygiène",
    chapter: "Stérilisation", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "La classification de Spaulding classe le matériel médical en :",
        options: [{ text: "Propre / Sale / Stérile", isCorrect: false },{ text: "Critique / Semi-critique / Non critique", isCorrect: true },{ text: "Usage unique / Réutilisable / Mixte", isCorrect: false },{ text: "Métal / Plastique / Textile", isCorrect: false }],
        explanation: "La classification de Spaulding (1968) classe le matériel selon le risque infectieux : critique (contact avec tissu stérile ou sang → stérilisation obligatoire), semi-critique (contact muqueuse → désinfection haute), non critique (contact peau saine → désinfection basse)." },
      { text: "La stérilisation à la vapeur d'eau (autoclave) nécessite :",
        options: [{ text: "134°C pendant 3 minutes à 3 bars de pression", isCorrect: true },{ text: "100°C pendant 30 minutes", isCorrect: false },{ text: "121°C pendant 1 minute", isCorrect: false },{ text: "150°C pendant 10 secondes", isCorrect: false }],
        explanation: "La stérilisation vapeur (autoclave) est le standard : 134°C, 3 bars, 3 minutes (cycle court pour matériel non emballé) ou 134°C, 3 bars, 18 minutes (cycle long). Elle détruit TOUS les micro-organismes y compris les spores." },
      { text: "La désinfection de haut niveau (DHN) est utilisée pour :",
        options: [{ text: "Les scalpels et instruments chirurgicaux", isCorrect: false },{ text: "Le matériel semi-critique comme les endoscopes (gastroscopes, bronchoscopes)", isCorrect: true },{ text: "Les sols et surfaces hospitalières", isCorrect: false },{ text: "Les linges et textiles médicaux", isCorrect: false }],
        explanation: "La DHN (glutaraldéhyde, acide peracétique, peroxyde d'hydrogène) détruit tous les micro-organismes sauf les spores à forte concentration. Elle est utilisée pour les endoscopes et instruments thermosensibles ne pouvant pas être stérilisés à l'autoclave." },
      { text: "Le prétraitement (décontamination) du matériel médical souillé vise à :",
        options: [{ text: "Stériliser le matériel avant nettoyage", isCorrect: false },{ text: "Diminuer la charge microbienne initiale pour sécuriser le transport et le nettoyage ultérieur", isCorrect: true },{ text: "Remplacer le nettoyage manuel", isCorrect: false },{ text: "Éliminer définitivement les spores", isCorrect: false }],
        explanation: "Le prétraitement (immersion dans une solution détergente-désinfectante juste après usage) réduit la charge microbienne, empêche le séchage des souillures biologiques et sécurise le transport vers la stérilisation centrale (CSSD). Il précède obligatoirement le nettoyage." },
      { text: "Qu'est-ce que la péremption d'un dispositif médical stérile ?",
        options: [{ text: "La date de fabrication du dispositif", isCorrect: false },{ text: "La date limite jusqu'à laquelle la stérilité du dispositif est garantie si l'emballage est intact", isCorrect: true },{ text: "La date de première utilisation autorisée", isCorrect: false },{ text: "Le délai de stérilisation recommandé", isCorrect: false }],
        explanation: "La date de péremption d'un DM stérile indique la limite de validité de la stérilité, sous réserve d'un emballage intact et d'un stockage approprié. Un dispositif périmé ou à emballage endommagé ne doit PAS être utilisé." },
      { text: "Les antiseptiques locaux (Bétadine, Dakin, chlorhexidine) servent à :",
        options: [{ text: "Stériliser le matériel médical réutilisable", isCorrect: false },{ text: "Réduire la charge microbienne sur la peau ou les muqueuses vivantes", isCorrect: true },{ text: "Désinfecter les surfaces inanimées", isCorrect: false },{ text: "Traiter les infections systémiques profondes", isCorrect: false }],
        explanation: "Les antiseptiques sont utilisés sur les tissus vivants (peau, muqueuses, plaies) pour réduire la colonisation microbienne et prévenir les infections. Ils ne sont pas utilisés sur les surfaces inertes (qui nécessitent des désinfectants)." },
      { text: "Le processus de nettoyage-désinfection-stérilisation suit impérativement l'ordre :",
        options: [{ text: "Stérilisation → Nettoyage → Désinfection", isCorrect: false },{ text: "Nettoyage → Rincage → Désinfection/Stérilisation", isCorrect: true },{ text: "Désinfection → Nettoyage → Stérilisation", isCorrect: false },{ text: "Nettoyage → Stérilisation → Désinfection", isCorrect: false }],
        explanation: "L'ordre est impératif : 1) Prétraitement (décontamination) ; 2) Nettoyage (élimination des souillures organiques) ; 3) Rinçage ; 4) Séchage ; 5) Désinfection ou stérilisation. Sans nettoyage préalable, les souillures protègent les micro-organismes et rendent la stérilisation inefficace." },
      { text: "L'indicateur chimique de stérilisation (bandelette) sert à :",
        options: [{ text: "Garantir la stérilité du contenu d'un emballage", isCorrect: false },{ text: "Prouver que le matériel a bien traversé un cycle de stérilisation (indicateur de passage)", isCorrect: true },{ text: "Mesurer la température exacte atteinte dans l'autoclave", isCorrect: false },{ text: "Identifier la date de péremption du dispositif", isCorrect: false }],
        explanation: "L'indicateur chimique de passage (bandelette colorimétrique) change de couleur au contact de la vapeur chaude : il prouve que l'emballage a traversé un cycle, mais ne garantit pas la stérilité réelle (seuls les indicateurs biologiques la confirment)." },
      { text: "Quel est l'agent de stérilisation de choix pour les dispositifs thermosensibles ?",
        options: [{ text: "La vapeur d'eau à 134°C (autoclave)", isCorrect: false },{ text: "L'oxyde d'éthylène (ETO) ou le peroxyde d'hydrogène plasma (VH2O2)", isCorrect: true },{ text: "L'eau de Javel à haute concentration", isCorrect: false },{ text: "La chaleur sèche (poupinel) à 180°C", isCorrect: false }],
        explanation: "Pour les dispositifs thermosensibles (câbles optiques, endoscopes non autoclavables, matériels électroniques) : oxyde d'éthylène (ETO, gaz toxique mais basse température) ou plasma de peroxyde d'hydrogène (Sterrad®). Ce dernier est plus récent, plus rapide et sans résidu toxique." },
      { text: "Le bon conditionnement d'un dispositif médical avant stérilisation garantit :",
        options: [{ text: "Uniquement la traçabilité du matériel", isCorrect: false },{ text: "Le maintien de la stérilité jusqu'à l'ouverture en conditions aseptiques", isCorrect: true },{ text: "La durée de la stérilisation", isCorrect: false },{ text: "L'identification du type de micro-organismes éliminés", isCorrect: false }],
        explanation: "Le conditionnement (sachets thermosoudés, containers stérilisation) doit permettre la pénétration de l'agent stérilisant ET maintenir la stérilité jusqu'à l'utilisation. Il doit être adapté au procédé de stérilisation et préserver l'intégrité de la barrière stérile." }
    ]
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 2.11 – Pharmacologie et thérapeutiques (5 quiz)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Pharmacocinétique",
    description: "Devenir du médicament dans l'organisme : absorption, distribution, métabolisme, élimination",
    semester: "Semestre 1", category: "UE 2.11 - Pharmacologie et thérapeutiques",
    chapter: "Pharmacocinétique", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "Les quatre étapes de la pharmacocinétique (modèle ADME) sont :",
        options: [{ text: "Administration, Distribution, Métabolisme, Excrétion", isCorrect: false },{ text: "Absorption, Distribution, Métabolisme, Élimination", isCorrect: true },{ text: "Action, Diffusion, Modification, Épuration", isCorrect: false },{ text: "Absorption, Diffusion, Modification, Excrétion", isCorrect: false }],
        explanation: "ADME : Absorption (entrée du médicament dans la circulation), Distribution (répartition dans les tissus), Métabolisme (transformation, principalement hépatique), Élimination (excrétion, principalement rénale). Ces 4 étapes déterminent la concentration du médicament au site d'action." },
      { text: "La biodisponibilité d'un médicament est :",
        options: [{ text: "La quantité de médicament absorbée par les cellules cibles", isCorrect: false },{ text: "La fraction de la dose administrée qui atteint la circulation systémique sous forme active", isCorrect: true },{ text: "La vitesse à laquelle le médicament est éliminé", isCorrect: false },{ text: "La concentration maximale atteinte dans le sang", isCorrect: false }],
        explanation: "La biodisponibilité (F) = fraction de la dose administrée atteignant la circulation générale sous forme active. Elle est de 100% pour la voie IV. Les voies orales subissent l'effet de premier passage hépatique qui réduit la biodisponibilité." },
      { text: "L'effet de premier passage hépatique concerne :",
        options: [{ text: "Les médicaments administrés par voie intraveineuse", isCorrect: false },{ text: "Les médicaments administrés par voie orale, métabolisés par le foie avant d'atteindre la circulation générale", isCorrect: true },{ text: "Les médicaments administrés par voie sous-cutanée uniquement", isCorrect: false },{ text: "Les médicaments éliminés par les reins", isCorrect: false }],
        explanation: "Après absorption intestinale, les médicaments per os passent par la veine porte vers le foie avant d'atteindre la circulation générale (premier passage hépatique). Ce métabolisme précoce réduit leur biodisponibilité. Certains médicaments ont un effet de premier passage > 90% (ex : nitroglycérine, propranolol)." },
      { text: "La demi-vie d'élimination (t½) d'un médicament représente :",
        options: [{ text: "Le temps nécessaire pour absorber la moitié de la dose", isCorrect: false },{ text: "Le temps nécessaire pour que la concentration plasmatique diminue de moitié", isCorrect: true },{ text: "La durée d'action du médicament", isCorrect: false },{ text: "Le temps pour atteindre la concentration maximale", isCorrect: false }],
        explanation: "La t½ est le temps nécessaire pour que la concentration plasmatique d'un médicament diminue de 50%. Elle détermine le rythme d'administration. En pratique : il faut 4-5 t½ pour atteindre l'état d'équilibre (steady state) et pour éliminer complètement le médicament." },
      { text: "L'insuffisance rénale impose souvent un ajustement posologique car :",
        options: [{ text: "Elle augmente le métabolisme hépatique", isCorrect: false },{ text: "Elle réduit l'élimination des médicaments à excrétion rénale, risquant d'accumuler le produit", isCorrect: true },{ text: "Elle modifie l'absorption digestive", isCorrect: false },{ text: "Elle diminue la liaison aux protéines plasmatiques", isCorrect: false }],
        explanation: "En cas d'insuffisance rénale, la clairance des médicaments à élimination rénale est réduite, entraînant leur accumulation et un risque de toxicité. L'ajustement posologique (réduction de dose ou espacement des prises) est indispensable selon la clairance de la créatinine (formule MDRD, CKD-EPI)." },
      { text: "La liaison aux protéines plasmatiques (albumine) d'un médicament signifie que :",
        options: [{ text: "Le médicament est totalement inactif", isCorrect: false },{ text: "Seule la fraction libre (non liée) est pharmacologiquement active et diffuse dans les tissus", isCorrect: true },{ text: "Le médicament est stocké dans le foie", isCorrect: false },{ text: "Le médicament est prêt à être éliminé", isCorrect: false }],
        explanation: "Un médicament fortement lié aux protéines plasmatiques (ex : warfarine 99% liée) a une fraction libre limitée. Seule la fraction libre est active et diffuse dans les tissus. En cas d'hypoalbuminémie ou de compétition médicamenteuse, la fraction libre augmente et peut provoquer une toxicité." },
      { text: "Le volume de distribution (Vd) d'un médicament reflète :",
        options: [{ text: "Le volume sanguin total de l'organisme", isCorrect: false },{ text: "La répartition du médicament entre le plasma et les tissus (tendance à s'accumuler dans les tissus)", isCorrect: true },{ text: "La quantité totale de médicament administrée", isCorrect: false },{ text: "Le volume urinaire dans lequel le médicament est éliminé", isCorrect: false }],
        explanation: "Le Vd est un paramètre fictif indiquant la capacité du médicament à se distribuer dans les tissus. Un Vd élevé (ex : chloroquine : 200-800 L) indique une forte accumulation tissulaire. Un Vd faible (héparine : 0,05 L/kg) indique un confinement plasmatique." },
      { text: "L'indice thérapeutique (IT) d'un médicament est :",
        options: [{ text: "La dose efficace pour 50% des patients (DE50)", isCorrect: false },{ text: "Le rapport entre la dose toxique et la dose efficace (DL50/DE50) ; plus il est faible, plus le médicament est dangereux", isCorrect: true },{ text: "La concentration plasmatique maximale tolérée", isCorrect: false },{ text: "Le nombre de prises journalières recommandées", isCorrect: false }],
        explanation: "L'IT (DL50/DE50) mesure la marge entre l'effet thérapeutique et la toxicité. Un IT étroit (digoxine, lithium, warfarine, aminosides, vancomycine) impose une surveillance thérapeutique (dosages plasmatiques) pour maintenir le médicament dans la fenêtre thérapeutique." },
      { text: "La voie sublinguale permet d'éviter :",
        options: [{ text: "Le métabolisme rénal", isCorrect: false },{ text: "L'effet de premier passage hépatique, permettant une action rapide", isCorrect: true },{ text: "La liaison aux protéines plasmatiques", isCorrect: false },{ text: "La distribution dans les tissus", isCorrect: false }],
        explanation: "La voie sublinguale (ex : nitroglycérine) permet une absorption directe par la muqueuse buccale dans la circulation générale, contournant le tube digestif et le premier passage hépatique. Elle assure une action rapide (2-3 minutes pour la trinitrine)." },
      { text: "Le cytochrome P450 (CYP450) joue un rôle majeur dans :",
        options: [{ text: "L'absorption intestinale des médicaments", isCorrect: false },{ text: "Le métabolisme hépatique des médicaments (biotransformation de phase I)", isCorrect: true },{ text: "L'élimination rénale des médicaments", isCorrect: false },{ text: "La liaison des médicaments aux récepteurs cibles", isCorrect: false }],
        explanation: "Les cytochromes P450 (CYP3A4, CYP2D6, CYP2C9…) sont des enzymes hépatiques (et intestinales) qui biotransforment les médicaments en phase I (oxydation, réduction). Certains médicaments induisent (rifampicine) ou inhibent (érythromycine, jus de pamplemousse) le CYP450, modifiant la pharmacocinétique d'autres médicaments." }
    ]
  },
  {
    title: "Analgésiques et psychotropes",
    description: "Pharmacologie des médicaments du système nerveux central",
    semester: "Semestre 1", category: "UE 2.11 - Pharmacologie et thérapeutiques",
    chapter: "Pharmacologie du SNC", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Le paracétamol (acétaminophène) agit principalement comme :",
        options: [{ text: "Anti-inflammatoire non stéroïdien (AINS)", isCorrect: false },{ text: "Analgésique et antipyrétique central, sans action anti-inflammatoire périphérique significative", isCorrect: true },{ text: "Opioïde central", isCorrect: false },{ text: "Corticoïde", isCorrect: false }],
        explanation: "Le paracétamol est un analgésique et antipyrétique d'action centrale (inhibition des COX centrales, modulation des systèmes opioïdes et sérotonergiques). Il n'a pas d'effet anti-inflammatoire périphérique significatif. Sa surdose hépatique est une urgence (antidote : N-acétylcystéine)." },
      { text: "La dose maximale de paracétamol chez l'adulte est de :",
        options: [{ text: "1 g/j", isCorrect: false },{ text: "4 g/j (1 g toutes les 6h)", isCorrect: true },{ text: "8 g/j", isCorrect: false },{ text: "500 mg/j", isCorrect: false }],
        explanation: "La dose maximale de paracétamol est de 4 g/j chez l'adulte sain, à réduire à 2-3 g/j en cas d'insuffisance hépatique, dénutrition ou éthylisme chronique. L'intervalle entre prises doit être de minimum 4h. La surdose (> 10 g) provoque une hépatite fulminante." },
      { text: "Les AINS (ibuprofène, kétoprofène) contre-indiqués en cas de :",
        options: [{ text: "Douleur légère à modérée", isCorrect: false },{ text: "Ulcère gastrique actif, insuffisance rénale, grossesse (3e trimestre), allergie à l'aspirine", isCorrect: true },{ text: "Fièvre uniquement chez l'adulte", isCorrect: false },{ text: "Hypertension artérielle légère", isCorrect: false }],
        explanation: "Les AINS (inhibiteurs des COX-1 et COX-2) sont contre-indiqués en cas d'ulcère gastro-duodénal actif (risque hémorragique), insuffisance rénale (réduction du débit glomérulaire), 3e trimestre de grossesse (fermeture prématurée du canal artériel), et hypersensibilité aux AINS." },
      { text: "La morphine est une contre-indication absolue en cas de :",
        options: [{ text: "Douleur cancéreuse", isCorrect: false },{ text: "Insuffisance respiratoire sévère non assistée et allergie connue", isCorrect: true },{ text: "Douleur post-opératoire", isCorrect: false },{ text: "Patient de plus de 75 ans", isCorrect: false }],
        explanation: "La morphine est contre-indiquée en cas d'insuffisance respiratoire sévère non ventilée (risque de dépression respiratoire), de traumatisme crânien avec HTIC, d'allergie connue aux opioïdes, et chez le nourrisson < 6 mois. L'antidote est la naloxone (Narcan®)." },
      { text: "Les benzodiazépines (diazépam, lorazépam) sont des :",
        options: [{ text: "Antipsychotiques", isCorrect: false },{ text: "Anxiolytiques, hypnotiques et anticonvulsivants agissant sur les récepteurs GABA-A", isCorrect: true },{ text: "Antidépresseurs tricycliques", isCorrect: false },{ text: "Opioïdes de palier 2", isCorrect: false }],
        explanation: "Les benzodiazépines potentialisent l'action du GABA (principal neurotransmetteur inhibiteur) sur les récepteurs GABA-A, entraînant anxiolyse, sédation, myorelaxation et effets anticonvulsivants. Risque de dépendance, tolérance et syndrome de sevrage si arrêt brutal." },
      { text: "Les antidépresseurs ISRS (fluoxétine, sertraline, paroxétine) agissent en :",
        options: [{ text: "Inhibant la monoamine oxydase (MAO)", isCorrect: false },{ text: "Bloquant la recapture de la sérotonine dans la fente synaptique", isCorrect: true },{ text: "Stimulant les récepteurs dopaminergiques", isCorrect: false },{ text: "Augmentant la synthèse de noradrénaline", isCorrect: false }],
        explanation: "Les ISRS (Inhibiteurs Sélectifs de la Recapture de la Sérotonine) bloquent le transporteur SERT, augmentant la disponibilité synaptique de la sérotonine. Ils sont indiqués dans la dépression, les troubles anxieux, l'TOC. Délai d'action : 2-4 semaines." },
      { text: "Quel est le risque majeur d'une surdose d'opioïdes ?",
        options: [{ text: "Hypertension artérielle sévère", isCorrect: false },{ text: "Dépression respiratoire pouvant conduire à l'apnée et au décès", isCorrect: true },{ text: "Convulsions tonico-cloniques", isCorrect: false },{ text: "Hépatotoxicité sévère", isCorrect: false }],
        explanation: "La dépression respiratoire est l'effet indésirable le plus grave des opioïdes. La triade de surdosage : myosis punctiforme, bradypnée/apnée, coma. Traitement : naloxone IV (0,4 mg à répéter), ventilation assistée. Surveiller la fréquence respiratoire (> 12/min) et la sédation." },
      { text: "La constipation sous morphine est :",
        options: [{ text: "Un effet transitoire disparaissant après la première semaine", isCorrect: false },{ text: "Un effet indésirable constant nécessitant une prescription systématique de laxatifs", isCorrect: true },{ text: "Un effet uniquement chez les sujets âgés", isCorrect: false },{ text: "Un signe de surdosage en morphine", isCorrect: false }],
        explanation: "La constipation sous opioïdes est un effet indésirable persistant (pas de tolérance, contrairement aux nausées et à la sédation). Les récepteurs μ intestinaux ralentissent le transit. Un laxatif osmotique ou stimulant doit être prescrit systématiquement avec la morphine." },
      { text: "Les antipsychotiques (halopéridol, rispéridone, olanzapine) sont indiqués dans :",
        options: [{ text: "L'anxiété légère et les troubles du sommeil", isCorrect: false },{ text: "La schizophrénie, les épisodes maniaques et les déliria", isCorrect: true },{ text: "La dépression sans symptômes psychotiques uniquement", isCorrect: false },{ text: "La douleur neuropathique chronique", isCorrect: false }],
        explanation: "Les antipsychotiques (neuroleptiques) bloquent les récepteurs dopaminergiques D2 (et autres). Indications : schizophrénie, épisodes maniaques bipolaires, agitation psychotique, délire, vomissements réfractaires. Effets secondaires : syndrome parkinsonien, dyskinésies tardives, hypotension orthostatique." },
      { text: "La naloxone (Narcan®) est l'antidote des opioïdes car elle :",
        options: [{ text: "Accélère l'élimination des opioïdes par le rein", isCorrect: false },{ text: "Entre en compétition avec les opioïdes sur leurs récepteurs (antagoniste µ pur)", isCorrect: true },{ text: "Active le métabolisme hépatique des opioïdes", isCorrect: false },{ text: "Stimule les centres respiratoires bulbaires directement", isCorrect: false }],
        explanation: "La naloxone est un antagoniste compétitif pur des récepteurs opioïdes µ (mu). Elle déplace les opioïdes de leurs récepteurs et reverse rapidement leurs effets (dépression respiratoire, sedation). Attention : sa demi-vie est courte (60-90 min), nécessitant une surveillance prolongée après injection." }
    ]
  },
  {
    title: "Antibiotiques et anti-infectieux",
    description: "Classes d'antibiotiques, mécanismes d'action et résistances",
    semester: "Semestre 1", category: "UE 2.11 - Pharmacologie et thérapeutiques",
    chapter: "Antibiothérapie", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "Les antibiotiques de la famille des bêta-lactamines comprennent :",
        options: [{ text: "Les aminosides (gentamicine) et les quinolones", isCorrect: false },{ text: "Les pénicillines, céphalosporines, carbapénèmes et monobactams", isCorrect: true },{ text: "Les macrolides (érythromycine) et les tétracyclines", isCorrect: false },{ text: "Les glycopeptides (vancomycine) et les lincosamides", isCorrect: false }],
        explanation: "Les bêta-lactamines constituent la plus grande famille d'antibiotiques : pénicillines (amoxicilline, pipéracilline), céphalosporines (1re à 5e génération), carbapénèmes (imipénème, méropénème), monobactams (aztréonam). Elles inhibent la synthèse de la paroi bactérienne (liaison aux PLP)." },
      { text: "La résistance d'une bactérie aux bêta-lactamines par production de BLSE signifie :",
        options: [{ text: "La bactérie est sensible aux pénicillines classiques", isCorrect: false },{ text: "La bactérie produit des enzymes hydrolysant les bêta-lactamines à spectre étendu (pénicillines et céphalosporines)", isCorrect: true },{ text: "La bactérie ne peut pas être traitée par aucun antibiotique", isCorrect: false },{ text: "La résistance est uniquement acquise par mutation", isCorrect: false }],
        explanation: "Les BLSE (Bêta-Lactamases à Spectre Élargi) sont des enzymes produites par certaines entérobactéries (E. coli, Klebsiella) qui hydrolysent la plupart des pénicillines et céphalosporines. Le traitement repose sur les carbapénèmes ou la ticarcilline-clavulanate selon l'antibiogramme." },
      { text: "Les aminosides (gentamicine, amikacine) sont caractérisés par :",
        options: [{ text: "Une action uniquement sur les bactéries anaérobies", isCorrect: false },{ text: "Une activité bactéricide concentration-dépendante et une ototoxicité/néphrotoxicité", isCorrect: true },{ text: "Une bonne diffusion dans les sécrétions bronchiques", isCorrect: false },{ text: "L'absence d'effets indésirables rénaux", isCorrect: false }],
        explanation: "Les aminosides (inhibent la synthèse protéique bactérienne au niveau du ribosome 30S) ont une activité concentration-dépendante (une dose unique journalière optimise l'efficacité et réduit la toxicité). Risques : néphrotoxicité (surveillance créatinine) et ototoxicité (surveillance auditive en traitement prolongé)." },
      { text: "La vancomycine (glycopeptide) est l'antibiotique de référence pour traiter :",
        options: [{ text: "Les infections à bactéries Gram négatif", isCorrect: false },{ text: "Les infections graves à SARM (Staphylococcus aureus résistant à la méticilline)", isCorrect: true },{ text: "Les infections fongiques invasives", isCorrect: false },{ text: "La tuberculose pulmonaire", isCorrect: false }],
        explanation: "La vancomycine (glycopeptide) inhibe la synthèse de la paroi bactérienne des Gram positif. C'est l'antibiotique de référence dans les infections sévères à SARM. Elle nécessite une surveillance des dosages sériques (indice thérapeutique étroit, risque de néphro/ototoxicité)." },
      { text: "Les fluoroquinolones (ciprofloxacine, lévofloxacine) agissent en :",
        options: [{ text: "Inhibant la synthèse protéique bactérienne", isCorrect: false },{ text: "Inhibant les ADN-gyrases et topoisomérases IV bactériennes, bloquant la réplication de l'ADN", isCorrect: true },{ text: "Perturbant la membrane plasmique bactérienne", isCorrect: false },{ text: "Inhibant la synthèse des folates", isCorrect: false }],
        explanation: "Les fluoroquinolones inhibent les topoisomérases bactériennes (ADN-gyrase, topo IV), enzymes essentielles au déroulement et à la réplication de l'ADN bactérien. Large spectre (Gram + et -). Contre-indications : grossesse, enfant, allongement QT." },
      { text: "La durée d'antibiothérapie doit être :",
        options: [{ text: "Toujours d'au moins 3 semaines pour tout type d'infection", isCorrect: false },{ text: "La plus courte possible et adaptée à l'infection, au germe et à la réponse clinique", isCorrect: true },{ text: "Identique pour toutes les infections bactériennes (7 jours systématiques)", isCorrect: false },{ text: "Indéterminée et à poursuivre tant qu'il y a des symptômes", isCorrect: false }],
        explanation: "Le principe de bon usage des antibiotiques impose des durées adaptées (courtes si possible) pour réduire la pression de sélection des résistances et les effets indésirables. Ex : cystite simple = 3-7j ; pneumonie = 5-7j ; endocardite = 4-6 semaines." },
      { text: "L'antibiothérapie probabiliste (empirique) est prescrite :",
        options: [{ text: "Après réception de l'antibiogramme", isCorrect: false },{ text: "Avant identification du germe, sur la base des données épidémiologiques et cliniques", isCorrect: true },{ text: "Uniquement en ambulatoire pour les infections bénignes", isCorrect: false },{ text: "Sur la base des habitudes du prescripteur uniquement", isCorrect: false }],
        explanation: "L'antibiothérapie probabiliste est initiée avant les résultats microbiologiques, sur la base de l'épidémiologie locale et du tableau clinique (site d'infection, terrain, gravité). Elle est ensuite réajustée (de-escalade) à la réception de l'antibiogramme." },
      { text: "Le cotrimoxazole (Bactrim®) est une association de :",
        options: [{ text: "Amoxicilline et acide clavulanique", isCorrect: false },{ text: "Sulfaméthoxazole et triméthoprime, inhibant la synthèse des folates bactériens", isCorrect: true },{ text: "Ciprofloxacine et métronidazole", isCorrect: false },{ text: "Pénicilline G et gentamicine", isCorrect: false }],
        explanation: "Le cotrimoxazole (SMX+TMP) inhibe deux étapes consécutives de la synthèse des folates bactériens (synergie bactéricide). Indications : infections urinaires, pneumocystose (Pneumocystis jirovecii chez l'immunodéprimé), toxoplasmose en prophylaxie." },
      { text: "Quel antibiotique ne doit jamais être administré chez la femme enceinte (> 8 SA) en raison de ses effets sur le squelette fœtal ?",
        options: [{ text: "L'amoxicilline", isCorrect: false },{ text: "Les tétracyclines (doxycycline, minocycline)", isCorrect: true },{ text: "La céfazoline", isCorrect: false },{ text: "Le métronidazole (1er trimestre uniquement déconseillé)", isCorrect: false }],
        explanation: "Les tétracyclines sont contre-indiquées à partir du 2e trimestre de grossesse : elles se lient au calcium et s'incorporent dans les os et les dents du fœtus (coloration des dents, malformations osseuses). Également contre-indiquées chez l'enfant < 8 ans." },
      { text: "La prophylaxie antibiotique chirurgicale pré-opératoire vise à :",
        options: [{ text: "Traiter toute infection préexistante avant la chirurgie", isCorrect: false },{ text: "Réduire le risque d'infection du site opératoire pendant l'acte chirurgical", isCorrect: true },{ text: "Prévenir les infections urinaires post-opératoires systématiquement", isCorrect: false },{ text: "Stériliser le champ opératoire à l'intérieur des tissus", isCorrect: false }],
        explanation: "La prophylaxie antibiotique chirurgicale est une dose unique d'antibiotique (ou quelques doses) administrée 30-60 min avant l'incision pour atteindre des concentrations tissulaires efficaces pendant l'acte opératoire. Elle réduit le risque d'ISO (infections du site opératoire) de 50-75%." }
    ]
  },
  {
    title: "Médicaments cardiovasculaires",
    description: "Pharmacologie des médicaments agissant sur le cœur et les vaisseaux",
    semester: "Semestre 1", category: "UE 2.11 - Pharmacologie et thérapeutiques",
    chapter: "Cardiopharmacie", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "Les bêta-bloquants (métoprolol, aténolol) agissent en :",
        options: [{ text: "Bloquant les récepteurs alpha-adrénergiques vasculaires", isCorrect: false },{ text: "Bloquant les récepteurs bêta-1 cardiaques, réduisant la fréquence et la contractilité", isCorrect: true },{ text: "Inhibant l'enzyme de conversion de l'angiotensine", isCorrect: false },{ text: "Bloquant les canaux calciques cardiaques", isCorrect: false }],
        explanation: "Les bêta-bloquants inhibent les récepteurs bêta-1 cardiaques, diminuant la fréquence (effet chronotrope négatif) et la contractilité (effet inotrope négatif). Indications : HTA, angine de poitrine, insuffisance cardiaque chronique, arythmies. Contre-indication : asthme, bradycardie sévère." },
      { text: "Les IEC (ramipril, énalapril) sont utilisés dans :",
        options: [{ text: "La tachycardie ventriculaire uniquement", isCorrect: false },{ text: "L'hypertension artérielle, l'insuffisance cardiaque et la néphropathie diabétique", isCorrect: true },{ text: "L'angor instable uniquement", isCorrect: false },{ text: "L'hypotension orthostatique", isCorrect: false }],
        explanation: "Les IEC inhibent l'enzyme de conversion (transformant l'angiotensine I en angiotensine II vasoconstrictrice). Ils réduisent la pré et post-charge cardiaques. Effets indésirables : toux sèche (bradykinine), hyperkaliémie, insuffisance rénale aiguë. Contre-indication : grossesse, sténose rénale bilatérale." },
      { text: "La digoxine (digitalique) est utilisée principalement dans :",
        options: [{ text: "L'hypertension artérielle systolique", isCorrect: false },{ text: "La fibrillation atriale (pour contrôler la fréquence ventriculaire) et l'insuffisance cardiaque systolique", isCorrect: true },{ text: "L'angine de poitrine à l'effort", isCorrect: false },{ text: "Les extrasystoles ventriculaires isolées", isCorrect: false }],
        explanation: "La digoxine inhibe la Na/K-ATPase, augmentant le calcium intracellulaire (inotrope positif) et ralentissant la conduction nœud AV (chronotrope et dromotrope négatif). Indice thérapeutique très étroit → risque de surdosage (nausées, arythmies, bradycardie). Surveillance taux de digoxine et kaliémie." },
      { text: "L'aspirine à faible dose (75-100 mg/j) utilisée en prévention cardio-vasculaire agit comme :",
        options: [{ text: "Anticoagulant oral inhibant la synthèse des facteurs de coagulation", isCorrect: false },{ text: "Antiagrégant plaquettaire par inhibition irréversible de la COX-1 plaquettaire (thromboxane A2)", isCorrect: true },{ text: "Thrombolytique dissolve les caillots existants", isCorrect: false },{ text: "Vasodilatateur coronarien", isCorrect: false }],
        explanation: "L'aspirine à faible dose inhibe de façon irréversible la COX-1 plaquettaire, bloquant la synthèse de thromboxane A2 (agrégant plaquettaire). L'effet dure toute la vie de la plaquette (7-10 jours). Elle est utilisée en prévention primaire et secondaire des événements thromboemboliques artériels." },
      { text: "Les statines (atorvastatine, simvastatine) réduisent le risque cardiovasculaire en :",
        options: [{ text: "Fluidifiant le sang et réduisant sa viscosité", isCorrect: false },{ text: "Inhibant la HMG-CoA réductase, réduisant la synthèse hépatique de cholestérol", isCorrect: true },{ text: "Augmentant l'élimination rénale du cholestérol", isCorrect: false },{ text: "Bloquant l'absorption intestinale des triglycérides", isCorrect: false }],
        explanation: "Les statines inhibent la HMG-CoA réductase, enzyme-clé de la synthèse endogène du cholestérol. Elles réduisent le LDL-cholestérol de 30-50%, diminuant le risque d'événements cardiovasculaires. Effets secondaires : myalgies, myopathie (surveiller CPK), hépatotoxicité." },
      { text: "La trinitrine (nitroglycérine) sublinguale est utilisée en cas de :",
        options: [{ text: "Hypertension artérielle chronique", isCorrect: false },{ text: "Crise angineuse aiguë (angor d'effort), agissant en 1-3 minutes", isCorrect: true },{ text: "Insuffisance cardiaque chronique compensée", isCorrect: false },{ text: "Fibrillation atriale paroxystique", isCorrect: false }],
        explanation: "La trinitrine SL (ou spray) libère du monoxyde d'azote (NO) provoquant une vasodilatation veineuse (réduction de la précharge) et artérielle coronarienne. Délai d'action 1-3 minutes. Effets secondaires : céphalées (vasodilatation cérébrale), hypotension orthostatique." },
      { text: "La surveillance infirmière d'un patient sous anticoagulant oral (AVK : warfarine) inclut :",
        options: [{ text: "La mesure de la créatinine uniquement", isCorrect: false },{ text: "La surveillance de l'INR (cible 2-3 pour la plupart des indications) et des signes hémorragiques", isCorrect: true },{ text: "L'ECG quotidien", isCorrect: false },{ text: "La numération plaquettaire uniquement", isCorrect: false }],
        explanation: "Les AVK (warfarine, fluindione, acénocoumarol) nécessitent une surveillance régulière de l'INR (International Normalized Ratio), reflet de l'anticoagulation. Cible habituelle : INR 2-3. Surveiller : signes d'hémorragie (cutanée, digestive, urinaire), interactions médicamenteuses et alimentaires (vitamine K)." },
      { text: "Les héparines de bas poids moléculaire (HBPM : énoxaparine, daltéparine) sont préférées à l'héparine standard car :",
        options: [{ text: "Elles ne nécessitent aucune surveillance biologique", isCorrect: false },{ text: "Elles ont une pharmacocinétique plus prévisible et peuvent être administrées en SC une fois par jour", isCorrect: true },{ text: "Elles sont actives par voie orale", isCorrect: false },{ text: "Elles n'ont aucun risque de thrombopénie", isCorrect: false }],
        explanation: "Les HBPM ont une biodisponibilité SC élevée (90%), une t½ plus longue et une activité anti-Xa plus prévisible que l'héparine non fractionnée. Elles sont administrées en 1-2 injections SC/j. Surveillance anti-Xa si insuffisance rénale, obésité morbide ou grossesse. Risque de TIH plus faible mais non nul." },
      { text: "Les diurétiques de l'anse (furosémide) sont utilisés dans :",
        options: [{ text: "L'hypertension artérielle légère en première intention", isCorrect: false },{ text: "L'œdème aigu pulmonaire (OAP), l'insuffisance cardiaque congestive et les œdèmes sévères", isCorrect: true },{ text: "La prévention de la thrombose veineuse", isCorrect: false },{ text: "La crise hypertensive uniquement", isCorrect: false }],
        explanation: "Le furosémide inhibe le cotransporteur Na-K-2Cl dans l'anse de Henlé, entraînant une diurèse puissante et rapide. Utilisé dans OAP (voie IV), insuffisance cardiaque et œdèmes. Surveiller : kaliémie (hypokaliémie), natrémie, volémie, pression artérielle et diurèse." },
      { text: "La surveillance d'un patient sous antihypertenseur comprend :",
        options: [{ text: "La mesure de la glycémie uniquement", isCorrect: false },{ text: "La mesure de la PA, de la fréquence cardiaque, la détection d'hypotension orthostatique et d'effets indésirables spécifiques", isCorrect: true },{ text: "Uniquement l'ECG mensuel", isCorrect: false },{ text: "La surveillance de la température corporelle", isCorrect: false }],
        explanation: "La surveillance sous antihypertenseurs inclut : mesure régulière de la PA (couchée et debout pour hypotension orthostatique), fréquence cardiaque, poids (œdèmes, diurèse), et effets indésirables spécifiques (toux sous IEC, œdèmes des chevilles sous inhibiteurs calciques, hyperkaliémie sous IEC/ARA2)." }
    ]
  },
  {
    title: "Voies d'administration et surveillance thérapeutique",
    description: "Techniques d'administration des médicaments et surveillance des traitements",
    semester: "Semestre 1", category: "UE 2.11 - Pharmacologie et thérapeutiques",
    chapter: "Thérapeutiques et administration", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "La voie intraveineuse directe (IVD) est caractérisée par :",
        options: [{ text: "Un délai d'action de 30 minutes", isCorrect: false },{ text: "Une action immédiate et une biodisponibilité de 100%", isCorrect: true },{ text: "Une absorption lente et régulière", isCorrect: false },{ text: "Un effet de premier passage hépatique important", isCorrect: false }],
        explanation: "La voie IVD permet une action quasi-immédiate (pic plasmatique en secondes) et une biodisponibilité de 100% (pas d'absorption nécessaire). Elle est utilisée pour les urgences et les médicaments ne pouvant être absorbés autrement. Nécessite une surveillance rapprochée des effets." },
      { text: "La voie intramusculaire (IM) est contre-indiquée en cas de :",
        options: [{ text: "Douleur légère à modérée", isCorrect: false },{ text: "Traitement anticoagulant, troubles de la coagulation, thrombopénie sévère", isCorrect: true },{ text: "Difficultés de déglutition", isCorrect: false },{ text: "Patient obèse uniquement", isCorrect: false }],
        explanation: "La voie IM est contre-indiquée en cas de traitement anticoagulant ou de troubles de la coagulation (risque d'hématome intramusculaire extensif). Elle est également évitée en cas de thrombopénie sévère, de mauvaise vascularisation locale et de patients dénutris (résorption imprévisible)." },
      { text: "La vérification des 5B avant toute administration de médicament comprend :",
        options: [{ text: "Bon budget, Bonne bureaucratie, Bon bilan, Bonne banque, Bonne bactériologie", isCorrect: false },{ text: "Bon médicament, Bonne dose, Bon patient, Bonne voie, Bon moment", isCorrect: true },{ text: "Bon médecin, Bonne infirmière, Bonne pharmacie, Bon résultat, Bon patient", isCorrect: false },{ text: "Bonne couleur, Bonne consistance, Bonne date, Bon conditionnement, Bon stockage", isCorrect: false }],
        explanation: "La règle des 5B (ou 5 rights) est une check-list de sécurité médicamenteuse indispensable avant chaque administration : vérifier le Bon médicament, la Bonne dose, le Bon patient (identité), la Bonne voie d'administration, et le Bon moment (heure, fréquence)." },
      { text: "La perfusion intraveineuse à la pompe à seringue (PSE) nécessite :",
        options: [{ text: "Un contrôle uniquement en début de perfusion", isCorrect: false },{ text: "Une surveillance régulière du débit, de la voie veineuse, du médicament et des signes d'effets indésirables", isCorrect: true },{ text: "Un changement de seringue toutes les 24h uniquement", isCorrect: false },{ text: "Aucune surveillance si le patient est conscient", isCorrect: false }],
        explanation: "La PSE requiert une surveillance continue : débit programmé (ml/h), point de ponction (inflammation, extravasation), état du patient (signes d'effet thérapeutique ou toxique), étiquetage correct de la seringue, date de péremption de la préparation." },
      { text: "L'injection sous-cutanée d'insuline nécessite une rotation des sites car :",
        options: [{ text: "Pour des raisons esthétiques uniquement", isCorrect: false },{ text: "Pour éviter la lipodystrophie et assurer une absorption régulière de l'insuline", isCorrect: true },{ text: "Pour prévenir les infections locales uniquement", isCorrect: false },{ text: "Pour diminuer la douleur des injections", isCorrect: false }],
        explanation: "La lipodystrophie (hypertrophie ou atrophie du tissu sous-cutané) se développe en cas d'injections répétées au même endroit et perturbe l'absorption de l'insuline. La rotation des sites (abdomen, cuisses, bras, fesses) dans une zone de 5-7 cm assure une absorption régulière et prévisible." },
      { text: "Qu'est-ce qu'une extravasation lors d'une perfusion IV ?",
        options: [{ text: "Le passage accidentel d'air dans la perfusion", isCorrect: false },{ text: "Le passage accidentel du liquide de perfusion dans les tissus périphériques au lieu de la veine", isCorrect: true },{ text: "La précipitation du médicament dans la tubulure", isCorrect: false },{ text: "L'infection du site de ponction veineuse", isCorrect: false }],
        explanation: "L'extravasation est le passage du liquide de perfusion (surtout des médicaments vésicants : chimiothérapie, certains électrolytes, vasopresseurs) dans les tissus périphériques. Elle provoque douleur, œdème, érythème et peut causer des nécroses tissulaires graves." },
      { text: "La traçabilité de l'administration médicamenteuse dans le dossier patient comprend :",
        options: [{ text: "Uniquement la signature de l'infirmier après administration", isCorrect: false },{ text: "Le nom du médicament, la dose, la voie, l'heure d'administration, le nom de l'infirmier et les observations", isCorrect: true },{ text: "Seulement la date et l'heure d'administration", isCorrect: false },{ text: "Le nom du prescripteur uniquement", isCorrect: false }],
        explanation: "La traçabilité médicamenteuse dans le dossier patient est une obligation légale et de sécurité. Elle doit comprendre : médicament (DCI), dose administrée, voie, date et heure, identité de l'infirmier ayant administré, et toute observation (refus, effet indésirable, administration différée)." },
      { text: "Les incompatibilités médicamenteuses en perfusion peuvent provoquer :",
        options: [{ text: "Uniquement une modification de l'aspect de la solution", isCorrect: false },{ text: "Une inactivation du médicament, une précipitation, une réaction chimique toxique ou une embolie", isCorrect: true },{ text: "Uniquement une coloration anormale sans conséquence", isCorrect: false },{ text: "Toujours une réaction allergique grave", isCorrect: false }],
        explanation: "Les incompatibilités physicochimiques en perfusion peuvent : inactiver un ou les deux médicaments (perte d'efficacité), former un précipité (occlusion du cathéter, embolie), ou produire des composés toxiques. Vérifier le dictionnaire des incompatibilités ou consulter le pharmacien avant tout mélange." },
      { text: "La surveillance d'un patient recevant du potassium IV (KCl) en perfusion impose :",
        options: [{ text: "Un débit rapide pour corriger rapidement l'hypokaliémie", isCorrect: false },{ text: "Un débit lent (< 10-20 mmol/h), sur voie centrale si possible, avec monitoring cardiaque", isCorrect: true },{ text: "L'administration en IVD directe uniquement", isCorrect: false },{ text: "Une surveillance de la glycémie toutes les heures", isCorrect: false }],
        explanation: "Le KCl IV est potentiellement dangereux : un apport trop rapide provoque une hyperkaliémie aiguë (arrêt cardiaque). Règle : jamais en IVD directe, débit < 10-20 mmol/h, concentration < 40 mmol/L sur voie périphérique, monitoring ECG continu si débit > 10 mmol/h ou patient à risque." },
      { text: "L'éducation thérapeutique du patient (ETP) concernant son traitement médicamenteux vise à :",
        options: [{ text: "Le rendre dépendant du soignant pour la gestion de ses médicaments", isCorrect: false },{ text: "Lui permettre d'acquérir les compétences pour gérer sa maladie et son traitement de façon autonome", isCorrect: true },{ text: "Lui expliquer le mécanisme d'action détaillé de chaque médicament", isCorrect: false },{ text: "Réduire le nombre de médicaments prescrits", isCorrect: false }],
        explanation: "L'ETP (loi du 21 juillet 2009) vise à rendre le patient acteur de sa santé : comprendre sa maladie et ses traitements, reconnaître les signes d'alerte, gérer son traitement au quotidien, et adapter son mode de vie. Elle améliore l'observance et la qualité de vie." }
    ]
  }
];
