// ─── PARTIE 2 : UE 2.2 · UE 2.4 ────────────────────────────────────────────
module.exports = [

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 2.2 – Cycles de la vie et grandes fonctions (5 quiz)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Système cardiovasculaire",
    description: "Anatomie et physiologie du cœur et des vaisseaux",
    semester: "Semestre 1", category: "UE 2.2 - Cycles de la vie et grandes fonctions",
    chapter: "Cardiologie", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Quel est le rôle principal du cœur ?",
        options: [{ text: "Filtrer le sang et éliminer les déchets", isCorrect: false },{ text: "Pomper le sang pour assurer la circulation dans tout l'organisme", isCorrect: true },{ text: "Produire les cellules sanguines", isCorrect: false },{ text: "Réguler la composition du sang", isCorrect: false }],
        explanation: "Le cœur est une pompe musculaire qui propulse le sang dans la grande et la petite circulation, assurant l'apport en O2 et nutriments à tous les tissus et l'élimination des déchets métaboliques." },
      { text: "Le cœur est composé de combien de cavités ?",
        options: [{ text: "2 cavités (1 oreillette, 1 ventricule)", isCorrect: false },{ text: "4 cavités (2 oreillettes, 2 ventricules)", isCorrect: true },{ text: "3 cavités", isCorrect: false },{ text: "6 cavités", isCorrect: false }],
        explanation: "Le cœur comprend 4 cavités : oreillette droite et gauche (reçoivent le sang) et ventricule droit et gauche (éjectent le sang). Le septum interventriculaire sépare le cœur gauche (grande circulation) du cœur droit (petite circulation)." },
      { text: "La petite circulation (circulation pulmonaire) va :",
        options: [{ text: "Du cœur gauche vers les organes puis retour au cœur droit", isCorrect: false },{ text: "Du ventricule droit vers les poumons puis retour à l'oreillette gauche", isCorrect: true },{ text: "Du ventricule gauche vers les poumons", isCorrect: false },{ text: "De l'oreillette droite directement aux poumons", isCorrect: false }],
        explanation: "La petite circulation (pulmonaire) : ventricule droit → artère pulmonaire → poumons (hématose) → veines pulmonaires → oreillette gauche. Le sang est oxygéné dans les poumons et débarrassé du CO2." },
      { text: "La valvule mitrale sépare :",
        options: [{ text: "L'oreillette droite du ventricule droit", isCorrect: false },{ text: "L'oreillette gauche du ventricule gauche", isCorrect: true },{ text: "Le ventricule gauche de l'aorte", isCorrect: false },{ text: "Le ventricule droit de l'artère pulmonaire", isCorrect: false }],
        explanation: "La valvule mitrale (bicuspide) est située entre l'oreillette gauche et le ventricule gauche. Elle empêche le reflux sanguin lors de la contraction ventriculaire. Son insuffisance provoque un souffle cardiaque." },
      { text: "Quelle est la valeur normale de la pression artérielle systolique chez l'adulte ?",
        options: [{ text: "60 à 80 mmHg", isCorrect: false },{ text: "100 à 140 mmHg", isCorrect: true },{ text: "150 à 180 mmHg", isCorrect: false },{ text: "80 à 100 mmHg", isCorrect: false }],
        explanation: "La pression artérielle normale est inférieure à 140/90 mmHg. La systolique (pression maximale lors de la contraction ventriculaire) est normalement entre 100 et 140 mmHg, la diastolique entre 60 et 90 mmHg." },
      { text: "L'électrocardiogramme (ECG) mesure :",
        options: [{ text: "La pression à l'intérieur des cavités cardiaques", isCorrect: false },{ text: "L'activité électrique du cœur", isCorrect: true },{ text: "Le débit cardiaque", isCorrect: false },{ text: "La résistance vasculaire périphérique", isCorrect: false }],
        explanation: "L'ECG enregistre l'activité électrique du cœur via des électrodes cutanées. Il permet de détecter les troubles du rythme (fibrillation, flutter), les blocs de conduction et les signes d'ischémie myocardique (infarctus)." },
      { text: "Le nœud sino-auriculaire (NSA) est :",
        options: [{ text: "Une valve cardiaque", isCorrect: false },{ text: "Le pacemaker naturel du cœur, initiateur de l'influx électrique", isCorrect: true },{ text: "Une artère coronaire", isCorrect: false },{ text: "Un muscle cardiaque accessoire", isCorrect: false }],
        explanation: "Le NSA (nœud de Keith et Flack), situé dans l'oreillette droite, est le pacemaker naturel du cœur. Il génère spontanément des influx électriques (60-100/min) qui se propagent aux oreillettes puis aux ventricules via le faisceau de His." },
      { text: "L'hypotension orthostatique se définit par :",
        options: [{ text: "Une pression artérielle élevée en position debout", isCorrect: false },{ text: "Une chute de la PA systolique ≥ 20 mmHg au passage en position debout", isCorrect: true },{ text: "Une pression artérielle basse uniquement la nuit", isCorrect: false },{ text: "Une fréquence cardiaque trop lente", isCorrect: false }],
        explanation: "L'hypotension orthostatique est définie par une chute de la pression artérielle systolique ≥ 20 mmHg (ou diastolique ≥ 10 mmHg) dans les 3 minutes suivant le passage en position debout. Elle peut causer vertiges et syncopes." },
      { text: "Les artères coronaires irriguent :",
        options: [{ text: "Les poumons", isCorrect: false },{ text: "Le muscle cardiaque (myocarde)", isCorrect: true },{ text: "Le cerveau", isCorrect: false },{ text: "Les reins", isCorrect: false }],
        explanation: "Les artères coronaires (gauche et droite) partent de l'aorte et vascularisent le myocarde. Leur obstruction (athérosclérose, thrombose) provoque l'ischémie myocardique et l'infarctus du myocarde." },
      { text: "La fréquence cardiaque normale au repos chez l'adulte est de :",
        options: [{ text: "40 à 60 battements/minute", isCorrect: false },{ text: "60 à 100 battements/minute", isCorrect: true },{ text: "100 à 120 battements/minute", isCorrect: false },{ text: "120 à 160 battements/minute", isCorrect: false }],
        explanation: "La fréquence cardiaque normale au repos est de 60 à 100 bpm. En dessous de 60 bpm : bradycardie. Au-dessus de 100 bpm : tachycardie. L'athlète entraîné peut avoir une FC de repos à 40-50 bpm (physiologique)." }
    ]
  },
  {
    title: "Système respiratoire",
    description: "Anatomie et physiologie de l'appareil respiratoire",
    semester: "Semestre 1", category: "UE 2.2 - Cycles de la vie et grandes fonctions",
    chapter: "Pneumologie", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Quelle est la fonction principale de l'appareil respiratoire ?",
        options: [{ text: "Filtrer le sang et éliminer les déchets azotés", isCorrect: false },{ text: "Assurer les échanges gazeux : apport d'O2 et élimination du CO2", isCorrect: true },{ text: "Réguler la température corporelle", isCorrect: false },{ text: "Produire les globules rouges", isCorrect: false }],
        explanation: "L'appareil respiratoire assure l'hématose : apport d'oxygène (O2) aux cellules et élimination du dioxyde de carbone (CO2) produit par le métabolisme cellulaire. Cette fonction est vitale et nécessite une ventilation continue." },
      { text: "Les alvéoles pulmonaires sont le siège de :",
        options: [{ text: "La filtration de l'air inspiré", isCorrect: false },{ text: "Les échanges gazeux entre l'air et le sang capillaire", isCorrect: true },{ text: "La production du mucus bronchique", isCorrect: false },{ text: "La régulation de la fréquence respiratoire", isCorrect: false }],
        explanation: "Les alvéoles (300 millions chez l'adulte, surface totale ≈ 70 m²) sont en contact avec les capillaires pulmonaires. Les échanges gazeux se font par diffusion passive à travers une membrane très fine (0,5 µm)." },
      { text: "La fréquence respiratoire normale au repos chez l'adulte est de :",
        options: [{ text: "5 à 10 cycles/minute", isCorrect: false },{ text: "12 à 20 cycles/minute", isCorrect: true },{ text: "25 à 35 cycles/minute", isCorrect: false },{ text: "40 à 50 cycles/minute", isCorrect: false }],
        explanation: "La fréquence respiratoire normale au repos est de 12 à 20 cycles/min. La tachypnée (> 20/min) peut signer une détresse respiratoire, une infection ou une anxiété. La bradypnée (< 12/min) peut indiquer une dépression du centre respiratoire." },
      { text: "Quel muscle est le principal acteur de la respiration ?",
        options: [{ text: "Les muscles intercostaux", isCorrect: false },{ text: "Le diaphragme", isCorrect: true },{ text: "Le muscle grand pectoral", isCorrect: false },{ text: "Le muscle sterno-cléido-mastoïdien", isCorrect: false }],
        explanation: "Le diaphragme est le muscle principal de la respiration. Sa contraction (inspiration) aplatit le dôme diaphragmatique, augmentant le volume thoracique et créant une dépression qui aspire l'air dans les poumons." },
      { text: "La SpO2 mesure :",
        options: [{ text: "La pression partielle en O2 dans le sang artériel", isCorrect: false },{ text: "La saturation en oxygène de l'hémoglobine par oxymétrie de pouls", isCorrect: true },{ text: "La fréquence respiratoire", isCorrect: false },{ text: "La capacité pulmonaire totale", isCorrect: false }],
        explanation: "La SpO2 (saturation pulsée en O2) mesure non invasivement le pourcentage d'hémoglobine saturée en oxygène. La valeur normale est ≥ 95%. En dessous de 90%, c'est une désaturation nécessitant une intervention." },
      { text: "La trachée se divise en deux bronches souches au niveau de :",
        options: [{ text: "Le larynx", isCorrect: false },{ text: "La carène (niveau de la 4e vertèbre thoracique)", isCorrect: true },{ text: "La 1re côte", isCorrect: false },{ text: "Le diaphragme", isCorrect: false }],
        explanation: "La trachée (longueur ≈ 12 cm) se divise à la carène (au niveau de D4-D5) en bronche souche droite et gauche. La bronche droite est plus verticale que la gauche, d'où la fréquence plus élevée de corps étrangers à droite." },
      { text: "L'hypoxie désigne :",
        options: [{ text: "Un excès d'oxygène dans les tissus", isCorrect: false },{ text: "Un manque d'oxygène au niveau des tissus", isCorrect: true },{ text: "Un excès de CO2 dans le sang", isCorrect: false },{ text: "Une insuffisance de ventilation", isCorrect: false }],
        explanation: "L'hypoxie est l'insuffisance d'apport ou d'utilisation d'O2 par les tissus. Elle peut être hypoxémique (PaO2 basse), anémique (manque d'hémoglobine), circulatoire (débit sanguin insuffisant) ou histotoxique (intoxication)." },
      { text: "La plèvre est :",
        options: [{ text: "Le muscle séparant thorax et abdomen", isCorrect: false },{ text: "La membrane séreuse double enveloppant chaque poumon", isCorrect: true },{ text: "Le tissu de soutien des bronchioles", isCorrect: false },{ text: "La membrane tapissant les alvéoles", isCorrect: false }],
        explanation: "La plèvre est une séreuse à deux feuillets (viscéral collé au poumon, pariétal collé à la paroi) entre lesquels existe un espace virtuel (cavité pleurale). Son inflammation (pleurésie) ou un épanchement (hydro/pneumothorax) est pathologique." },
      { text: "Le surfactant pulmonaire a pour rôle de :",
        options: [{ text: "Humecter les voies aériennes supérieures", isCorrect: false },{ text: "Réduire la tension de surface des alvéoles et éviter leur collapsus", isCorrect: true },{ text: "Défendre contre les infections pulmonaires", isCorrect: false },{ text: "Transporter l'O2 dans les alvéoles", isCorrect: false }],
        explanation: "Le surfactant (produit par les pneumocytes de type II) réduit la tension de surface alvéolaire, empêchant le collapsus des alvéoles à l'expiration. Sa carence chez le prématuré cause la maladie des membranes hyalines." },
      { text: "L'asthme se caractérise principalement par :",
        options: [{ text: "Une destruction permanente des alvéoles", isCorrect: false },{ text: "Une inflammation bronchique réversible avec hyper-réactivité et bronchospasme", isCorrect: true },{ text: "Une fibrose pulmonaire progressive", isCorrect: false },{ text: "Un épanchement liquidien dans la plèvre", isCorrect: false }],
        explanation: "L'asthme est une maladie inflammatoire chronique des bronches caractérisée par une hyperréactivité bronchique, des épisodes de bronchospasme réversible, avec dyspnée sifflante. Il est traité par bronchodilatateurs et corticoïdes inhalés." }
    ]
  },
  {
    title: "Système nerveux",
    description: "Organisation et fonctionnement du système nerveux central et périphérique",
    semester: "Semestre 1", category: "UE 2.2 - Cycles de la vie et grandes fonctions",
    chapter: "Neurologie", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "Le système nerveux central (SNC) est composé de :",
        options: [{ text: "Les nerfs crâniens et spinaux uniquement", isCorrect: false },{ text: "L'encéphale (cerveau, cervelet, tronc cérébral) et la moelle épinière", isCorrect: true },{ text: "Le système sympathique et parasympathique", isCorrect: false },{ text: "Les ganglions nerveux et les plexus", isCorrect: false }],
        explanation: "Le SNC comprend l'encéphale (cerveau, cervelet, tronc cérébral) et la moelle épinière. Le système nerveux périphérique (SNP) regroupe les nerfs crâniens (12 paires) et spinaux (31 paires) qui relient le SNC au reste du corps." },
      { text: "Quel est le rôle du cervelet ?",
        options: [{ text: "Contrôler les fonctions végétatives (respiration, fréquence cardiaque)", isCorrect: false },{ text: "Coordonner les mouvements et maintenir l'équilibre", isCorrect: true },{ text: "Traiter les informations sensorielles conscientes", isCorrect: false },{ text: "Réguler le cycle veille-sommeil", isCorrect: false }],
        explanation: "Le cervelet coordonne les mouvements volontaires, maintient l'équilibre et la posture, et régule le tonus musculaire. Une lésion cérébelleuse provoque une ataxie (démarche ébrieuse), des tremblements intentionnels et une dysarthrie." },
      { text: "Le neurone est caractérisé par :",
        options: [{ text: "Sa capacité de division cellulaire rapide", isCorrect: false },{ text: "La présence d'un axone (transmission) et de dendrites (réception)", isCorrect: true },{ text: "L'absence de noyau cellulaire", isCorrect: false },{ text: "Sa localisation exclusive dans le cerveau", isCorrect: false }],
        explanation: "Le neurone est la cellule fonctionnelle du système nerveux. Il possède : un corps cellulaire (soma), des dendrites (reçoivent les signaux entrants) et un axone (transmet l'influx nerveux vers d'autres neurones ou effecteurs)." },
      { text: "La myéline gaine les axones et permet :",
        options: [{ text: "De nourrir les neurones en glucose", isCorrect: false },{ text: "Une conduction nerveuse plus rapide par sauts de Ranvier", isCorrect: true },{ text: "La synthèse des neurotransmetteurs", isCorrect: false },{ text: "La formation de nouvelles connexions synaptiques", isCorrect: false }],
        explanation: "La myéline est une gaine lipidique isolante enroulée autour des axones (par les cellules de Schwann en périphérie, par les oligodendrocytes dans le SNC). Elle permet la conduction saltatoire (de nœud de Ranvier en nœud), beaucoup plus rapide." },
      { text: "La synapse est :",
        options: [{ text: "La gaine de myéline entourant l'axone", isCorrect: false },{ text: "La zone de communication entre deux neurones ou entre un neurone et un effecteur", isCorrect: true },{ text: "Le corps cellulaire du neurone", isCorrect: false },{ text: "La membrane protectrice du cerveau", isCorrect: false }],
        explanation: "La synapse est la jonction fonctionnelle entre deux neurones (ou entre un neurone et un muscle/glande). La transmission synaptique chimique implique la libération de neurotransmetteurs dans la fente synaptique." },
      { text: "La barrière hémato-encéphalique (BHE) a pour rôle de :",
        options: [{ text: "Produire le liquide céphalorachidien", isCorrect: false },{ text: "Protéger le cerveau en filtrant sélectivement les substances passant du sang au SNC", isCorrect: true },{ text: "Séparer le cerveau du cervelet", isCorrect: false },{ text: "Transmettre les influx nerveux entre les deux hémisphères", isCorrect: false }],
        explanation: "La BHE est formée par les cellules endothéliales des capillaires cérébraux, hermétiquement joints. Elle protège le cerveau des agents pathogènes, toxines et fluctuations des substances sanguines, tout en laissant passer O2, glucose et certains médicaments." },
      { text: "Le système nerveux autonome (végétatif) contrôle :",
        options: [{ text: "Les mouvements volontaires des muscles striés", isCorrect: false },{ text: "Les fonctions involontaires : cœur, digestion, glandes, vaisseaux", isCorrect: true },{ text: "La perception consciente de la douleur", isCorrect: false },{ text: "La mémorisation des informations", isCorrect: false }],
        explanation: "Le SNA (végétatif) régule les fonctions involontaires via deux divisions antagonistes : le sympathique (réaction de stress, 'fight or flight') et le parasympathique (repos, digestion). Il innerve le cœur, les viscères, les vaisseaux et les glandes." },
      { text: "L'AVC (accident vasculaire cérébral) ischémique est causé par :",
        options: [{ text: "Un saignement dans le parenchyme cérébral", isCorrect: false },{ text: "L'occlusion d'une artère cérébrale entraînant une ischémie du territoire concerné", isCorrect: true },{ text: "Une hypertension intracrânienne aiguë", isCorrect: false },{ text: "Une démyélinisation des fibres cérébrales", isCorrect: false }],
        explanation: "L'AVC ischémique (80% des AVC) est dû à l'occlusion d'une artère cérébrale (thrombose, embolie) privant un territoire cérébral d'oxygène. Les signes (FAST : Face, Arm, Speech, Time) nécessitent une prise en charge urgente < 4h30." },
      { text: "Le réflexe ostéo-tendineux (ROT) emprunte quel arc réflexe ?",
        options: [{ text: "Un arc polysynaptique passant par le cerveau", isCorrect: false },{ text: "Un arc monosynaptique médullaire", isCorrect: true },{ text: "Un arc passant par le cervelet", isCorrect: false },{ text: "Un arc passant par le tronc cérébral", isCorrect: false }],
        explanation: "Le ROT (ex : réflexe rotulien) est un arc monosynaptique : le fuseau neuromusculaire (récepteur) → neurone afférent → moelle épinière → neurone moteur → muscle effecteur. Il évalue l'intégrité du nerf périphérique et de la moelle." },
      { text: "La méningite est une inflammation de :",
        options: [{ text: "Du parenchyme cérébral", isCorrect: false },{ text: "Des méninges (membranes enveloppant le cerveau et la moelle épinière)", isCorrect: true },{ text: "Du ventricule cérébral", isCorrect: false },{ text: "De la barrière hémato-encéphalique", isCorrect: false }],
        explanation: "La méningite est l'inflammation des méninges (dure-mère, arachnoïde, pie-mère). Elle se manifeste par une triade : céphalées intenses, fièvre, raideur de nuque. Les formes bactériennes (méningocoque, pneumocoque) sont des urgences vitales." }
    ]
  },
  {
    title: "Système digestif et nutrition",
    description: "Fonctionnement de l'appareil digestif et bases de la nutrition",
    semester: "Semestre 1", category: "UE 2.2 - Cycles de la vie et grandes fonctions",
    chapter: "Gastro-entérologie", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Dans quel organe débute la digestion chimique des glucides ?",
        options: [{ text: "L'estomac", isCorrect: false },{ text: "La bouche (salive avec amylase salivaire)", isCorrect: true },{ text: "L'intestin grêle", isCorrect: false },{ text: "Le duodénum", isCorrect: false }],
        explanation: "La digestion des glucides débute dans la bouche grâce à l'amylase salivaire (ptyaline) qui hydrolyse l'amidon en maltose. Elle reprend dans le duodénum avec l'amylase pancréatique." },
      { text: "Quel est le rôle du suc gastrique (acide chlorhydrique) dans l'estomac ?",
        options: [{ text: "Digérer les glucides", isCorrect: false },{ text: "Créer un milieu acide activant la pepsine pour digérer les protéines", isCorrect: true },{ text: "Absorber les vitamines liposolubles", isCorrect: false },{ text: "Neutraliser les acides des aliments", isCorrect: false }],
        explanation: "L'HCl gastrique (pH 1,5-2) acidifie le contenu stomacal, active le pepsinogène en pepsine (enzyme protéolytique) et détruit la majorité des agents pathogènes ingérés. La muqueuse gastrique se protège par une couche de mucus." },
      { text: "L'absorption des nutriments se fait principalement dans :",
        options: [{ text: "L'estomac", isCorrect: false },{ text: "L'intestin grêle (jéjunum et iléon)", isCorrect: true },{ text: "Le gros intestin (côlon)", isCorrect: false },{ text: "La bouche", isCorrect: false }],
        explanation: "L'intestin grêle (6-7 m de long) est le principal site d'absorption grâce à sa muqueuse formant des villosités et des microvillosités (bordure en brosse), multipliant la surface d'absorption (≈ 200 m²)." },
      { text: "Quelle est la fonction principale du côlon (gros intestin) ?",
        options: [{ text: "Absorber les nutriments essentiels", isCorrect: false },{ text: "Réabsorber l'eau et les électrolytes, former les selles", isCorrect: true },{ text: "Sécréter des enzymes digestives", isCorrect: false },{ text: "Produire la bile", isCorrect: false }],
        explanation: "Le côlon réabsorbe l'eau (1,5 L/jour) et les électrolytes (sodium, chlore) du chyme intestinal, transformant ce dernier en matières fécales. Il héberge également le microbiote intestinal (bactéries commensales)." },
      { text: "La bile est produite par le foie et stockée dans :",
        options: [{ text: "Le pancréas", isCorrect: false },{ text: "La vésicule biliaire", isCorrect: true },{ text: "L'estomac", isCorrect: false },{ text: "Le duodénum", isCorrect: false }],
        explanation: "La bile est synthétisée continuellement par le foie (600-1000 ml/j) et stockée/concentrée dans la vésicule biliaire. Elle est déversée dans le duodénum lors de la digestion pour émulsifier les graisses (favorisant l'action des lipases)." },
      { text: "L'indice de masse corporelle (IMC) se calcule par :",
        options: [{ text: "Poids (kg) × Taille (m)", isCorrect: false },{ text: "Poids (kg) / Taille² (m²)", isCorrect: true },{ text: "Poids (kg) / Taille (m)", isCorrect: false },{ text: "Taille (m) / Poids² (kg²)", isCorrect: false }],
        explanation: "L'IMC = Poids (kg) / Taille² (m²). Valeurs : < 18,5 = sous-poids ; 18,5-24,9 = normal ; 25-29,9 = surpoids ; ≥ 30 = obésité (classe I : 30-35, II : 35-40, III : > 40 = obésité morbide)." },
      { text: "Les vitamines liposolubles sont :",
        options: [{ text: "B1, B6, B12 et C", isCorrect: false },{ text: "A, D, E et K", isCorrect: true },{ text: "B9, B12 et C", isCorrect: false },{ text: "B2, B3 et C", isCorrect: false }],
        explanation: "Les vitamines liposolubles (A, D, E, K) sont stockées dans les graisses corporelles et le foie. Les vitamines hydrosolubles (groupe B et C) ne sont pas stockées et doivent être apportées régulièrement. Leur absorption nécessite des lipides alimentaires." },
      { text: "La dénutrition chez le patient hospitalisé est dépistée par :",
        options: [{ text: "La glycémie à jeun", isCorrect: false },{ text: "L'albuminémie, la préalbumine et l'évaluation clinique (NRS-2002, MNA)", isCorrect: true },{ text: "La formule NFS uniquement", isCorrect: false },{ text: "Le taux de LDL cholestérol", isCorrect: false }],
        explanation: "La dénutrition est dépistée par des marqueurs biologiques (albuminémie < 35 g/L, préalbumine < 0,20 g/L) et des outils validés : NRS-2002 (hospitalisés), MNA (personnes âgées). Elle augmente la morbi-mortalité et les complications." },
      { text: "Quelle enzyme pancréatique digère les lipides ?",
        options: [{ text: "L'amylase pancréatique", isCorrect: false },{ text: "La lipase pancréatique", isCorrect: true },{ text: "La trypsine", isCorrect: false },{ text: "La maltase", isCorrect: false }],
        explanation: "La lipase pancréatique hydrolyse les triglycérides en monoglycérides et acides gras libres dans le duodénum. Elle nécessite la bile (émulsification des graisses) pour agir efficacement." },
      { text: "Une alimentation équilibrée doit apporter environ :",
        options: [{ text: "80% glucides, 10% lipides, 10% protéines", isCorrect: false },{ text: "50-55% glucides, 30-35% lipides, 12-15% protéines", isCorrect: true },{ text: "40% protéines, 40% glucides, 20% lipides", isCorrect: false },{ text: "70% lipides, 20% glucides, 10% protéines", isCorrect: false }],
        explanation: "Les recommandations nutritionnelles (ANSES) pour un adulte : 50-55% de l'énergie en glucides (dont < 10% sucres simples), 30-35% en lipides (favoriser insaturés), 12-15% en protéines (0,8 g/kg/j au minimum)." }
    ]
  },
  {
    title: "Système urinaire et rénal",
    description: "Anatomie, physiologie rénale et régulation hydro-électrolytique",
    semester: "Semestre 1", category: "UE 2.2 - Cycles de la vie et grandes fonctions",
    chapter: "Urologie", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Quel est le rôle principal des reins ?",
        options: [{ text: "Produire les hormones sexuelles", isCorrect: false },{ text: "Filtrer le sang, éliminer les déchets et réguler le volume et la composition des liquides corporels", isCorrect: true },{ text: "Produire les globules rouges", isCorrect: false },{ text: "Dégrader les médicaments", isCorrect: false }],
        explanation: "Les reins assurent la filtration du sang (± 180 L/jour de filtrat glomérulaire), l'élimination des déchets métaboliques (urée, créatinine), la régulation hydro-électrolytique, acido-basique, et sécrètent érythropoïétine et rénine." },
      { text: "Le néphron est :",
        options: [{ text: "Le canal urinaire reliant rein et vessie", isCorrect: false },{ text: "L'unité fonctionnelle de base du rein", isCorrect: true },{ text: "La membrane enveloppant le rein", isCorrect: false },{ text: "Le système de vascularisation du rein", isCorrect: false }],
        explanation: "Chaque rein contient environ 1 million de néphrons, unités fonctionnelles composées du glomérule de Malpighi (filtration), du tube contourné proximal, de l'anse de Henlé (concentration), du tube contourné distal et du tube collecteur." },
      { text: "La diurèse normale d'un adulte est d'environ :",
        options: [{ text: "200 à 400 mL/24h", isCorrect: false },{ text: "1000 à 1500 mL/24h", isCorrect: true },{ text: "3000 à 4000 mL/24h", isCorrect: false },{ text: "500 à 800 mL/24h", isCorrect: false }],
        explanation: "La diurèse normale est de 1000 à 1500 mL/24h (environ 0,5-1 mL/kg/h). L'oligurie (< 400 mL/24h) et l'anurie (< 100 mL/24h) sont des signes d'alarme. La polyurie (> 3 L/24h) peut signer un diabète insipide ou sucré." },
      { text: "La créatininémie est un marqueur de :",
        options: [{ text: "L'état nutritionnel du patient", isCorrect: false },{ text: "La fonction rénale (filtration glomérulaire)", isCorrect: true },{ text: "L'état d'hydratation uniquement", isCorrect: false },{ text: "La fonction hépatique", isCorrect: false }],
        explanation: "La créatinine est un déchet du métabolisme musculaire éliminé uniquement par filtration rénale. Son élévation (hypercreatininémie) signe une insuffisance rénale. Normale : 60-110 µmol/L (H) ; 45-90 µmol/L (F)." },
      { text: "L'ADH (hormone antidiurétique ou vasopressine) agit en :",
        options: [{ text: "Augmentant la diurèse et l'élimination d'eau", isCorrect: false },{ text: "Réabsorbant l'eau dans le tube collecteur pour concentrer les urines", isCorrect: true },{ text: "Augmentant l'élimination du sodium", isCorrect: false },{ text: "Diminuant la pression artérielle", isCorrect: false }],
        explanation: "L'ADH (sécrétée par la post-hypophyse) augmente la perméabilité à l'eau des tubes collecteurs, favorisant la réabsorption d'eau et la concentration des urines. Sa carence cause le diabète insipide (polyurie hypotonique)." },
      { text: "Le syndrome néphrotique se caractérise par :",
        options: [{ text: "Une hématurie macroscopique et une hypertension artérielle", isCorrect: false },{ text: "Une protéinurie massive, hypoalbuminémie et œdèmes", isCorrect: true },{ text: "Une insuffisance rénale aiguë avec anurie", isCorrect: false },{ text: "Des douleurs lombaires et une pollakiurie", isCorrect: false }],
        explanation: "Le syndrome néphrotique est défini par une protéinurie > 3,5 g/24h, hypoalbuminémie < 30 g/L, œdèmes déclives. Il résulte d'une atteinte des podocytes glomérulaires (altération du filtre). Risque de thrombose et infections." },
      { text: "L'infection urinaire basse (cystite) se manifeste par :",
        options: [{ text: "Fièvre élevée, frissons et douleurs lombaires", isCorrect: false },{ text: "Pollakiurie, brûlures mictionnelles, urines troubles sans fièvre", isCorrect: true },{ text: "Anurie et œdèmes généralisés", isCorrect: false },{ text: "Hématurie macroscopique indolore", isCorrect: false }],
        explanation: "La cystite (infection vésicale basse) se manifeste par une pollakiurie (mictions fréquentes), des brûlures mictionnelles, une pesanteur pelvienne, parfois une hématurie. Elle est sans fièvre ni signe général. Touche surtout la femme (urètre court)." },
      { text: "L'urée sanguine (urémie) provient de :",
        options: [{ text: "La dégradation des glucides alimentaires", isCorrect: false },{ text: "La dégradation des protéines dans le foie (catabolisme des acides aminés)", isCorrect: true },{ text: "La synthèse des acides nucléiques", isCorrect: false },{ text: "La métabolisation des lipides", isCorrect: false }],
        explanation: "L'urée est synthétisée dans le foie lors du catabolisme des acides aminés (cycle de l'urée). Éliminée par le rein, son augmentation (> 8 mmol/L) évoque une insuffisance rénale ou une augmentation du catabolisme protéique." },
      { text: "La rétention urinaire aiguë chez l'homme est souvent causée par :",
        options: [{ text: "Une infection rénale (pyélonéphrite)", isCorrect: false },{ text: "Un adénome (hypertrophie bénigne) de la prostate", isCorrect: true },{ text: "Une cystite aiguë", isCorrect: false },{ text: "Un calcul rénal", isCorrect: false }],
        explanation: "L'hypertrophie bénigne de la prostate (HBP) est la cause la plus fréquente de rétention urinaire aiguë chez l'homme de plus de 50 ans. La prostate comprime l'urètre, empêchant la miction. Le traitement d'urgence est le sondage urinaire." },
      { text: "L'équilibre acido-basique normal du sang correspond à un pH de :",
        options: [{ text: "6,9 à 7,2", isCorrect: false },{ text: "7,35 à 7,45", isCorrect: true },{ text: "7,5 à 7,8", isCorrect: false },{ text: "8,0 à 8,5", isCorrect: false }],
        explanation: "Le pH sanguin normal est maintenu entre 7,35 et 7,45 grâce aux systèmes tampons (bicarbonate, protéines, phosphates), la régulation respiratoire (CO2) et rénale (HCO3-). Acidose < 7,35, alcalose > 7,45." }
    ]
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 2.4 – Processus traumatiques (4 quiz)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Inflammation et cicatrisation",
    description: "Mécanismes physiologiques de l'inflammation et de la réparation tissulaire",
    semester: "Semestre 1", category: "UE 2.4 - Processus traumatiques",
    chapter: "Inflammation", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Quels sont les 4 signes cardinaux de l'inflammation aiguë ?",
        options: [{ text: "Fièvre, tachycardie, hypotension, pâleur", isCorrect: false },{ text: "Rougeur (rubor), chaleur (calor), tuméfaction (tumor), douleur (dolor)", isCorrect: true },{ text: "Œdème, cyanose, ictère, purpura", isCorrect: false },{ text: "Prurit, éruption, desquamation, ulcération", isCorrect: false }],
        explanation: "Les 4 signes cardinaux de l'inflammation aiguë, décrits par Celse, sont : rougeur (vasodilatation), chaleur (augmentation du débit sanguin local), tuméfaction (œdème), douleur (prostaglandines, bradykinine). Virchow y a ajouté l'impotence fonctionnelle." },
      { text: "La réaction inflammatoire est initiée par la libération de :",
        options: [{ text: "Hormones thyroïdiennes", isCorrect: false },{ text: "Médiateurs chimiques (histamine, prostaglandines, cytokines) par les mastocytes et macrophages", isCorrect: true },{ text: "Enzymes digestives", isCorrect: false },{ text: "Anticorps spécifiques uniquement", isCorrect: false }],
        explanation: "L'inflammation débute par la reconnaissance du danger (PAMP, DAMP) par les macrophages résidents et mastocytes, qui libèrent des médiateurs chimiques : histamine (vasodilatation), prostaglandines (douleur, fièvre), cytokines (TNF, IL-1, IL-6)." },
      { text: "La phase de cicatrisation d'une plaie comprend dans l'ordre :",
        options: [{ text: "Remodelage → Prolifération → Hémostase → Inflammation", isCorrect: false },{ text: "Hémostase → Inflammation → Prolifération → Remodelage", isCorrect: true },{ text: "Inflammation → Hémostase → Remodelage → Prolifération", isCorrect: false },{ text: "Prolifération → Hémostase → Inflammation → Remodelage", isCorrect: false }],
        explanation: "La cicatrisation se déroule en 4 phases : 1) Hémostase (coagulation, plug plaquettaire) ; 2) Inflammation (nettoyage) ; 3) Prolifération (fibrose, néo-angiogenèse, épithélialisation) ; 4) Remodelage (maturation de la cicatrice, jusqu'à 2 ans)." },
      { text: "La cicatrisation en première intention est caractérisée par :",
        options: [{ text: "Une plaie laissée ouverte à combler par le tissu de granulation", isCorrect: false },{ text: "Une suture précoce des berges rapprochées d'une plaie propre", isCorrect: true },{ text: "L'utilisation d'une greffe cutanée", isCorrect: false },{ text: "Une plaie infectée traitée par antibiothérapie", isCorrect: false }],
        explanation: "La cicatrisation de première intention est obtenue par rapprochement chirurgical (suture, agrafes, colle) des berges d'une plaie propre et non infectée. Elle est plus rapide, laisse une cicatrice minime." },
      { text: "Le collagène est synthétisé par :",
        options: [{ text: "Les lymphocytes", isCorrect: false },{ text: "Les fibroblastes", isCorrect: true },{ text: "Les mastocytes", isCorrect: false },{ text: "Les polynucléaires neutrophiles", isCorrect: false }],
        explanation: "Les fibroblastes, recrutés dans la plaie lors de la phase proliférative, synthétisent le collagène (principalement de type I et III) et la matrice extracellulaire qui constituent la trame de la cicatrice. La résistance mécanique augmente progressivement." },
      { text: "Qu'est-ce qu'une cicatrice chéloïde ?",
        options: [{ text: "Une cicatrice en creux (atrophique)", isCorrect: false },{ text: "Une cicatrice hypertrophique envahissant les tissus sains au-delà des berges", isCorrect: true },{ text: "Une cicatrice infectée", isCorrect: false },{ text: "Une plaie non cicatrisée depuis plus d'un mois", isCorrect: false }],
        explanation: "La chéloïde est une cicatrice hypertrophique fibrotique qui dépasse les berges de la plaie initiale et continue à croître. Elle est plus fréquente chez les personnes à peau foncée. Elle peut être traitée par infiltrations de corticoïdes, compression ou chirurgie." },
      { text: "L'inflammation chronique se distingue de l'inflammation aiguë par :",
        options: [{ text: "L'absence de lymphocytes", isCorrect: false },{ text: "La prédominance de macrophages et lymphocytes avec fibrose possible", isCorrect: true },{ text: "Une résolution rapide en 48-72h", isCorrect: false },{ text: "L'absence de vascularisation", isCorrect: false }],
        explanation: "L'inflammation chronique (semaines/mois) est caractérisée par un infiltrat de mononucléaires (macrophages, lymphocytes, plasmocytes), une néo-angiogenèse et une fibrose. Elle peut former des granulomes (tuberculose, Crohn)." },
      { text: "La douleur inflammatoire est principalement médiée par :",
        options: [{ text: "L'adrénaline et la noradrénaline", isCorrect: false },{ text: "Les prostaglandines et la bradykinine", isCorrect: true },{ text: "Le cortisol et l'aldostérone", isCorrect: false },{ text: "La mélatonine et la sérotonine", isCorrect: false }],
        explanation: "Les prostaglandines (PGE2, PGI2) sensibilisent les nocicepteurs à la douleur et causent la fièvre centrale. La bradykinine active directement les nocicepteurs. Les AINS inhibent les cyclo-oxygénases (COX), réduisant la synthèse de prostaglandines." },
      { text: "Le plasma riche en plaquettes (PRP) est utilisé en cicatrisation car :",
        options: [{ text: "Il possède des propriétés anticoagulantes", isCorrect: false },{ text: "Il concentre des facteurs de croissance plaquettaires favorisant la réparation tissulaire", isCorrect: true },{ text: "Il élimine les bactéries des plaies infectées", isCorrect: false },{ text: "Il remplace le collagène dans les plaies chroniques", isCorrect: false }],
        explanation: "Le PRP concentre des facteurs de croissance (PDGF, TGF-β, VEGF, EGF) libérés par les plaquettes. Ces facteurs stimulent la prolifération cellulaire, la synthèse de collagène et l'angiogenèse, accélérant la cicatrisation des plaies difficiles." },
      { text: "Quel facteur favorise la mauvaise cicatrisation d'une plaie ?",
        options: [{ text: "Un apport nutritionnel adéquat en protéines et vitamine C", isCorrect: false },{ text: "Le diabète, la dénutrition, la corticothérapie et l'infection locale", isCorrect: true },{ text: "Une bonne vascularisation locale", isCorrect: false },{ text: "L'humidification régulière de la plaie", isCorrect: false }],
        explanation: "Les facteurs de mauvaise cicatrisation sont : locaux (infection, ischémie, tension sur les berges, corps étranger) et généraux (diabète, dénutrition, immunosuppression, corticothérapie, insuffisance veineuse ou artérielle, âge avancé)." }
    ]
  },
  {
    title: "Traumatismes et soins d'urgence",
    description: "Prise en charge des traumatismes physiques courants",
    semester: "Semestre 1", category: "UE 2.4 - Processus traumatiques",
    chapter: "Traumatologie", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Quelle est la classification des fractures selon le degré d'ouverture cutanée ?",
        options: [{ text: "Stable / Instable / Comminutive", isCorrect: false },{ text: "Fracture fermée / Fracture ouverte (avec communication avec l'extérieur)", isCorrect: true },{ text: "Complète / Incomplète / Pathologique", isCorrect: false },{ text: "Directe / Indirecte / De stress", isCorrect: false }],
        explanation: "Une fracture fermée n'a pas de communication avec l'extérieur. Une fracture ouverte (Cauchoix-Duparc grade I-III) présente une solution de continuité cutanée, exposant l'os et imposant une prise en charge chirurgicale urgente." },
      { text: "Les signes cliniques d'une fracture sont :",
        options: [{ text: "Fièvre, rougeur et chaleur locale uniquement", isCorrect: false },{ text: "Douleur, déformation, impotence fonctionnelle, ecchymose, crépitement", isCorrect: true },{ text: "Pâleur, hypotension et tachycardie uniquement", isCorrect: false },{ text: "Œdème seul sans douleur", isCorrect: false }],
        explanation: "Les signes d'une fracture : douleur exquise à la palpation, déformation du membre, impotence fonctionnelle, ecchymose (hématome), parfois crépitement osseux à la mobilisation (ne PAS provoquer). La radiographie confirme le diagnostic." },
      { text: "L'immobilisation d'une fracture doit inclure :",
        options: [{ text: "Uniquement le foyer de fracture", isCorrect: false },{ text: "L'articulation sus-jacente et sous-jacente au foyer de fracture", isCorrect: true },{ text: "Uniquement l'articulation la plus proche", isCorrect: false },{ text: "Le membre entier systématiquement", isCorrect: false }],
        explanation: "La règle d'immobilisation des fractures : immobiliser l'articulation au-dessus ET en dessous du foyer de fracture. Ex : fracture de jambe → immobiliser la cheville ET le genou. Cela prévient le déplacement du foyer." },
      { text: "La contusion cérébrale (traumatisme crânien) est surveillée par :",
        options: [{ text: "La mesure de la glycémie", isCorrect: false },{ text: "L'échelle de Glasgow (GCS) évaluant ouverture des yeux, réponse verbale et motrice", isCorrect: true },{ text: "La prise de la température", isCorrect: false },{ text: "La mesure de la SpO2 uniquement", isCorrect: false }],
        explanation: "L'échelle de Glasgow (3-15 points) évalue l'état de conscience après traumatisme crânien : ouverture des yeux (1-4), réponse verbale (1-5), réponse motrice (1-6). Score ≤ 8 : coma grave nécessitant une intubation. À surveiller toutes les heures en phase aiguë." },
      { text: "Une entorse est définie comme :",
        options: [{ text: "La rupture complète d'un tendon", isCorrect: false },{ text: "Un traumatisme ligamentaire sans rupture osseuse", isCorrect: true },{ text: "Une luxation articulaire partielle", isCorrect: false },{ text: "Une fracture du cartilage articulaire", isCorrect: false }],
        explanation: "L'entorse est un traumatisme articulaire avec étirement, déchirure partielle ou totale des ligaments, sans luxation. Grades : bénigne (grade I, distension), moyenne (grade II, déchirure partielle), grave (grade III, rupture totale)." },
      { text: "Le protocole RICE (ou GRICE) pour les traumatismes des membres comprend :",
        options: [{ text: "Repos, Incision, Compression, Élévation", isCorrect: false },{ text: "Glaçage, Repos, Immobilisation/compression, Élévation", isCorrect: true },{ text: "Réchauffement, Immobilisation, Compression, Exercice", isCorrect: false },{ text: "Récupération, Inflammation, Cicatrisation, Évacuation", isCorrect: false }],
        explanation: "Le protocole GRICE (Glaçage, Repos, Immobilisation-Compression, Élévation) est le traitement initial des traumatismes musculo-squelettiques sans fracture. Le glaçage réduit œdème et douleur dans les 48 premières heures (pas de chaleur en phase aiguë)." },
      { text: "Un pneumothorax compressif est une urgence car il provoque :",
        options: [{ text: "Une simple gêne respiratoire sans risque vital", isCorrect: false },{ text: "Un collapsus cardio-circulatoire par compression des structures médiastinales", isCorrect: true },{ text: "Une infection pleurale grave", isCorrect: false },{ text: "Une hémorragie interne thoracique", isCorrect: false }],
        explanation: "Le pneumothorax compressif (air sous pression dans la plèvre) est une urgence vitale : le médiastin est dévié, comprimant le cœur et les gros vaisseaux. Signes : détresse respiratoire, tachycardie, hypotension, trachée déviée. Traitement : exsufflation en urgence." },
      { text: "Le choc hémorragique survient quand la perte sanguine dépasse :",
        options: [{ text: "100 mL", isCorrect: false },{ text: "30% de la volémie totale (environ 1500 mL chez l'adulte)", isCorrect: true },{ text: "10% de la volémie", isCorrect: false },{ text: "5 litres de sang", isCorrect: false }],
        explanation: "Le choc hémorragique classe III-IV survient pour des pertes > 30% de la volémie (> 1500 mL chez un adulte de 70 kg). Il se manifeste par une tachycardie, hypotension, marbrures, confusion. Urgence absolue : remplissage vasculaire + hémostase chirurgicale." },
      { text: "La règle des 9 de Wallace est utilisée pour évaluer :",
        options: [{ text: "La profondeur d'une brûlure", isCorrect: false },{ text: "La surface cutanée brûlée (SCB) en pourcentage", isCorrect: true },{ text: "Le score de douleur", isCorrect: false },{ text: "Le degré d'hydratation du patient brûlé", isCorrect: false }],
        explanation: "La règle des 9 de Wallace divise le corps en zones de 9% chacune : tête (9%), chaque bras (9%), chaque jambe (18%), tronc ant. (18%), tronc post. (18%), périnée (1%). Elle permet d'estimer rapidement la SCB pour adapter la réanimation." },
      { text: "Qu'est-ce qu'une luxation ?",
        options: [{ text: "Un glissement partiel des surfaces articulaires", isCorrect: false },{ text: "La perte complète et permanente des rapports normaux entre les surfaces articulaires", isCorrect: true },{ text: "Une fracture adjacente à une articulation", isCorrect: false },{ text: "Un épanchement liquidien dans une articulation", isCorrect: false }],
        explanation: "La luxation est la perte complète de contact entre les surfaces articulaires. Elle peut être traumatique (chute, choc) ou récidivante (instabilité). Elle nécessite une réduction (manipulation pour repositionner l'articulation) souvent sous anesthésie." }
    ]
  },
  {
    title: "Mécanismes de la douleur",
    description: "Physiologie de la douleur et principes de prise en charge",
    semester: "Semestre 1", category: "UE 2.4 - Processus traumatiques",
    chapter: "Douleur", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "La douleur aiguë et la douleur chronique se distinguent principalement par :",
        options: [{ text: "Leur intensité sur l'échelle EVA", isCorrect: false },{ text: "Leur durée : aiguë < 3 mois, chronique > 3-6 mois persistante ou récidivante", isCorrect: true },{ text: "La cause : traumatique vs médicale", isCorrect: false },{ text: "La localisation : périphérique vs centrale", isCorrect: false }],
        explanation: "La douleur aiguë (< 3 mois) est un signal d'alarme utile, souvent traitable. La douleur chronique (> 3-6 mois) est une maladie en soi, avec composantes biologiques, psychologiques et sociales (modèle biopsychosocial), nécessitant une prise en charge multidisciplinaire." },
      { text: "L'échelle EVA (Echelle Visuelle Analogique) est une réglette permettant d'évaluer :",
        options: [{ text: "La localisation précise de la douleur", isCorrect: false },{ text: "L'intensité de la douleur de 0 (absence) à 10 (maximale imaginable)", isCorrect: true },{ text: "Le type de douleur (nociceptive vs neuropathique)", isCorrect: false },{ text: "L'effet des antalgiques sur la douleur", isCorrect: false }],
        explanation: "L'EVA est une réglette de 10 cm. Le patient déplace un curseur de 0 (aucune douleur) à 10 (douleur maximale imaginable). Elle est simple et reproductible. D'autres outils : ENS (numérique), échelle des visages (enfants), DOLOPLUS (personnes âgées)." },
      { text: "Les opioïdes de palier 3 (morphine) agissent en :",
        options: [{ text: "Inhibant la synthèse des prostaglandines", isCorrect: false },{ text: "Se fixant sur les récepteurs opioïdes μ (mu) modulant la transmission douloureuse", isCorrect: true },{ text: "Bloquant les canaux sodiques des nocicepteurs", isCorrect: false },{ text: "Augmentant la sérotonine au niveau de la synapse", isCorrect: false }],
        explanation: "La morphine et les opioïdes forts se lient aux récepteurs opioïdes μ (mu) présents dans le cerveau, la moelle et les tissus périphériques. Ils inhibent la transmission douloureuse à plusieurs niveaux. Effets secondaires : constipation, nausées, sédation, dépression respiratoire." },
      { text: "La classification OMS des antalgiques en 3 paliers place au palier 1 :",
        options: [{ text: "La morphine et les opioïdes forts", isCorrect: false },{ text: "Le paracétamol, l'aspirine et les AINS", isCorrect: true },{ text: "La codéine et le tramadol", isCorrect: false },{ text: "Les anesthésiques locaux", isCorrect: false }],
        explanation: "Palier 1 OMS : analgésiques non opioïdes (paracétamol, AINS, aspirine). Palier 2 : opioïdes faibles (codéine, tramadol, dihydrocodéine). Palier 3 : opioïdes forts (morphine, oxycodone, fentanyl). On adapte le palier à l'intensité de la douleur (EVA 1-3 / 4-6 / 7-10)." },
      { text: "La douleur neuropathique se distingue par :",
        options: [{ text: "Une douleur proportionnelle à la lésion tissulaire", isCorrect: false },{ text: "Des sensations de brûlure, décharges électriques, allodynie, hyperalgésie liées à une lésion nerveuse", isCorrect: true },{ text: "Une réponse totale aux AINS", isCorrect: false },{ text: "Une localisation toujours diffuse", isCorrect: false }],
        explanation: "La douleur neuropathique résulte d'une lésion ou dysfonction du système nerveux. Elle se manifeste par des brûlures, fourmillements, décharges électriques, allodynie (douleur à un stimulus normalement indolore), hyperalgésie. Elle répond peu aux antalgiques classiques mais aux antiépileptiques/antidépresseurs." },
      { text: "L'allodynie est définie comme :",
        options: [{ text: "Une douleur absente malgré une lésion importante", isCorrect: false },{ text: "Une douleur provoquée par un stimulus normalement non douloureux", isCorrect: true },{ text: "Une douleur maximale sans cause retrouvée", isCorrect: false },{ text: "Une augmentation de la sensibilité à tous les stimuli", isCorrect: false }],
        explanation: "L'allodynie est la perception douloureuse d'un stimulus qui, normalement, n'est pas douloureux (ex : simple effleurement de la peau). C'est un signe caractéristique de la douleur neuropathique (zona, neuropathie diabétique)." },
      { text: "La théorie du portillon (Gate Control Theory) a été proposée par :",
        options: [{ text: "Ronald Melzack et Patrick Wall", isCorrect: true },{ text: "Charles Sherrington et Edgar Adrian", isCorrect: false },{ text: "Sigmund Freud et Carl Jung", isCorrect: false },{ text: "René Descartes et Galien", isCorrect: false }],
        explanation: "Melzack et Wall (1965) ont proposé la théorie du portillon (Gate Control) : l'influx douloureux peut être modulé ('portillon ouvert ou fermé') au niveau de la corne postérieure de la moelle par des fibres sensitives non douloureuses (A-bêta)." },
      { text: "Les co-analgésiques (adjuvants) utilisés dans la douleur neuropathique sont :",
        options: [{ text: "Paracétamol et AINS uniquement", isCorrect: false },{ text: "Antiépileptiques (prégabaline, gabapentine) et antidépresseurs tricycliques", isCorrect: true },{ text: "Morphine et fentanyl exclusivement", isCorrect: false },{ text: "Benzodiazépines et antihistaminiques", isCorrect: false }],
        explanation: "Les co-analgésiques (adjuvants) de la douleur neuropathique comprennent : antiépileptiques (prégabaline, gabapentine, carbamazépine) et antidépresseurs tricycliques (amitriptyline). Ils modulent la transmission nerveuse anormale impliquée dans la douleur neuropathique." },
      { text: "La douleur projetée désigne :",
        options: [{ text: "Une douleur imaginaire sans substrat organique", isCorrect: false },{ text: "Une douleur ressentie à distance de sa source (ex : infarctus → douleur bras gauche)", isCorrect: true },{ text: "Une douleur transmise d'un patient à l'autre", isCorrect: false },{ text: "Une douleur provoquée par l'anxiété", isCorrect: false }],
        explanation: "La douleur projetée est perçue à distance de l'organe source, car les afférences viscérales et somatiques convergent sur les mêmes neurones médullaires. Ex : infarctus du myocarde → douleur thoracique irradiant au bras gauche et à la mâchoire." },
      { text: "L'évaluation de la douleur chez un patient non communicant utilise :",
        options: [{ text: "L'EVA uniquement", isCorrect: false },{ text: "Des échelles comportementales (ALGOPLUS, DOLOPLUS, FLACC)", isCorrect: true },{ text: "L'échelle numérique verbale", isCorrect: false },{ text: "Le score de Glasgow", isCorrect: false }],
        explanation: "Les patients non communicants (nourrissons, personnes âgées avec démence, patients sous sédation) nécessitent des échelles comportementales : FLACC (enfants), DOLOPLUS/ALGOPLUS (personnes âgées). Elles évaluent les comportements douloureux : faciès, mouvements, vocalisation." }
    ]
  },
  {
    title: "Réponse au stress et processus physiopathologiques",
    description: "Mécanismes de réponse au stress et processus pathologiques généraux",
    semester: "Semestre 1", category: "UE 2.4 - Processus traumatiques",
    chapter: "Physiopathologie", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "Le syndrome général d'adaptation (SGA) de Hans Selye comprend :",
        options: [{ text: "Infection → Fièvre → Guérison", isCorrect: false },{ text: "Alarme → Résistance → Épuisement", isCorrect: true },{ text: "Stress → Adaptation → Normalisation", isCorrect: false },{ text: "Choc → Coma → Récupération", isCorrect: false }],
        explanation: "Selye (1936) décrit 3 phases : 1) Alarme (activation du système sympathique, libération cortisol/adrénaline) ; 2) Résistance (adaptation aux agents stressants) ; 3) Épuisement (si le stress persiste, faillite des mécanismes d'adaptation, maladies)." },
      { text: "L'axe hypothalamo-hypophyso-surrénalien (HHS) répond au stress en sécrétant :",
        options: [{ text: "De l'insuline et du glucagon", isCorrect: false },{ text: "Du cortisol par les glandes surrénales sous stimulation du CRH et de l'ACTH", isCorrect: true },{ text: "De la mélatonine et de la sérotonine", isCorrect: false },{ text: "De la FSH et de la LH", isCorrect: false }],
        explanation: "Face au stress, l'hypothalamus sécrète le CRH → hypophyse libère l'ACTH → cortex surrénalien sécrète le cortisol. Le cortisol mobilise les réserves énergétiques, inhibe l'inflammation et module la réponse immunitaire." },
      { text: "La nécrose diffère de l'apoptose car elle est :",
        options: [{ text: "Une mort cellulaire programmée physiologique", isCorrect: false },{ text: "Une mort cellulaire accidentelle, incontrôlée, avec réaction inflammatoire", isCorrect: true },{ text: "Sans conséquence pour les cellules voisines", isCorrect: false },{ text: "Bénéfique pour le renouvellement tissulaire", isCorrect: false }],
        explanation: "La nécrose est une mort cellulaire pathologique, non programmée, causée par un trauma, l'ischémie ou des toxines. Elle déclenche une inflammation (libération du contenu cellulaire). L'apoptose est une mort ordonnée, sans inflammation, physiologiquement utile." },
      { text: "L'atrophie d'un organe ou tissu désigne :",
        options: [{ text: "L'augmentation pathologique du volume d'un organe", isCorrect: false },{ text: "La diminution du volume d'un organe ou tissu par réduction de la taille ou du nombre des cellules", isCorrect: true },{ text: "La transformation d'un tissu en un autre de même type", isCorrect: false },{ text: "La multiplication incontrôlée des cellules", isCorrect: false }],
        explanation: "L'atrophie est la réduction de taille (diminution du volume cellulaire) ou du nombre (apoptose) des cellules constituant un tissu. Causes : dénutrition, dénervation, ischémie chronique, immobilisation, vieillissement (sarcopénie)." },
      { text: "L'hypertrophie musculaire observée lors d'un entraînement intense est due à :",
        options: [{ text: "L'augmentation du nombre de cellules musculaires (hyperplasie)", isCorrect: false },{ text: "L'augmentation de la taille des fibres musculaires existantes", isCorrect: true },{ text: "La transformation de cellules graisseuses en cellules musculaires", isCorrect: false },{ text: "La création de nouvelles mitochondries uniquement", isCorrect: false }],
        explanation: "L'hypertrophie musculaire est une adaptation à la demande accrue : augmentation du volume des fibres musculaires par synthèse de protéines contractiles (myosine, actine). Le nombre de cellules (hyperplasie) ne change pratiquement pas chez l'adulte." },
      { text: "Le processus de thrombose est initié par :",
        options: [{ text: "Une augmentation de la diurèse", isCorrect: false },{ text: "La triade de Virchow : stase sanguine, lésion endothéliale, hypercoagulabilité", isCorrect: true },{ text: "Une réaction allergique grave", isCorrect: false },{ text: "Une infection bactérienne systémique", isCorrect: false }],
        explanation: "La triade de Virchow identifie les 3 facteurs favorisant la thrombose : 1) stase sanguine (immobilisation, varices) ; 2) lésion de l'endothélium vasculaire (atherosclérose, traumatisme) ; 3) hypercoagulabilité (cancer, grossesse, mutations génétiques)." },
      { text: "L'embolie pulmonaire est la complication d'une :",
        options: [{ text: "Phlébite superficielle des membres supérieurs", isCorrect: false },{ text: "Thrombose veineuse profonde (TVP) des membres inférieurs principalement", isCorrect: true },{ text: "Artérite des membres inférieurs", isCorrect: false },{ text: "Insuffisance cardiaque congestive", isCorrect: false }],
        explanation: "L'embolie pulmonaire est la migration d'un thrombus (caillot) d'une veine profonde (TVP, principalement des membres inférieurs) vers les artères pulmonaires. Signes : dyspnée brutale, douleur thoracique, tachycardie. Urgence thérapeutique." },
      { text: "L'ischémie est définie comme :",
        options: [{ text: "Un excès de vascularisation dans un tissu", isCorrect: false },{ text: "Une réduction ou interruption de l'apport sanguin à un tissu ou organe", isCorrect: true },{ text: "Une accumulation de liquide dans les tissus", isCorrect: false },{ text: "Une inflammation chronique d'un vaisseau", isCorrect: false }],
        explanation: "L'ischémie est l'insuffisance d'apport sanguin (et donc d'O2 et de nutriments) à un tissu. Elle peut être fonctionnelle (spasme) ou organique (obstruction artérielle). Les conséquences varient selon le tissu et la durée (réversible vs nécrose)." },
      { text: "Le syndrome de détresse respiratoire aiguë (SDRA) est caractérisé par :",
        options: [{ text: "Une obstruction bronchique réversible", isCorrect: false },{ text: "Une hypoxémie sévère réfractaire à l'O2, des infiltrats bilatéraux et une atteinte alvéolaire diffuse", isCorrect: true },{ text: "Un épanchement pleural unilatéral", isCorrect: false },{ text: "Une bronchoconstriction et un wheezing", isCorrect: false }],
        explanation: "Le SDRA est une insuffisance respiratoire aiguë grave (PaO2/FiO2 < 200 mmHg) avec œdème pulmonaire lésionnel (non cardiogénique), infiltrats bilatéraux et hypoxémie réfractaire à l'O2. Il nécessite une ventilation mécanique en réanimation." },
      { text: "Le choc septique est défini par :",
        options: [{ text: "Une infection localisée sans retentissement systémique", isCorrect: false },{ text: "Une sepsis avec hypotension persistante malgré remplissage et nécessitant des vasopresseurs", isCorrect: true },{ text: "Une simple fièvre > 39°C avec hémocultures positives", isCorrect: false },{ text: "Un choc anaphylactique causé par une bactérie", isCorrect: false }],
        explanation: "Le choc septique est le stade le plus grave du sepsis : hypotension artérielle persistante malgré un remplissage adéquat, nécessitant des vasopresseurs pour maintenir une PAM ≥ 65 mmHg, avec lactate > 2 mmol/L. Mortalité : 30-50%." }
    ]
  }
];
