// ─── PARTIE 6 : 2e quiz par chapitre — UE 1.1 · UE 1.3 · UE 2.1 · UE 2.2 ───
module.exports = [

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 1.1 – Psychologie, sociologie, anthropologie
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Mécanismes de défense et relation soignant-soigné",
    description: "Approfondissement des mécanismes de défense et de la relation thérapeutique",
    semester: "Semestre 1", category: "UE 1.1 - Psychologie, sociologie, anthropologie",
    chapter: "Introduction à la psychologie", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Quel mécanisme de défense consiste à transformer une pulsion inacceptable en son contraire ?",
        options: [{ text: "La formation réactionnelle", isCorrect: true },{ text: "La projection", isCorrect: false },{ text: "La régression", isCorrect: false },{ text: "La sublimation", isCorrect: false }],
        explanation: "La formation réactionnelle transforme une pulsion inacceptable (ex : haine) en son contraire manifeste (ex : gentillesse excessive)." },
      { text: "Qu'est-ce que le 'refoulement' en psychanalyse ?",
        options: [{ text: "Le retour à un comportement infantile", isCorrect: false },{ text: "Le rejet dans l'inconscient d'une pensée insupportable", isCorrect: true },{ text: "L'attribution à autrui de ses propres défauts", isCorrect: false },{ text: "La transformation d'une pulsion en activité socialement valorisée", isCorrect: false }],
        explanation: "Le refoulement est le mécanisme de défense fondamental : il consiste à maintenir dans l'inconscient des représentations inacceptables pour le Moi." },
      { text: "La 'sublimation' est un mécanisme de défense considéré comme :",
        options: [{ text: "Pathologique et à traiter", isCorrect: false },{ text: "Mature et socialement valorisé", isCorrect: true },{ text: "Primitif et immature", isCorrect: false },{ text: "Spécifique aux enfants", isCorrect: false }],
        explanation: "La sublimation est considérée comme un mécanisme mature car elle canalise les pulsions vers des activités socialement valorisées (art, sport, créativité)." },
      { text: "Dans la relation soignant-soigné, le 'contre-transfert' désigne :",
        options: [{ text: "Le transfert du dossier médical entre services", isCorrect: false },{ text: "Les réactions émotionnelles inconscientes du soignant envers le patient", isCorrect: true },{ text: "Le refus du patient d'accepter les soins", isCorrect: false },{ text: "La transmission d'une infection au soignant", isCorrect: false }],
        explanation: "Le contre-transfert est l'ensemble des réactions émotionnelles inconscientes du soignant en réponse au transfert du patient. Le soignant doit l'identifier pour maintenir une posture professionnelle." },
      { text: "Selon Rogers, la 'congruence' du soignant signifie :",
        options: [{ text: "Être d'accord avec tous les propos du patient", isCorrect: false },{ text: "Respecter les normes institutionnelles strictement", isCorrect: false },{ text: "Être authentique et cohérent entre ce que l'on ressent et ce que l'on exprime", isCorrect: true },{ text: "Maintenir une distance émotionnelle totale", isCorrect: false }],
        explanation: "La congruence est l'une des 3 conditions de Rogers : le soignant doit être authentique, sans façade, cohérent entre son ressenti et son expression." },
      { text: "Le mécanisme de 'déni' est particulièrement observé chez :",
        options: [{ text: "Les patients qui demandent beaucoup d'informations", isCorrect: false },{ text: "Les patients qui refusent de reconnaître la réalité de leur maladie", isCorrect: true },{ text: "Les patients qui expriment leur colère ouvertement", isCorrect: false },{ text: "Les patients qui pleurent fréquemment", isCorrect: false }],
        explanation: "Le déni permet de se protéger d'une réalité insupportable (diagnostic grave). Le soignant ne doit pas brusquement forcer la prise de conscience." },
      { text: "L'écoute active dans la relation d'aide implique :",
        options: [{ text: "Donner rapidement des conseils pour rassurer", isCorrect: false },{ text: "Reformuler, poser des questions ouvertes et laisser des silences", isCorrect: true },{ text: "Parler davantage pour combler les silences", isCorrect: false },{ text: "Éviter tout contact visuel pour ne pas intimider", isCorrect: false }],
        explanation: "L'écoute active comprend la reformulation, les questions ouvertes, les silences bienveillants et les signes non verbaux d'attention. Elle favorise l'expression du patient." },
      { text: "La 'résilience' est favorisée par :",
        options: [{ text: "L'isolement social et le retrait", isCorrect: false },{ text: "La présence de facteurs protecteurs comme le soutien social et les ressources internes", isCorrect: true },{ text: "L'absence de tout vécu traumatisant", isCorrect: false },{ text: "Un environnement totalement sans contraintes", isCorrect: false }],
        explanation: "La résilience dépend de facteurs protecteurs : soutien social, estime de soi, sens donné à l'épreuve, capacité à chercher de l'aide." },
      { text: "Qu'est-ce que la 'relation d'objet' en psychanalyse ?",
        options: [{ text: "La relation du soignant avec le matériel médical", isCorrect: false },{ text: "La manière dont un individu entre en relation avec autrui, modelée par ses expériences précoces", isCorrect: true },{ text: "L'attachement pathologique aux biens matériels", isCorrect: false },{ text: "La relation thérapeutique avec un objet transitionnel", isCorrect: false }],
        explanation: "La relation d'objet décrit la façon dont un individu investit affectivement ses objets relationnels (personnes), en lien avec ses premières expériences d'attachement." },
      { text: "Face à un patient qui 'intellectualise' sa maladie, le soignant doit :",
        options: [{ text: "Le corriger et lui rappeler qu'il évite ses émotions", isCorrect: false },{ text: "Reconnaître ce mode défensif et l'accompagner progressivement vers ses émotions", isCorrect: true },{ text: "Ignorer ses questions et parler uniquement des soins techniques", isCorrect: false },{ text: "Lui prescrire immédiatement un soutien psychologique obligatoire", isCorrect: false }],
        explanation: "L'intellectualisation est un mécanisme défensif qui doit être respecté. Le soignant accompagne sans forcer, en créant un espace sécurisant pour l'expression émotionnelle." }
    ]
  },
  {
    title: "Socialisation, identité et représentations sociales de la santé",
    description: "Concepts sociologiques appliqués aux soins infirmiers",
    semester: "Semestre 1", category: "UE 1.1 - Psychologie, sociologie, anthropologie",
    chapter: "Sociologie des soins", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Selon Parsons, quel est le rôle du 'malade' dans la société ?",
        options: [{ text: "Il doit rester actif et ne pas accepter la dispense de ses obligations", isCorrect: false },{ text: "Il bénéficie de droits (dispense) en échange d'obligations (chercher à guérir)", isCorrect: true },{ text: "Il perd tous ses droits civiques pendant la maladie", isCorrect: false },{ text: "Il doit isoler pour ne pas contaminer la société", isCorrect: false }],
        explanation: "Parsons décrit le rôle de malade comme un statut social : 2 droits (dispense des rôles habituels, non-responsabilité) contre 2 obligations (vouloir guérir, consulter un médecin)." },
      { text: "La 'stigmatisation' selon Goffman correspond à :",
        options: [{ text: "Une marque physique permanente sur le corps du patient", isCorrect: false },{ text: "Un processus par lequel un attribut discrédite l'individu et réduit son identité", isCorrect: true },{ text: "L'étiquetage positif des professionnels de santé", isCorrect: false },{ text: "La reconnaissance officielle d'un handicap par l'État", isCorrect: false }],
        explanation: "Pour Goffman, la stigmatisation réduit l'individu à un seul attribut (maladie, handicap, différence) qui le disqualifie socialement et menace son identité." },
      { text: "Les 'inégalités sociales de santé' sont principalement liées à :",
        options: [{ text: "Des différences génétiques entre les classes sociales", isCorrect: false },{ text: "La position sociale, les conditions de vie et l'accès aux soins", isCorrect: true },{ text: "Des comportements individuels irresponsables", isCorrect: false },{ text: "La géographie uniquement", isCorrect: false }],
        explanation: "Les inégalités sociales de santé résultent de déterminants sociaux : revenus, éducation, logement, emploi, accès aux soins. Elles sont systématiques et évitables." },
      { text: "La socialisation primaire se déroule principalement :",
        options: [{ text: "À l'école primaire entre 6 et 11 ans", isCorrect: false },{ text: "Dans la famille durant la petite enfance", isCorrect: true },{ text: "Au travail à l'âge adulte", isCorrect: false },{ text: "Dans le groupe de pairs à l'adolescence", isCorrect: false }],
        explanation: "La socialisation primaire se produit dans la famille durant l'enfance : c'est là que l'individu intègre les normes, valeurs et rôles fondamentaux de sa société." },
      { text: "Qu'est-ce que la 'médicalisation de la société' ?",
        options: [{ text: "L'augmentation du nombre de médecins dans la population", isCorrect: false },{ text: "Le processus par lequel des phénomènes de vie courante sont définis comme problèmes médicaux", isCorrect: true },{ text: "L'obligation de consulter un médecin pour tout problème", isCorrect: false },{ text: "L'amélioration de l'accès aux soins pour tous", isCorrect: false }],
        explanation: "La médicalisation désigne le processus par lequel des expériences normales (naissance, vieillesse, tristesse, obésité) deviennent des problèmes médicaux nécessitant une intervention professionnelle." },
      { text: "Les 'représentations sociales de la maladie' influencent :",
        options: [{ text: "Uniquement les médecins dans leurs diagnostics", isCorrect: false },{ text: "Les comportements de santé des individus et leur recours aux soins", isCorrect: true },{ text: "Seulement les remboursements de la Sécurité Sociale", isCorrect: false },{ text: "La formation des étudiants en soins infirmiers uniquement", isCorrect: false }],
        explanation: "Les représentations sociales (croyances populaires sur la maladie) influencent fortement les comportements : délai de consultation, observance thérapeutique, acceptation du diagnostic." },
      { text: "Le concept de 'capital social' (Bourdieu) en santé désigne :",
        options: [{ text: "Les revenus disponibles pour payer les soins", isCorrect: false },{ text: "Le réseau de relations sociales qui constitue une ressource pour l'individu", isCorrect: true },{ text: "Les diplômes et qualifications professionnelles", isCorrect: false },{ text: "Les biens matériels du patient", isCorrect: false }],
        explanation: "Le capital social correspond au réseau de relations (famille, amis, associations) qui peut constituer une ressource en cas de maladie : soutien moral, aide pratique, information." },
      { text: "L'approche 'biopsychosociale' en soins infirmiers implique :",
        options: [{ text: "Traiter uniquement la dimension biologique de la maladie", isCorrect: false },{ text: "Intégrer les dimensions biologique, psychologique et sociale dans la prise en charge", isCorrect: true },{ text: "Déléguer les aspects psychologiques aux psychiatres uniquement", isCorrect: false },{ text: "Se concentrer sur les examens biologiques et l'imagerie", isCorrect: false }],
        explanation: "Le modèle biopsychosocial d'Engel (1977) invite à considérer l'individu dans sa globalité : corps (bio), vécu (psycho) et environnement social (social)." },
      { text: "Le 'recours aux soins' peut être retardé par :",
        options: [{ text: "Une bonne couverture sociale uniquement", isCorrect: false },{ text: "La peur du diagnostic, la distance géographique ou les croyances culturelles", isCorrect: true },{ text: "Le fait d'avoir un médecin traitant désigné", isCorrect: false },{ text: "Une faible consommation de médicaments", isCorrect: false }],
        explanation: "Le recours aux soins est influencé par de nombreux facteurs : peur du diagnostic, coût, distance, représentations culturelles, confiance dans le système médical." },
      { text: "La 'désaffiliation sociale' peut avoir des conséquences sur la santé car :",
        options: [{ text: "Elle augmente le remboursement des soins", isCorrect: false },{ text: "L'isolement social est un facteur de risque de morbidité et mortalité", isCorrect: true },{ text: "Elle améliore l'autonomie et l'indépendance du patient", isCorrect: false },{ text: "Elle n'a pas d'impact sur la santé physique", isCorrect: false }],
        explanation: "L'isolement social est un facteur de risque majeur : il est associé à une augmentation de la mortalité, des pathologies cardiovasculaires, de la dépression et du déclin cognitif." }
    ]
  },
  {
    title: "Anthropologie, culture et pratiques de soin",
    description: "Diversité culturelle et compétences transculturelles en soins infirmiers",
    semester: "Semestre 1", category: "UE 1.1 - Psychologie, sociologie, anthropologie",
    chapter: "Anthropologie et santé", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Les 3 dimensions anthropologiques de la maladie sont :",
        options: [{ text: "Biologique, chirurgicale et pharmacologique", isCorrect: false },{ text: "Disease (bio), Illness (vécu subjectif), Sickness (construction sociale)", isCorrect: true },{ text: "Aiguë, chronique et terminale", isCorrect: false },{ text: "Physique, mentale et sociale", isCorrect: false }],
        explanation: "Disease = lésion objectivable ; Illness = vécu subjectif du patient ; Sickness = la maladie telle que définie et reconnue socialement et culturellement." },
      { text: "L'ethnocentrisme en soins infirmiers se manifeste quand le soignant :",
        options: [{ text: "Adapte ses soins aux pratiques culturelles du patient", isCorrect: false },{ text: "Juge les pratiques du patient à l'aune de sa propre culture", isCorrect: true },{ text: "Consulte un interprète médical", isCorrect: false },{ text: "Respecte les refus de soins pour raisons religieuses", isCorrect: false }],
        explanation: "L'ethnocentrisme consiste à considérer sa propre culture comme la norme de référence et à évaluer les autres cultures par rapport à elle, souvent négativement." },
      { text: "La 'compétence culturelle' du soignant implique :",
        options: [{ text: "Connaître toutes les cultures du monde", isCorrect: false },{ text: "Reconnaître et respecter les valeurs culturelles du patient pour adapter les soins", isCorrect: true },{ text: "Imposer les normes médicales occidentales", isCorrect: false },{ text: "Ignorer les croyances pour se concentrer sur le traitement", isCorrect: false }],
        explanation: "La compétence culturelle est la capacité à comprendre et intégrer les valeurs, croyances et pratiques culturelles du patient dans la démarche de soin." },
      { text: "Un patient refuse une transfusion sanguine pour des raisons religieuses. Quelle est la bonne attitude ?",
        options: [{ text: "Réaliser la transfusion sans son consentement car sa vie est en danger", isCorrect: false },{ text: "Respecter le refus si le patient est majeur et capable, informer le médecin et proposer des alternatives", isCorrect: true },{ text: "Appeler immédiatement le psychiatre", isCorrect: false },{ text: "Ignorer le refus et contacter la famille", isCorrect: false }],
        explanation: "Le droit au refus de soins est fondamental. Face à un patient majeur et capable, le soignant doit respecter son choix, l'informer des conséquences et chercher des alternatives avec l'équipe médicale." },
      { text: "Les 'rites de passage' dans l'anthropologie médicale sont importants car :",
        options: [{ text: "Ils sont interdits en milieu hospitalier", isCorrect: false },{ text: "Ils marquent les transitions de vie et peuvent influencer le rapport à la maladie et aux soins", isCorrect: true },{ text: "Ils remplacent les traitements médicaux traditionnels", isCorrect: false },{ text: "Ils sont uniquement pratiqués dans les sociétés primitives", isCorrect: false }],
        explanation: "Les rites de passage (naissance, initiation, mariage, mort) structurent les transitions de vie. Les ignorer peut créer des incompréhensions dans la relation de soin." },
      { text: "Le 'relativisme culturel' en soins infirmiers signifie :",
        options: [{ text: "Que toutes les pratiques culturelles doivent être acceptées sans questionnement", isCorrect: false },{ text: "Comprendre les pratiques culturelles dans leur propre contexte sans jugement de valeur", isCorrect: true },{ text: "Que les soins doivent être différents selon la nationalité", isCorrect: false },{ text: "Relativiser l'importance de la culture dans les soins", isCorrect: false }],
        explanation: "Le relativisme culturel est une posture méthodologique qui consiste à comprendre les pratiques dans leur contexte culturel propre avant de les évaluer." },
      { text: "Face à une barrière linguistique avec un patient, le soignant doit privilégier :",
        options: [{ text: "Parler très fort et lentement pour se faire comprendre", isCorrect: false },{ text: "Un interprète professionnel médical plutôt qu'un membre de la famille", isCorrect: true },{ text: "Demander à un autre patient de traduire", isCorrect: false },{ text: "Limiter les informations données pour éviter les malentendus", isCorrect: false }],
        explanation: "Un interprète professionnel médical est préférable car il garantit la confidentialité, la précision médicale et évite les biais liés à l'implication émotionnelle des proches." },
      { text: "Les 'médecines traditionnelles' (phytothérapie, acupuncture, etc.) pratiquées par le patient doivent :",
        options: [{ text: "Être systématiquement interdites pendant l'hospitalisation", isCorrect: false },{ text: "Être identifiées et évaluées pour détecter d'éventuelles interactions avec les traitements", isCorrect: true },{ text: "Être encouragées comme substitut aux traitements conventionnels", isCorrect: false },{ text: "Être ignorées car sans effet scientifiquement prouvé", isCorrect: false }],
        explanation: "Les pratiques de médecine traditionnelle peuvent interagir avec les médicaments (ex : millepertuis et anticoagulants). Le soignant doit les identifier dans l'anamnèse sans jugement." },
      { text: "La 'douleur' est une expérience culturellement influencée car :",
        options: [{ text: "Les seuils de douleur physique varient selon les gènes", isCorrect: false },{ text: "Les cultures influencent la façon d'exprimer, de signifier et de tolérer la douleur", isCorrect: true },{ text: "La douleur n'existe que dans les cultures occidentales", isCorrect: false },{ text: "Les médicaments antalgiques ont des effets variables selon l'ethnie", isCorrect: false }],
        explanation: "L'expression et la signification de la douleur sont culturellement construites. Certaines cultures valorisent la stoïcité, d'autres l'expression émotionnelle. L'IDE doit adapter son évaluation." },
      { text: "Qu'est-ce que l''itinéraire thérapeutique' d'un patient ?",
        options: [{ text: "L'ensemble des services hospitaliers par lesquels passe le patient", isCorrect: false },{ text: "La suite des recours thérapeutiques utilisés par le patient face à sa maladie (tradipraticiens, médecins, etc.)", isCorrect: true },{ text: "Le trajet domicile-hôpital du patient", isCorrect: false },{ text: "Le protocole thérapeutique prescrit par le médecin", isCorrect: false }],
        explanation: "L'itinéraire thérapeutique décrit le parcours du patient à travers différents systèmes de soins : automédication, médecine traditionnelle, médecine conventionnelle. Le comprendre améliore la relation de soin." }
    ]
  },
  {
    title: "Stades du développement : de l'enfant à l'adulte",
    description: "Théories du développement psychologique tout au long de la vie",
    semester: "Semestre 1", category: "UE 1.1 - Psychologie, sociologie, anthropologie",
    chapter: "Psychologie du développement", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Selon Erikson, la crise psychosociale de l'adolescence est :",
        options: [{ text: "Intimité vs Isolement", isCorrect: false },{ text: "Identité vs Confusion des rôles", isCorrect: true },{ text: "Initiative vs Culpabilité", isCorrect: false },{ text: "Industrie vs Infériorité", isCorrect: false }],
        explanation: "Erikson situe à l'adolescence la crise 'Identité vs Confusion des rôles' : le jeune doit construire une identité stable en intégrant ses expériences passées et ses aspirations futures." },
      { text: "L'objet transitionnel (Winnicott) est :",
        options: [{ text: "Un médicament de transition entre deux traitements", isCorrect: false },{ text: "Un objet (doudou, peluche) qui aide l'enfant à tolérer la séparation d'avec sa mère", isCorrect: true },{ text: "Une technique de sevrage du biberon", isCorrect: false },{ text: "L'attachement pathologique à un objet matériel", isCorrect: false }],
        explanation: "L'objet transitionnel de Winnicott (0-2 ans) est un objet investi affectivement qui représente la mère en son absence et aide l'enfant à développer son autonomie psychique." },
      { text: "La 'zone proximale de développement' (Vygotsky) est :",
        options: [{ text: "La zone du cerveau responsable du développement", isCorrect: false },{ text: "L'écart entre ce que l'enfant sait faire seul et avec l'aide d'un adulte", isCorrect: true },{ text: "La période optimale pour commencer la scolarité", isCorrect: false },{ text: "Une zone géographique favorable au développement de l'enfant", isCorrect: false }],
        explanation: "La ZPD est l'espace d'apprentissage optimal où l'enfant peut progresser avec l'aide d'un pair ou d'un adulte. Elle oriente l'enseignement et l'accompagnement éducatif." },
      { text: "Piaget : qu'est-ce que la 'permanence de l'objet' ?",
        options: [{ text: "La capacité à ne pas perdre ses affaires personnelles", isCorrect: false },{ text: "La compréhension qu'un objet existe même quand il n'est plus perçu", isCorrect: true },{ text: "La fixation à un objet particulier dans la petite enfance", isCorrect: false },{ text: "La mémorisation permanente des objets vus", isCorrect: false }],
        explanation: "La permanence de l'objet s'acquiert vers 18-24 mois (fin du stade sensori-moteur) : l'enfant comprend qu'un objet caché continue d'exister, même hors de sa perception." },
      { text: "La 'crise du milieu de vie' (40-50 ans) selon les théories développementales se caractérise par :",
        options: [{ text: "Une augmentation du bien-être et de la satisfaction professionnelle", isCorrect: false },{ text: "Une remise en question de ses choix de vie, valeurs et priorités", isCorrect: true },{ text: "L'apparition systématique d'une dépression nécessitant un traitement", isCorrect: false },{ text: "L'arrêt du développement psychologique", isCorrect: false }],
        explanation: "La crise du milieu de vie est une période de bilan et de questionnement sur le sens de sa vie. Elle peut conduire à des réorientations importantes et à un renouveau personnel." },
      { text: "Chez le nourrisson, l'attachement 'insécure évitant' se caractérise par :",
        options: [{ text: "Un enfant qui pleure excessivement en présence de l'étranger", isCorrect: false },{ text: "Un enfant qui ignore la figure d'attachement lors de retrouvailles", isCorrect: true },{ text: "Un enfant alternant recherche de contact et rejet à l'égard du caregiver", isCorrect: false },{ text: "Un enfant totalement apathique sans réaction visible", isCorrect: false }],
        explanation: "L'attachement insécure évitant : l'enfant a appris que ses besoins ne seront pas satisfaits, il minimise ses émotions et n'exprime pas sa détresse. Il ignore le caregiver au retour." },
      { text: "Le développement moral selon Kohlberg évolue de :",
        options: [{ text: "L'égocentrisme vers l'altruisme pur", isCorrect: false },{ text: "La morale préconventionnelle (punition/récompense) vers la morale postconventionnelle (principes universels)", isCorrect: true },{ text: "L'obéissance absolue vers la désobéissance totale", isCorrect: false },{ text: "La morale religieuse vers la morale laïque", isCorrect: false }],
        explanation: "Kohlberg décrit 3 niveaux : préconventionnel (éviter punition), conventionnel (conformité sociale), postconventionnel (principes éthiques universels). Peu d'adultes atteignent le niveau 3." },
      { text: "Les modifications cognitives du vieillissement normal incluent :",
        options: [{ text: "Une perte totale de la mémoire épisodique", isCorrect: false },{ text: "Un ralentissement du traitement de l'information et une légère baisse de la mémoire de travail", isCorrect: true },{ text: "Une amélioration de la mémoire de travail", isCorrect: false },{ text: "La disparition de la mémoire sémantique", isCorrect: false }],
        explanation: "Le vieillissement normal entraîne un ralentissement cognitif et une légère baisse de la mémoire de travail, mais les mémoires à long terme et sémantique sont globalement préservées." },
      { text: "L'hospitalisation d'un enfant de 2 ans peut entraîner :",
        options: [{ text: "Une accélération de son développement grâce aux stimulations", isCorrect: false },{ text: "Une angoisse de séparation et une régression développementale", isCorrect: true },{ text: "Aucune conséquence psychologique notable à cet âge", isCorrect: false },{ text: "Une amélioration de l'attachement avec les soignants", isCorrect: false }],
        explanation: "L'hospitalisation représente pour l'enfant en bas âge une séparation potentiellement traumatisante. Elle peut engendrer régression, angoisse, refus alimentaire. La présence parentale est essentielle." },
      { text: "L'adolescent hospitalisé a particulièrement besoin :",
        options: [{ text: "D'être traité exactement comme un enfant pour le rassurer", isCorrect: false },{ text: "D'une prise en compte de son identité, de son autonomie et de sa confidentialité", isCorrect: true },{ text: "D'être séparé de ses pairs pour éviter les comportements à risque", isCorrect: false },{ text: "D'une surveillance constante et d'un contrôle strict", isCorrect: false }],
        explanation: "L'adolescent en crise identitaire doit voir son autonomie respectée, ses questions prises au sérieux et la confidentialité assurée. L'IDE adapte sa communication à cette étape de développement." }
    ]
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 1.3 – Législation, éthique, déontologie
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Secret professionnel et droits des patients — approfondissement",
    description: "Cas pratiques sur le secret professionnel et les droits des usagers",
    semester: "Semestre 1", category: "UE 1.3 - Législation, éthique, déontologie",
    chapter: "Droits des usagers", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "Une famille demande à l'IDE des informations sur l'état de santé de leur proche majeur. L'IDE doit :",
        options: [{ text: "Tout communiquer pour rassurer la famille", isCorrect: false },{ text: "Refuser toute information sans l'accord préalable du patient", isCorrect: true },{ text: "Communiquer les informations non confidentielles uniquement", isCorrect: false },{ text: "Orienter vers le médecin sans aucune explication", isCorrect: false }],
        explanation: "Le secret professionnel protège le patient, y compris vis-à-vis de sa famille. Sans accord explicite du patient, l'IDE ne peut communiquer aucune information médicale." },
      { text: "Les directives anticipées sont valables :",
        options: [{ text: "3 ans, puis elles doivent être obligatoirement renouvelées", isCorrect: false },{ text: "Sans limite de durée, sauf si le patient les révoque ou les modifie", isCorrect: true },{ text: "Uniquement pendant l'hospitalisation en cours", isCorrect: false },{ text: "1 an, renouvelable une fois", isCorrect: false }],
        explanation: "Depuis la loi Claeys-Leonetti 2016, les directives anticipées sont valables indéfiniment. Elles s'imposent au médecin sauf en cas d'urgence vitale ou si elles sont inappropriées à la situation." },
      { text: "La personne de confiance peut :",
        options: [{ text: "Prendre des décisions médicales à la place du patient inconscient", isCorrect: false },{ text: "Être consultée et témoigner des volontés du patient s'il ne peut s'exprimer", isCorrect: true },{ text: "Accéder librement au dossier médical du patient", isCorrect: false },{ text: "Modifier les directives anticipées si elle juge que c'est dans l'intérêt du patient", isCorrect: false }],
        explanation: "La personne de confiance n'est pas un représentant légal. Elle est consultée et son témoignage prime sur celui des proches, mais elle ne prend pas de décision à la place du patient." },
      { text: "Le secret médical peut être levé SANS l'accord du patient dans le cas de :",
        options: [{ text: "La demande d'un employeur pour une visite de reprise", isCorrect: false },{ text: "La déclaration obligatoire de certaines maladies (listériose, tuberculose, etc.)", isCorrect: true },{ text: "La curiosité d'un étudiant en médecine en stage", isCorrect: false },{ text: "L'enquête d'un journaliste sur les conditions d'hospitalisation", isCorrect: false }],
        explanation: "Les maladies à déclaration obligatoire (DO) permettent de lever partiellement le secret médical dans l'intérêt de la santé publique. La liste est fixée par décret." },
      { text: "Le droit d'accès au dossier médical : quel est le délai légal de communication ?",
        options: [{ text: "Immédiatement sur demande orale", isCorrect: false },{ text: "8 jours (48h si hospitalisation datant de moins de 5 jours)", isCorrect: true },{ text: "1 mois pour toute demande", isCorrect: false },{ text: "3 mois pour les dossiers complexes", isCorrect: false }],
        explanation: "Loi Kouchner 2002 : le délai est de 8 jours à partir de la demande (48h si hospitalisation récente < 5 jours). Le dossier peut être consulté sur place ou envoyé par courrier." },
      { text: "Face au refus de soins d'un patient majeur conscient, l'IDE doit :",
        options: [{ text: "Réaliser le soin malgré tout car c'est dans l'intérêt du patient", isCorrect: false },{ text: "Respecter le refus, informer sur les conséquences, tracer et prévenir le médecin", isCorrect: true },{ text: "Appeler immédiatement les urgences pour hospitalisation sous contrainte", isCorrect: false },{ text: "Laisser le patient sans aucune information supplémentaire", isCorrect: false }],
        explanation: "Le refus de soins d'un patient majeur et conscient doit être respecté (autonomie). L'IDE informe des risques, le patient signe un refus de soins, l'IDE trace et prévient le médecin." },
      { text: "La loi Kouchner (2002) a notamment introduit :",
        options: [{ text: "La sédation profonde et continue en fin de vie", isCorrect: false },{ text: "Le droit à l'information, le consentement éclairé et la personne de confiance", isCorrect: true },{ text: "L'interdiction de l'acharnement thérapeutique", isCorrect: false },{ text: "La création de l'Ordre National des Infirmiers", isCorrect: false }],
        explanation: "La loi du 4 mars 2002 (Kouchner) est la grande loi sur les droits des malades : droit à l'information, consentement éclairé, personne de confiance, accès au dossier médical." },
      { text: "Un mineur de 16 ans peut-il consentir seul à ses soins ?",
        options: [{ text: "Non, jamais avant 18 ans", isCorrect: false },{ text: "Oui, pour certains soins (contraception, IVG, addictions) s'il souhaite garder le secret vis-à-vis de ses parents", isCorrect: true },{ text: "Oui, pour tous les soins dès 16 ans", isCorrect: false },{ text: "Oui, uniquement en situation d'urgence vitale", isCorrect: false }],
        explanation: "La loi prévoit des exceptions permettant au mineur de consulter seul et en secret pour : contraception, IVG, dépistage VIH, prise en charge des addictions. Cela protège son accès aux soins." },
      { text: "La 'maltraitance' sur personne vulnérable doit être signalée :",
        options: [{ text: "Uniquement si l'IDE en est témoin direct", isCorrect: false },{ text: "Dès qu'il existe des raisons plausibles de le croire, sans certitude absolue requise", isCorrect: true },{ text: "Uniquement après l'accord de l'équipe médicale complète", isCorrect: false },{ text: "Jamais, car cela viole le secret professionnel", isCorrect: false }],
        explanation: "L'article 226-14 du Code Pénal lève le secret professionnel pour les signalements de maltraitance sur mineurs ou personnes vulnérables. La certitude absolue n'est pas exigée : les présomptions suffisent." },
      { text: "L'information médicale doit être délivrée par le médecin de manière :",
        options: [{ text: "Systématiquement écrite et en présence d'un témoin", isCorrect: false },{ text: "Loyale, claire, appropriée et adaptée à la capacité de compréhension du patient", isCorrect: true },{ text: "Uniquement technique sans aspect émotionnel", isCorrect: false },{ text: "Complète d'emblée sans tenir compte de l'état du patient", isCorrect: false }],
        explanation: "L'information doit être loyale (vraie), claire (compréhensible), appropriée (adaptée à la situation) et délivrée de manière humaine, tenant compte du rythme et de l'état du patient." }
    ]
  },
  {
    title: "Éthique clinique avancée et fin de vie",
    description: "Dilemmes éthiques, loi Claeys-Leonetti et décisions de fin de vie",
    semester: "Semestre 1", category: "UE 1.3 - Législation, éthique, déontologie",
    chapter: "Éthique médicale", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "La loi Claeys-Leonetti (2016) autorise pour les patients en fin de vie :",
        options: [{ text: "L'euthanasie active sur demande du patient", isCorrect: false },{ text: "La sédation profonde et continue jusqu'au décès, associée à l'arrêt des traitements", isCorrect: true },{ text: "Le suicide assisté par un médecin", isCorrect: false },{ text: "La mise en sommeil artificiel pour une durée indéterminée", isCorrect: false }],
        explanation: "La loi Claeys-Leonetti 2016 instaure le droit à la sédation profonde et continue jusqu'au décès pour les patients dont le pronostic vital est engagé à court terme, souffrant de symptômes réfractaires." },
      { text: "L'obstination déraisonnable (acharnement thérapeutique) est définie comme :",
        options: [{ text: "Tout traitement curatif appliqué à un patient âgé", isCorrect: false },{ text: "Des traitements inutiles, disproportionnés ou n'ayant d'autre effet que le maintien artificiel de la vie", isCorrect: true },{ text: "Le refus de soulager la douleur par crainte des effets indésirables", isCorrect: false },{ text: "La prolongation de la vie par tout moyen disponible", isCorrect: false }],
        explanation: "L'art. L1110-5-1 du CSP interdit l'obstination déraisonnable : les traitements qui n'ont pas d'autre effet que le maintien artificiel de la vie ou qui sont manifestement disproportionnés." },
      { text: "Le principe de 'double effet' en éthique médicale s'applique quand :",
        options: [{ text: "Un traitement a exactement 2 effets positifs", isCorrect: false },{ text: "Un acte bénéfique a un effet néfaste prévisible mais non intentionnel et proportionné", isCorrect: true },{ text: "Deux médecins prescrivent le même traitement simultanément", isCorrect: false },{ text: "Un médicament a des effets différents selon le patient", isCorrect: false }],
        explanation: "Le double effet (ex : morphine forte dose qui soulage ET peut raccourcir la vie) est éthiquement acceptable si : intention bonne, effet néfaste non intentionnel, bénéfice proportionné au risque." },
      { text: "La démarche collégiale en fin de vie réunit obligatoirement :",
        options: [{ text: "Uniquement le médecin référent et l'infirmière coordinatrice", isCorrect: false },{ text: "L'équipe soignante, un médecin consultant, la personne de confiance, et tient compte des directives anticipées", isCorrect: true },{ text: "La famille et le patient uniquement", isCorrect: false },{ text: "Un jury de 12 médecins comme dans un procès", isCorrect: false }],
        explanation: "La démarche collégiale est obligatoire avant toute décision de LAT (Limitation et Arrêt des Thérapeutiques). Elle intègre l'équipe soignante, un consultant externe, et respecte les directives anticipées et la personne de confiance." },
      { text: "Le principe de 'non-malfaisance' (primum non nocere) implique pour l'IDE :",
        options: [{ text: "De ne jamais administrer de médicaments ayant des effets secondaires", isCorrect: false },{ text: "D'évaluer systématiquement bénéfices/risques avant tout acte de soin", isCorrect: true },{ text: "De refuser tout soin invasif", isCorrect: false },{ text: "De prioriser le confort du soignant pour éviter les erreurs", isCorrect: false }],
        explanation: "La non-malfaisance oblige à peser les bénéfices et les risques de chaque acte. Un soin peut avoir des inconvénients mais est justifié si le bénéfice est proportionné." },
      { text: "La 'clause de conscience' permet à un soignant de :",
        options: [{ text: "Refuser n'importe quel soin sans justification", isCorrect: false },{ text: "Refuser un acte légal contraire à ses convictions, sous condition d'orienter le patient", isCorrect: true },{ text: "Imposer ses convictions morales au patient", isCorrect: false },{ text: "Ignorer les directives institutionnelles qu'il juge non éthiques", isCorrect: false }],
        explanation: "La clause de conscience permet de refuser un acte légal (ex : IVG) contraire à ses convictions personnelles, MAIS le soignant a l'obligation d'orienter immédiatement le patient vers un autre professionnel." },
      { text: "En éthique, l'autonomie du patient signifie :",
        options: [{ text: "Que le patient doit être laissé seul pour prendre ses décisions", isCorrect: false },{ text: "Le droit du patient à prendre des décisions éclairées concernant sa santé", isCorrect: true },{ text: "Que le médecin suit toujours les volontés du patient même dangereuses", isCorrect: false },{ text: "L'indépendance physique totale du patient", isCorrect: false }],
        explanation: "L'autonomie (Beauchamp & Childress) est le droit fondamental du patient à prendre des décisions concernant sa santé, à condition d'être correctement informé et capable de discernement." },
      { text: "Qu'est-ce que la 'bientraitance' dans les soins ?",
        options: [{ text: "L'absence totale de maltraitance", isCorrect: false },{ text: "Une culture soignante active qui place la personne au centre, au-delà de l'absence de maltraitance", isCorrect: true },{ text: "La gentillesse naturelle du soignant", isCorrect: false },{ text: "Le respect strict des protocoles de soins", isCorrect: false }],
        explanation: "La bientraitance est une démarche proactive qui va au-delà de l'absence de maltraitance : elle implique respect de la dignité, personnalisation des soins, attention au bien-être global." },
      { text: "Un soignant témoin d'une maltraitance commise par un collègue doit :",
        options: [{ text: "Régler le problème entre collègues sans en parler à l'institution", isCorrect: false },{ text: "Alerter immédiatement la hiérarchie et, si nécessaire, effectuer un signalement", isCorrect: true },{ text: "Attendre de voir si cela se reproduit avant d'agir", isCorrect: false },{ text: "Confronter seul le collègue concerné sans impliquer la hiérarchie", isCorrect: false }],
        explanation: "Le soignant a l'obligation légale et déontologique de signaler toute maltraitance. Le silence est une complicité passive. La voie hiérarchique est prioritaire, suivie si nécessaire du signalement judiciaire." },
      { text: "La justice (4e principe de Beauchamp & Childress) en soins infirmiers implique :",
        options: [{ text: "Que tous les patients reçoivent exactement le même traitement", isCorrect: false },{ text: "Une répartition équitable des ressources et des soins selon les besoins de chacun", isCorrect: true },{ text: "Que les soignants soient rémunérés équitablement", isCorrect: false },{ text: "L'application stricte du droit sans exception", isCorrect: false }],
        explanation: "La justice implique l'équité dans l'accès et la distribution des soins en fonction des besoins réels de chaque patient, pas d'un traitement uniforme ignorant les différences." }
    ]
  },
  {
    title: "Responsabilité infirmière : fautes, sanctions et pratique sûre",
    description: "Types de responsabilité, erreurs médicamenteuses et gestion des risques",
    semester: "Semestre 1", category: "UE 1.3 - Législation, éthique, déontologie",
    chapter: "Responsabilité juridique", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "Une infirmière administre un médicament prescrit sans vérifier l'identité du patient. Il y a confusion et le patient reçoit un médicament qui n'est pas le sien. Quelle responsabilité est engagée ?",
        options: [{ text: "Uniquement la responsabilité du médecin prescripteur", isCorrect: false },{ text: "La responsabilité civile et potentiellement pénale de l'IDE", isCorrect: true },{ text: "Aucune, car la prescription médicale est correcte", isCorrect: false },{ text: "Uniquement la responsabilité de l'hôpital", isCorrect: false }],
        explanation: "L'IDE a l'obligation de vérifier l'identité du patient avant toute administration (règle des 5B). L'erreur d'identité engage sa responsabilité civile (dommage) et potentiellement pénale (mise en danger d'autrui)." },
      { text: "La 'faute de service' en secteur public hospitalier engage la responsabilité de :",
        options: [{ text: "L'agent fautif personnellement", isCorrect: false },{ text: "L'établissement de santé", isCorrect: true },{ text: "L'État central uniquement", isCorrect: false },{ text: "Le Conseil de l'Ordre des infirmiers", isCorrect: false }],
        explanation: "En secteur public, la faute de service (non détachable de la mission) engage la responsabilité de l'établissement de santé (hôpital), qui peut ensuite se retourner contre l'agent en cas de faute personnelle détachable." },
      { text: "Qu'est-ce qu'un EIAS (Événement Indésirable Associé aux Soins) ?",
        options: [{ text: "Uniquement un accident grave ayant entraîné le décès", isCorrect: false },{ text: "Tout événement inattendu lié aux soins ayant causé ou risqué de causer un dommage au patient", isCorrect: true },{ text: "Un incident concernant uniquement les médicaments", isCorrect: false },{ text: "Un événement déclarable uniquement par les médecins", isCorrect: false }],
        explanation: "Un EIAS (ou EIG — Événement Indésirable Grave) désigne tout événement lié aux soins, prévu ou imprévu, ayant entraîné ou risqué d'entraîner un dommage. Le déclaration est non punitive et vise l'amélioration." },
      { text: "La traçabilité dans le dossier patient est importante car :",
        options: [{ text: "Elle permet d'augmenter la rémunération des soignants", isCorrect: false },{ text: "Elle constitue une preuve légale : 'ce qui n'est pas tracé est réputé ne pas avoir été fait'", isCorrect: true },{ text: "Elle est uniquement utile pour les statistiques hospitalières", isCorrect: false },{ text: "Elle permet d'augmenter le score de qualité de l'hôpital", isCorrect: false }],
        explanation: "La traçabilité a valeur de preuve médicolégale. En cas de litige, un soin non documenté est considéré comme non réalisé, même s'il l'a réellement été." },
      { text: "L'IDE peut-il refuser d'exécuter une prescription médicale ?",
        options: [{ text: "Jamais, le médecin a toujours autorité absolue", isCorrect: false },{ text: "Oui, si la prescription lui semble dangereuse — il doit le signaler au prescripteur et tracer son refus", isCorrect: true },{ text: "Oui, à tout moment et pour n'importe quelle raison personnelle", isCorrect: false },{ text: "Uniquement s'il a l'accord écrit du médecin-chef", isCorrect: false }],
        explanation: "L'IDE a un devoir d'alerte et peut refuser une prescription manifestement dangereuse. Il doit contacter le prescripteur, ne pas exécuter si le danger est confirmé, et tracer son refus dans le dossier." },
      { text: "La responsabilité pénale de l'IDE peut être engagée en cas de :",
        options: [{ text: "Retard dans l'administration d'un médicament non urgent", isCorrect: false },{ text: "Homicide involontaire, mise en danger d'autrui ou non-assistance à personne en danger", isCorrect: true },{ text: "Toute erreur médicale, même mineure", isCorrect: false },{ text: "Désaccord avec les directives institutionnelles", isCorrect: false }],
        explanation: "La responsabilité pénale sanctionne les infractions : homicide involontaire (imprudence grave), blessures involontaires, mise en danger délibérée, non-assistance à personne en danger." },
      { text: "En cas d'AES (Accident d'Exposition au Sang), l'IDE doit :",
        options: [{ text: "Attendre 24h pour voir si une infection se développe", isCorrect: false },{ text: "Soins locaux immédiats, déclaration en accident de travail sous 24h, évaluation TPE VIH < 4h", isCorrect: true },{ text: "Continuer le soin et déclarer à la fin de la semaine", isCorrect: false },{ text: "Prévenir uniquement le patient source", isCorrect: false }],
        explanation: "Protocole AES : 1) soins locaux (nettoyage, antisepsie) ; 2) déclaration AT < 24h ; 3) évaluation du risque VIH et TPE si indiqué (< 4h) ; 4) sérologies patient source et IDE ; 5) suivi 3-6 mois." },
      { text: "Le DPC (Développement Professionnel Continu) est :",
        options: [{ text: "Facultatif pour les infirmières ayant plus de 20 ans d'expérience", isCorrect: false },{ text: "Une obligation légale pour tous les professionnels de santé tout au long de leur carrière", isCorrect: true },{ text: "Obligatoire uniquement pour les infirmières de réanimation", isCorrect: false },{ text: "Remplacé par l'e-learning depuis 2020", isCorrect: false }],
        explanation: "Le DPC est une obligation légale pour tous les professionnels de santé (art. L4021-1 CSP). Il associe formation, évaluation des pratiques et gestion des risques pour maintenir et développer les compétences." },
      { text: "Une IDE travaillant en libéral engage sa responsabilité :",
        options: [{ text: "Via son employeur comme en milieu hospitalier", isCorrect: false },{ text: "À titre personnel : responsabilité civile professionnelle couverte par une assurance obligatoire", isCorrect: true },{ text: "Elle est protégée par le secret professionnel dans tous les cas", isCorrect: false },{ text: "Uniquement si elle n'a pas de prescription médicale", isCorrect: false }],
        explanation: "L'IDE libéral exerce en nom propre. Sa responsabilité civile professionnelle est personnelle et doit obligatoirement être couverte par une assurance RCP (responsabilité civile professionnelle)." },
      { text: "La 'délégation de tâches' à une aide-soignante par l'IDE implique que :",
        options: [{ text: "L'IDE n'est plus responsable une fois la tâche déléguée", isCorrect: false },{ text: "L'IDE reste responsable du choix de la délégation et de la supervision", isCorrect: true },{ text: "L'aide-soignante assume seule la responsabilité de l'acte délégué", isCorrect: false },{ text: "Toute délégation est interdite sauf autorisation médicale écrite", isCorrect: false }],
        explanation: "L'IDE peut déléguer des actes dans le cadre réglementaire, mais reste responsable de la pertinence de la délégation, de la vérification des compétences et de la supervision de l'aide-soignante." }
    ]
  },
  {
    title: "Code de déontologie infirmier — applications pratiques",
    description: "Applications concrètes du code de déontologie dans la pratique quotidienne",
    semester: "Semestre 1", category: "UE 1.3 - Législation, éthique, déontologie",
    chapter: "Déontologie infirmière", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Le code de déontologie infirmier est intégré dans :",
        options: [{ text: "Le Code du travail", isCorrect: false },{ text: "Le Code de la santé publique (décret du 25 novembre 2016)", isCorrect: true },{ text: "Le Code civil", isCorrect: false },{ text: "Le règlement intérieur de chaque hôpital", isCorrect: false }],
        explanation: "Le code de déontologie infirmier a été intégré dans le Code de la santé publique par décret du 25 novembre 2016 (art. R4312-1 à R4312-92), lui donnant force réglementaire." },
      { text: "L'IDE doit exercer ses fonctions avec :",
        options: [{ text: "L'efficacité maximale au détriment du bien-être du patient si nécessaire", isCorrect: false },{ text: "Conscience, dévouement et compétence, en respectant la dignité des personnes", isCorrect: true },{ text: "Une neutralité émotionnelle totale sans empathie", isCorrect: false },{ text: "Une obéissance absolue aux prescriptions sans esprit critique", isCorrect: false }],
        explanation: "Le code de déontologie impose à l'IDE d'exercer avec conscience, dévouement et compétence, dans le respect de la vie et de la dignité de chaque personne." },
      { text: "Face à un conflit avec un collègue sur la prise en charge d'un patient, l'IDE doit :",
        options: [{ text: "Imposer sa propre décision car elle connaît mieux le patient", isCorrect: false },{ text: "Rechercher une solution concertée dans l'intérêt du patient, en impliquant si nécessaire la hiérarchie", isCorrect: true },{ text: "Éviter tout conflit en cédant systématiquement", isCorrect: false },{ text: "Documenter le conflit sans chercher à le résoudre", isCorrect: false }],
        explanation: "La déontologie impose la concertation et le travail en équipe dans l'intérêt du patient. En cas de désaccord persistant, la hiérarchie ou la direction des soins peut être sollicitée." },
      { text: "Le devoir de signalement de l'IDE s'applique :",
        options: [{ text: "Uniquement pour les maladies infectieuses contagieuses", isCorrect: false },{ text: "Pour toute situation mettant en danger la santé ou la sécurité du patient", isCorrect: true },{ text: "Exclusivement pour les décès inattendus", isCorrect: false },{ text: "Seulement sur demande explicite du médecin", isCorrect: false }],
        explanation: "L'IDE a un devoir de signalement (art. R4312-20 CSP) pour toute situation mettant en danger le patient, y compris les pratiques à risque de collègues ou des conditions de soin inadaptées." },
      { text: "L'IDE doit refuser de participer à :",
        options: [{ text: "Tout acte auquel le patient n'a pas consenti explicitement par écrit", isCorrect: false },{ text: "Tout acte portant atteinte à la dignité humaine ou contraire à la déontologie", isCorrect: true },{ text: "Les soins aux patients difficiles ou agressifs", isCorrect: false },{ text: "Les gardes supplémentaires non rémunérées", isCorrect: false }],
        explanation: "Le code de déontologie interdit à l'IDE de participer à tout acte portant atteinte à la dignité humaine, même sous pression hiérarchique (ex : participation à des actes de maltraitance)." },
      { text: "La formation continue est pour l'IDE :",
        options: [{ text: "Une option personnelle sans obligation légale", isCorrect: false },{ text: "Une obligation déontologique et légale pour maintenir ses compétences", isCorrect: true },{ text: "Obligatoire uniquement après 10 ans de pratique", isCorrect: false },{ text: "Financée exclusivement par l'IDE lui-même", isCorrect: false }],
        explanation: "Art. R4312-10 CSP : l'IDE a l'obligation de maintenir et développer ses compétences tout au long de sa carrière. Cette obligation déontologique est renforcée par le DPC (obligation légale)." },
      { text: "Un IDE peut-il exercer une activité commerciale liée à son activité professionnelle ?",
        options: [{ text: "Oui, librement, c'est une source de revenus complémentaires", isCorrect: false },{ text: "Non, tout acte commercial lié à sa pratique est interdit par le code de déontologie", isCorrect: true },{ text: "Oui, sous réserve de déclaration à l'Ordre des infirmiers", isCorrect: false },{ text: "Oui, uniquement pour les produits de para-pharmacie", isCorrect: false }],
        explanation: "Le code de déontologie interdit tout acte de commerce lié à la profession infirmière (vente de produits, publicité commerciale) pour éviter tout conflit d'intérêt et protéger l'indépendance professionnelle." },
      { text: "L'IDE doit informer le patient sur :",
        options: [{ text: "Uniquement les effets secondaires graves des médicaments", isCorrect: false },{ text: "Les soins, leur déroulement, les alternatives possibles et les risques prévisibles", isCorrect: true },{ text: "Tout ce que le patient demande, y compris le diagnostic médical", isCorrect: false },{ text: "Seulement les aspects techniques des soins infirmiers", isCorrect: false }],
        explanation: "L'IDE informe le patient sur les soins infirmiers qu'il prodigue : objectifs, déroulement, risques prévisibles. L'information médicale (diagnostic, pronostic) relève du médecin." },
      { text: "Face à un patient qui lui offre un cadeau onéreux, l'IDE doit :",
        options: [{ text: "L'accepter pour ne pas blesser le patient", isCorrect: false },{ text: "Décliner poliment en expliquant les règles déontologiques", isCorrect: true },{ text: "L'accepter et le déclarer à la direction", isCorrect: false },{ text: "L'accepter uniquement si la valeur ne dépasse pas 50€", isCorrect: false }],
        explanation: "Le code de déontologie interdit d'accepter des cadeaux pouvant influencer la relation de soin ou créer un sentiment d'obligation. L'IDE décline avec tact, sans blesser le patient." },
      { text: "Le rôle de l'Ordre National des Infirmiers (ONI) est :",
        options: [{ text: "Gérer les salaires et conditions de travail des infirmières", isCorrect: false },{ text: "Veiller au respect de la déontologie et défendre l'honneur et l'indépendance de la profession", isCorrect: true },{ text: "Organiser les concours d'entrée en IFSI", isCorrect: false },{ text: "Prescrire les formations obligatoires aux infirmières", isCorrect: false }],
        explanation: "L'ONI (créé par loi 2006) est chargé de veiller au respect du code de déontologie, d'assurer la défense de l'honneur et de l'indépendance de la profession, et de tenir le tableau de l'ordre." }
    ]
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 2.1 – Biologie fondamentale
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Cycle cellulaire, division et génétique",
    description: "Mitose, méiose, hérédité et maladies génétiques",
    semester: "Semestre 1", category: "UE 2.1 - Biologie fondamentale",
    chapter: "Génétique fondamentale", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "La cellule humaine normale contient :",
        options: [{ text: "23 chromosomes", isCorrect: false },{ text: "46 chromosomes (23 paires)", isCorrect: true },{ text: "48 chromosomes", isCorrect: false },{ text: "44 chromosomes + 2 gonosomes", isCorrect: false }],
        explanation: "La cellule humaine diploïde (2n) contient 46 chromosomes : 22 paires d'autosomes + 1 paire de gonosomes (XX chez la femme, XY chez l'homme)." },
      { text: "Lors de la méiose, le nombre de chromosomes :",
        options: [{ text: "Reste à 46 dans les cellules filles", isCorrect: false },{ text: "Est réduit de moitié : les gamètes ont 23 chromosomes (n)", isCorrect: true },{ text: "Double pour donner des cellules à 92 chromosomes", isCorrect: false },{ text: "Varie selon le sexe de l'individu", isCorrect: false }],
        explanation: "La méiose est une division réductionnelle : à partir d'une cellule à 2n=46, elle produit 4 gamètes haploïdes à n=23 chromosomes." },
      { text: "La trisomie 21 (syndrome de Down) résulte de :",
        options: [{ text: "Une délétion du chromosome 21", isCorrect: false },{ text: "La présence d'un chromosome 21 surnuméraire (3 au lieu de 2)", isCorrect: true },{ text: "Une mutation ponctuelle sur le gène 21", isCorrect: false },{ text: "L'absence d'un chromosome 21", isCorrect: false }],
        explanation: "La trisomie 21 est due à une non-disjonction lors de la méiose : une paire de chromosomes 21 ne se sépare pas, donnant un gamète avec 2 chromosomes 21. L'embryon en a donc 3." },
      { text: "La mucoviscidose est une maladie :",
        options: [{ text: "Autosomale dominante liée au chromosome X", isCorrect: false },{ text: "Autosomale récessive due à une mutation du gène CFTR", isCorrect: true },{ text: "Mitochondriale transmise par la mère uniquement", isCorrect: false },{ text: "Chromosomique par trisomie", isCorrect: false }],
        explanation: "La mucoviscidose est autosomale récessive (chromosome 7, gène CFTR). Deux copies mutées sont nécessaires. Risque de 25% si les deux parents sont porteurs hétérozygotes." },
      { text: "La drépanocytose est une maladie causée par :",
        options: [{ text: "Un déficit en facteur VIII de coagulation", isCorrect: false },{ text: "Une mutation de l'hémoglobine (HbS) entraînant une déformation des globules rouges en faucille", isCorrect: true },{ text: "L'absence de plaquettes sanguines", isCorrect: false },{ text: "Un excès de fer dans le sang", isCorrect: false }],
        explanation: "La drépanocytose est une mutation ponctuelle du gène de la β-globine (HbS). Les GR en faucille obstruent les capillaires (crises vaso-occlusives) et se détruisent (anémie hémolytique)." },
      { text: "Le phénomène d'épigenèse correspond à :",
        options: [{ text: "Une mutation permanente et irréversible de l'ADN", isCorrect: false },{ text: "Des modifications de l'expression des gènes sans altération de la séquence d'ADN", isCorrect: true },{ text: "La synthèse d'une nouvelle protéine à partir de rien", isCorrect: false },{ text: "La duplication complète du génome", isCorrect: false }],
        explanation: "L'épigénétique étudie les modifications héréditaires de l'expression génique sans changement de séquence ADN (méthylation, histones). L'environnement peut modifier l'expression des gènes." },
      { text: "Les maladies liées au chromosome X (hémophilie A) touchent préférentiellement :",
        options: [{ text: "Les femmes car elles ont 2 chromosomes X", isCorrect: false },{ text: "Les hommes car ils n'ont qu'un seul chromosome X (pas de compensation possible)", isCorrect: true },{ text: "Les deux sexes de façon égale", isCorrect: false },{ text: "Uniquement les enfants nés de deux parents atteints", isCorrect: false }],
        explanation: "Les maladies récessives liées à l'X touchent les hommes (XY) : une seule copie mutée suffit. Les femmes (XX) sont protégées par leur deuxième chromosome X sain (conductrices)." },
      { text: "La réplication de l'ADN se produit :",
        options: [{ text: "Lors de la mitose uniquement", isCorrect: false },{ text: "En phase S de l'interphase, avant la division cellulaire", isCorrect: true },{ text: "Après la division cellulaire pour reconstituer les stocks", isCorrect: false },{ text: "Uniquement dans les cellules souches", isCorrect: false }],
        explanation: "La réplication de l'ADN se produit en phase S (Synthèse) de l'interphase, avant la division cellulaire. Chaque brin sert de matrice pour créer un nouveau double brin (réplication semi-conservative)." },
      { text: "Un gène suppresseur de tumeur (p53) a pour rôle :",
        options: [{ text: "D'accélérer la division cellulaire", isCorrect: false },{ text: "De contrôler le cycle cellulaire et d'induire l'apoptose en cas d'anomalie", isCorrect: true },{ text: "De stimuler la croissance tumorale", isCorrect: false },{ text: "De bloquer la synthèse des protéines", isCorrect: false }],
        explanation: "p53 est le 'gardien du génome' : il détecte les dommages à l'ADN, bloque le cycle cellulaire pour permettre la réparation et déclenche l'apoptose si la réparation est impossible." },
      { text: "L'amniocentèse est un examen prénatal qui analyse :",
        options: [{ text: "Le sang maternel pour détecter les anomalies chromosomiques", isCorrect: false },{ text: "Les cellules fœtales présentes dans le liquide amniotique", isCorrect: true },{ text: "Les anticorps maternels anti-fœtaux", isCorrect: false },{ text: "La morphologie fœtale par échographie", isCorrect: false }],
        explanation: "L'amniocentèse (15-18 SA) prélève du liquide amniotique contenant des cellules fœtales. L'analyse cytogénétique permet de détecter des anomalies chromosomiques (trisomies, délétions)." }
    ]
  },
  {
    title: "Métabolisme, homéostasie et biochimie clinique",
    description: "Régulations métaboliques, pH et valeurs biologiques normales",
    semester: "Semestre 1", category: "UE 2.1 - Biologie fondamentale",
    chapter: "Biochimie", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "L'acidose métabolique se caractérise par :",
        options: [{ text: "pH > 7,45 et HCO₃⁻ élevé", isCorrect: false },{ text: "pH < 7,35 et HCO₃⁻ bas", isCorrect: true },{ text: "pH < 7,35 et PaCO₂ élevée", isCorrect: false },{ text: "pH > 7,45 et PaCO₂ basse", isCorrect: false }],
        explanation: "L'acidose métabolique : pH < 7,35 avec HCO₃⁻ < 22 mmol/L (perte de bases ou accumulation d'acides). Causes : insuffisance rénale, diarrhée, acidocétose diabétique." },
      { text: "L'hyperglycémie chronique dans le diabète entraîne des complications par :",
        options: [{ text: "Un déficit en insuline uniquement", isCorrect: false },{ text: "La glycation des protéines et l'altération des vaisseaux sanguins (angiopathie)", isCorrect: true },{ text: "Une augmentation du cholestérol", isCorrect: false },{ text: "Une diminution de la glycolyse", isCorrect: false }],
        explanation: "L'hyperglycémie chronique provoque la glycation des protéines (HbA1c, protéines vasculaires) entraînant des complications micro- (rétinopathie, néphropathie) et macro-vasculaires (AVC, IDM)." },
      { text: "La créatinine plasmatique est un marqueur de :",
        options: [{ text: "La fonction hépatique", isCorrect: false },{ text: "La fonction rénale (filtration glomérulaire)", isCorrect: true },{ text: "L'inflammation systémique", isCorrect: false },{ text: "La masse musculaire uniquement", isCorrect: false }],
        explanation: "La créatinine est éliminée par filtration glomérulaire. Son élévation plasmatique traduit une insuffisance rénale. Normale : H 60-110 µmol/L, F 45-90 µmol/L." },
      { text: "L'urée sanguine élevée (urémie) peut indiquer :",
        options: [{ text: "Un excès de protéines alimentaires uniquement", isCorrect: false },{ text: "Une insuffisance rénale, une déshydratation ou un catabolisme protéique excessif", isCorrect: true },{ text: "Un diabète de type 2", isCorrect: false },{ text: "Un déficit en vitamines", isCorrect: false }],
        explanation: "L'urée provient du catabolisme protéique. Elle est éliminée par le rein. Son élévation peut être due à une insuffisance rénale, une déshydratation, un régime hyperprotéique ou un hypercatabolisme." },
      { text: "Le taux de protéines C-réactive (CRP) est un marqueur de :",
        options: [{ text: "La fonction rénale", isCorrect: false },{ text: "L'inflammation (synthèse hépatique en réponse aux cytokines)", isCorrect: true },{ text: "La coagulation sanguine", isCorrect: false },{ text: "L'équilibre acido-basique", isCorrect: false }],
        explanation: "La CRP est synthétisée par le foie en réponse aux cytokines inflammatoires (IL-6). Elle augmente dans toutes les inflammations (infection, nécrose tissulaire). Normale < 5 mg/L." },
      { text: "La kaliémie normale est de :",
        options: [{ text: "135–145 mmol/L", isCorrect: false },{ text: "3,5–5,0 mmol/L", isCorrect: true },{ text: "0,8–1,2 mmol/L", isCorrect: false },{ text: "8,5–10,5 mg/dL", isCorrect: false }],
        explanation: "La kaliémie normale est de 3,5–5,0 mmol/L. L'hypokaliémie (< 3,5) expose aux arythmies et faiblesse musculaire. L'hyperkaliémie (> 5,0) est potentiellement mortelle (fibrillation ventriculaire)." },
      { text: "L'HbA1c (hémoglobine glyquée) reflète :",
        options: [{ text: "La glycémie du jour de la prise de sang", isCorrect: false },{ text: "L'équilibre glycémique moyen des 2–3 derniers mois", isCorrect: true },{ text: "Le taux d'insuline sécrété sur 24 heures", isCorrect: false },{ text: "La réserve de glycogène hépatique", isCorrect: false }],
        explanation: "L'HbA1c reflète la glycation de l'hémoglobine sur la durée de vie des GR (120 jours). Elle traduit l'équilibre glycémique des 2-3 derniers mois. Objectif diabétique : < 7% (53 mmol/mol)." },
      { text: "Les triglycérides sont principalement stockés dans :",
        options: [{ text: "Le foie sous forme de glycogène", isCorrect: false },{ text: "Le tissu adipeux sous forme de lipides de réserve", isCorrect: true },{ text: "Les muscles sous forme d'ATP", isCorrect: false },{ text: "Les os sous forme de calcium", isCorrect: false }],
        explanation: "Les triglycérides (lipides de réserve) sont stockés dans les adipocytes du tissu adipeux. Lors d'un jeûne, la lipolyse libère des acides gras utilisés comme source d'énergie." },
      { text: "La phosphatase alcaline (PAL) élevée peut traduire :",
        options: [{ text: "Une atteinte rénale aiguë", isCorrect: false },{ text: "Une atteinte hépatique ou osseuse (isoenzymes différentes)", isCorrect: true },{ text: "Un déficit en vitamines du groupe B", isCorrect: false },{ text: "Une infection virale systémique", isCorrect: false }],
        explanation: "La PAL a plusieurs isoenzymes : hépatique (cholestase) et osseuse (remodelage osseux, maladie de Paget, métastases osseuses). L'identification de l'isoenzyme permet d'orienter le diagnostic." },
      { text: "La valeur normale de la natrémie est :",
        options: [{ text: "3,5–5,0 mmol/L", isCorrect: false },{ text: "135–145 mmol/L", isCorrect: true },{ text: "95–105 mmol/L", isCorrect: false },{ text: "22–26 mmol/L", isCorrect: false }],
        explanation: "La natrémie normale est de 135–145 mmol/L. C'est le principal cation du liquide extracellulaire, régulant l'osmolarité plasmatique. Hyponatrémie < 135, hypernatrémie > 145." }
    ]
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 2.2 – Cycles de la vie et grandes fonctions
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Pathologies cardiovasculaires et surveillance IDE",
    description: "Infarctus, insuffisance cardiaque, hypertension et surveillance infirmière",
    semester: "Semestre 1", category: "UE 2.2 - Cycles de la vie et grandes fonctions",
    chapter: "Cardiologie", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "Les signes cliniques de l'insuffisance cardiaque gauche sont :",
        options: [{ text: "Œdèmes des membres inférieurs et turgescence jugulaire", isCorrect: false },{ text: "Dyspnée d'effort puis de repos, orthopnée, crépitants pulmonaires", isCorrect: true },{ text: "Douleur thoracique irradiant dans le bras gauche", isCorrect: false },{ text: "Bradycardie et hypotension artérielle", isCorrect: false }],
        explanation: "L'insuffisance cardiaque gauche entraîne une stase pulmonaire : dyspnée d'effort, orthopnée (dyspnée en position allongée), crépitants des bases, toux nocturne. L'IC droite donne les œdèmes périphériques." },
      { text: "Les signes typiques d'un infarctus du myocarde (IDM) sont :",
        options: [{ text: "Palpitations et vertiges", isCorrect: false },{ text: "Douleur thoracique intense, prolongée (> 20 min), constrictive, irradiant dans le bras gauche ou la mâchoire", isCorrect: true },{ text: "Céphalées et confusion mentale", isCorrect: false },{ text: "Dyspnée isolée sans douleur", isCorrect: false }],
        explanation: "L'IDM se manifeste par une douleur thoracique typique : intense, prolongée, constrictive, irradiant dans le bras gauche, la mâchoire ou l'épigastre, associée à sueurs et malaise. Urgence absolue." },
      { text: "L'HTA est définie par des valeurs persistantes :",
        options: [{ text: "PAS > 120 mmHg ou PAD > 80 mmHg", isCorrect: false },{ text: "PAS ≥ 140 mmHg et/ou PAD ≥ 90 mmHg à plusieurs mesures", isCorrect: true },{ text: "PAS > 160 mmHg uniquement", isCorrect: false },{ text: "PAD > 100 mmHg uniquement", isCorrect: false }],
        explanation: "L'HTA est définie par PAS ≥ 140 mmHg et/ou PAD ≥ 90 mmHg mesurée à plusieurs reprises (HAS 2023). C'est le principal facteur de risque cardiovasculaire modifiable." },
      { text: "La fibrillation auriculaire (FA) expose principalement au risque de :",
        options: [{ text: "Infarctus du myocarde", isCorrect: false },{ text: "Embolie cérébrale (AVC ischémique) par formation de thrombus dans l'oreillette gauche", isCorrect: true },{ text: "Tamponnade cardiaque", isCorrect: false },{ text: "Hypertension artérielle", isCorrect: false }],
        explanation: "La FA entraîne une stase sanguine dans l'oreillette gauche favorisant la formation de thrombus. L'embolisation vers le cerveau provoque un AVC ischémique. Traitement préventif : anticoagulants." },
      { text: "La surveillance IDE d'un patient sous anticoagulants oraux (AVK) comprend :",
        options: [{ text: "La surveillance de la glycémie et de l'HbA1c", isCorrect: false },{ text: "La surveillance de l'INR, des signes hémorragiques et des interactions médicamenteuses", isCorrect: true },{ text: "La surveillance de la créatinine uniquement", isCorrect: false },{ text: "La prise de poids quotidienne uniquement", isCorrect: false }],
        explanation: "Sous AVK : surveillance de l'INR (cible 2-3), signes hémorragiques (hématomes, épistaxis, hématurie, méléna), interactions médicamenteuses nombreuses, conseils alimentaires (vitamine K)." },
      { text: "L'œdème aigu pulmonaire (OAP) cardiogénique se traite en urgence par :",
        options: [{ text: "Position déclive, apport liquidien IV rapide", isCorrect: false },{ text: "Position demi-assise, O₂, diurétiques IV (furosémide), dérivés nitrés", isCorrect: true },{ text: "Antibiothérapie IV et kinésithérapie respiratoire", isCorrect: false },{ text: "Hémodialyse et restriction sodée uniquement", isCorrect: false }],
        explanation: "L'OAP cardiogénique est une urgence. Prise en charge : position demi-assise (jambes pendantes), O₂ (masque haute concentration), furosémide IV (diurèse) et dérivés nitrés (vasodilatation)." },
      { text: "Le signe de Homans (douleur du mollet à la dorsiflexion du pied) oriente vers :",
        options: [{ text: "Une fracture du péroné", isCorrect: false },{ text: "Une thrombose veineuse profonde (TVP)", isCorrect: true },{ text: "Une insuffisance artérielle des membres inférieurs", isCorrect: false },{ text: "Une sciatique", isCorrect: false }],
        explanation: "Le signe de Homans est un signe clinique classique de TVP (même s'il manque de sensibilité/spécificité). Douleur à la dorsiflexion passive du pied indique une possible thrombose du mollet. Confirmation par écho-Doppler." },
      { text: "La surveillance d'un patient porteur d'un pacemaker comprend :",
        options: [{ text: "Contrôle de la glycémie toutes les 6 heures", isCorrect: false },{ text: "FC, PA, signes d'infection locale, et éducation sur les interférences électromagnétiques", isCorrect: true },{ text: "Mesure du débit urinaire toutes les heures", isCorrect: false },{ text: "Surveillance de la SpO₂ uniquement", isCorrect: false }],
        explanation: "Surveillance pacemaker : FC (doit respecter la fréquence programmée), PA, site d'implantation (infection), éducation : éviter champs électromagnétiques puissants (IRM selon type), carte de pacemaker." },
      { text: "Le BNP (Brain Natriuretic Peptide) est un marqueur biologique de :",
        options: [{ text: "L'infarctus du myocarde", isCorrect: false },{ text: "L'insuffisance cardiaque (distension des ventricules)", isCorrect: true },{ text: "L'embolie pulmonaire", isCorrect: false },{ text: "La dissection aortique", isCorrect: false }],
        explanation: "Le BNP (et NT-proBNP) est sécrété par les ventricules sous pression. Son élévation est un marqueur sensible et spécifique d'insuffisance cardiaque, utile pour le diagnostic et le suivi." },
      { text: "Face à un arrêt cardiorespiratoire, la première action de l'IDE est :",
        options: [{ text: "Appeler le médecin et attendre ses instructions", isCorrect: false },{ text: "Appeler à l'aide, débuter la RCP (30 compressions : 2 insufflations) et utiliser le DEA", isCorrect: true },{ text: "Mettre le patient en position latérale de sécurité", isCorrect: false },{ text: "Injecter de l'adrénaline IV immédiatement", isCorrect: false }],
        explanation: "Face à un ACR : appel à l'aide + RCP immédiate (30:2) + DEA le plus tôt possible. Chaque minute sans RCP réduit les chances de survie de 10%. L'adrénaline est administrée par le médecin après défibrillation." }
    ]
  },
  {
    title: "Pathologies respiratoires et prise en charge infirmière",
    description: "BPCO, asthme, pneumonie, insuffisance respiratoire — surveillance IDE",
    semester: "Semestre 1", category: "UE 2.2 - Cycles de la vie et grandes fonctions",
    chapter: "Pneumologie", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "La BPCO (Broncho-Pneumopathie Chronique Obstructive) est caractérisée par :",
        options: [{ text: "Une obstruction bronchique réversible après bronchodilatateur", isCorrect: false },{ text: "Une obstruction bronchique permanente et progressive, principalement due au tabac", isCorrect: true },{ text: "Des crises paroxystiques avec intervalle libre normal", isCorrect: false },{ text: "Une atteinte uniquement des alvéoles pulmonaires", isCorrect: false }],
        explanation: "La BPCO est une obstruction bronchique permanente, non totalement réversible, d'évolution progressive. Cause principale : tabac (90%). Spirométrie : VEMS/CVF < 0,70 post-bronchodilatateur." },
      { text: "L'asthme se différencie de la BPCO par :",
        options: [{ text: "Une obstruction permanente sans possibilité de réversibilité", isCorrect: false },{ text: "Une obstruction bronchique réversible, avec crises paroxystiques et intervalles libres", isCorrect: true },{ text: "L'absence de traitement efficace", isCorrect: false },{ text: "Un âge de début toujours > 60 ans", isCorrect: false }],
        explanation: "L'asthme est caractérisé par une hyperréactivité bronchique avec obstruction réversible (spontanément ou sous bronchodilatateur), des crises dyspnéiques paroxystiques avec intervalles libres normaux." },
      { text: "La surveillance SpO₂ d'un patient BPCO sévère : pourquoi ne pas cibler 100% d'O₂ ?",
        options: [{ text: "L'O₂ est toxique pour les muqueuses bronchiques en BPCO", isCorrect: false },{ text: "Le patient BPCO est adapté à l'hypercapnie et un excès d'O₂ peut supprimer sa commande respiratoire", isCorrect: true },{ text: "L'O₂ favorise les infections chez le BPCO", isCorrect: false },{ text: "Il n'y a aucune raison, la cible doit toujours être 100%", isCorrect: false }],
        explanation: "Chez le BPCO sévère hypercapnique, la commande respiratoire devient hypoxique (non hypercapnique). Un O₂ excessif peut abolir cette commande → hypoventilation. Cible SpO₂ : 88–92%." },
      { text: "La pneumonie bactérienne communautaire se manifeste typiquement par :",
        options: [{ text: "Toux sèche, fièvre progressive et absence de signes auscultatoires", isCorrect: false },{ text: "Fièvre élevée brutale, frisson, toux productive avec expectoration purulente, douleur pleurale", isCorrect: true },{ text: "Dyspnée progressive sur plusieurs semaines sans fièvre", isCorrect: false },{ text: "Hémoptysie massive sans fièvre", isCorrect: false }],
        explanation: "La pneumonie bactérienne typique (pneumocoque) : début brutal, fièvre > 39°C avec frissons, toux productive (expectoration rouillée), douleur thoracique, foyer de condensation à l'auscultation." },
      { text: "L'embolie pulmonaire (EP) se présente le plus souvent par :",
        options: [{ text: "Toux chronique productive et fièvre prolongée", isCorrect: false },{ text: "Dyspnée brutale, douleur thoracique, tachycardie, et parfois hémoptysie", isCorrect: true },{ text: "Bradycardie et hypotension avec fièvre", isCorrect: false },{ text: "Hoquet persistant et météorisme abdominal", isCorrect: false }],
        explanation: "L'EP se présente typiquement par une dyspnée brutale (+ fréquent), une douleur thoracique pleurale, une tachycardie, et parfois une hémoptysie. Le gold standard diagnostic est l'angio-scanner thoracique." },
      { text: "La kinésithérapie respiratoire est indiquée pour :",
        options: [{ text: "Augmenter la SpO₂ lors d'un OAP cardiogénique", isCorrect: false },{ text: "Faciliter le désencombrement bronchique (BPCO, mucoviscidose, post-opératoire)", isCorrect: true },{ text: "Traiter les crises d'asthme aiguë", isCorrect: false },{ text: "Réduire la fréquence respiratoire dans l'hyperventilation", isCorrect: false }],
        explanation: "La kinésithérapie respiratoire aide à mobiliser et expectorer les sécrétions bronchiques. Elle est indiquée dans la BPCO, la mucoviscidose, le post-opératoire et les pathologies neuromusculaires." },
      { text: "Lors d'une oxygénothérapie par lunettes nasales, le débit habituel est :",
        options: [{ text: "10–15 L/min", isCorrect: false },{ text: "1–6 L/min", isCorrect: true },{ text: "0,5 L/min uniquement", isCorrect: false },{ text: "8–12 L/min", isCorrect: false }],
        explanation: "Les lunettes nasales délivrent de l'O₂ à faible débit (1–6 L/min), correspondant à une FiO₂ de 24–44%. Au-delà de 4 L/min, le masque simple ou à haute concentration est préféré." },
      { text: "Le pneumothorax spontané se manifeste par :",
        options: [{ text: "Dyspnée progressive sur plusieurs jours avec fièvre", isCorrect: false },{ text: "Douleur thoracique latérale brutale et dyspnée, avec abolition du murmure vésiculaire d'un côté", isCorrect: true },{ text: "Toux chronique avec hémoptysies répétées", isCorrect: false },{ text: "Œdème du visage et cyanose progressive", isCorrect: false }],
        explanation: "Le pneumothorax spontané : douleur thoracique latérale brutale + dyspnée, abolition du murmure vésiculaire du côté atteint, tympanisme à la percussion. Confirmer par radio thorax. Urgence si complet." },
      { text: "La surveillance infirmière d'un patient sous ventilation non invasive (VNI) comprend :",
        options: [{ text: "Uniquement la SpO₂ et la FR", isCorrect: false },{ text: "SpO₂, FR, FC, confort du masque, tolérance, fuites, gazométrie et état de conscience", isCorrect: true },{ text: "La pression artérielle toutes les 4 heures uniquement", isCorrect: false },{ text: "Le poids quotidien et la diurèse", isCorrect: false }],
        explanation: "La surveillance VNI est multidimensionnelle : paramètres vitaux (SpO₂, FR, FC, PA), efficacité (gazométrie), confort (fuites du masque, escarre nasale), état de conscience et tolérance psychologique." },
      { text: "La tuberculose pulmonaire est transmise par :",
        options: [{ text: "Contact avec des sécrétions digestives contaminées", isCorrect: false },{ text: "Voie aérienne par l'inhalation de gouttelettes (noyaux de Wells) contenant Mycobacterium tuberculosis", isCorrect: true },{ text: "Contact cutané direct avec une personne infectée", isCorrect: false },{ text: "Voie sanguine uniquement (transfusion, partage de seringues)", isCorrect: false }],
        explanation: "La tuberculose (BK) se transmet par voie aérienne via les noyaux de Wells (micro-gouttelettes restant en suspension). Précautions complémentaires AIR indispensables (chambre pression négative, masque FFP2)." }
    ]
  },
  {
    title: "Neurologie clinique et surveillance du patient neurologique",
    description: "AVC, épilepsie, méningite — signes cliniques et rôle infirmier",
    semester: "Semestre 1", category: "UE 2.2 - Cycles de la vie et grandes fonctions",
    chapter: "Neurologie", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "Les signes d'alerte d'un AVC (acronyme FAST) sont :",
        options: [{ text: "Fièvre, Agitation, Somnolence, Tachycardie", isCorrect: false },{ text: "Face (asymétrie faciale), Arm (faiblesse bras), Speech (troubles parole), Time (appeler le 15)", isCorrect: true },{ text: "Fatigue, Anxiété, Syncope, Tremblements", isCorrect: false },{ text: "Froid, Acouphènes, Scotome, Tension", isCorrect: false }],
        explanation: "FAST : Face (asymétrie, déviation commissure), Arm (déficit moteur d'un bras), Speech (aphasie, dysarthrie), Time (urgence extrême, appeler le 15, fenêtre thérapeutique 4h30 pour thrombolyse)." },
      { text: "L'AVC hémorragique se distingue de l'AVC ischémique par :",
        options: [{ text: "Des signes strictement identiques, seul le scanner les différencie", isCorrect: true },{ text: "Des céphalées toujours absentes dans l'AVC hémorragique", isCorrect: false },{ text: "Un début toujours progressif", isCorrect: false },{ text: "Une hémiplégie exclusivement du côté gauche", isCorrect: false }],
        explanation: "Cliniquement, AVC ischémique et hémorragique peuvent être similaires. Le scanner cérébral sans injection est INDISPENSABLE pour les différencier (hyperdensité spontanée = hémorragie) car le traitement est opposé." },
      { text: "La conduite à tenir lors d'une crise épileptique tonico-clonique est :",
        options: [{ text: "Introduire un objet dans la bouche pour éviter la morsure de langue", isCorrect: false },{ text: "Protéger la tête, écarter les objets dangereux, mettre en PLS après la crise, chronométrer", isCorrect: true },{ text: "Retenir les membres pour éviter les traumatismes", isCorrect: false },{ text: "Administrer immédiatement un antiépileptique IV", isCorrect: false }],
        explanation: "Crise épileptique : NE PAS mettre d'objet en bouche, NE PAS retenir les membres. Protéger la tête, chronométrer, PLS après la crise. Si > 5 min → état de mal épileptique → urgence médicale." },
      { text: "La méningite bactérienne se manifeste par la triade classique :",
        options: [{ text: "Fièvre, toux et douleurs abdominales", isCorrect: false },{ text: "Fièvre, céphalées et raideur de nuque (syndrome méningé)", isCorrect: true },{ text: "Fièvre, conscience altérée et convulsions uniquement", isCorrect: false },{ text: "Confusion, vomissements et photophobie sans fièvre", isCorrect: false }],
        explanation: "Méningite bactérienne : fièvre élevée + céphalées intenses + raideur de nuque (signe de Kernig, Brudzinski). Purpura fulminans = urgence vitale absolue (méningocoque). PL pour confirmer + antibiothérapie immédiate." },
      { text: "Le signe de Babinski (positif) traduit :",
        options: [{ text: "Une atteinte du nerf périphérique (système nerveux périphérique)", isCorrect: false },{ text: "Une atteinte de la voie pyramidale (système nerveux central)", isCorrect: true },{ text: "Un développement neurologique normal chez l'adulte", isCorrect: false },{ text: "Une hypoglycémie sévère", isCorrect: false }],
        explanation: "Le signe de Babinski (extension du gros orteil à la stimulation plantaire) est pathologique chez l'adulte : il signe une atteinte de la voie pyramidale (AVC, SEP, tumeur, compression médullaire)." },
      { text: "La maladie de Parkinson se caractérise principalement par :",
        options: [{ text: "Tremblement d'action, spasticité et démence précoce", isCorrect: false },{ text: "Tremblement de repos, akinésie, rigidité en roue dentée et instabilité posturale", isCorrect: true },{ text: "Paralysie flasque progressive et amyotrophie", isCorrect: false },{ text: "Crises épileptiques et confusion chronique", isCorrect: false }],
        explanation: "Parkinson : triade clinique — tremblement de REPOS (4-6 Hz, 'émiettement du pain'), akinésie/bradykinésie, rigidité 'en roue dentée'. Dû à la dégénérescence des neurones dopaminergiques." },
      { text: "L'hypertension intracrânienne (HTIC) se manifeste par la triade de Cushing :",
        options: [{ text: "Tachycardie, hypotension et tachypnée", isCorrect: false },{ text: "Hypertension artérielle, bradycardie et bradypnée", isCorrect: true },{ text: "Fièvre, raideur de nuque et photophobie", isCorrect: false },{ text: "Mydriase bilatérale, agitation et coma", isCorrect: false }],
        explanation: "Triade de Cushing (HTIC) : HTA réflexe + bradycardie compensatrice + bradypnée. Associée à : céphalées (pires le matin), vomissements en jet, œdème papillaire, troubles de conscience progressifs." },
      { text: "La surveillance neurologique post-AVC comprend :",
        options: [{ text: "Uniquement le score de Glasgow toutes les 24 heures", isCorrect: false },{ text: "Score de Glasgow, déficit moteur/sensitif, vigilance, PA, glycémie, température, SpO₂", isCorrect: true },{ text: "Uniquement la prise de température et la PA", isCorrect: false },{ text: "Seulement l'imagerie cérébrale répétée", isCorrect: false }],
        explanation: "Surveillance neurologique post-AVC : GCS, déficits (moteurs, sensitifs, langage), PA (objectifs stricts), glycémie (hyperglycémie aggrave le pronostic), température (fièvre aggrave), SpO₂, déglutition." },
      { text: "La sclérose en plaques (SEP) est une maladie :",
        options: [{ text: "Dégénérative touchant exclusivement les muscles", isCorrect: false },{ text: "Démyélinisante auto-immune du SNC, évoluant par poussées et rémissions (forme rémittente)", isCorrect: true },{ text: "Infectieuse bactérienne touchant la moelle épinière", isCorrect: false },{ text: "Génétique avec transmission autosomale dominante", isCorrect: false }],
        explanation: "La SEP est une maladie démyélinisante auto-immune qui détruit la gaine de myéline du SNC. Forme la plus fréquente (85%) : rémittente-récurrente — poussées avec récupération partielle ou complète." },
      { text: "Devant une confusion aiguë chez un patient âgé hospitalisé, le premier réflexe est :",
        options: [{ text: "Administrer un sédatif pour calmer l'agitation", isCorrect: false },{ text: "Rechercher une cause somatique : infection, déshydratation, hypoglycémie, rétention urinaire, médicament", isCorrect: true },{ text: "Appeler le psychiatre pour syndrome confusionnel", isCorrect: false },{ text: "Mettre en contention physique pour sécurité", isCorrect: false }],
        explanation: "La confusion aiguë (syndrome confusionnel) chez le sujet âgé est presque toujours d'origine somatique : infection (urinaire ++), déshydratation, médicament psychoactif, douleur, rétention urinaire, hypoglycémie." }
    ]
  },
];
