// ─── PARTIE 5 : UE 6.1 · UE 6.2 ────────────────────────────────────────────
module.exports = [

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 6.1 – Méthodes de travail et TIC (3 quiz)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Organisation du travail infirmier",
    description: "Gestion du temps, priorisation et organisation en milieu de soins",
    semester: "Semestre 1", category: "UE 6.1 - Méthodes de travail et TIC",
    chapter: "Organisation professionnelle", difficulty: "easy", duration: 15, isPublished: true,
    questions: [
      { text: "La méthode de priorisation des soins en début de poste repose sur :",
        options: [{ text: "L'ordre d'entrée dans les chambres", isCorrect: false },{ text: "L'urgence clinique, les horaires des thérapeutiques et les contraintes organisationnelles", isCorrect: true },{ text: "Les préférences personnelles de l'infirmier", isCorrect: false },{ text: "L'ordre alphabétique des patients", isCorrect: false }],
        explanation: "La priorisation en début de poste : 1) Urgences cliniques identifiées à la transmission ; 2) Thérapeutiques chronodépendantes (insuline, antibiotiques IV, anticoagulants) ; 3) Soins de nursing du matin ; 4) Soins programmés, pansements, bilans ; 5) Tâches administratives. Toujours réévaluer en cours de poste." },
      { text: "La transmission de relève entre équipes soignantes doit obligatoirement inclure :",
        options: [{ text: "Uniquement les nouveaux patients admis dans le service", isCorrect: false },{ text: "L'état clinique de chaque patient, les événements du poste, les soins à venir et les points de vigilance", isCorrect: true },{ text: "Les plaintes administratives des patients", isCorrect: false },{ text: "Le planning des congés de l'équipe suivante", isCorrect: false }],
        explanation: "Une transmission de qualité couvre : état clinique actuel (constantes, évolution), événements significatifs du poste (chute, douleur, examen), soins réalisés et à faire, thérapeutiques en cours, points de vigilance spécifiques (allergie, risque de chute, isolement) et éléments relationnels ou familiaux importants." },
      { text: "Le travail en binôme infirmier/aide-soignant (IDE/AS) est organisé selon :",
        options: [{ text: "La hiérarchie stricte : l'IDE donne des ordres à l'AS", isCorrect: false },{ text: "La complémentarité des rôles : l'IDE coordonne et délègue certains soins dans le cadre légal", isCorrect: true },{ text: "La préférence personnelle de chacun", isCorrect: false },{ text: "La règle : l'AS réalise tous les soins, l'IDE surveille", isCorrect: false }],
        explanation: "L'IDE et l'AS travaillent en complémentarité : l'IDE réalise les actes relevant de son rôle propre et prescrit (soins techniques, évaluation, éducation), délègue à l'AS les soins de nursing relevant de son rôle (hygiène, aide au repas, changes), tout en gardant la responsabilité de la coordination et de la surveillance." },
      { text: "La gestion du stress professionnel en soins infirmiers passe par :",
        options: [{ text: "Ignorer les situations difficiles et rester stoïque", isCorrect: false },{ text: "La régulation émotionnelle, le soutien entre pairs, les groupes de parole et la supervision", isCorrect: true },{ text: "Travailler seul pour éviter les conflits d'équipe", isCorrect: false },{ text: "Ne pas parler des difficultés aux collègues", isCorrect: false }],
        explanation: "La gestion du stress professionnel infirmier repose sur : la reconnaissance et l'expression des émotions (ne pas les nier), le soutien entre pairs (débriefing informel), les groupes de parole et analyses de pratique, la supervision professionnelle, l'équilibre vie pro/vie perso, et le management bienveillant." },
      { text: "Le déclaration d'un événement indésirable associé aux soins (EIAS) est :",
        options: [{ text: "Une démarche facultative réservée aux médecins", isCorrect: false },{ text: "Une obligation pour tous les professionnels de santé, dans une logique non punitive d'amélioration continue", isCorrect: true },{ text: "Une procédure judiciaire automatique", isCorrect: false },{ text: "Réservée aux erreurs médicamenteuses graves uniquement", isCorrect: false }],
        explanation: "La déclaration des EIAS (incidents, erreurs, presque-accidents) est une obligation déontologique et légale pour tous les soignants. Elle s'inscrit dans une démarche non punitive d'amélioration de la qualité et de la sécurité des soins. Tout signalement est analysé (CREX, RMM) pour prévenir la récidive." },
      { text: "Le protocole de soins est un document qui :",
        options: [{ text: "Remplace la prescription médicale individuelle", isCorrect: false },{ text: "Décrit les étapes standardisées pour réaliser un soin ou gérer une situation clinique, validé par l'équipe", isCorrect: true },{ text: "Est rédigé uniquement par le médecin chef de service", isCorrect: false },{ text: "Est optionnel et indicatif dans la pratique soignante", isCorrect: false }],
        explanation: "Un protocole de soins est un document de référence élaboré et validé par l'équipe pluridisciplinaire, décrivant la conduite à tenir standardisée face à une situation clinique ou pour réaliser un soin. Il garantit la qualité, la sécurité et la continuité des pratiques. Il s'appuie sur les données probantes et les recommandations HAS." },
      { text: "La réunion de synthèse pluridisciplinaire (staff) a lieu pour :",
        options: [{ text: "Évaluer les performances des infirmiers du service", isCorrect: false },{ text: "Coordonner la prise en charge globale du patient entre tous les professionnels impliqués", isCorrect: true },{ text: "Décider des plannings de travail", isCorrect: false },{ text: "Informer les familles des décisions médicales", isCorrect: false }],
        explanation: "Le staff pluridisciplinaire (médecin, infirmier, AS, kiné, diététicien, AS social, psychologue…) permet de : partager les informations sur chaque patient, définir un projet de soins cohérent, coordonner les interventions, anticiper la sortie et les besoins à domicile. Il est le pivot de la prise en charge centrée sur la personne." },
      { text: "La check-list 'Sécurité du patient au bloc opératoire' (type OMS) est réalisée :",
        options: [{ text: "Uniquement après l'intervention chirurgicale", isCorrect: false },{ text: "En trois temps : avant induction anesthésique, avant incision, avant sortie de salle", isCorrect: true },{ text: "Uniquement par le chirurgien", isCorrect: false },{ text: "Uniquement pour les chirurgies majeures", isCorrect: false }],
        explanation: "La check-list sécurité opératoire (OMS 2008, généralisée en France par la HAS) se déroule en 3 temps : Sign In (avant induction : identité, site chirurgical, allergie, matériel), Time Out (avant incision : confirmation à voix haute), Sign Out (avant sortie : comptage compresses, étiquetage pièces anatomiques). Elle réduit la mortalité chirurgicale de 40%." },
      { text: "L'ergonomie au travail pour le personnel soignant vise à :",
        options: [{ text: "Augmenter le rendement des soignants", isCorrect: false },{ text: "Adapter l'environnement et les outils de travail aux capacités humaines pour prévenir les TMS et accidents", isCorrect: true },{ text: "Réduire le nombre de soignants nécessaires", isCorrect: false },{ text: "Améliorer uniquement l'esthétique des postes de travail", isCorrect: false }],
        explanation: "L'ergonomie (du grec ergon = travail, nomos = loi) adapte les conditions de travail aux capacités et limites humaines. En soins infirmiers : hauteur réglable des lits, aides techniques à la manutention (lève-malade, disques de transfert), organisation des espaces, formation aux gestes et postures." },
      { text: "La continuité des soins lors d'une absence imprévue de l'infirmier est assurée par :",
        options: [{ text: "La suspension des soins jusqu'au retour de l'infirmier", isCorrect: false },{ text: "Le remplacement par un collègue qualifié, avec transmission complète des informations essentielles", isCorrect: true },{ text: "La délégation de tous les soins à l'aide-soignant", isCorrect: false },{ text: "L'appel du patient à sa famille pour les soins basiques", isCorrect: false }],
        explanation: "La continuité des soins est une obligation légale et éthique : en cas d'absence, l'infirmier doit assurer une transmission complète et s'assurer qu'un professionnel qualifié prend le relais. L'établissement a l'obligation d'organiser les remplacements et de garantir la sécurité des soins 24h/24." }
    ]
  },
  {
    title: "Dossier patient informatisé et outils numériques",
    description: "Utilisation des systèmes d'information de santé en pratique infirmière",
    semester: "Semestre 1", category: "UE 6.1 - Méthodes de travail et TIC",
    chapter: "Informatique de santé", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Le Dossier Patient Informatisé (DPI) en milieu hospitalier permet de :",
        options: [{ text: "Remplacer toute communication orale entre soignants", isCorrect: false },{ text: "Centraliser et partager en temps réel les informations médicales, paramédicales et administratives du patient", isCorrect: true },{ text: "Facturer automatiquement les actes de soins", isCorrect: false },{ text: "Remplacer la prescription médicale papier uniquement", isCorrect: false }],
        explanation: "Le DPI centralise : données administratives (identité, droits), dossier médical (prescriptions, comptes-rendus), dossier infirmier (transmissions, paramètres vitaux, plans de soins), résultats d'examens, imagerie. Il améliore la coordination entre professionnels, réduit les erreurs et facilite la traçabilité." },
      { text: "La prescription médicamenteuse informatisée (PMSI) contribue à la sécurité en :",
        options: [{ text: "Rendant inutile la vérification par l'infirmier", isCorrect: false },{ text: "Réduisant les erreurs de retranscription, alertant sur les interactions et contre-indications", isCorrect: true },{ text: "Permettant à l'infirmier de modifier les doses", isCorrect: false },{ text: "Automatisant l'administration des médicaments", isCorrect: false }],
        explanation: "La prescription médicamenteuse informatisée réduit les erreurs liées aux ordonnances manuscrites illisibles, alerte sur les interactions médicamenteuses et les contre-indications, facilite la dispensation par la pharmacie, et génère automatiquement les plans d'administration pour l'infirmier." },
      { text: "La confidentialité des données de santé informatisées est régie par :",
        options: [{ text: "Les règles internes de chaque établissement uniquement", isCorrect: false },{ text: "Le RGPD (Règlement Général sur la Protection des Données) et la loi Informatique et Libertés", isCorrect: true },{ text: "Le code du travail uniquement", isCorrect: false },{ text: "Les directives de l'OMS", isCorrect: false }],
        explanation: "Les données de santé sont des données sensibles bénéficiant d'une protection renforcée sous le RGPD (règlement européen 2016/679) et la loi Informatique et Libertés (CNIL). Leur traitement nécessite des mesures de sécurité spécifiques : pseudonymisation, chiffrement, contrôle des accès par identifiant personnel." },
      { text: "L'identifiant personnel de connexion au DPI est :",
        options: [{ text: "Partageable avec les collègues en cas d'urgence", isCorrect: false },{ text: "Strictement personnel et ne doit jamais être communiqué ni partagé", isCorrect: true },{ text: "Le même pour toute l'équipe infirmière d'un service", isCorrect: false },{ text: "Facultatif si l'on connaît le mot de passe d'un collègue", isCorrect: false }],
        explanation: "L'identifiant et le mot de passe de connexion au DPI sont personnels et confidentiels. Les utiliser garantit la traçabilité des accès et des actes (qui a vu, modifié, tracé quoi et quand). Les partager est une faute déontologique et juridique : chaque soignant est responsable des actions effectuées sous son identifiant." },
      { text: "La télémédecine en soins infirmiers comprend :",
        options: [{ text: "Uniquement la téléconsultation médicale par vidéo", isCorrect: false },{ text: "La téléconsultation, la télésurveillance, la téléexpertise et l'assistance médicale à distance", isCorrect: true },{ text: "L'envoi de messages texte aux patients uniquement", isCorrect: false },{ text: "Uniquement les applications de prise de rendez-vous", isCorrect: false }],
        explanation: "La télémédecine (loi HPST 2009) comprend : téléconsultation (consultation à distance par vidéo), téléexpertise (avis d'un médecin expert sollicité à distance), télésurveillance médicale (suivi à distance de paramètres physiologiques), téléassistance médicale, régulation médicale. Elle développe l'accès aux soins dans les zones sous-dotées." },
      { text: "Le Mon Espace Santé (ex-Dossier Médical Partagé) est :",
        options: [{ text: "Un dossier médical uniquement accessible au médecin traitant", isCorrect: false },{ text: "Un espace numérique personnel permettant au patient de centraliser et partager ses données de santé", isCorrect: true },{ text: "Un outil de gestion administrative hospitalière", isCorrect: false },{ text: "Un registre national des hospitalisations", isCorrect: false }],
        explanation: "Mon Espace Santé (déployé depuis 2022) est le carnet de santé numérique de chaque citoyen français : ordonnances, comptes-rendus, vaccinations, résultats d'examens. Il favorise la coordination entre professionnels de santé et l'accès du patient à ses propres données de santé." },
      { text: "La traçabilité des actes dans le DPI a une valeur :",
        options: [{ text: "Uniquement statistique pour les études épidémiologiques", isCorrect: false },{ text: "Médicolégale, de continuité des soins et de qualité/sécurité", isCorrect: true },{ text: "Uniquement administrative pour la facturation", isCorrect: false },{ text: "Purement informative sans conséquence pratique", isCorrect: false }],
        explanation: "La traçabilité dans le DPI a une valeur triple : médicolégale (preuve en cas de litige : ce qui n'est pas tracé n'est pas prouvé), continuité des soins (informations disponibles pour tous les soignants 24h/24), et qualité (audit des pratiques, indicateurs qualité, accréditation HAS)." },
      { text: "Les outils de communication sécurisée entre professionnels de santé (Messagerie Sécurisée de Santé - MSSanté) permettent :",
        options: [{ text: "D'envoyer des données patient par email classique", isCorrect: false },{ text: "D'échanger des données médicales de façon chiffrée et conforme au secret médical", isCorrect: true },{ text: "De partager les données patient sur les réseaux sociaux professionnels", isCorrect: false },{ text: "Uniquement de recevoir des résultats de laboratoire", isCorrect: false }],
        explanation: "La MSSanté est la messagerie sécurisée officielle des professionnels de santé français. Elle permet l'échange de données médicales chiffrées de bout en bout, entre professionnels habilités, dans le respect du secret médical et du RGPD. Elle remplace les fax et emails non sécurisés pour les données de santé." },
      { text: "Lors d'une cyberattaque sur le système informatique hospitalier, la priorité est :",
        options: [{ text: "De continuer les soins normalement en attendant la résolution", isCorrect: false },{ text: "D'activer le plan de continuité d'activité (PCA) avec retour aux supports papier et alerter la direction", isCorrect: true },{ text: "De tenter de résoudre soi-même le problème informatique", isCorrect: false },{ text: "D'informer les patients immédiatement par voie de presse", isCorrect: false }],
        explanation: "En cas de cyberattaque ou panne du DPI, le Plan de Continuité d'Activité (PCA) est activé : retour aux supports papier (prescriptions, transmissions), déconnexion des systèmes atteints, alerte à la direction et à l'ANSSI (Agence Nationale de la Sécurité des Systèmes d'Information), signalement à la CNIL si données compromises." },
      { text: "La formation aux outils numériques de santé pour les infirmiers est :",
        options: [{ text: "Optionnelle et uniquement pour les services de réanimation", isCorrect: false },{ text: "Une nécessité professionnelle intégrée au DPC pour maintenir des compétences adaptées aux évolutions technologiques", isCorrect: true },{ text: "Uniquement assurée par les fournisseurs de logiciels", isCorrect: false },{ text: "Réservée aux infirmiers coordinateurs uniquement", isCorrect: false }],
        explanation: "La formation aux TIC de santé fait partie des compétences infirmières à maintenir et développer dans le cadre du DPC (Développement Professionnel Continu). Les évolutions rapides des outils numériques (DPI, télémédecine, IA diagnostique) nécessitent une formation continue tout au long de la carrière." }
    ]
  },
  {
    title: "Recherche documentaire et pratiques fondées sur des preuves",
    description: "Méthodes de recherche en soins infirmiers et Evidence-Based Nursing",
    semester: "Semestre 1", category: "UE 6.1 - Méthodes de travail et TIC",
    chapter: "Documentation et EBN", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "L'Evidence-Based Nursing (EBN) ou soins fondés sur les preuves intègre :",
        options: [{ text: "Uniquement les données de la recherche scientifique", isCorrect: false },{ text: "Les meilleures preuves scientifiques disponibles, l'expertise clinique et les préférences du patient", isCorrect: true },{ text: "Uniquement les recommandations des sociétés savantes", isCorrect: false },{ text: "Uniquement l'expérience du soignant senior", isCorrect: false }],
        explanation: "L'EBN (Sackett, 1996) intègre trois sources complémentaires : 1) les meilleures preuves de la recherche (études cliniques, méta-analyses) ; 2) l'expertise et le jugement clinique du professionnel ; 3) les valeurs et préférences du patient. La pratique optimale résulte de l'intégration de ces trois dimensions." },
      { text: "La hiérarchie des niveaux de preuve en médecine/soins place au niveau le plus élevé :",
        options: [{ text: "L'avis d'un expert", isCorrect: false },{ text: "La méta-analyse d'essais contrôlés randomisés (ECR) et les revues systématiques", isCorrect: true },{ text: "L'étude de cas (case report)", isCorrect: false },{ text: "L'étude de cohorte rétrospective", isCorrect: false }],
        explanation: "La pyramide des preuves (du plus faible au plus fort) : opinion d'expert → série de cas → étude cas-témoins → cohorte → ECR → méta-analyse d'ECR. Les méta-analyses et revues systématiques (Cochrane) constituent le niveau de preuve le plus élevé (niveau 1)." },
      { text: "La HAS (Haute Autorité de Santé) publie des recommandations de bonne pratique (RBP) pour :",
        options: [{ text: "Établir les tarifs des actes médicaux", isCorrect: false },{ text: "Guider les professionnels vers les pratiques cliniques les plus efficaces et sûres, fondées sur les preuves", isCorrect: true },{ text: "Gérer les ressources humaines hospitalières", isCorrect: false },{ text: "Former les étudiants en soins infirmiers", isCorrect: false }],
        explanation: "La HAS élabore des recommandations de bonne pratique (RBP), guides du parcours de soins, référentiels d'évaluation et de certification. Elles synthétisent les données probantes et guident les professionnels de santé dans leurs décisions cliniques pour améliorer la qualité et la sécurité des soins." },
      { text: "Pour réaliser une recherche documentaire fiable en soins infirmiers, on utilise :",
        options: [{ text: "Uniquement Wikipedia et les moteurs de recherche grand public", isCorrect: false },{ text: "Les bases de données médicales : PubMed, CINAHL, Cochrane, em-consulte, HAS", isCorrect: true },{ text: "Uniquement les manuels de cours", isCorrect: false },{ text: "Uniquement les revues professionnelles papier", isCorrect: false }],
        explanation: "Les bases de données spécialisées garantissent des sources fiables et indexées : PubMed (bibliothèque médicale US, accès gratuit), CINAHL (soins infirmiers), Cochrane Library (revues systématiques), em-consulte (revues francophones), site HAS (recommandations françaises). Évaluer critiquement toute source (auteur, journal, méthodologie, date)." },
      { text: "L'analyse critique d'un article scientifique évalue :",
        options: [{ text: "Uniquement les conclusions de l'auteur", isCorrect: false },{ text: "La pertinence clinique de la question, la méthodologie, les biais potentiels, les résultats et leur applicabilité", isCorrect: true },{ text: "Uniquement le facteur d'impact de la revue", isCorrect: false },{ text: "Uniquement la notoriété des auteurs", isCorrect: false }],
        explanation: "La lecture critique d'un article (grille PICO, CONSORT, STROBE selon le type d'étude) évalue : la question de recherche (PICO : Patient, Intervention, Comparateur, Outcome), le design méthodologique, les biais, la taille d'échantillon, la signification statistique vs clinique, et l'applicabilité en pratique." },
      { text: "La recherche en soins infirmiers contribue à la profession car :",
        options: [{ text: "Elle permet de publier pour obtenir des promotions", isCorrect: false },{ text: "Elle développe un corpus de connaissances propres, améliore les pratiques et renforce l'autonomie professionnelle", isCorrect: true },{ text: "Elle est réservée aux infirmiers titulaires d'un doctorat", isCorrect: false },{ text: "Elle n'a pas d'impact direct sur la pratique clinique quotidienne", isCorrect: false }],
        explanation: "La recherche infirmière (clinique, fondamentale, appliquée) contribue à : développer un savoir disciplinaire propre, valider ou remettre en question les pratiques existantes, améliorer la qualité des soins par l'EBN, et affirmer l'autonomie et la professionnalisation de la discipline infirmière." },
      { text: "Le mémoire de fin d'études infirmières (TFE) développe chez l'étudiant :",
        options: [{ text: "Uniquement des compétences rédactionnelles", isCorrect: false },{ text: "La capacité de questionner sa pratique, de mener une réflexion clinique fondée sur des preuves et de formaliser un raisonnement", isCorrect: true },{ text: "Des compétences uniquement en recherche fondamentale", isCorrect: false },{ text: "Uniquement la connaissance d'un sujet médical précis", isCorrect: false }],
        explanation: "Le TFE (Travail de Fin d'Études) développe : la capacité à identifier une question clinique (issu d'une situation de stage), à mener une recherche documentaire rigoureuse, à analyser critiquement les sources, à raisonner de façon structurée et à argumenter une réponse professionnelle fondée sur des preuves." },
      { text: "Un protocole de recherche clinique impliquant des patients doit impérativement obtenir :",
        options: [{ text: "Uniquement l'accord du directeur de l'établissement", isCorrect: false },{ text: "L'avis favorable d'un Comité de Protection des Personnes (CPP) et le consentement éclairé des participants", isCorrect: true },{ text: "Uniquement l'autorisation de la HAS", isCorrect: false },{ text: "L'accord de la Caisse d'Assurance Maladie uniquement", isCorrect: false }],
        explanation: "Toute recherche impliquant des personnes humaines (loi Jardé, 2012) nécessite : l'avis favorable d'un CPP (Comité de Protection des Personnes) qui évalue l'éthique du protocole, l'autorisation de l'ANSM pour les essais médicamenteux, et le consentement libre et éclairé de chaque participant." },
      { text: "La notion de 'conflit d'intérêts' dans la recherche médicale concerne :",
        options: [{ text: "Uniquement les chercheurs travaillant pour l'industrie pharmaceutique", isCorrect: false },{ text: "Tout lien financier, professionnel ou personnel pouvant influencer les résultats ou leur interprétation", isCorrect: true },{ text: "Les désaccords entre chercheurs sur la méthodologie", isCorrect: false },{ text: "Les conflits entre les différentes équipes de recherche", isCorrect: false }],
        explanation: "Un conflit d'intérêts est une situation où des intérêts personnels (financiers, professionnels, relationnels) d'un chercheur peuvent influencer la réalisation ou l'interprétation d'une étude. Leur déclaration est obligatoire dans toute publication scientifique pour garantir la transparence et l'intégrité de la recherche." },
      { text: "Le cadre de référence d'un travail de recherche infirmière est :",
        options: [{ text: "La liste des auteurs consultés uniquement", isCorrect: false },{ text: "L'ensemble des concepts théoriques et des modèles qui guident la compréhension du sujet étudié", isCorrect: true },{ text: "Le résumé (abstract) du mémoire", isCorrect: false },{ text: "La méthodologie de collecte des données", isCorrect: false }],
        explanation: "Le cadre de référence (ou cadre conceptuel) définit les concepts-clés et les théories qui structurent la réflexion (ex : théorie du confort de Kolcaba, modèle de Henderson, théorie du soin de Watson). Il oriente la collecte des données et l'analyse, et permet d'articuler la recherche à la discipline infirmière." }
    ]
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 6.2 – Anglais médical (4 quiz)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Vocabulaire médical de base en anglais",
    description: "Essential medical vocabulary for nursing students",
    semester: "Semestre 1", category: "UE 6.2 - Anglais médical",
    chapter: "Medical vocabulary", difficulty: "easy", duration: 15, isPublished: true,
    questions: [
      { text: "What does 'dyspnea' mean?",
        options: [{ text: "Chest pain", isCorrect: false },{ text: "Difficulty breathing / shortness of breath", isCorrect: true },{ text: "Difficulty swallowing", isCorrect: false },{ text: "Irregular heartbeat", isCorrect: false }],
        explanation: "'Dyspnea' (or dyspnoea in British English) means difficulty breathing or shortness of breath. 'Dysphagia' = difficulty swallowing. 'Dysarthria' = difficulty speaking. The prefix 'dys-' indicates difficulty or abnormality." },
      { text: "What is the English term for 'soins infirmiers' ?",
        options: [{ text: "Medical care", isCorrect: false },{ text: "Nursing care", isCorrect: true },{ text: "Health care management", isCorrect: false },{ text: "Clinical assistance", isCorrect: false }],
        explanation: "'Nursing care' is the English equivalent of 'soins infirmiers'. A nurse is 'a nurse' (UK/US), and the profession is 'nursing'. 'Medical care' refers more broadly to healthcare. 'Nursing' comes from the Latin 'nutrire' (to nourish, care for)." },
      { text: "Which prefix means 'heart' in medical terminology?",
        options: [{ text: "Nephro-", isCorrect: false },{ text: "Cardio-", isCorrect: true },{ text: "Pneumo-", isCorrect: false },{ text: "Neuro-", isCorrect: false }],
        explanation: "The prefix 'cardio-' refers to the heart (Greek 'kardia'). Examples: cardiology, cardiogram, cardiovascular. 'Nephro-' = kidney; 'pneumo-' = lung; 'neuro-' = nerve. Learning prefixes and suffixes is key to understanding medical terminology." },
      { text: "What does 'NPO' (or 'NBM') mean in a clinical context?",
        options: [{ text: "Normal physiological observation", isCorrect: false },{ text: "Nothing by mouth / nil by mouth (patient must not eat or drink)", isCorrect: true },{ text: "Neurological patient observation", isCorrect: false },{ text: "No prescription ordered", isCorrect: false }],
        explanation: "'NPO' stands for 'Nil Per Os' (Latin: nothing by mouth). 'NBM' (Nothing By Mouth) is the British equivalent. Both indicate the patient must not eat, drink or take oral medications — commonly ordered before surgery or certain procedures." },
      { text: "What is a 'vital sign'?",
        options: [{ text: "A laboratory blood test result", isCorrect: false },{ text: "A measurable physiological parameter indicating the body's basic functions (BP, HR, RR, temp, SpO2)", isCorrect: true },{ text: "A sign of a life-threatening emergency only", isCorrect: false },{ text: "A clinical sign visible only on X-ray", isCorrect: false }],
        explanation: "Vital signs ('constantes vitales' in French) are measurable parameters indicating the body's basic functions: blood pressure (BP), heart rate (HR), respiratory rate (RR), temperature (Temp) and oxygen saturation (SpO2). They are the foundation of clinical assessment." },
      { text: "What does 'IV' stand for in medication administration?",
        options: [{ text: "Intravascular", isCorrect: false },{ text: "Intravenous", isCorrect: true },{ text: "Intravitreal", isCorrect: false },{ text: "Inferior vein", isCorrect: false }],
        explanation: "'IV' stands for 'Intravenous' — administration directly into a vein. Other common routes: IM (Intramuscular), SC or SubQ (Subcutaneous), PO (Per Os = oral), SL (Sublingual), ID (Intradermal), PR (Per Rectum). Knowing these abbreviations is essential for safe medication administration." },
      { text: "What is 'tachycardia'?",
        options: [{ text: "A heart rate below 60 beats per minute", isCorrect: false },{ text: "A heart rate above 100 beats per minute at rest", isCorrect: true },{ text: "Irregular heart rhythm", isCorrect: false },{ text: "Absence of heartbeat", isCorrect: false }],
        explanation: "Tachycardia (Greek 'tachys' = fast, 'kardia' = heart) is a resting heart rate above 100 bpm. Bradycardia is below 60 bpm. Arrhythmia is an irregular rhythm. 'Asystole' means absence of cardiac electrical activity. These terms appear in ECG interpretation and cardiac monitoring." },
      { text: "Which suffix means 'surgical removal of' in medical terms?",
        options: [{ text: "-itis", isCorrect: false },{ text: "-ectomy", isCorrect: true },{ text: "-oscopy", isCorrect: false },{ text: "-plasty", isCorrect: false }],
        explanation: "'-ectomy' means surgical removal: appendectomy (appendix), mastectomy (breast), cholecystectomy (gallbladder), gastrectomy (stomach). '-itis' = inflammation; '-oscopy' = visual examination (endoscopy); '-plasty' = surgical repair/reconstruction." },
      { text: "How would you ask a patient about their pain level in English?",
        options: [{ text: "Are you in pain? You look sad.", isCorrect: false },{ text: "On a scale from 0 to 10, where 0 is no pain and 10 is the worst pain imaginable, how would you rate your pain?", isCorrect: true },{ text: "Do you have a headache or a stomachache?", isCorrect: false },{ text: "Does it hurt a lot or a little?", isCorrect: false }],
        explanation: "The standardized pain assessment question uses the Numeric Rating Scale (NRS): 'On a scale of 0 to 10, where 0 is no pain and 10 is the worst pain imaginable, how would you rate your pain right now?' This is equivalent to the French ENS/EVA used clinically." },
      { text: "What does 'PRN' mean on a prescription?",
        options: [{ text: "Pre-renal nephropathy", isCorrect: false },{ text: "Pro Re Nata — as needed / when required", isCorrect: true },{ text: "Prolonged release nutritional supplement", isCorrect: false },{ text: "Prescribed by registered nurse", isCorrect: false }],
        explanation: "'PRN' (Latin: Pro Re Nata = as the situation demands) means 'as needed'. A PRN prescription is administered only when the patient requires it (e.g., paracetamol PRN for pain, antiemetic PRN for nausea), rather than on a fixed schedule. Equivalent to 'si besoin' in French." }
    ]
  },
  {
    title: "Anatomie et systèmes du corps en anglais",
    description: "Body systems anatomy vocabulary in English",
    semester: "Semestre 1", category: "UE 6.2 - Anglais médical",
    chapter: "Anatomy in English", difficulty: "easy", duration: 15, isPublished: true,
    questions: [
      { text: "What is the English term for 'poumon' ?",
        options: [{ text: "Kidney", isCorrect: false },{ text: "Lung", isCorrect: true },{ text: "Liver", isCorrect: false },{ text: "Spleen", isCorrect: false }],
        explanation: "'Lung' = poumon. 'Kidney' = rein. 'Liver' = foie. 'Spleen' = rate. 'Heart' = cœur. 'Brain' = cerveau. 'Stomach' = estomac. 'Intestine' = intestin. 'Gallbladder' = vésicule biliaire. 'Pancreas' = pancréas." },
      { text: "The term 'myocardial infarction' (MI) refers to:",
        options: [{ text: "Inflammation of the heart muscle", isCorrect: false },{ text: "A heart attack caused by blockage of a coronary artery", isCorrect: true },{ text: "A tear in the aorta", isCorrect: false },{ text: "Irregular heart rhythm", isCorrect: false }],
        explanation: "'Myocardial infarction' (MI) = heart attack ('infarctus du myocarde'). 'Myo' = muscle, 'cardio' = heart, 'infarction' = tissue death due to blocked blood supply. Also called 'acute coronary syndrome' (ACS) in its acute phase. Symptoms: chest pain, dyspnea, diaphoresis (sweating)." },
      { text: "What does 'hypertension' mean?",
        options: [{ text: "Low blood pressure", isCorrect: false },{ text: "High blood pressure (BP consistently above 140/90 mmHg)", isCorrect: true },{ text: "Fast heart rate", isCorrect: false },{ text: "Abnormal tension in muscles", isCorrect: false }],
        explanation: "'Hypertension' (HTN) = high blood pressure ('hypertension artérielle' in French). The prefix 'hyper-' means above/excessive; 'hypotension' = low blood pressure. BP is measured in mmHg (millimetres of mercury). Normal: < 120/80 mmHg; Hypertension: ≥ 140/90 mmHg." },
      { text: "Which body system does 'renal' refer to?",
        options: [{ text: "Respiratory system", isCorrect: false },{ text: "Urinary/kidney system", isCorrect: true },{ text: "Reproductive system", isCorrect: false },{ text: "Reticular system", isCorrect: false }],
        explanation: "'Renal' refers to the kidneys ('rénal' in French). Renal failure = insuffisance rénale. Related terms: 'nephrology' (study of kidneys), 'urinary tract infection' (UTI) = infection urinaire. 'Renal' comes from the Latin 'renes' (kidneys)." },
      { text: "What is 'diaphoresis'?",
        options: [{ text: "Difficulty breathing", isCorrect: false },{ text: "Excessive sweating", isCorrect: true },{ text: "Abnormal dilation of pupils", isCorrect: false },{ text: "Absence of urine production", isCorrect: false }],
        explanation: "'Diaphoresis' means profuse/excessive sweating ('diaphorèse' or 'sudation profuse' in French). It is a clinical sign seen in: hypoglycemia, myocardial infarction, shock, sepsis, fever, anxiety. 'Anhidrosis' = absence of sweating." },
      { text: "What is the English word for 'os' (bone)?",
        options: [{ text: "Cartilage", isCorrect: false },{ text: "Bone", isCorrect: true },{ text: "Joint", isCorrect: false },{ text: "Tendon", isCorrect: false }],
        explanation: "'Bone' = os. 'Joint' = articulation. 'Tendon' = tendon. 'Ligament' = ligament. 'Cartilage' = cartilage. 'Fracture' is the same in both languages. 'Orthopedics' (US) or 'orthopaedics' (UK) is the specialty dealing with the musculoskeletal system." },
      { text: "In a clinical handover in English, what does 'ISBAR' stand for?",
        options: [{ text: "Identify, Status, Background, Assessment, Recommendation", isCorrect: true },{ text: "Infection, Surgery, Blood, Allergy, Review", isCorrect: false },{ text: "Intake, Symptoms, Blood test, Allergy, Referral", isCorrect: false },{ text: "Intervention, Safety, Breathing, Alert, Report", isCorrect: false }],
        explanation: "ISBAR is the English equivalent of SBAR (used in French-speaking countries): Identity (patient ID), Situation (current clinical situation), Background (relevant history), Assessment (your clinical evaluation), Recommendation (what action you suggest). It structures clinical communication and reduces errors." },
      { text: "What does 'edema' (or 'oedema') mean?",
        options: [{ text: "A skin rash", isCorrect: false },{ text: "Abnormal accumulation of fluid in body tissues causing swelling", isCorrect: true },{ text: "An allergic reaction", isCorrect: false },{ text: "Internal bleeding", isCorrect: false }],
        explanation: "'Edema' (American spelling) or 'oedema' (British) = 'œdème' in French. It refers to excess fluid accumulation in interstitial spaces causing swelling. Types: pitting edema (leaves a dent when pressed), pulmonary edema (lungs), cerebral edema (brain), peripheral edema (ankles/feet)." },
      { text: "What is the meaning of 'subcutaneous' (SC or SubQ)?",
        options: [{ text: "Under the skin (between the dermis and the muscle)", isCorrect: true },{ text: "Inside a vein", isCorrect: false },{ text: "Under the muscle", isCorrect: false },{ text: "Inside the spinal canal", isCorrect: false }],
        explanation: "'Subcutaneous' (SC/SubQ) = 'sous-cutané' in French. 'Sub-' means 'below/under', 'cutaneous' relates to the skin ('cutis'). SC injections are given in the fatty layer beneath the dermis. Used for: insulin, LMWH (heparin), vaccines. Angle: 45-90° depending on adipose tissue thickness." },
      { text: "What is 'anemia' (or 'anaemia')?",
        options: [{ text: "Excess of red blood cells", isCorrect: false },{ text: "Deficiency of red blood cells or hemoglobin, reducing oxygen-carrying capacity", isCorrect: true },{ text: "Absence of white blood cells", isCorrect: false },{ text: "Excess of platelets", isCorrect: false }],
        explanation: "'Anemia' (US) / 'anaemia' (UK) = 'anémie' in French. It is defined by hemoglobin below normal levels (< 12 g/dL in women, < 13 g/dL in men). Causes: iron deficiency (most common), vitamin B12/B9 deficiency, blood loss, hemolysis, chronic disease. Symptoms: fatigue, pallor, dyspnea on exertion." }
    ]
  },
  {
    title: "Communication clinique en anglais",
    description: "Communicating with patients and colleagues in English in a clinical setting",
    semester: "Semestre 1", category: "UE 6.2 - Anglais médical",
    chapter: "Clinical communication in English", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "How would you introduce yourself to an English-speaking patient?",
        options: [{ text: "I am the nurse. What do you need?", isCorrect: false },{ text: "Good morning, my name is [name], I'll be your nurse today. How are you feeling?", isCorrect: true },{ text: "Hello. I will do your care now.", isCorrect: false },{ text: "I'm here to check on you. Do you have pain?", isCorrect: false }],
        explanation: "A professional introduction includes: greeting (Good morning/afternoon), your name, your role, and an open question about the patient's wellbeing. This establishes trust and opens communication. In formal settings, use 'Mr/Mrs [surname]' unless the patient prefers their first name." },
      { text: "How do you explain to a patient that they need to fast before surgery?",
        options: [{ text: "You must not eat. Surgery is coming.", isCorrect: false },{ text: "From midnight tonight, you must not eat or drink anything — including water — before your operation.", isCorrect: true },{ text: "No food please. Doctor's orders.", isCorrect: false },{ text: "It's better if you don't eat too much before the operation.", isCorrect: false }],
        explanation: "Clear preoperative fasting instructions should include: the specific time from which fasting begins, what is prohibited (food AND fluids, including water), and why (to reduce aspiration risk during anesthesia). Always use simple, direct language without medical jargon when speaking to patients." },
      { text: "A patient says: 'I'm allergic to penicillin.' What is the correct nursing response?",
        options: [{ text: "Don't worry, we won't give you penicillin.", isCorrect: false },{ text: "Thank you for telling me. Can you describe what happened when you took penicillin? I'll document this allergy in your records immediately.", isCorrect: true },{ text: "Are you sure? Penicillin allergy is very rare.", isCorrect: false },{ text: "OK, I'll pass this information to the doctor later.", isCorrect: false }],
        explanation: "When a patient reports an allergy: 1) Thank them for the information; 2) Clarify the type of reaction (rash, anaphylaxis, intolerance); 3) Document it immediately in the medical record and alert wristband; 4) Inform the medical team. Never dismiss or delay allergy documentation — it is a patient safety priority." },
      { text: "Which phrase is used to check patient understanding after giving instructions?",
        options: [{ text: "Did you listen to everything I said?", isCorrect: false },{ text: "Could you explain back to me in your own words what we just discussed?", isCorrect: true },{ text: "Do you understand? Yes or no?", isCorrect: false },{ text: "It's very simple, so you should understand.", isCorrect: false }],
        explanation: "The 'teach-back method' (or 'return demonstration') asks the patient to explain what they understood in their own words: 'Could you tell me in your own words what you're going to do when you get home?' This is the gold standard for verifying health literacy and understanding." },
      { text: "How would you say 'tension artérielle' in English?",
        options: [{ text: "Heart rate", isCorrect: false },{ text: "Blood pressure (BP)", isCorrect: true },{ text: "Pulse rate", isCorrect: false },{ text: "Arterial tension index", isCorrect: false }],
        explanation: "'Blood pressure' (BP) = 'tension artérielle' (TA or PA in French). It is measured in mmHg with a sphygmomanometer ('tensiomètre'). Systolic pressure ('pression systolique') / diastolic pressure ('pression diastolique'). Normal: < 120/80 mmHg. 'Pulse' or 'pulse rate' = pouls/fréquence cardiaque." },
      { text: "What does a nurse say when preparing to give an injection?",
        options: [{ text: "I'm going to hurt you now. Hold on.", isCorrect: false },{ text: "I'm going to give you an injection now. You may feel a small pinch. Please try to relax your arm.", isCorrect: true },{ text: "Injection time! Don't move.", isCorrect: false },{ text: "This will be very painful. Are you ready?", isCorrect: false }],
        explanation: "Before an injection: inform the patient ('I'm going to give you an injection'), describe the sensation ('you may feel a small pinch or sting'), ask them to relax the muscle, and reassure ('it will only take a moment'). This respects informed consent and reduces anxiety." },
      { text: "What does 'DNR' or 'DNAR' mean in a clinical context?",
        options: [{ text: "Do Not Refer (to a specialist)", isCorrect: false },{ text: "Do Not Resuscitate / Do Not Attempt Resuscitation — no CPR if cardiac arrest", isCorrect: true },{ text: "Daily Nurse Report", isCorrect: false },{ text: "Drug Not Required", isCorrect: false }],
        explanation: "'DNR' (Do Not Resuscitate) or 'DNAR' (Do Not Attempt Resuscitation) = 'directive de ne pas réanimer'. It is a medical order indicating that CPR should not be initiated if the patient's heart stops. Equivalent to 'LATA' (Limitation et arrêt des thérapeutiques actives) in French. Must be clearly documented and communicated to all team members." },
      { text: "How would you ask a patient if they have any allergies?",
        options: [{ text: "You're not allergic to anything, right?", isCorrect: false },{ text: "Do you have any known allergies to medications, foods, or latex?", isCorrect: true },{ text: "Are you allergic to penicillin?", isCorrect: false },{ text: "Have you ever taken antibiotics before?", isCorrect: false }],
        explanation: "The standardized allergy screening question covers all categories: medications (including antibiotics, NSAIDs, anaesthetics), foods (nuts, shellfish, eggs), latex (relevant for surgical procedures), and contrast dye. Always ask with an open-ended question, then document the reaction type, not just the allergen." },
      { text: "What does the abbreviation 'Hx' stand for in clinical notes?",
        options: [{ text: "Heart examination", isCorrect: false },{ text: "History (medical history)", isCorrect: true },{ text: "Hexokinase test", isCorrect: false },{ text: "Hospital transfer", isCorrect: false }],
        explanation: "'Hx' = History (medical history). Common clinical abbreviations in English: Dx = Diagnosis; Tx = Treatment; Rx = Prescription; Sx = Symptoms; PMHx = Past Medical History; FHx = Family History; SHx = Social History. These abbreviations appear frequently in English-language patient notes and international clinical literature." },
      { text: "What is the English equivalent of 'bilan sanguin' (blood tests)?",
        options: [{ text: "Blood survey", isCorrect: false },{ text: "Blood work / blood panel / laboratory tests", isCorrect: true },{ text: "Blood count only", isCorrect: false },{ text: "Blood sample", isCorrect: false }],
        explanation: "'Blood work' or 'blood panel' = 'bilan sanguin'. Specific tests: CBC (Complete Blood Count) = NFS (Numération Formule Sanguine); BMP/CMP (Basic/Comprehensive Metabolic Panel) = bilan métabolique; ABG (Arterial Blood Gas) = gaz du sang artériel; PT/INR = TP/INR (coagulation). 'Blood sample' = 'prélèvement sanguin' (the act of taking blood)." }
    ]
  },
  {
    title: "Situations cliniques et abréviations médicales en anglais",
    description: "Clinical scenarios and key medical abbreviations in English",
    semester: "Semestre 1", category: "UE 6.2 - Anglais médical",
    chapter: "Clinical situations and abbreviations", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "A patient's SpO2 is 88% and they are breathing rapidly. What would you say to the team?",
        options: [{ text: "The patient seems a little tired.", isCorrect: false },{ text: "The patient is desaturating — SpO2 88%, tachypneic. I'm applying oxygen and requesting urgent medical review.", isCorrect: true },{ text: "I think the monitor might be wrong.", isCorrect: false },{ text: "Should I give them water?", isCorrect: false }],
        explanation: "An SpO2 of 88% with tachypnea (fast breathing) is a medical emergency requiring immediate action: apply supplemental oxygen, call the team using ISBAR structure, monitor continuously. Normal SpO2 ≥ 95%; 88% indicates significant hypoxemia ('désaturation' in French)." },
      { text: "What does 'COPD' stand for?",
        options: [{ text: "Coronary Obstructive Pulmonary Disease", isCorrect: false },{ text: "Chronic Obstructive Pulmonary Disease", isCorrect: true },{ text: "Cardiac Output and Pulmonary Dysfunction", isCorrect: false },{ text: "Chronic Obstructive Peripheral Disease", isCorrect: false }],
        explanation: "'COPD' (Chronic Obstructive Pulmonary Disease) = 'BPCO' (Bronchopneumopathie Chronique Obstructive) in French. It is a progressive lung disease causing airflow limitation — mainly caused by smoking. Includes chronic bronchitis and emphysema. Treated with bronchodilators (SABA, LABA) and inhaled corticosteroids." },
      { text: "What does 'CVA' stand for in medical English?",
        options: [{ text: "Cardiac Valve Assessment", isCorrect: false },{ text: "Cerebrovascular Accident (stroke)", isCorrect: true },{ text: "Cervical Vertebra Alignment", isCorrect: false },{ text: "Central Venous Access", isCorrect: false }],
        explanation: "'CVA' (Cerebrovascular Accident) = stroke = 'AVC' (Accident Vasculaire Cérébral) in French. There are two types: ischemic stroke (blockage of a cerebral artery, 80%) and hemorrhagic stroke (bleeding in the brain, 20%). The acronym FAST (Face drooping, Arm weakness, Speech difficulty, Time to call emergency) helps recognize stroke signs." },
      { text: "What is a 'urinary catheter' used for?",
        options: [{ text: "Measuring blood pressure", isCorrect: false },{ text: "Draining urine directly from the bladder via the urethra", isCorrect: true },{ text: "Administering intravenous fluids", isCorrect: false },{ text: "Collecting a stool sample", isCorrect: false }],
        explanation: "A 'urinary catheter' = 'sonde urinaire' in French. A Foley catheter (with balloon to hold it in place) is used for: urinary retention, monitoring urine output, incontinence management, post-operative care, certain urological procedures. Strict aseptic technique is required to prevent CAUTI (catheter-associated urinary tract infections)." },
      { text: "The medical abbreviation 'OD' means:",
        options: [{ text: "Once daily (once per day)", isCorrect: true },{ text: "Overdose only", isCorrect: false },{ text: "On demand", isCorrect: false },{ text: "Oral dose", isCorrect: false }],
        explanation: "'OD' (Latin: omni die = every day) = once daily. Other Latin dosing abbreviations: BD/BID = twice daily; TDS/TID = three times daily; QDS/QID = four times daily; PRN = as needed; STAT = immediately; AC = before meals; PC = after meals; HS = at bedtime. Understanding these abbreviations is essential for safe medication administration." },
      { text: "What does 'ICU' stand for?",
        options: [{ text: "Internal Care Unit", isCorrect: false },{ text: "Intensive Care Unit", isCorrect: true },{ text: "Integrated Clinical Unit", isCorrect: false },{ text: "Infectious Control Unit", isCorrect: false }],
        explanation: "'ICU' (Intensive Care Unit) = 'réanimation' or 'soins intensifs' (SI) in French. The ICU provides intensive monitoring and life support for critically ill patients. 'HDU' (High Dependency Unit) = 'unité de soins continus' (USC). 'A&E' or 'ED' (Emergency Department) = 'urgences'." },
      { text: "A patient is described as 'febrile'. This means they have:",
        options: [{ text: "Low blood pressure", isCorrect: false },{ text: "An elevated body temperature (fever)", isCorrect: true },{ text: "Abdominal pain", isCorrect: false },{ text: "Shortness of breath", isCorrect: false }],
        explanation: "'Febrile' = 'fébrile' (having a fever). Fever is defined as body temperature > 38°C (100.4°F). 'Afebrile' = without fever. Fever is assessed by: oral, tympanic (ear), axillary, or rectal thermometry. It is a key clinical indicator of infection, inflammation, or other systemic processes." },
      { text: "What does the AVPU scale assess?",
        options: [{ text: "Pain intensity (A=Absent, V=Visible, P=Present, U=Unbearable)", isCorrect: false },{ text: "Level of consciousness (Alert, Voice, Pain, Unresponsive)", isCorrect: true },{ text: "Allergy severity (Anaphylaxis, Vomiting, Pain, Urticaria)", isCorrect: false },{ text: "Cardiac rhythm (Atrial, Ventricular, Pacemaker, Unknown)", isCorrect: false }],
        explanation: "The AVPU scale rapidly assesses level of consciousness: A = Alert (fully awake, equivalent to GCS 15); V = responds to Voice (GCS 9-13); P = responds to Pain only (GCS 5-8); U = Unresponsive (GCS 3, coma). It is used in rapid clinical assessment (triage, ward deterioration) and is simpler than the full Glasgow Coma Scale." },
      { text: "What is 'handwashing compliance' in infection control?",
        options: [{ text: "The availability of soap and water in a clinical area", isCorrect: false },{ text: "The rate at which healthcare workers correctly perform hand hygiene at the required moments", isCorrect: true },{ text: "The patient's ability to wash their own hands", isCorrect: false },{ text: "The frequency of environmental cleaning", isCorrect: false }],
        explanation: "'Hand hygiene compliance' = taux d'observance à l'hygiène des mains. It measures how often healthcare workers (HCWs) perform hand hygiene at the WHO's '5 Moments': before patient contact, before aseptic procedure, after body fluid exposure, after patient contact, and after touching patient surroundings. WHO target: > 80% compliance." },
      { text: "A patient is described as being 'nil by mouth' (NBM). The nurse should:",
        options: [{ text: "Offer them water only, not food", isCorrect: false },{ text: "Ensure no oral intake (food, fluids, medications by mouth), provide oral hygiene and IV hydration if prescribed", isCorrect: true },{ text: "Allow small sips of water every 2 hours", isCorrect: false },{ text: "Ask the doctor if tea without sugar is permitted", isCorrect: false }],
        explanation: "NBM (Nil By Mouth) = NPO = 'à jeun strict'. No food, no fluids (including water, ice chips), no oral medications unless specifically ordered. Key nursing actions: explain to patient, place NBM sign above the bed, provide regular oral hygiene (mouth swabs to prevent dryness), ensure IV fluids are running if prescribed, document." }
    ]
  }
];
