// ─── PARTIE 7 : 2e quiz par chapitre — UE 2.4 · UE 2.10 · UE 2.11 · UE 3.1 ─
module.exports = [

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 2.4 – Processus traumatiques
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Cicatrisation et prise en charge des plaies chroniques",
    description: "Phases de cicatrisation, types de plaies et soins adaptés",
    semester: "Semestre 1", category: "UE 2.4 - Processus traumatiques",
    chapter: "Inflammation", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Lors de la phase inflammatoire de la cicatrisation, on observe :",
        options: [{ text: "Formation de tissu de granulation rouge vif", isCorrect: false },{ text: "Vasodilatation, œdème, rougeur, chaleur et afflux de cellules immunitaires", isCorrect: true },{ text: "Épidermisation et fermeture de la plaie", isCorrect: false },{ text: "Remodelage du collagène uniquement", isCorrect: false }],
        explanation: "La phase inflammatoire (J0–J5) est caractérisée par la réponse vasculaire (vasodilatation, œdème) et l'afflux de neutrophiles puis macrophages qui détruisent les débris et bactéries." },
      { text: "Le tissu de granulation d'une plaie est reconnaissable car il est :",
        options: [{ text: "Blanc et fibreux", isCorrect: false },{ text: "Rouge vif, bourgeonnant, fragile et saignant facilement", isCorrect: true },{ text: "Jaune et purulent", isCorrect: false },{ text: "Noir et nécrotique", isCorrect: false }],
        explanation: "Le tissu de granulation (phase proliférative) est rouge vif, granuleux, fragile et saignant facilement. Il comble la plaie grâce à la néoangiogenèse et aux fibroblastes. C'est un signe favorable." },
      { text: "La classification colorimétrique des plaies chroniques : que signifie une plaie JAUNE ?",
        options: [{ text: "Nécrose sèche à déterger", isCorrect: false },{ text: "Présence de fibrine et de tissu nécrotique humide, nécessitant une détersion", isCorrect: true },{ text: "Tissu de granulation sain à protéger", isCorrect: false },{ text: "Épidermisation en cours", isCorrect: false }],
        explanation: "Jaune = fibrine (tissu mort humide). Nécessite une détersion (autolytique, mécanique ou chirurgicale) pour préparer la plaie. À distinguer du rouge (granulation à protéger) et du noir (nécrose sèche)." },
      { text: "Un facteur LOCAL défavorable à la cicatrisation est :",
        options: [{ text: "L'âge avancé du patient", isCorrect: false },{ text: "L'infection de la plaie et la présence de corps étrangers", isCorrect: true },{ text: "La corticothérapie systémique", isCorrect: false },{ text: "La dénutrition protéique", isCorrect: false }],
        explanation: "Facteurs locaux défavorables : infection (biofilm), corps étrangers, hématome, ischémie locale, mauvais pansement, cisaillement/friction. Les facteurs généraux incluent diabète, âge, dénutrition." },
      { text: "L'escarre de stade 2 se caractérise par :",
        options: [{ text: "Un érythème non blanchissable sur peau intacte", isCorrect: false },{ text: "Une phlyctène (cloque) ou une abrasion superficielle du derme", isCorrect: true },{ text: "Une perte de substance avec atteinte du tissu sous-cutané", isCorrect: false },{ text: "Une nécrose profonde atteignant l'os", isCorrect: false }],
        explanation: "Escarre stade 2 (NPUAP/EPUAP) : perte partielle de peau — phlyctène intacte ou rompue, ou abrasion superficielle du derme. Le derme profond n'est pas atteint." },
      { text: "La détersion enzymatique des plaies utilise :",
        options: [{ text: "De la Bétadine pour dissoudre les tissus nécrotiques", isCorrect: false },{ text: "Des pommades contenant des enzymes protéolytiques pour dégrader les tissus morts", isCorrect: true },{ text: "De l'eau oxygénée à forte concentration", isCorrect: false },{ text: "Un courant électrique de basse fréquence", isCorrect: false }],
        explanation: "La détersion enzymatique utilise des préparations à base de collagénase (ex : Flammazine®, Iruxol®) qui dégradent sélectivement le tissu nécrotique sans altérer le tissu sain." },
      { text: "Le choix du pansement pour une plaie avec tissu de granulation et faible exsudat est :",
        options: [{ text: "Compresse sèche non adhérente changée 2×/jour", isCorrect: false },{ text: "Pansement hydrocolloïde fin ou interface de type tulle gras pour protéger et maintenir l'humidité", isCorrect: true },{ text: "Alginates pour absorber l'exsudat abondant", isCorrect: false },{ text: "Charbon actif pour les odeurs", isCorrect: false }],
        explanation: "En phase de granulation avec faible exsudat : pansement maintenant l'humidité (hydrocolloïde) ou interface non adhérente (tulle gras, Urgotul®). Les alginates sont pour les plaies très exsudatives." },
      { text: "La surveillance d'une plaie opératoire (ISO) en post-opératoire précoce comprend :",
        options: [{ text: "Uniquement la douleur et la température locale", isCorrect: false },{ text: "Aspect (rougeur, chaleur, œdème, écoulement), douleur, température et cicatrice en tension", isCorrect: true },{ text: "La mesure de la taille de la plaie uniquement", isCorrect: false },{ text: "Le changement quotidien du pansement sans observation", isCorrect: false }],
        explanation: "Surveillance ISO : signes locaux d'infection (rougeur, chaleur, tuméfaction, écoulement purulent), douleur locale, fièvre, désunion de la cicatrice. Documentation systématique avec traçabilité." },
      { text: "La cicatrice chéloïde se différencie de la cicatrice hypertrophique car :",
        options: [{ text: "Elle est plus petite que la plaie initiale", isCorrect: false },{ text: "Elle déborde largement au-delà des bords de la plaie initiale", isCorrect: true },{ text: "Elle disparaît spontanément en quelques mois", isCorrect: false },{ text: "Elle ne provoque aucun symptôme", isCorrect: false }],
        explanation: "La cicatrice chéloïde envahit les tissus sains au-delà de la plaie initiale (envahissement). La cicatrice hypertrophique reste dans les limites de la plaie. Toutes deux sont liées à une surproduction de collagène." },
      { text: "L'objectif d'une plaie maintenue en milieu humide est :",
        options: [{ text: "Réduire le risque infectieux par dessiccation des bactéries", isCorrect: false },{ text: "Favoriser la migration cellulaire et accélérer la cicatrisation", isCorrect: true },{ text: "Faciliter le retrait du pansement sans douleur uniquement", isCorrect: false },{ text: "Réduire les coûts en limitant les changements de pansement", isCorrect: false }],
        explanation: "Le maintien d'un milieu humide (concept de Winter, 1962) accélère la cicatrisation en favorisant la migration des fibroblastes et kératinocytes, protège les terminaisons nerveuses et limite la douleur." }
    ]
  },
  {
    title: "Traumatologie avancée : chocs, fractures complexes et urgences",
    description: "États de choc, fractures ouvertes, syndrome des loges, urgences traumatiques",
    semester: "Semestre 1", category: "UE 2.4 - Processus traumatiques",
    chapter: "Traumatologie", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "Dans le choc hypovolémique de stade 3, on observe :",
        options: [{ text: "PA normale, légère tachycardie, anxiété modérée", isCorrect: false },{ text: "Hypotension franche, tachycardie > 120 bpm, confusion, oligurie sévère", isCorrect: true },{ text: "Bradycardie paradoxale et peau rosée", isCorrect: false },{ text: "Perte de 15% de la volémie uniquement", isCorrect: false }],
        explanation: "Choc stade 3 (perte 30–40% volémie) : hypotension franche, tachycardie > 120 bpm, confusion mentale, peau froide et marbrée, oligurie. Urgence vitale nécessitant remplissage rapide et transfusion." },
      { text: "Le premier geste devant une hémorragie externe abondante est :",
        options: [{ text: "Poser un garrot et appeler le 15", isCorrect: false },{ text: "Compression manuelle directe et ferme sur le point de saignement", isCorrect: true },{ text: "Appeler les secours sans toucher la plaie", isCorrect: false },{ text: "Mettre le patient en position de choc (jambes surélevées) avant toute autre action", isCorrect: false }],
        explanation: "La compression manuelle directe est LE premier geste anti-hémorragique. Elle est simple, efficace et immédiate. Le garrot n'est utilisé qu'en cas d'échec ou d'hémorragie non compressible des membres." },
      { text: "Le syndrome des loges est une urgence chirurgicale car :",
        options: [{ text: "Il provoque une infection rapide du tissu osseux", isCorrect: false },{ text: "La pression dans la loge dépasse la pression de perfusion capillaire → ischémie musculaire irréversible", isCorrect: true },{ text: "Il entraîne une thrombose veineuse profonde systématique", isCorrect: false },{ text: "Il cause une paralysie définitive par atteinte nerveuse centrale", isCorrect: false }],
        explanation: "Le syndrome des loges : augmentation de pression dans la loge musculaire (plâtre serré, hématome) → compression vasculo-nerveuse → ischémie. Au-delà de 6h : nécrose musculaire irréversible. Traitement : fasciotomie." },
      { text: "Une fracture ouverte de type III (Gustilo) implique :",
        options: [{ text: "Une plaie < 1 cm avec contamination minime", isCorrect: false },{ text: "Une plaie > 10 cm avec contamination massive et lésions vasculo-nerveuses", isCorrect: true },{ text: "Une fracture fermée avec hématome sous-cutané", isCorrect: false },{ text: "Une fracture avec un fragment osseux exposé < 5 cm", isCorrect: false }],
        explanation: "Classification de Gustilo : Type I (plaie < 1 cm, propre), Type II (1–10 cm), Type III (> 10 cm, contamination massive, lésions vasculo-nerveuses). Plus le grade est élevé, plus le risque infectieux et de complication est élevé." },
      { text: "La surveillance d'un membre plâtré comprend les 6 P :",
        options: [{ text: "Pression, Pouls, Peau, Phlébite, Position, Pharmacologie", isCorrect: false },{ text: "Pain (douleur), Pressure (tension), Paresthésie, Paralysie, Pallor (pâleur), Pulselessness (pouls aboli)", isCorrect: true },{ text: "Poids, Périmètre, Pouls, PA, Papule, Prurit", isCorrect: false },{ text: "Plaie, Pus, Pyrexie, Paralysie, Plâtre, Périmètre", isCorrect: false }],
        explanation: "Les 6P du syndrome des loges doivent être surveillés après tout plâtrage : douleur disproportionnée, tension de la loge, paresthésies, paralysie, pâleur et abolition du pouls distal." },
      { text: "Devant une luxation de hanche prothétique, la position à éviter est :",
        options: [{ text: "La position allongée sur le dos", isCorrect: false },{ text: "La flexion de hanche > 90° et la rotation interne (selon le type de prothèse)", isCorrect: true },{ text: "La position assise avec hanches à 90°", isCorrect: false },{ text: "La marche avec appui partiel", isCorrect: false }],
        explanation: "Après PTH par voie postérieure : éviter flexion > 90°, adduction et rotation interne (risque de luxation postérieure). Par voie antérieure : éviter extension et rotation externe." },
      { text: "Le traitement de l'entorse de cheville grade 3 (rupture ligamentaire totale) est :",
        options: [{ text: "Repos 24h et reprise d'activité immédiate", isCorrect: false },{ text: "Immobilisation courte (botte ou attelle), puis rééducation proprioceptive intensive", isCorrect: true },{ text: "Chirurgie systématique dans les 24h", isCorrect: false },{ text: "Infiltration de corticoïdes et anti-inflammatoires uniquement", isCorrect: false }],
        explanation: "Grade 3 (rupture totale) : immobilisation courte (2–3 semaines en botte) puis rééducation proprioceptive intensive. La chirurgie est réservée aux cas d'instabilité chronique persistante après rééducation." },
      { text: "La complication la plus redoutée d'une fracture du col du fémur chez le sujet âgé est :",
        options: [{ text: "L'infection post-opératoire systématique", isCorrect: false },{ text: "La nécrose aseptique de la tête fémorale et les complications du décubitus (pneumopathie, EP, escarres)", isCorrect: true },{ text: "La non-consolidation uniquement", isCorrect: false },{ text: "La coxarthrose secondaire uniquement", isCorrect: false }],
        explanation: "Fracture du col du fémur chez le sujet âgé : risque de nécrose aseptique (ligament rond lésé), mais surtout complications de l'alitement si chirurgie retardée (TVP, EP, pneumopathie, escarres, dénutrition). Opérer vite." },
      { text: "L'immobilisation plâtrée circulaire est contre-indiquée dans les premières heures post-traumatiques car :",
        options: [{ text: "Elle empêche la radiographie de contrôle", isCorrect: false },{ text: "L'œdème post-traumatique peut augmenter et créer une compression dans un plâtre circulaire rigide", isCorrect: true },{ text: "Elle favorise les infections locales", isCorrect: false },{ text: "Elle est trop lourde pour le patient", isCorrect: false }],
        explanation: "En phase aiguë, l'œdème est progressif. Un plâtre circulaire rigide posé trop tôt peut devenir compressif → syndrome des loges. On préfère une attelle (gouttière) bivalvée les premières 48–72h." },
      { text: "La prévention de l'embolie pulmonaire après fracture du membre inférieur repose sur :",
        options: [{ text: "Le repos strict au lit pendant 3 semaines", isCorrect: false },{ text: "Anticoagulation préventive (HBPM), bas de contention, mobilisation précoce", isCorrect: true },{ text: "L'aspirine à forte dose uniquement", isCorrect: false },{ text: "L'hydratation orale abondante uniquement", isCorrect: false }],
        explanation: "Prévention TVP/EP après fracture MI : HBPM prophylactique, bas de contention, mobilisation précoce (lever précoce), hydratation. La durée de l'anticoagulation dépend du type de fracture et du terrain." }
    ]
  },
  {
    title: "Évaluation et prise en charge de la douleur aiguë et chronique",
    description: "Outils d'évaluation, paliers antalgiques et douleur neuropathique",
    semester: "Semestre 1", category: "UE 2.4 - Processus traumatiques",
    chapter: "Douleur", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "La douleur neuropathique se distingue de la douleur nociceptive par :",
        options: [{ text: "Son intensité toujours plus élevée (EVA > 8)", isCorrect: false },{ text: "Des brûlures, décharges électriques, allodynie et mauvaise réponse aux AINS", isCorrect: true },{ text: "Une localisation exclusivement abdominale", isCorrect: false },{ text: "Sa réponse excellente aux opioïdes forts", isCorrect: false }],
        explanation: "Douleur neuropathique : lésion du système nerveux → brûlures, fourmillements, décharges électriques, allodynie (douleur au toucher léger). Répond mal aux AINS mais mieux aux antidépresseurs (amitriptyline) et antiépileptiques (gabapentine)." },
      { text: "L'échelle ALGOPLUS est utilisée pour évaluer la douleur chez :",
        options: [{ text: "Les nourrissons de 0 à 3 mois", isCorrect: false },{ text: "Les personnes âgées avec troubles de la communication en situation aiguë", isCorrect: true },{ text: "Les patients sous sédation en réanimation", isCorrect: false },{ text: "Les enfants de 4 à 12 ans", isCorrect: false }],
        explanation: "ALGOPLUS est une échelle comportementale d'hétéro-évaluation pour la personne âgée en douleur aiguë (urgences, soins). 5 items comportementaux. Seuil d'intervention : score ≥ 2." },
      { text: "La morphine orale à libération prolongée (LP) doit être administrée :",
        options: [{ text: "En cas de douleur intense, à la demande du patient", isCorrect: false },{ text: "À heures fixes toutes les 12h pour maintenir un taux sérique stable", isCorrect: true },{ text: "Uniquement en cas d'échec des opioïdes faibles et écrasée si nécessaire", isCorrect: false },{ text: "Une seule fois par jour le matin uniquement", isCorrect: false }],
        explanation: "Les morphiniques LP (MST Continus®, Skenan®) s'administrent à heures FIXES toutes les 12h pour maintenir un taux sanguin stable. JAMAIS écraser. Les accès douloureux sont traités par morphine à libération immédiate." },
      { text: "L'allodynie est définie comme :",
        options: [{ text: "Une douleur absente malgré une lésion tissulaire évidente", isCorrect: false },{ text: "Une douleur provoquée par un stimulus normalement non douloureux", isCorrect: true },{ text: "Une augmentation anormale de la réponse à un stimulus douloureux", isCorrect: false },{ text: "Une douleur fantôme après amputation", isCorrect: false }],
        explanation: "L'allodynie : un stimulus normalement indolore (effleurement, contact vestimentaire, température ambiante) provoque une douleur. Elle est caractéristique des douleurs neuropathiques." },
      { text: "La PCA (Patient Controlled Analgesia) permet au patient de :",
        options: [{ text: "S'administrer des bolus de morphine IV sans limitation", isCorrect: false },{ text: "S'autoadministrer des bolus de morphine IV dans les limites programmées par le médecin", isCorrect: true },{ text: "Choisir librement son antalgique parmi plusieurs options", isCorrect: false },{ text: "Adapter sa dose de morphine LP selon sa douleur", isCorrect: false }],
        explanation: "La PCA est une pompe programmée par le médecin qui permet au patient de s'administrer des bolus d'antalgique IV en cas de douleur, avec une dose maximale et un délai réfractaire programmés." },
      { text: "Les co-antalgiques (adjuvants) comprennent :",
        options: [{ text: "Les AINS et le paracétamol uniquement", isCorrect: false },{ text: "Les antidépresseurs (amitriptyline), antiépileptiques (gabapentine), corticoïdes et kétamine", isCorrect: true },{ text: "Les opioïdes de palier 2 uniquement", isCorrect: false },{ text: "Les anxiolytiques et somnifères uniquement", isCorrect: false }],
        explanation: "Les co-antalgiques potentialisent l'effet antalgique ou traitent un type de douleur spécifique : antidépresseurs et antiépileptiques pour les neuropathies, corticoïdes pour l'inflammation, kétamine pour les douleurs réfractaires." },
      { text: "La surveillance d'un patient sous morphine IV en PCA comprend :",
        options: [{ text: "Uniquement la douleur par EVA", isCorrect: false },{ text: "EVA, fréquence respiratoire, sédation (score de Ramsay), SpO₂ et signe de dépression respiratoire", isCorrect: true },{ text: "La pression artérielle et la température uniquement", isCorrect: false },{ text: "La diurèse et le transit uniquement", isCorrect: false }],
        explanation: "Surveillance morphine IV : EVA (efficacité), FR (dépression respiratoire si < 12/min), sédation (Ramsay : si > 2, réduire dose), SpO₂ (< 94% = alarme). Antidote : Naloxone (Narcan®) disponible." },
      { text: "La douleur provoquée par les soins (DPS) doit être anticipée par :",
        options: [{ text: "L'information seule sans traitement médicamenteux", isCorrect: false },{ text: "Une prémédication antalgique adaptée, une anesthésie locale et des techniques non pharmacologiques", isCorrect: true },{ text: "L'accélération du soin pour réduire la durée de la douleur", isCorrect: false },{ text: "La sédation générale systématique", isCorrect: false }],
        explanation: "La DPS est anticipée : prémédication 30–60 min avant (paracétamol, AINS, opioïde), anesthésie locale (EMLA, xylocaïne), et techniques non pharmacologiques (distraction, hypnose, MEOPA)." },
      { text: "Le MEOPA (Mélange Équimolaire O₂ Protoxyde d'Azote) est indiqué pour :",
        options: [{ text: "La sédation profonde en réanimation", isCorrect: false },{ text: "L'analgésie de courte durée lors de soins douloureux (pansements, ponctions)", isCorrect: true },{ text: "Le traitement des douleurs neuropathiques chroniques", isCorrect: false },{ text: "Le traitement des crises hyperalgiques drépanocytaires uniquement", isCorrect: false }],
        explanation: "Le MEOPA (Kalinox®) est un gaz analgésique et anxiolytique utilisé pour les soins douloureux de courte durée. Effet rapide (3 min) et réversible à l'arrêt. Utilisable à domicile par IDE formée." },
      { text: "L'hyperalgésie induite par les opioïdes (OIH) se manifeste par :",
        options: [{ text: "Une réduction progressive de la douleur au fil du traitement", isCorrect: false },{ text: "Une augmentation paradoxale de la douleur malgré l'augmentation des doses d'opioïdes", isCorrect: true },{ text: "Une accoutumance rapide et une efficacité maintenue à forte dose", isCorrect: false },{ text: "Une douleur uniquement au site d'injection de l'opioïde", isCorrect: false }],
        explanation: "L'OIH : phénomène paradoxal où les opioïdes à forte dose ou au long cours sensibilisent les nocicepteurs → la douleur augmente au lieu de diminuer. Prise en charge : rotation des opioïdes, kétamine, réduction des doses." }
    ]
  },
  {
    title: "Physiopathologie des processus tumoraux et dégénératifs",
    description: "Cancer, inflammation chronique, processus dégénératifs et implications infirmières",
    semester: "Semestre 1", category: "UE 2.4 - Processus traumatiques",
    chapter: "Physiopathologie", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "La carcinogenèse (processus tumoral) est liée à :",
        options: [{ text: "Une multiplication trop lente des cellules", isCorrect: false },{ text: "Des mutations génétiques affectant les gènes de prolifération et de mort cellulaire", isCorrect: true },{ text: "Un excès de cellules immunitaires dans l'organisme", isCorrect: false },{ text: "Une réponse inflammatoire exagérée uniquement", isCorrect: false }],
        explanation: "La carcinogenèse implique des mutations dans les proto-oncogènes (activateurs de division) et les gènes suppresseurs de tumeur (inhibiteurs). Ces mutations permettent une division incontrôlée et l'échappement à l'apoptose." },
      { text: "La différence entre une tumeur bénigne et maligne est :",
        options: [{ text: "La taille uniquement : > 5 cm = maligne", isCorrect: false },{ text: "La tumeur maligne envahit les tissus voisins et peut métastaser ; la bénigne reste encapsulée", isCorrect: true },{ text: "La tumeur bénigne se traite par chimiothérapie uniquement", isCorrect: false },{ text: "La tumeur maligne est toujours visible à l'œil nu", isCorrect: false }],
        explanation: "Tumeur bénigne : bien délimitée, encapsulée, pas d'invasion ni de métastase. Tumeur maligne : invasive, angiogenèse, capacité à métastaser. La biopsie (anapath) est le gold standard de classification." },
      { text: "Les métastases se forment par :",
        options: [{ text: "La division sur place de cellules tumorales bénignes", isCorrect: false },{ text: "La dissémination de cellules tumorales via le sang ou la lymphe vers des organes à distance", isCorrect: true },{ text: "La transformation de cellules saines en cellules cancéreuses par contact", isCorrect: false },{ text: "Un mécanisme uniquement observé dans les cancers du sang", isCorrect: false }],
        explanation: "Les métastases résultent de la dissémination de cellules tumorales par voie hématogène ou lymphatique, qui colonisent des organes à distance (foie, poumons, os, cerveau selon le cancer primitif)." },
      { text: "L'inflammation chronique peut favoriser le développement tumoral car :",
        options: [{ text: "Elle détruit toutes les cellules tumorales en excès", isCorrect: false },{ text: "Elle crée un microenvironnement pro-tumoral avec cytokines, radicaux libres et angiogenèse", isCorrect: true },{ text: "Elle bloque la division cellulaire par immunosuppression", isCorrect: false },{ text: "Elle active systématiquement les gènes suppresseurs de tumeur", isCorrect: false }],
        explanation: "L'inflammation chronique (ex : hépatite chronique → CHC ; gastrite à H. pylori → cancer gastrique) produit des cytokines, radicaux libres et facteurs angiogéniques qui favorisent la mutagenèse et la croissance tumorale." },
      { text: "Le marqueur tumoral PSA est utilisé pour le dépistage du :",
        options: [{ text: "Cancer du côlon", isCorrect: false },{ text: "Cancer de la prostate", isCorrect: true },{ text: "Cancer du pancréas", isCorrect: false },{ text: "Cancer du testicule", isCorrect: false }],
        explanation: "Le PSA (Prostate Specific Antigen) est une glycoprotéine sécrétée par la prostate. Son élévation (> 4 ng/mL) peut orienter vers un cancer de la prostate, mais aussi une hypertrophie bénigne. Confirmation par biopsie." },
      { text: "La neutropénie fébrile sous chimiothérapie est une urgence car :",
        options: [{ text: "La fièvre en elle-même est dangereuse pour les cellules tumorales", isCorrect: false },{ text: "Le patient immuno-déprimé est exposé à des infections bactériennes rapidement mortelles", isCorrect: true },{ text: "La fièvre indique une rechute tumorale systématique", isCorrect: false },{ text: "Elle nécessite une suspension définitive du traitement", isCorrect: false }],
        explanation: "Neutropénie fébrile (PNN < 500/mm³ + T° > 38,3°C) : urgence infectieuse. Sans granulocytes, l'organisme ne peut pas combattre les bactéries. Antibiothérapie IV à large spectre en urgence (< 1h)." },
      { text: "L'arthrose est un processus dégénératif touchant :",
        options: [{ text: "La membrane synoviale uniquement (synovite chronique)", isCorrect: false },{ text: "Le cartilage articulaire avec dégradation progressive et réaction osseuse sous-chondrale", isCorrect: true },{ text: "Les tendons et ligaments périarticulaires", isCorrect: false },{ text: "Le muscle squelettique périarticulaire", isCorrect: false }],
        explanation: "L'arthrose est la dégradation du cartilage articulaire (perte de protéoglycanes, fibres de collagène). La réaction osseuse sous-chondrale produit des ostéophytes. Douleur mécanique, raideur matinale < 30 min." },
      { text: "L'ostéoporose se définit par :",
        options: [{ text: "Une infection chronique de l'os", isCorrect: false },{ text: "Une diminution de la densité minérale osseuse (T-score ≤ -2,5 DS) avec risque fracturaire", isCorrect: true },{ text: "Un excès de calcium dans l'os", isCorrect: false },{ text: "Une inflammation chronique du périoste", isCorrect: false }],
        explanation: "L'ostéoporose : T-score ≤ -2,5 DS à la DXA (densitométrie osseuse). Risque fracturaire élevé (rachis, col du fémur, poignet). Prévention : calcium, vitamine D, activité physique, traitement hormonal si indiqué." },
      { text: "La mucite buccale est un effet indésirable fréquent de :",
        options: [{ text: "La radiothérapie cérébrale uniquement", isCorrect: false },{ text: "La chimiothérapie (surtout les antimétabolites) et la radiothérapie cervicofaciale", isCorrect: true },{ text: "Les corticoïdes à forte dose uniquement", isCorrect: false },{ text: "L'immunothérapie uniquement", isCorrect: false }],
        explanation: "La mucite est une inflammation des muqueuses digestives (bouche, gorge, intestin) causée par la chimiothérapie (5-FU, méthotrexate) et la radiothérapie cervicofaciale. Soins de bouche rigoureux, alimentation adaptée." },
      { text: "La cachexie tumorale est définie comme :",
        options: [{ text: "Une prise de poids pathologique liée à la corticothérapie anti-tumorale", isCorrect: false },{ text: "Un syndrome métabolique complexe avec perte de masse musculaire non compensable par l'alimentation", isCorrect: true },{ text: "Un déficit exclusif en vitamines liposolubles", isCorrect: false },{ text: "Une anorexie isolée sans perte de masse musculaire", isCorrect: false }],
        explanation: "La cachexie cancéreuse : perte de poids > 5% en 6 mois (ou IMC < 20 + perte > 2%), avec perte musculaire irréductible même par apport nutritionnel. Médiée par cytokines pro-inflammatoires (TNFα, IL-6)." }
    ]
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 2.10 – Infectiologie, hygiène
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Infections associées aux soins : prévention et gestion des épidémies",
    description: "Bactéries multi-résistantes, épidémies nosocomiales et mesures de contrôle",
    semester: "Semestre 1", category: "UE 2.10 - Infectiologie, hygiène",
    chapter: "Infections nosocomiales", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "Le SARM (Staphylococcus aureus Résistant à la Méticilline) est traité en 1ère intention par :",
        options: [{ text: "Amoxicilline-acide clavulanique (Augmentin®)", isCorrect: false },{ text: "Vancomycine (glycopeptide)", isCorrect: true },{ text: "Pénicilline G en IV", isCorrect: false },{ text: "Ciprofloxacine en oral", isCorrect: false }],
        explanation: "Le SARM est résistant à toutes les bêta-lactamines. Le traitement de référence est la vancomycine (glycopeptide IV). Daptomycine et linézolide sont des alternatives. Isolement contact obligatoire." },
      { text: "Les précautions complémentaires 'contact' (PCC) pour SARM comprennent :",
        options: [{ text: "Masque FFP2, chambre à pression négative et combinaison intégrale", isCorrect: false },{ text: "Chambre individuelle ou regroupement, surblouse + gants à l'entrée, FHA à la sortie", isCorrect: true },{ text: "Masque chirurgical uniquement pour les soins", isCorrect: false },{ text: "Aucune mesure supplémentaire si le patient est sous antibiothérapie", isCorrect: false }],
        explanation: "PCC pour BMR contact (SARM, ERV, EBLSE, C. difficile) : chambre seule ou cohorting, surblouse + gants obligatoires à l'entrée, FHA à la sortie, matériel dédié, signalétique sur la porte." },
      { text: "Clostridium difficile (C. diff) provoque des diarrhées associées aux antibiotiques. La FHA est-elle efficace contre les spores ?",
        options: [{ text: "Oui, la FHA détruit toutes les spores en 30 secondes", isCorrect: false },{ text: "Non, la FHA ne détruit pas les spores de C. difficile — le lavage au savon est nécessaire", isCorrect: true },{ text: "Oui, si on utilise une FHA à base de chlorhexidine", isCorrect: false },{ text: "Oui, uniquement la FHA à l'alcool pur à 90°", isCorrect: false }],
        explanation: "Les spores de C. difficile résistent à l'alcool ! Le lavage des mains au savon (friction mécanique) est indispensable. La désinfection des surfaces se fait au chlore (eau de Javel 0,5%)." },
      { text: "Un patient porteur d'une EBLSE (entérobactérie productrice de bêta-lactamase à spectre étendu) doit être :",
        options: [{ text: "Isolé en chambre à pression positive", isCorrect: false },{ text: "Placé en chambre individuelle avec précautions contact et signalement au laboratoire", isCorrect: true },{ text: "Traité systématiquement par carbapenème", isCorrect: false },{ text: "Hospitalisé en service de maladies infectieuses uniquement", isCorrect: false }],
        explanation: "EBLSE : précautions contact (chambre individuelle, gants/surblouse), signalement au laboratoire et à l'EOH (Équipe Opérationnelle d'Hygiène). Le traitement dépend de l'antibiogramme (souvent carbapenème si infection)." },
      { text: "La surveillance épidémiologique des IAS dans un établissement est assurée par :",
        options: [{ text: "Uniquement les médecins infectiologues", isCorrect: false },{ text: "L'EOH (Équipe Opérationnelle d'Hygiène) avec le CLIN ou CME", isCorrect: true },{ text: "L'ARS uniquement pour les infections graves", isCorrect: false },{ text: "Les cadres de santé des services uniquement", isCorrect: false }],
        explanation: "L'EOH coordonne la surveillance et la prévention des IAS en lien avec le CLIN (Comité de Lutte contre les IAS). Elle forme les soignants, enquête sur les épidémies et rédige les protocoles d'hygiène." },
      { text: "Un EIG (Événement Indésirable Grave) associé aux soins doit être déclaré :",
        options: [{ text: "Uniquement à la direction de l'hôpital en interne", isCorrect: false },{ text: "À l'ARS (Agence Régionale de Santé) et à la HAS via le portail national de signalement", isCorrect: true },{ text: "Uniquement si le patient décède", isCorrect: false },{ text: "Au procureur de la République dans les 24h", isCorrect: false }],
        explanation: "Les EIG sont signalés à l'ARS et à la HAS via le portail signalement-sante.gouv.fr. La déclaration est obligatoire, non punitive et vise l'amélioration de la sécurité des soins (culture 'apprendre de ses erreurs')." },
      { text: "L'infection urinaire sur sonde vésicale est prévenue par :",
        options: [{ text: "L'irrigation vésicale quotidienne au sérum physiologique", isCorrect: false },{ text: "Circuit fermé maintenu, sac déclive, désinfection du méat, réévaluation quotidienne de la nécessité de la sonde", isCorrect: true },{ text: "L'antibiothérapie prophylactique systématique", isCorrect: false },{ text: "Le changement de sonde toutes les 24h", isCorrect: false }],
        explanation: "Prévention IU sur sonde : circuit fermé stérile, sac toujours déclive (jamais remonté), hygiène du méat urinaire, connexions limitées, réévaluation quotidienne du maintien de la sonde." },
      { text: "Le taux d'IAS en France représente environ :",
        options: [{ text: "1% des hospitalisations", isCorrect: false },{ text: "5% des hospitalisations, soit environ 700 000 cas/an", isCorrect: true },{ text: "15% des hospitalisations", isCorrect: false },{ text: "25% des hospitalisations en chirurgie", isCorrect: false }],
        explanation: "En France, environ 5% des patients hospitalisés contractent une IAS, soit 700 000 cas/an dont 4 200 décès directement imputables. Un tiers serait évitable par une meilleure application des mesures préventives." },
      { text: "La surveillance des bactériémies liées aux cathéters centraux comprend :",
        options: [{ text: "Le retrait systématique du cathéter toutes les 48h", isCorrect: false },{ text: "L'inspection quotidienne du point de ponction, pansement occlusif, technique aseptique stricte", isCorrect: true },{ text: "L'antibiothérapie prophylactique systématique pendant la durée du cathéter", isCorrect: false },{ text: "La culture du cathéter toutes les semaines", isCorrect: false }],
        explanation: "Prévention bactériémie liée au cathéter central : technique aseptique à la pose et aux manipulations, inspection quotidienne, pansement stérile occlusif, retrait dès que non nécessaire. Durée < 7 jours idéalement." },
      { text: "Le taux de mortalité attribuable au sepsis est d'environ :",
        options: [{ text: "5–10%", isCorrect: false },{ text: "20–30% (choc septique : 40–50%)", isCorrect: true },{ text: "1–2%", isCorrect: false },{ text: "60–70% systématiquement", isCorrect: false }],
        explanation: "Sepsis : mortalité 20–30%. Choc septique : 40–50%. Première heure critique (bundle 'Hour-1') : hémocultures, antibiotiques, lactate, remplissage, vasopresseurs. Chaque heure de retard augmente la mortalité de 7%." }
    ]
  },
  {
    title: "Hygiène des mains, désinfection et stérilisation — applications",
    description: "Applications pratiques de l'hygiène hospitalière et techniques de désinfection",
    semester: "Semestre 1", category: "UE 2.10 - Infectiologie, hygiène",
    chapter: "Hygiène hospitalière", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Combien de temps dure une friction hydro-alcoolique (FHA) efficace ?",
        options: [{ text: "5 secondes", isCorrect: false },{ text: "20–30 secondes jusqu'au séchage complet", isCorrect: true },{ text: "1 minute minimum", isCorrect: false },{ text: "10 secondes suffisent", isCorrect: false }],
        explanation: "La FHA dure 20–30 secondes, en couvrant toutes les zones (paumes, dos des mains, espaces interdigitaux, pouces, ongles) jusqu'au séchage complet. C'est plus rapide et plus efficace que le lavage au savon." },
      { text: "Le lavage simple au savon doux est OBLIGATOIRE (à la place de la FHA) dans le cas de :",
        options: [{ text: "Toute prise en charge d'un patient immunodéprimé", isCorrect: false },{ text: "Mains visiblement souillées ou après contact avec un patient à C. difficile ou spores", isCorrect: true },{ text: "Avant la pose d'une perfusion intraveineuse", isCorrect: false },{ text: "Après le retrait des gants propres", isCorrect: false }],
        explanation: "Le lavage au savon est obligatoire quand les mains sont visiblement souillées (sang, excréments) et après contact avec C. difficile (spores résistantes à l'alcool). Il mécano-décroche les spores." },
      { text: "Le port de gants en soins infirmiers :",
        options: [{ text: "Remplace la friction hydro-alcoolique avant et après le soin", isCorrect: false },{ text: "Ne remplace jamais l'hygiène des mains — FHA avant ET après le port de gants", isCorrect: true },{ text: "Est obligatoire pour tout contact avec un patient, même sans risque de contact avec liquides biologiques", isCorrect: false },{ text: "Est réservé aux soins stériles uniquement", isCorrect: false }],
        explanation: "Les gants protègent mais ne remplacent pas l'hygiène des mains. Il faut faire une FHA AVANT d'enfiler les gants (préparer les mains) et APRÈS les avoir retirés (les mains peuvent être contaminées au retrait)." },
      { text: "La désinfection à l'alcool à 70° est efficace contre :",
        options: [{ text: "Les spores bactériennes et les champignons uniquement", isCorrect: false },{ text: "La plupart des bactéries, virus enveloppés et champignons (pas les spores)", isCorrect: true },{ text: "Uniquement les virus enveloppés (VIH, VHB)", isCorrect: false },{ text: "Toutes les formes microbiennes y compris les prions", isCorrect: false }],
        explanation: "L'alcool à 70° est bactéricide, virucide (virus enveloppés : VIH, VHB, SARS-CoV-2) et fongicide. Il est inactif sur les spores (C. difficile, charbon). Les prions nécessitent une procédure spécifique (soude + autoclave)." },
      { text: "La classification de Spaulding classe le matériel médical selon :",
        options: [{ text: "Son coût et sa durabilité", isCorrect: false },{ text: "Son niveau de risque infectieux selon la zone anatomique contactée", isCorrect: true },{ text: "Sa composition chimique et sa résistance à la chaleur", isCorrect: false },{ text: "Sa fréquence d'utilisation en milieu hospitalier", isCorrect: false }],
        explanation: "Spaulding classe le matériel en 3 niveaux selon le risque infectieux : critique (pénètre tissus stériles) → stérilisation ; semi-critique (muqueuses intactes) → DHN ; non critique (peau saine) → désinfection niveau bas/moyen." },
      { text: "Le matériel à usage unique (UU) a pour avantage principal :",
        options: [{ text: "Il est moins coûteux que le matériel réutilisable", isCorrect: false },{ text: "Il élimine le risque de transmission croisée lié à une décontamination insuffisante", isCorrect: true },{ text: "Il est moins polluant que le matériel réutilisable", isCorrect: false },{ text: "Il offre une meilleure qualité de soin que le matériel réutilisable", isCorrect: false }],
        explanation: "Le matériel UU (seringue, aiguille, cathéter, gants) élimine le risque de transmission croisée par retraitement insuffisant. Sa réutilisation est formellement interdite en France." },
      { text: "La traçabilité de la stérilisation comprend :",
        options: [{ text: "Uniquement la date de fabrication du dispositif médical", isCorrect: false },{ text: "Le numéro de cycle d'autoclave, la date, le contenu, les paramètres de stérilisation et la DLUO", isCorrect: true },{ text: "Uniquement la signature de l'IDE qui a utilisé le matériel", isCorrect: false },{ text: "La durée d'utilisation du matériel stérilisé", isCorrect: false }],
        explanation: "La traçabilité de la stérilisation inclut : n° de lot/cycle, date de stérilisation, contenu de la charge, paramètres (T°, temps, pression), indicateurs chimiques (virage couleur), DLUO et identification de l'utilisateur." },
      { text: "L'eau de Javel (hypochlorite de sodium) est particulièrement indiquée pour :",
        options: [{ text: "La désinfection des instruments chirurgicaux métalliques", isCorrect: false },{ text: "La désinfection des surfaces après contact avec des matières fécales ou spores (C. difficile)", isCorrect: true },{ text: "L'antisepsie des plaies cutanées", isCorrect: false },{ text: "La stérilisation des dispositifs médicaux thermosensibles", isCorrect: false }],
        explanation: "L'eau de Javel (0,5% de chlore actif) est sporicide et virucide. Elle est indiquée pour la désinfection des surfaces après contamination par matières fécales, vomissements, ou C. difficile. Irritante, à diluer correctement." },
      { text: "Le bionettoyage d'une chambre après la sortie d'un patient porteur de SARM comprend :",
        options: [{ text: "Un simple aérage de 30 minutes sans nettoyage", isCorrect: false },{ text: "Nettoyage + désinfection de toutes les surfaces avec un produit détergent-désinfectant, en commençant par le haut", isCorrect: true },{ text: "Uniquement la désinfection du lit et des poignées de porte", isCorrect: false },{ text: "L'irradiation UV de la chambre pendant 10 minutes", isCorrect: false }],
        explanation: "Bionettoyage terminal (sortie BMR) : nettoyage + désinfection de TOUTES les surfaces (haut vers bas, propre vers sale), matelas, literie, équipements. Selon protocole EOH avec produit à spectre adapté." },
      { text: "La technique aseptique pour une pose de cathéter veineux périphérique comprend :",
        options: [{ text: "Désinfection cutanée avec un coton imbibé d'alcool uniquement", isPublished: false, isCorrect: false },{ text: "Hygiène des mains, gants, désinfection en 4 temps (déterger, rincer, sécher, antisepsie) ou 2 temps sur peau propre", isCorrect: true },{ text: "Le port d'une blouse stérile et de lunettes de protection obligatoire", isCorrect: false },{ text: "Une seule application d'antiseptique sans temps de contact", isCorrect: false }],
        explanation: "Pose CVP : FHA, gants propres, désinfection cutanée en 4 temps (si peau sale : Bétadine savon + rinçage + séchage + Bétadine alcoolique) ou 2 temps (si peau propre : nettoyage + antiseptique alcoolique)." }
    ]
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 2.11 – Pharmacologie et thérapeutiques
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Pharmacologie avancée : toxicité, surdosage et antidotes",
    description: "Toxicité médicamenteuse, surdosages et conduites à tenir infirmières",
    semester: "Semestre 1", category: "UE 2.11 - Pharmacologie et thérapeutiques",
    chapter: "Pharmacocinétique", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "En cas de surdosage à la morphine (dépression respiratoire), l'antidote est :",
        options: [{ text: "N-acétylcystéine (Fluimucil®)", isCorrect: false },{ text: "Naloxone (Narcan®)", isCorrect: true },{ text: "Flumazénil (Anexate®)", isCorrect: false },{ text: "Charbon activé oral", isCorrect: false }],
        explanation: "La naloxone (Narcan®) est l'antagoniste compétitif des récepteurs opioïdes μ. Elle inverse la dépression respiratoire en quelques minutes. Demi-vie courte : nécessite souvent des réinjections ou perfusion continue." },
      { text: "L'antidote du surdosage en benzodiazépines est :",
        options: [{ text: "Naloxone (Narcan®)", isCorrect: false },{ text: "Flumazénil (Anexate®)", isCorrect: true },{ text: "Atropine", isCorrect: false },{ text: "Vitamine K", isCorrect: false }],
        explanation: "Le flumazénil (Anexate®) est l'antagoniste spécifique des benzodiazépines au niveau du récepteur GABA-A. Il lève la sédation mais a une demi-vie courte (1h) → risque de re-sédation à surveiller." },
      { text: "L'interaction entre les AVK et les AINS est dangereuse car :",
        options: [{ text: "Les AINS réduisent l'efficacité des AVK", isCorrect: false },{ text: "Les AINS augmentent l'effet anticoagulant des AVK et inhibent l'agrégation plaquettaire → risque hémorragique majeur", isCorrect: true },{ text: "Les AINS accélèrent le métabolisme hépatique des AVK", isCorrect: false },{ text: "Les AINS bloquent la vitamine K nécessaire aux AVK", isCorrect: false }],
        explanation: "AINS + AVK : double risque hémorragique — les AINS déplacent les AVK de leur liaison protéique (↑ fraction libre) ET inhibent les plaquettes. Association contre-indiquée ou à surveiller très étroitement." },
      { text: "Les inducteurs enzymatiques hépatiques (rifampicine, carbamazépine) réduisent l'efficacité de nombreux médicaments car :",
        options: [{ text: "Ils augmentent l'absorption intestinale et la biodisponibilité", isCorrect: false },{ text: "Ils stimulent le cytochrome P450 hépatique → métabolisation accélérée → concentration plasmatique réduite", isCorrect: true },{ text: "Ils bloquent la liaison protéique des médicaments", isCorrect: false },{ text: "Ils réduisent l'élimination rénale des médicaments", isCorrect: false }],
        explanation: "Les inducteurs enzymatiques activent le CYP450 hépatique → dégradation plus rapide des médicaments co-administrés → perte d'efficacité. Ex : rifampicine réduit l'efficacité des contraceptifs oraux, AVK, tacrolimus." },
      { text: "La iatrogénie médicamenteuse chez le sujet âgé est favorisée par :",
        options: [{ text: "Une absorption intestinale plus rapide", isCorrect: false },{ text: "La polypharmacie, la réduction de la fonction rénale et hépatique, et la modification du volume de distribution", isCorrect: true },{ text: "Une sensibilité réduite aux médicaments", isCorrect: false },{ text: "Une meilleure observance thérapeutique", isCorrect: false }],
        explanation: "Iatrogénie chez le sujet âgé : polypharmacie (interactions), ↓ filtration rénale (accumulation), ↓ métabolisme hépatique, ↓ albumine (↑ fraction libre), ↑ sensibilité (BZD, morphiniques), ↓ eau corporelle." },
      { text: "L'insuffisance rénale aiguë impose d'adapter les posologies des médicaments à élimination rénale car :",
        options: [{ text: "L'absorption intestinale est réduite dans l'IRA", isCorrect: false },{ text: "La réduction de la filtration glomérulaire entraîne une accumulation et un risque de toxicité", isCorrect: true },{ text: "Le foie compense entièrement l'élimination rénale", isCorrect: false },{ text: "L'IRA augmente le volume de distribution des médicaments", isCorrect: false }],
        explanation: "En IRA, les médicaments à élimination rénale s'accumulent → toxicité (ex : aminosides → ototoxicité/néphrotoxicité, digoxine → troubles du rythme, HBPM → hémorragie). Adapter la dose et/ou l'intervalle selon la clairance." },
      { text: "La tobramycine (aminoside) est monitored par dosage des :",
        options: [{ text: "Concentrations résiduelles (creux) pour vérifier l'absence de toxicité", isCorrect: true },{ text: "Concentrations au pic uniquement pour vérifier l'efficacité", isCorrect: false },{ text: "Concentrations urinaires quotidiennes", isCorrect: false },{ text: "Aucun dosage n'est nécessaire si la fonction rénale est normale", isCorrect: false }],
        explanation: "Les aminosides nécessitent un suivi de la concentration résiduelle (creux avant la dose suivante) pour éviter l'accumulation et la toxicité (oto et néphrotoxicité). Le pic permet de vérifier l'efficacité bactéricide." },
      { text: "Le délai d'action d'une injection sous-cutanée (SC) d'insuline rapide est de :",
        options: [{ text: "Immédiat (< 1 minute)", isCorrect: false },{ text: "15–30 minutes pour le début d'action", isCorrect: true },{ text: "2–4 heures", isCorrect: false },{ text: "Identique à la voie IV", isCorrect: false }],
        explanation: "Insuline rapide SC : début d'action 15–30 min, pic à 1–3h, durée 4–6h. C'est pourquoi elle est administrée avant le repas (15–30 min). En urgence, l'insuline IV a un effet quasi immédiat." },
      { text: "La thrombopénie induite par l'héparine (TIH) est une complication :",
        options: [{ text: "Fréquente et bénigne qui disparaît spontanément", isCorrect: false },{ text: "Rare mais grave : thrombopénie + thromboses paradoxales par activation plaquettaire", isCorrect: true },{ text: "Spécifique aux HBPM uniquement", isCorrect: false },{ text: "Sans conséquence si les plaquettes restent > 50 G/L", isCorrect: false }],
        explanation: "La TIH type 2 : réaction immunologique (anticorps anti-PF4/héparine), thrombopénie > 50% entre J5–J14 + thromboses artérielles et veineuses (paradoxal). Arrêt IMMÉDIAT de toute héparine + relais par anticoagulant alternatif." },
      { text: "La prescription d'un médicament 'hors AMM' signifie que :",
        options: [{ text: "Le médicament est illégal et ne peut pas être dispensé", isCorrect: false },{ text: "Le médicament est utilisé dans une indication non approuvée par l'autorisation de mise sur le marché", isCorrect: true },{ text: "Le médicament n'a pas encore été testé chez l'homme", isCorrect: false },{ text: "Le médicament n'est pas remboursé par la Sécurité Sociale", isCorrect: false }],
        explanation: "Une prescription hors AMM est légale si elle est justifiée par des données scientifiques probantes (études, recommandations). Le médecin doit en informer le patient et tracer la justification dans le dossier." }
    ]
  },
  {
    title: "Thérapeutiques spécialisées : chimiothérapie, dialyse et nutrition artificielle",
    description: "Principes et surveillance des thérapeutiques complexes",
    semester: "Semestre 1", category: "UE 2.11 - Pharmacologie et thérapeutiques",
    chapter: "Thérapeutiques et administration", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "La nutrition parentérale totale (NPT) est indiquée quand :",
        options: [{ text: "Le patient refuse de manger pendant 24h", isCorrect: false },{ text: "Le tube digestif est non fonctionnel et la nutrition entérale est impossible", isCorrect: true },{ text: "Le patient a un IMC < 25", isCorrect: false },{ text: "La nutrition entérale est trop coûteuse", isCorrect: false }],
        explanation: "La NPT est indiquée quand le TD est non fonctionnel (grêle court, occlusion, fistule) ou inaccessible. Elle est administrée par voie centrale (cathéter central ou PICC). Complications : infections, troubles métaboliques." },
      { text: "La vérification de la position d'une sonde naso-gastrique avant toute utilisation se fait par :",
        options: [{ text: "L'aspiration de liquide gastrique avec confirmation pH < 5,5 ± radiographie thoracique", isCorrect: true },{ text: "L'introduction d'air et l'auscultation de l'épigastre uniquement", isCorrect: false },{ text: "La mesure de la longueur de la sonde à l'extérieur uniquement", isCorrect: false },{ text: "La radiographie systématique après chaque repas", isCorrect: false }],
        explanation: "Vérification sonde nasogastrique : aspiration et contrôle pH < 5,5 (liquide gastrique acide). Si impossible ou doute → radiographie thoraco-abdominale. L'auscultation seule (insufflation d'air) n'est pas fiable." },
      { text: "La dialyse péritonéale (DP) utilise comme membrane de filtration :",
        options: [{ text: "Une membrane synthétique en cellulose", isCorrect: false },{ text: "Le péritoine (membrane naturelle de la cavité abdominale)", isCorrect: true },{ text: "Un filtre en hémodialyse externe", isCorrect: false },{ text: "La membrane des globules rouges", isCorrect: false }],
        explanation: "La dialyse péritonéale utilise le péritoine comme membrane semi-perméable naturelle. Le dialysat est introduit dans la cavité péritonéale, les déchets diffusent du sang vers le dialysat, puis le liquide est drainé." },
      { text: "La transfusion de globules rouges concentrés (CGR) nécessite avant tout :",
        options: [{ text: "Un groupe sanguin et rhésus seul effectué dans les 3 mois", isCorrect: false },{ text: "Un groupage sanguin (2 déterminations), RAI récente (< 72h en urgence) et contrôle ultime au lit du patient", isCorrect: true },{ text: "Uniquement le consentement écrit du patient", isCorrect: false },{ text: "Un ECG et une radiographie thoracique pré-transfusionnelle", isCorrect: false }],
        explanation: "Transfusion CGR : 2 déterminations de groupe ABO-Rh sur 2 prélèvements distincts, RAI < 72h, contrôle ultime au lit (concordance patient/produit). Le contrôle ultime est l'ultime barrière anti-erreur." },
      { text: "L'hémodialyse est réalisée 3 fois par semaine car :",
        options: [{ text: "C'est le rythme le plus commode pour le patient", isCorrect: false },{ text: "Elle compense partiellement la fonction rénale (épuration des déchets et de l'eau accumulés en 48h)", isCorrect: true },{ text: "Le rein résiduel fonctionne le reste du temps", isCorrect: false },{ text: "Des séances plus fréquentes ne sont pas techniquement possibles", isCorrect: false }],
        explanation: "L'hémodialyse classique (3×/semaine, 4h par séance) épure les déchets azotés et l'eau accumulés pendant les 48h inter-dialytiques. Des rythmes plus fréquents (dialyse quotidienne) améliorent le pronostic." },
      { text: "La surveillance d'une transfusion sanguine doit être particulièrement rigoureuse pendant :",
        options: [{ text: "La dernière heure de transfusion uniquement", isCorrect: false },{ text: "Les 15 premières minutes (risque de réaction hémolytique aiguë) et tout au long de la transfusion", isCorrect: true },{ text: "Uniquement si le patient a des antécédents d'allergie", isCorrect: false },{ text: "Après la fin de la transfusion pendant 2 heures", isCorrect: false }],
        explanation: "Surveillance transfusionnelle : constantes avant, à 15 min (pic de risque d'incompatibilité ABO), à 1h, en fin de transfusion et 1h après. Les 15 premières minutes sont cruciales : risque de choc hémolytique ABO immédiat." },
      { text: "La corticothérapie au long cours peut entraîner comme effets indésirables :",
        options: [{ text: "Hypoglycémie, hypotension et hyperkaliémie", isCorrect: false },{ text: "Ostéoporose, diabète cortico-induit, HTA, surinfections et syndrome de Cushing iatrogène", isCorrect: true },{ text: "Bradycardie et hyperthyroïdie", isCorrect: false },{ text: "Insuffisance rénale et hépatotoxicité", isCorrect: false }],
        explanation: "Corticothérapie prolongée : syndrome de Cushing (obésité androïde, vergetures), ostéoporose, HTA, hyperglycémie, immunosuppression (infections), atrophie musculaire, ulcère gastrique (association AINS)." },
      { text: "La compatibility médicamenteuse en seringue/poche IV doit être vérifiée car :",
        options: [{ text: "C'est uniquement une question esthétique (précipité coloré)", isCorrect: false },{ text: "Certains mélanges entraînent une précipitation, inactivation ou formation de produits toxiques", isCorrect: true },{ text: "Tous les médicaments IV sont compatibles entre eux", isCorrect: false },{ text: "L'incompatibilité n'a d'impact que sur la durée de conservation", isCorrect: false }],
        explanation: "L'incompatibilité physico-chimique peut provoquer : précipitation (obstruction cathéter, embolie), inactivation (perte d'efficacité), ou formation de produits toxiques. Vérifier les tableaux de compatibilité ou demander au pharmacien." },
      { text: "Le débit de perfusion pour administrer 500 mL en 4 heures en gouttes/minute est :",
        options: [{ text: "15 gouttes/min", isCorrect: false },{ text: "28 gouttes/min (500 mL ÷ 4h ÷ 60 min × 20 gouttes/mL)", isCorrect: true },{ text: "50 gouttes/min", isCorrect: false },{ text: "125 mL/h = 42 gouttes/min", isCorrect: false }],
        explanation: "Calcul : (500 mL × 20 gttes/mL) ÷ (4h × 60 min) = 10 000 ÷ 240 = 41,6 gttes/min ≈ 42 gttes/min. En débit horaire : 500/4 = 125 mL/h. Toujours vérifier le facteur gouttes selon la tubulure (20 gttes/mL standard)." },
      { text: "La pharmacovigilance est le système qui surveille :",
        options: [{ text: "Les stocks de médicaments dans les pharmacies hospitalières", isCorrect: false },{ text: "Les effets indésirables des médicaments après leur commercialisation (post-AMM)", isCorrect: true },{ text: "La qualité de fabrication des médicaments", isCorrect: false },{ text: "Les prix des médicaments remboursés par la Sécurité Sociale", isCorrect: false }],
        explanation: "La pharmacovigilance (ANSM) surveille les effets indésirables médicamenteux après AMM. Tout EI grave ou inattendu doit être déclaré par le professionnel de santé via le portail de signalement national." }
    ]
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UE 3.1 – Raisonnement et démarche clinique infirmière
  // ═══════════════════════════════════════════════════════════════════════════
  {
    title: "Raisonnement clinique avancé et situations complexes",
    description: "Raisonnement hypothético-déductif, priorisation et décisions cliniques",
    semester: "Semestre 1", category: "UE 3.1 - Raisonnement et démarche clinique infirmière",
    chapter: "Démarche clinique infirmière", difficulty: "hard", duration: 20, isPublished: true,
    questions: [
      { text: "La priorisation des soins selon le modèle de Maslow conduit à traiter en premier :",
        options: [{ text: "Les besoins d'estime de soi (dignité, respect)", isCorrect: false },{ text: "Les besoins physiologiques (respiration, circulation, douleur intense)", isCorrect: true },{ text: "Les besoins de sécurité (anxiété, peur)", isCorrect: false },{ text: "Les besoins d'appartenance (famille, lien social)", isCorrect: false }],
        explanation: "Maslow : les besoins physiologiques (survie) sont toujours prioritaires. Une détresse respiratoire ou une douleur sévère priment sur l'anxiété ou les besoins relationnels." },
      { text: "Le raisonnement clinique par 'scripts' de maladie est caractéristique :",
        options: [{ text: "Des étudiants en début de formation", isCorrect: false },{ text: "Des experts qui reconnaissent rapidement des patterns cliniques par analogie avec des cas mémorisés", isCorrect: true },{ text: "D'une approche uniquement utilisée en réanimation", isCorrect: false },{ text: "D'un processus délibéré et conscient uniquement", isCorrect: false }],
        explanation: "Les cliniciens experts utilisent la reconnaissance de patterns (scripts) pour un diagnostic rapide. Avantage : rapidité. Risque : biais de confirmation. À contrôler par une approche hypothético-déductive en cas de doute." },
      { text: "Le biais de confirmation dans le raisonnement clinique consiste à :",
        options: [{ text: "Vérifier systématiquement son diagnostic auprès du médecin", isCorrect: false },{ text: "Chercher uniquement les informations qui confirment l'hypothèse initiale et ignorer les données discordantes", isCorrect: true },{ text: "Confirmer le diagnostic par plusieurs examens complémentaires", isCorrect: false },{ text: "Demander systématiquement un deuxième avis médical", isCorrect: false }],
        explanation: "Le biais de confirmation est un biais cognitif dangereux : on ne cherche (inconsciemment) que les éléments qui confirment l'hypothèse initiale. Il peut mener à des erreurs diagnostiques graves." },
      { text: "Lors d'une détérioration clinique rapide d'un patient, l'IDE doit en priorité :",
        options: [{ text: "Attendre l'évolution pendant 1 heure avant d'alerter", isCorrect: false },{ text: "Évaluer les paramètres vitaux (ABCDE), alerter le médecin avec le SBAR et rester auprès du patient", isCorrect: true },{ text: "Contacter directement le réanimateur sans passer par le médecin référent", isCorrect: false },{ text: "Consulter le dossier médical avant toute action clinique", isCorrect: false }],
        explanation: "Face à une détérioration : ABCDE (Airway, Breathing, Circulation, Disability, Exposure), alerte immédiate avec SBAR (Situation, Background, Assessment, Recommendation), rester avec le patient." },
      { text: "Le concept de 'failure to rescue' désigne :",
        options: [{ text: "L'échec d'une technique de réanimation cardiopulmonaire", isCorrect: false },{ text: "Le décès ou la complication grave d'un patient dont les signes précoces de détérioration n'ont pas été détectés et traités à temps", isCorrect: true },{ text: "Le refus d'un patient d'accepter un traitement salvateur", isCorrect: false },{ text: "L'échec d'un système d'urgence à atteindre le patient à temps", isCorrect: false }],
        explanation: "'Failure to rescue' : décès ou morbidité grave suite à une complication non détectée ou traitée trop tard par les soignants. C'est un indicateur clé de qualité des soins infirmiers." },
      { text: "L'outil ABCDE en évaluation rapide du patient critique signifie :",
        options: [{ text: "Assessment, Blood, Consciousness, Diagnosis, Electrocardiogram", isCorrect: false },{ text: "Airway, Breathing, Circulation, Disability, Exposure", isCorrect: true },{ text: "Anamnèse, Bilan, Constantes, Douleur, Évolution", isCorrect: false },{ text: "Autonomie, Bien-être, Communication, Dignité, Évaluation", isCorrect: false }],
        explanation: "ABCDE : A (Airway — perméabilité des voies aériennes), B (Breathing — ventilation), C (Circulation — hémodynamique), D (Disability — neurologie, Glasgow, glycémie), E (Exposure — examen complet). Approche structurée d'urgence." },
      { text: "La méthode SBAR pour communiquer une dégradation au médecin inclut :",
        options: [{ text: "Signes, Bilan, Antécédents, Résultats", isCorrect: false },{ text: "Situation, Background (contexte), Assessment (évaluation), Recommendation", isCorrect: true },{ text: "Symptômes, Biologie, Anamnèse, Radiologie", isCorrect: false },{ text: "Sécurité, Bien-être, Autonomie, Résultats", isCorrect: false }],
        explanation: "SBAR : S (Qui, quoi, où — le problème immédiat), B (Background — antécédents, motif d'hospit), A (Assessment — évaluation clinique actuelle), R (Recommendation — ce que je demande/propose)." },
      { text: "L'évaluation initiale d'un patient admis aux urgences intègre :",
        options: [{ text: "Uniquement les constantes vitales", isCorrect: false },{ text: "Anamnèse, constantes vitales, examen clinique, antécédents, traitement en cours et motif de consultation", isCorrect: true },{ text: "Uniquement le diagnostic médical provisoire", isCorrect: false },{ text: "Les résultats biologiques avant l'examen clinique", isCorrect: false }],
        explanation: "L'évaluation globale initiale (triage) : constantes vitales, anamnèse (OPQRST pour la douleur), antécédents, traitements, examen clinique rapide. Elle oriente le tri et la priorisation des soins." },
      { text: "L'approche centrée sur le patient implique que :",
        options: [{ text: "Le soignant détermine seul les objectifs de soins selon son expertise", isCorrect: false },{ text: "Le patient est un partenaire actif dans la définition de ses objectifs et choix thérapeutiques", isCorrect: true },{ text: "Les préférences du patient ne sont prises en compte qu'en fin de vie", isCorrect: false },{ text: "Le patient suit strictement les décisions de l'équipe médicale", isCorrect: false }],
        explanation: "L'approche centrée sur le patient (patient-centered care) reconnaît le patient comme expert de son vécu et partenaire de soins. Elle améliore la satisfaction, l'observance et les résultats cliniques." },
      { text: "La pensée critique dans la démarche infirmière implique de :",
        options: [{ text: "Critiquer ouvertement les décisions médicales du médecin", isCorrect: false },{ text: "Remettre en question ses hypothèses, chercher des preuves et envisager d'autres explications", isCorrect: true },{ text: "Appliquer les protocoles sans réflexion pour éviter les erreurs", isCorrect: false },{ text: "Déléguer les décisions complexes au médecin systématiquement", isCorrect: false }],
        explanation: "La pensée critique est une compétence professionnelle essentielle : questionnement méthodique, recherche de preuves, tolérance à l'ambiguïté, considération du contexte. Elle évite les erreurs par routinisation excessive." }
    ]
  },
  {
    title: "Diagnostics infirmiers NANDA et planification des soins",
    description: "Formulation des diagnostics infirmiers, objectifs SMART et plan de soins",
    semester: "Semestre 1", category: "UE 3.1 - Raisonnement et démarche clinique infirmière",
    chapter: "Plan de soins", difficulty: "medium", duration: 15, isPublished: true,
    questions: [
      { text: "Un diagnostic infirmier NANDA est formulé selon le format PES :",
        options: [{ text: "Pathologie, Évolution, Soins", isCorrect: false },{ text: "Problème (libellé) / Étiologie (lié à…) / Signes (se manifestant par…)", isCorrect: true },{ text: "Plan, Exécution, Surveillance", isCorrect: false },{ text: "Patient, Équipe, Soignant", isCorrect: false }],
        explanation: "PES : Problème (diagnostic infirmier NANDA), Étiologie (facteurs favorisants), Signes/Symptômes (manifestations observables). Ex : 'Douleur aiguë liée à une fracture se manifestant par EVA 8/10 et grimaces'." },
      { text: "Parmi les suivants, lequel est un diagnostic infirmier NANDA (et non médical) ?",
        options: [{ text: "Pneumonie bactérienne à Pneumococcus", isCorrect: false },{ text: "Altération de la mobilité physique liée à la douleur se manifestant par une limitation des déplacements", isCorrect: true },{ text: "Insuffisance cardiaque congestive stade III NYHA", isCorrect: false },{ text: "Anémie ferriprive par carence martiale", isCorrect: false }],
        explanation: "Le diagnostic infirmier exprime la RÉPONSE du patient à sa pathologie, pas la pathologie elle-même. 'Altération de la mobilité physique' est un diagnostic infirmier ; 'pneumonie' est un diagnostic médical." },
      { text: "L'objectif de soin SMART 'Le patient marchera 50m avec son déambulateur d'ici 48h' est :",
        options: [{ text: "Trop ambitieux car non réaliste pour un patient hospitalisé", isCorrect: false },{ text: "SMART car il est Spécifique, Mesurable, Atteignable, Réaliste et Temporellement défini", isCorrect: true },{ text: "Insuffisant car il ne précise pas le rôle de l'IDE", isCorrect: false },{ text: "Incorrect car un objectif doit toujours être atteint immédiatement", isCorrect: false }],
        explanation: "Cet objectif respecte les critères SMART : Spécifique (marcher 50m avec déambulateur), Mesurable (50m), Atteignable (avec aide), Réaliste (patient hospitalisé), Temporel (48h)." },
      { text: "Le risque d'infection est un diagnostic infirmier :",
        options: [{ text: "De type 'problème actuel' car l'infection est déjà présente", isCorrect: false },{ text: "De type 'risque' car le problème n'est pas encore survenu mais est suspecté", isCorrect: true },{ text: "Inutile car seul le médecin peut identifier les risques infectieux", isCorrect: false },{ text: "Invalide car un diagnostic infirmier doit toujours être actuel", isCorrect: false }],
        explanation: "Les diagnostics NANDA incluent 3 types : problèmes actuels (se manifestent), risques (susceptibles de survenir), et promotion de la santé. 'Risque d'infection' est un diagnostic de risque préventif." },
      { text: "L'évaluation du plan de soins doit se faire :",
        options: [{ text: "Uniquement à la sortie du patient", isCorrect: false },{ text: "De façon continue, à des intervalles définis, pour vérifier l'atteinte des objectifs et réajuster", isCorrect: true },{ text: "Uniquement si le patient exprime une plainte", isCorrect: false },{ text: "Par le médecin référent uniquement", isCorrect: false }],
        explanation: "L'évaluation est continue et à intervalles définis : a-t-on atteint l'objectif ? (oui → résoudre ou maintenir, non → analyser pourquoi et réajuster le plan). La démarche est un cycle itératif." },
      { text: "Le diagnostic infirmier 'Anxiété liée à l'hospitalisation se manifestant par agitation et insomnie' appelle en priorité :",
        options: [{ text: "La prescription d'un anxiolytique par le médecin", isCorrect: false },{ text: "Des interventions de relation d'aide : écoute, information, présence, techniques de relaxation", isCorrect: true },{ text: "La mise en chambre individuelle et restriction des visites", isCorrect: false },{ text: "La surveillance rapprochée des constantes vitales uniquement", isCorrect: false }],
        explanation: "L'anxiété liée à l'hospitalisation relève d'abord du rôle propre infirmier : relation d'aide, écoute active, information, présence rassurante, technique de relaxation. La pharmacologie (anxiolytiques) est une option complémentaire." },
      { text: "La transmission ciblée (DAR) est utilisée pour :",
        options: [{ text: "Rédiger les ordonnances médicales", isCorrect: false },{ text: "Tracer les observations infirmières orientées sur les problèmes prioritaires du patient", isCorrect: true },{ text: "Communiquer avec la famille du patient", isCorrect: false },{ text: "Évaluer les compétences des étudiants infirmiers", isCorrect: false }],
        explanation: "La transmission ciblée DAR (Données/Actions/Résultats) est un mode de traçabilité centré sur les problèmes prioritaires. Elle structure l'information et facilite la continuité des soins entre les équipes." },
      { text: "La collaboration interdisciplinaire dans le plan de soins implique que :",
        options: [{ text: "L'IDE attend les instructions du médecin avant chaque intervention", isCorrect: false },{ text: "Chaque professionnel contribue avec son expertise spécifique dans un objectif commun centré sur le patient", isCorrect: true },{ text: "L'IDE supervise le travail de tous les autres professionnels de santé", isCorrect: false },{ text: "Le plan de soins infirmier est identique au plan médical", isCorrect: false }],
        explanation: "L'interdisciplinarité : médecin (diagnostic, traitement), IDE (soins infirmiers, surveillance), kiné (rééducation), AS (soins de base), diététicien (nutrition)... Chacun contribue à un projet commun centré patient." },
      { text: "Le diagnostic infirmier 'Déséquilibre nutritionnel : apports inférieurs aux besoins' peut être lié à :",
        options: [{ text: "Un diabète de type 2 uniquement", isCorrect: false },{ text: "Une anorexie, des troubles de la déglutition, des nausées post-chimiothérapie ou une dépression", isCorrect: true },{ text: "Une allergie alimentaire uniquement", isCorrect: false },{ text: "Un excès de mobilité physique", isCorrect: false }],
        explanation: "Le déficit nutritionnel peut être lié à : troubles de la déglutition (AVC), nausées (chimio), anorexie (dépression, cancer), douleur à la déglutition (mucite), troubles cognitifs. L'étiologie guide les interventions." },
      { text: "La surveillance post-opératoire en SSPI (Salle de Réveil) comprend :",
        options: [{ text: "Uniquement la douleur et la SpO₂", isCorrect: false },{ text: "Constantes vitales (TA, FC, FR, SpO₂, T°), conscience (Aldrete), douleur, nausées, site opératoire et diurèse", isCorrect: true },{ text: "Uniquement le niveau de conscience et la pression artérielle", isCorrect: false },{ text: "L'ECG et l'échocardiographie systématique", isCorrect: false }],
        explanation: "SSPI : score d'Aldrete (conscience, mobilité, PA, SpO₂, couleur) ≥ 9 pour la sortie. Surveillance : constantes, douleur (EVA), nausées/vomissements (NVPO), site opératoire, diurèse, drainage, réchauffement." }
    ]
  },
];
